### ISSUE TITLE
[EF Core/sqlite] EntityMaterializerSource.TryReadValue[TValue] NullReferenceException

### ISSUE THREAD

**Issue by chamons** [mono/mono#15852] opened 2019-07-26 20:05 UTC
_From @ChaseFlorell on Thu, 25 Jul 2019 21:40:27 GMT_

### Describe what is not working as expected.

Unfortunately we cannot reproduce this issue locally, however we are seeing an increasing number of exceptions landing in our AppCenter insights.

I'm cross posting from this issue as that's what I was instructed to do.
https://github.com/aspnet/EntityFrameworkCore/issues/16727

```
System
String.memcpy_aligned_1 (System.Byte* dest, System.Byte* src, System.Int32 size)
Microsoft.EntityFrameworkCore.Metadata.Internal
EntityMaterializerSource.TryReadValue[TValue] (Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer, System.Int32 index, Microsoft.EntityFrameworkCore.Metadata.IPropertyBase property)
(wrapper unknown) System.Object.gsharedvt_in()
(wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
System.Reflection
MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Linq.Expressions.Interpreter
MethodInfoCallInstruction.Run (System.Linq.Expressions.Interpreter.InterpretedFrame frame)
System.Linq.Expressions.Interpreter
Interpreter.Run (System.Linq.Expressions.Interpreter.InterpretedFrame frame)
System.Linq.Expressions.Interpreter
LightLambda.Run1[T0,TRet] (T0 arg0)
(wrapper unknown) System.Object.gsharedvt_in()
Microsoft.EntityFrameworkCore.Query.Internal
QueryBuffer.GetEntity (Microsoft.EntityFrameworkCore.Metadata.IKey key, Microsoft.EntityFrameworkCore.Query.EntityLoadInfo entityLoadInfo, System.Boolean queryStateManager, System.Boolean throwOnNullKey)
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
BufferedEntityShaper`1[TEntity].Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer)
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
BufferedOffsetEntityShaper`1[TEntity].Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer)
(wrapper unknown) System.Object.gsharedvt_out()
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
CompositeShaper+TypedCompositeShaper`5[TOuterShaper,TOuter,TInnerShaper,TInner,TResult].Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer)
(wrapper unknown) System.Object.gsharedvt_in()
(wrapper unknown) System.Object.gsharedvt_out()
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper+TypedCompositeShaper`5[TOuterShaper,TOuter,TInnerShaper,TInner,TResult].Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
IShaper<TResult>.Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer)
(wrapper unknown) System.Object.gsharedvt_in()
(wrapper unknown) System.Object.gsharedvt_out()
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
CompositeShaper+TypedCompositeShaper`5[TOuterShaper,TOuter,TInnerShaper,TInner,TResult].Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer)
(wrapper unknown) System.Object.gsharedvt_in()
(wrapper unknown) System.Object.gsharedvt_out()
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper+TypedCompositeShaper`5[TOuterShaper,TOuter,TInnerShaper,TInner,TResult].Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
IShaper<TResult>.Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer)
(wrapper unknown) System.Object.gsharedvt_in()
(wrapper unknown) System.Object.gsharedvt_out()
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
ProjectionShaper+TypedProjectionShaper`3[TShaper,TIn,TOut].Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer)
(wrapper unknown) System.Object.gsharedvt_in()
(wrapper unknown) System.Object.gsharedvt_out()
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper+TypedProjectionShaper`3[TShaper,TIn,TOut].Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
IShaper<TOut>.Shape (Microsoft.EntityFrameworkCore.Query.QueryContext queryContext, Microsoft.EntityFrameworkCore.Storage.ValueBuffer& valueBuffer)
(wrapper unknown) System.Object.gsharedvt_in()
Microsoft.EntityFrameworkCore.Query.Internal
AsyncQueryingEnumerable`1+AsyncEnumerator+<BufferlessMoveNext>d__12[T].MoveNext ()
Microsoft.EntityFrameworkCore.Query.Internal
AsyncQueryingEnumerable`1+AsyncEnumerator+<MoveNext>d__11[T].MoveNext ()
Microsoft.EntityFrameworkCore.Query.Internal
QueryBuffer+<IncludeCollectionAsync>d__13`3[TEntity,TRelated,TElement].MoveNext ()
Microsoft.EntityFrameworkCore.Query.Internal
IncludeCompiler+IncludeLoadTreeNodeBase+<_AwaitMany>d__8.MoveNext ()
Microsoft.EntityFrameworkCore.Query.Internal
IncludeCompiler+<_IncludeAsync>d__22`1[TEntity].MoveNext ()
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
TaskLiftingExpressionVisitor+<_ExecuteAsync>d__8`1[T].MoveNext ()
(wrapper unknown) System.Object.gsharedvt_out()
Microsoft.EntityFrameworkCore.Query
ResultOperatorHandler+AsyncGroupByAsyncEnumerable`3+GroupByAsyncEnumerator+<MoveNext>d__5[TSource,TKey,TElement].MoveNext ()
System.Linq
AsyncEnumerable+SkipAsyncIterator`1+<MoveNextCore>d__7[TSource].MoveNext ()
System.Linq
AsyncEnumerable+AsyncIterator`1+<MoveNext>d__10[TSource].MoveNext ()
System.Linq
AsyncEnumerable+TakeAsyncIterator`1+<MoveNextCore>d__7[TSource].MoveNext ()
System.Linq
AsyncEnumerable+AsyncIterator`1+<MoveNext>d__10[TSource].MoveNext ()
Microsoft.EntityFrameworkCore.Query.Internal
AsyncLinqOperatorProvider+AsyncSelectEnumerable`2+AsyncSelectEnumerator+<MoveNext>d__3[TSource,TResult].MoveNext ()
Microsoft.EntityFrameworkCore.Query.Internal
AsyncLinqOperatorProvider+ExceptionInterceptor`1+EnumeratorExceptionInterceptor+<MoveNext>d__5[T].MoveNext ()
System.Linq
AsyncEnumerable+<Aggregate_>d__6`3[TSource,TAccumulate,TResult].MoveNext ()
AgExpert.Mobile.Field.Core.Repositories
ActivityRepository+<List>d__2.MoveNext ()
AgExpert.Mobile.Field.Core.Services.Data
ActivityDataService+<ListActivities>d__6.MoveNext ()
AgExpert.Mobile.Field.ViewModels
ActivityListViewModel+<<LoadData>b__31_0>d.MoveNext ()
AgExpert.Mobile.Field.ViewModels
BaseViewModel+<RunSafeAsync>d__69.MoveNext ()
```

### Steps to reproduce
we cannot reproduce this locally, this is happening in production.
<img width="1626" alt="Screen Shot 2019-07-24 at 11 47 31 AM" src="https://user-images.githubusercontent.com/471626/61819921-d8b19980-ae08-11e9-8e02-ecef4512aad3.png">

```c#
public async Task<IEnumerable<ActivityListModel>> List(int skip, int pageSize, Expression<Func<Activity, bool>> predicate, CancellationToken token)
{
    var activities = await Activities.AsNoTracking()
        .Include(x => x.FieldCropYear.Field)
        .Include(x => x.SeedCropYear.SeedInput.SeedVariety.Seed)
        .Include(x => x.Seeds)
        .ThenInclude(x => x.SeedCropYear.SeedInput.SeedVariety.Seed)
        .Include(x => x.Fertilizers)
        .ThenInclude(x => x.FertilizerCropYear.FertilizerInput)
        .Include(x => x.Products)
        .ThenInclude(x => x.ProductCropYear.ProductInput.Product)
        .Where(predicate)
        .OrderByDescending(x => x.StartDate)
        .ThenByDescending(x => x.CreatedAt)
        // we have to group instead of distinct because EF doesn't play nice with Distinct + Skip/Take
        // GroupBy comes after ordering because we can't order an IGrouping
        .GroupBy(x => x.Id) 
        .Skip(skip)
        .Take(pageSize)
        // now we grab the first item of each group, since the group is a collection of the same record
        .Select(activity => new ActivityListModel(activity.First())) 
        .ToListAsync(token)
        .ConfigureAwait(false);

    return activities;
}
```

### Further technical details

EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: iOS 12.*
IDE: Not applicable, but we use Rider and VS Mac

_Copied from original issue xamarin/xamarin-macios#6653_

**Comment by chamons** [comment] 2019-07-26 20:05
_From @chamons on Fri, 26 Jul 2019 20:05:05 GMT_

This make me believe this is a mono issue, as the entire top half of the stack is lib or BCL code.

```
System
String.memcpy_aligned_1 (System.Byte* dest, System.Byte* src, System.Int32 size)
Microsoft.EntityFrameworkCore.Metadata.Internal
```

**Comment by divega** [comment] 2019-07-26 21:06
@marek-safar As per our past conversations, heads up that this issue is being reported as affecting EF Core running on Xamarin.

**Comment by steveisok** [comment] 2019-07-26 21:42
@MaximLipnin Please have a look and see if you can spot anything

**Comment by ChaseFlorell** [comment] 2019-07-27 04:36
To be clear, it's xamarin iOS that I'm experiencing it on. I have personally not seen this on Android, even though we share the code base.

**Comment by MaximLipnin** [comment] 2019-07-29 09:37
@ChaseFlorell  Is is possible to attach the version of xamarin iOS which you are experiencing the problem on? Could you extract any minimal project to build/run that reflect your production logic?

**Comment by ChaseFlorell** [comment] 2019-07-30 17:16
Here are the details around the build on Azure DevOps

=======================================================================
Task         : Xamarin.iOS
Description  : Build an iOS app with Xamarin on macOS
Version      : 1.131.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613729)
=======================================================================

**Comment by ChaseFlorell** [comment] 2019-07-30 17:17
also, I've still been unsuccessful in reproducing this locally, it's only showing up in our AppCenter Insights from our Production App. We've got multiple people experiencing the same issue.

**Comment by MaximLipnin** [comment] 2019-07-31 12:13
1. Could you please add build configuration from AppCenter? It should be something  like
![image](https://user-images.githubusercontent.com/3258267/62210747-8db5fa00-b3a5-11e9-8f2f-8bfa1cdf43b4.png)
2. Also please attach full build output (to get environment info).

**Comment by ChaseFlorell** [comment] 2019-07-31 14:55
We don't actually do it that way. Our current setup uses scripts to do the build, here where we set the version of xcode and mono

```bash
echo "Setting mono version to 5_16_0_0"
MONOVERSION=5_16_0_0
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$MONOVERSION
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
echo "Appending AppleSdkRoot to Settings.plist"
mkdir -p /Users/vsts/Library/Preferences/Xamarin
cd /Users/vsts/Library/Preferences/Xamarin
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"https://www.apple.com/DTDs/PropertyList-1.0.dtd\"><plist version=\"1.0\"><dict><key>AppleSdkRoot</key><string>/Applications/Xcode_10.1.app</string></dict></plist>" >> Settings.plist
echo "Setting Xcode version to 10.1 for Visual Studio for Mac"
sudo xcode-select -s /Applications/Xcode_10.1.app/Contents/Developer
sudo xcodebuild -showsdks
sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $MONOVERSION
```

**Comment by MaximLipnin** [comment] 2019-07-31 15:08
From that snippet I see that you use Mono 5.16. Could you try newer version of Mono in your setup and see if the issue is gone?

**Comment by ChaseFlorell** [comment] 2019-08-07 21:49
We're going to try this out as soon as we have cycles to change our pipeline and test it.

**Comment by ChaseFlorell** [comment] 2019-08-09 21:06
We've had to request that Azure DevOps update their mono version.
https://github.com/microsoft/azure-pipelines-image-generation/issues/1163

**Comment by MaximLipnin** [comment] 2020-09-14 06:43
It looks like the issue has been addressed so I'm closing it. Feel free to re-open if the problem isn't gone.

**Closed by MaximLipnin** 2020-09-14 06:43 UTC
Labels: area-BCL: mscorlib, needs more info
