### ISSUE TITLE
Object not garbage collected but according to .mlpd should be

### ISSUE THREAD

**Issue by DavidKarlas** [mono/mono#16996] opened 2019-09-23 13:30 UTC
## Steps to Reproduce

1. `git clone --branch memory https://github.com/xamarin/vs-editor-core`
2. `cd vs-editor-core`
2. `msbuild /r`
3. Now start profiling
* I set environment variable `MONO_ENV_OPTIONS` to `--profile=log:nodefaults,heapshot-on-shutdown,heapshot=ondemand,gcalloc,gcmove,gcroot,counter,maxframes=0,output="output.mlpd"`
* And use `open` application with `"vs-editor-core/bin/StandaloneMacEditor/Debug/net472/MonoDevelop.Ide.app"` as parameter
4. Once application starts use `Cmd+W` key binding to close Window
5. Make a snapshot
6. Observe that `Microsoft.VisualStudio.Text.Editor.Implementation.CocoaTextView` object is still not collected but there is no Root referencing it. Hence bug.

### Current Behavior
Object is alive but without "path to root".

### Expected Behavior
Either object is collected or has "path to root"

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
6.4.0.198

## Stacktrace
N/A

**Comment by marek-safar** [comment] 2019-09-24 14:49
@BrzVlad what do you need to track this issue down?

/cc @SamMonoRT

**Comment by BrzVlad** [comment] 2019-09-24 14:54
@abock Please provide the steps you are taking to have mono leak and the leaking rate you are experiencing. I can take a look afterwards.

**Comment by BrzVlad** [comment] 2019-09-24 15:14
So you mean I just start the application and it leaks forever ? That's it ?

**Comment by DavidKarlas** [comment] 2019-09-24 15:17
As mentioned in step 4 `Once application starts use Cmd+W key binding to close Window` at this point `Microsoft.VisualStudio.Text.Editor.Implementation.CocoaTextView` is not collected, but its not clear why its not collected.

**Comment by abock** [comment] 2019-09-24 15:19
When an editor window is closed (but the process still alive), you should notice leaks. Instances of `CocoaTextView` will still be around (along with anything hanging from it) and we'd expect them to be GCd (or for the profiler to reveal why not).

Creating new editors and closing them within a single process should make the leaks more apparent (basically <kbd>⌘N</kbd> and <kbd>⌘W</kbd> a lot).

**Comment by BrzVlad** [comment] 2019-09-24 16:15
I thought this is maybe leaking a single useless object, but it leaks about 30MB per `⌘W`, which is ridiculous.

**Comment by BrzVlad** [comment] 2019-09-25 17:40
<img width="1306" alt="Screen Shot 2019-09-25 at 8 31 42 PM" src="https://user-images.githubusercontent.com/4720621/65625526-a244f600-dfd4-11e9-86ad-285c0326468b.png">

**Comment by BrzVlad** [comment] 2019-09-25 17:42
We were missing root reporting for toggle ref objects. Mono's GC can't collect this object because it is held alive in Objective C. I would assume the application does something wrong. @abock  You should probably ask the macios team for help with the leak.

**Comment by Therzok** [comment] 2019-09-26 15:54
Dupe of https://github.com/mono/mono/issues/13062 ?

**Closed** 2019-09-26 19:39 UTC
Labels: area-Runtime: GC
