### ISSUE TITLE
Add test coverage for custom modifiers

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11350] opened 2018-10-24 15:17 UTC
We should import recently added CoreCLR tests for custom modifiers. We fail to pass the tests on array custom modifiers at least.

https://github.com/dotnet/coreclr/pull/20546

**Comment by lambdageek** [comment] 2019-02-12 21:05
https://gist.github.com/lambdageek/bf268c3e037dacfafb0e1734dee0b397 Standalone repro based on https://github.com/dotnet/coreclr/pull/20546/files

The test mostly exercises virtual calls.  We get about a half dozen of them wrong.

Don't know yet if it's because vtable setup is long or if the JIT dispatching the calls to incorrect slots.  My bet is that it's the vtable setup.

**Comment by lambdageek** [comment] 2019-02-13 22:02
From #12422 we now know that sometimes even if the vtable is correct, method-to-ir will incorrectly translate a `callvirt` (when it looks up a token to get a MonoMethod the signature equivalence uses a type equivalence that is insufficiently strict about cmods).

So there are two steps to working on this bug:
1. turn on vtable debug printing and check whether the correct methods are going in the vtable.
2. If they are, this is a duplicate of 12422; if the vtable is incorrect, then it's a separate issue.

**Comment by lambdageek** [comment] 2019-02-26 19:53
I see improvement from #13191 - the only bit that's failing now is the arrayModopt2 test at the end (exit  code 302)

**Comment by lambdageek** [comment] 2019-02-26 23:46
Arrays are failing for a pretty serious reason: We actually can't represent an array whose elements are of a type that has custom modifiers.   For a MONO_TYPE_SZARRAY we just store a `MonoClass*` (which doesn't have any place to store custom modifiers), and for a MONO_TYPE_ARRAY, we store a `MonoTypeArray*` which also just saves a `MonoClass*`, rank and bounds.

(This also applies to pointer and fnptr types)

I don't know the best way to go here: I guess we need to carry custom modifiers in a `MonoClass` (maybe allow variable-sized `byval_arg`)?

Alternately, maybe MonoTypeArray should hold a MonoType not a MonoClass for the element type (but the struct is in the public API, so we'd have to do something messy).

This will not be a quick fix.

**Comment by marek-safar** [comment] 2019-02-27 07:51
@vargaz could you validate this^ proposal?

**Comment by vargaz** [comment] 2019-02-27 08:05
I think if mono_type_equal () returns FALSE for 2 types, then their corresponding MonoClass-es should be different too. I'm not sure fixing this is really worth it it seems like a lot of work for little gain.

**Comment by lambdageek** [comment] 2019-04-23 13:18
This is done (primarily in #13320).  Arrays with an element type with custom modifiers are not supported (filed as #13203)

**Closed by lambdageek** 2019-04-23 13:18 UTC
Labels: task
