### ISSUE TITLE
WASM 13 error when blocking main thread.

### ISSUE THREAD

**Issue by kant2002** [mono/mono#11026] opened 2018-10-08 11:05 UTC
## Steps to Reproduce

Not sure how to repro in simpler fashion, but very simple blazor app is here https://github.com/kant2002/BlazorWasm13

The idea is that I block main thread using awaiter

```
var x = GetTaskAsync().GetAwaiter().GetResult();
```

I'm coming here from https://github.com/aspnet/Blazor/issues/1506

### Current Behavior
[WASM]: 13 reported in browser console.

### Expected Behavior

At least some indication that locking of main thread is not possible, and clearly better error message.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows
[x] WASM

**Version Used**:

bfc35fc6e65 (version taken here https://github.com/aspnet/Blazor/commit/8a878515a98d66052adb7eed847e893c06e45da4)

**Comment by kjpou1** [comment] 2018-10-26 11:58
After talking with https://github.com/danroth27 and https://github.com/SteveSandersonMS we will need to have more information.  

- Run the same type of test directly with the WebAssembly sdk and the browser locks up.
- Debugging Blazor inconclusive because it does not block main thread.  Abort/Error happens somewhere between Blazor http sendasync and wasm_invoke_marshalled.
- The method continues and executes the async method as if nothing happens.

**Comment by kant2002** [comment] 2018-10-26 19:11
Should I try to remove Blazor pieces step by step, so I could move closer to just having Mono in the browser?

**Comment by kjpou1** [comment] 2018-10-29 10:44
I think we will need to have more information from Blazor as this cannot seem to be duplicated it with just having Mono in the browser.  It locks up the browser or at least in all the tests I have been able to do to reproduce it.

This may be fixed in mono and we will have more information when Blazor updates mono.  Also, this is more that the error message needs to be clearer than anything else.

But definitely, if you can recreate it using just mono in the browser we would definitely be interested in looking at this.

**Comment by kjpou1** [comment] 2019-02-19 18:20
Closing this for now.  Please re-open if this is still a problem.

**Closed by kjpou1** 2019-02-19 18:20 UTC
