### ISSUE TITLE
[WASM] Typo in binding_support.js for parameter count validation

### ISSUE THREAD

**Issue by WinInsider** [mono/mono#18315] opened 2019-12-29 05:10 UTC
There is a typo in [binding_support.js on line 631](https://github.com/mono/mono/blob/master/sdks/wasm/src/binding_support.js#L631); which leads to runtime error.

should be length, instead of **leghth**

`args.length < args_marshal.leghth`

The check will not work because **leghth** is undefined on **args**; and then code throws JS Error on following line in code.

1) Error can be produced with Edge (EdgeHTML); Refresh page while F12 Edge Dev Tools are open...  check Console output for error.
2) csproj targets Mono.WebAssembly.Sdk `<Project Sdk="Mono.WebAssembly.Sdk">`
3) Using build [#4393](https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/4393/); have placed *.nupkg files in "packages" folder
4) the error is encountered when starting an app... calling Main method, seems parameter count check is failing

**Comment by lewing** [comment] 2020-01-03 01:32
The issue is more complicated than that see https://github.com/mono/mono/pull/18188 @kjpou1 is working on a proper fix

**Comment by lewing** [comment] 2020-04-07 03:04
This was fixed in https://github.com/mono/mono/pull/19150

**Closed by lewing** 2020-04-07 03:04 UTC
Labels: target-wasm
