### ISSUE TITLE
[merp] generate a crash report if process is killed with SIGTERM

### ISSUE THREAD

**Issue by kdubau** [mono/mono#17419] opened 2019-10-18 18:21 UTC
See this feature: https://github.com/mono/mono/issues/8236, https://github.com/mono/mono/pull/8240

It seems to have regressed with https://github.com/mono/mono/pull/17310 - we a not getting any information when VSMac hangs (known to be an urgent issue on Catalina) and a user need to force quit.

**Comment by kdubau** [comment] 2019-10-18 18:23
@lambdageek this looks like a regression. Looks like the attempt to fix https://github.com/mono/mono/issues/17271 removed this feature all together?

**Comment by lambdageek** [comment] 2019-10-21 18:54
All three of the following scenarios look the same to Mono:
1. someone force quits when VSfM hangs,
2. someone force quits just because they feel like it,
3. someone runs a script that runs `kill -TERM nnnnn` and kills VSfM that way.

We want MERP to pop up in all those cases?

**Comment by lambdageek** [comment] 2019-10-21 18:58
Another idea is to dump our old plaintext crash log to ide.log in the log directory so that the hang telemetry can upload it next time.

**Comment by kdubau** [comment] 2019-10-21 21:12
@slluis thoughts?

**Comment by slluis** [comment] 2019-10-22 11:16
Since mono can't differentiate between those 3 cases, we need MERP to always send a crash report. We can do some after-the-fact analysis to figure out what happened.

**Comment by lambdageek** [comment] 2019-10-22 16:47
Hm. Yea looks like we discussed this already in #8240.  So it is a regression.

(Although I believe Force Quit support has been broken since c3fe80a0c43be780e35f3a4091d3dc1023b35a00 - 2018-12.  That PR changed how the sigterm handler behaves, and I believe the Force Quit support was overlooked)

**Comment by vargaz** [comment] 2019-10-22 17:03
Just an opinion, but users really don't like apps doing something with SIGTERM, they want their apps to just quit.

**Comment by jaykrell** [comment] 2019-10-22 17:10
https://github.com/mono/mono/pull/8240#issuecomment-381249943

Often but not always, there is nowhere to type control-c, right?
Is that detectable, like lack of running from a console, or the console is gone?
Or do people use kill to send the same signal anyway, so not really a separate case?

What does Office do?
What does CoreCLR do?
What does Google Chrome do?
What does Microsoft Chrome do?
What does Safari do?
What does Firefox do?
What does Xcode do?
What does VSCode do?
What does Apple recommend or provide?

**Comment by lambdageek** [comment] 2019-10-22 17:17
Ctrl-C is a different signal (SIGINT).  SIGTERM is used by Force Quit and by `kill PID`, that's it.

**Comment by alexischr** [comment] 2019-10-23 13:07
As a data point, Force-Quitting or `kill -TERM`ing Microsoft Word results in MERP being activated, with a telemetry flag included in the data making it clear that this is a force quit (`Exception: SIG_FORCE_QUIT`)

**Comment by lambdageek** [comment] 2019-10-26 22:49
Fixed on `master`, `2019-10` and `2019-08`

**Comment by lambdageek** [comment] 2019-10-28 14:51
On 2019-08 and 2019-10, we need followup work to re-enable the SIGTERM signal handler when EnableMicrosoftTelemetry is called.

**Comment by lambdageek** [comment] 2019-10-28 21:43
Follow-up PRs were merged to 2019-08 and 2019-10.

**Closed by lambdageek** 2019-10-28 21:43 UTC
Labels: area-Runtime: Crash Reporting, regression
