### ISSUE TITLE
WebAssembly-specific issue : chrome run 1 hour later , crash

### ISSUE THREAD

**Issue by w8w8w8** [mono/mono#10250] opened 2018-08-23 01:20 UTC
1: Write C# class , Declare 1000 variables.
code like this:

> public Flowsheet() {
> a = 1.00002d;
> b = 2.6d;
> c = 0;
> ......
> .....
> }
> public void Run()
> {
> CALL(ref a, ref b);
> }
> private double a;
> public double A { get { return a; } set { a = value; } }
> private double b;
> public double B { get { return b; } set { b = value; } }
> private double c;
> public double C { get { return c; } set { c = value; } }
> .....
> public void CALL(ref double a, ref double b, .......) {
> double c = Math.Log(a / b);
> ......
> }

2: compile a dll file.
3: creat a blazor prject.
4: Use HttpClient GetByteArrayAsync load the dll file
5: I use js setInterVal() Execute Run(), and get 1000 variable's value, after 1 hour , my chrome crash.

![default](https://user-images.githubusercontent.com/4744039/44499228-90986d00-a6b5-11e8-970d-dfeace29ae86.png)

![default](https://user-images.githubusercontent.com/4744039/44499266-b9206700-a6b5-11e8-982d-44cc7f8d19c8.png)

I think  this is a WebAssembly-specific issue

**Comment by lewurm** [comment] 2018-08-23 16:32
Hello @w8w8w8, thanks for your bug report. Could you provide some code sample that reproduces the issue? Thanks!

**Comment by kumpera** [comment] 2018-08-24 02:54
This looks like an issue in Blazor's bindings. cc @stevesanderson

**Comment by w8w8w8** [comment] 2018-08-24 03:15
@lewurm there are my simple code. 
[simple.zip](https://github.com/mono/mono/files/2316854/simple.zip)

**Comment by w8w8w8** [comment] 2018-08-25 00:09
@SteveSandersonMS   OK， today I will upload a new project !

**Comment by w8w8w8** [comment] 2018-08-25 00:40
dependencies “Rectifyf”  in simple.zip file

**Comment by lewurm** [comment] 2018-08-27 13:52
which mono version did you test this with? the issue you are observing is potentially fixed by https://github.com/mono/mono/pull/9985

**Comment by kumpera** [comment] 2018-08-27 13:57
@SteveSandersonMS it's not 100% clear from the reporter what's the issue, but looks to be a memory leak of TypedArrays, which for a blazor app would be due to Blazor's bindings right?

**Comment by SteveSandersonMS** [comment] 2018-08-28 12:54
> looks to be a memory leak of TypedArrays, which for a blazor app would be due to Blazor's bindings right? 

I don't have any reason to think that. There isn't any code in Blazor's JS-side library that holds TypedArray instances anywhere that should be reachable beyond the current synchronous call.

**Comment by kumpera** [comment] 2018-08-28 13:30
@SteveSandersonMS I guess I'll have to dig deeper on this one.

**Comment by SteveSandersonMS** [comment] 2018-08-28 13:48
@kumpera It looks to me like the posted code is calling `Assembly.Load(bytes)`, possibly over and over in a loop. Since we don't support unloading assemblies, it would make sense if this was leaking.

**Comment by kumpera** [comment] 2018-08-28 15:34
Hmm, yes, that's by design. We don't support assembly unloading and it will cause unbound memory usage.

I'm sorry to say that this is not on our roadmap @w8w8w8. @luhenry do we have a tracking issue for that?

**Comment by w8w8w8** [comment] 2018-08-29 00:32
@SteveSandersonMS  I Assembly.load()  on `protected override async Task OnInitAsync()`, not over and over , ok, today I Reduce code ， and will upload new project.   @kumpera .
thank everybody

**Comment by w8w8w8** [comment] 2018-08-29 01:12
Since you said that it may be caused by **Assembly.Load(bytes)**, I re-doed a project. This project is very simple, just reflect the read value, and then output value in console,  _sorry my english_ .

> @functions {
>     [Parameter]
>     string Project { get; set; }
>     public int i = 1;
>     Rectifyf.FlowsheetBase Rectifyf = new Rectifyf.FlowsheetBase();
>     Type t;
>     protected override async Task OnInitAsync()
>     {
>         t = Rectifyf.GetType();
>     }
>     protected override void OnAfterRender()
>     {
>         base.OnAfterRender();
>         var timer = new Timer(new TimerCallback(_ =>
>         {
>             RUNRectifyf();
>         }), null, 1000, 500);
> 
>     }
>     public void RUNRectifyf() {
>         Rectifyf.Run();
>         PropertyInfo[] pro2 = t.GetProperties();
>         foreach (PropertyInfo item in pro2)
>         {
>             Console.WriteLine(item.Name + "--->" + item.MemberType + "--->" + item.PropertyType);
>         }
>     }
> }

the **Rectifyf.FlowsheetBase** class 
[Rectifyf.zip](https://github.com/mono/mono/files/2330320/Rectifyf.zip)

and  this is my chrome status:


![21](https://user-images.githubusercontent.com/4744039/44759202-32630280-ab6b-11e8-9911-b941620b6e69.png)
![31](https://user-images.githubusercontent.com/4744039/44759203-3858e380-ab6b-11e8-8422-c4c10d7b6891.png)


@kumpera @SteveSandersonMS @lewurm  I do not think this issue was caused by Assembly.Load(bytes)

so... I expect  thank you

**Comment by SteveSandersonMS** [comment] 2018-08-29 08:53
Thanks for the additional info, @w8w8w8.

The code posted above spams the console pretty hard.  It writes hundreds of items per second to the console. These are all strings that the browser has to keep in memory permanently (because you might scroll back up in the console window to see earlier entries). I might be wrong, but it looks like this is what primarily drives the memory growth.

As an experiment, I changed `RUNRectifyf` to the following:

```csharp
    public string result;

    public void RUNRectifyf() {
        Rectifyf.Run();
        PropertyInfo[] pro2 = t.GetProperties();
        foreach (PropertyInfo item in pro2)
        {
            result = item.Name + "--->" + item.MemberType + "--->" + item.PropertyType;
        }
    }
```

Notice that it still has to construct all the same strings on the .NET side (because `result` might be observed externally and hence can't be optimised away). The difference is that it just doesn't output them to the console any more.

Having removed the `Console.WriteLine`, I'm no longer seeing any memory growth over time. It looks stable.

Do you have any other reasons to think there's a memory leak somewhere else?

**Comment by w8w8w8** [comment] 2018-08-29 10:40
@SteveSandersonMS  thank you replay, I edit code and show value .  but chrome memory still growth


```
<p>@total</p>
<div id="JsonContent">
    @result
</div>
@functions {

    Rectifyf.FlowsheetBase Rectifyf = new Rectifyf.FlowsheetBase();
    Type t;
    protected override async Task OnInitAsync()
    {
        t = Rectifyf.GetType();
    }
    protected override void OnAfterRender()
    {
        base.OnAfterRender();
        var timer = new Timer(new TimerCallback(_ =>
        {
            RUNRectifyf();
        }), null, 1000, 500);

    }

    public string result;
    public int total = 0;
    public void RUNRectifyf() {
        Rectifyf.Run();
        result = "";
        total = 0;
        PropertyInfo[] pro2 = t.GetProperties();
        foreach (PropertyInfo item in pro2)
        {
            result += item.Name + "--->" + item.MemberType + "--->" + item.PropertyType;
            total += 1;
        }
        this.StateHasChanged();
    }

}
```
Is it because I use too many variables in Rectifyf.FlowsheetBase? there are 83 variables.
thank you.

**Comment by SteveSandersonMS** [comment] 2018-08-29 12:49
@w8w8w8 The new code you've posted causes an exponential growth in resource usage. Every time it renders, it adds another new timer, which in turn triggers more renders. The number of timers and renders will grow exponentially.

You should avoid starting additional timers after every render. For example, update your `OnAfterRender` code to:

```csharp
    bool isFirst = true;

    protected override void OnAfterRender()
    {
        base.OnAfterRender();

        if (isFirst)
        {
            isFirst = false;
            var timer = new Timer(new TimerCallback(_ =>
            {
                RUNRectifyf();
            }), null, 1000, 500);
        }
    }
```

Having done this, memory usage looks pretty stable to me. The main thing that causes growth still is that about every 30 seconds, it logs a message saying the GC ran, but it would take a *long* time for these log messages to cause any meaningful consequences.

**Comment by w8w8w8** [comment] 2018-08-29 12:55
@SteveSandersonMS  thank you， today  I off work, tomorrow, I do a test.  thank you.

**Comment by w8w8w8** [comment] 2018-08-30 01:37
I am sorry, I am coming again. today I change the code , delete C# timer, then use js interop , and changed RUNRectifyf() return value. and memory still growth.

1. c# code   

```
<input type="button" class="btn btn-primary" onclick="Operate(this)" value="开始" />
<div id="JsonContent">
    
</div>
@functions {

    static Rectifyf.FlowsheetBase Rectifyf = new Rectifyf.FlowsheetBase();
    static Type t;
    public static string result;
    public static int total = 0;

    protected override async Task OnInitAsync()
    {
        t = Rectifyf.GetType();
    }
    protected override void OnAfterRender()
    {
        base.OnAfterRender();
    }

    [JSInvokable]
    public static string RUNRectifyf()
    {
        Rectifyf.Run();
        result = "";
        total = 0;
        PropertyInfo[] pro2 = t.GetProperties();
        foreach (PropertyInfo item in pro2)
        {
            string FieldName = item.Name;
            PropertyInfo property = t.GetProperty(FieldName);
            object o = property.GetValue(Rectifyf, null);
            string Value = Convert.ToString(o);
            if (property.PropertyType.Name.Contains("[]"))
            {
                Value = "";
                double[] a = o as double[];
                for (int i = 0; i < a.Length; i++) {
                    Value += a[i] + ",";
                }
            }
            result += item.Name + "--->" + item.MemberType + "--->" + item.PropertyType +"--->"+ Value +";";
            total += 1;
        }
        return result;
    }
}
```

2: Javascript code

```
var count = 0; var GO;
var r = function sfRun() {
    window.clearTimeout(GO)
    DotNet.invokeMethodAsync("BlazorApp1", 'RUNRectifyf').then(function (parm) {
        count++;
        $("#JsonContent").html(parm);
        GO = window.setTimeout(function () {
            r();
        }, 500);
        
    });

}
function Operate(obj) {
    r();
}
```

I feel that my program is not wrong. but when I run my chrome , the memory still growth. 

@SteveSandersonMS  thank you for replay.

**Comment by w8w8w8** [comment] 2018-08-30 02:06
I am sorry, I am coming again. today I change the code , delete C# timer, then use js interop , and changed RUNRectifyf() return value. and memory still growth.

1. c# code   

```
<input type="button" class="btn btn-primary" onclick="Operate(this)" value="开始" />
<div id="JsonContent">
    
</div>
@functions {

    static Rectifyf.FlowsheetBase Rectifyf = new Rectifyf.FlowsheetBase();
    static Type t;
    public static string result;
    public static int total = 0;

    protected override async Task OnInitAsync()
    {
        t = Rectifyf.GetType();
    }
    protected override void OnAfterRender()
    {
        base.OnAfterRender();
    }

    [JSInvokable]
    public static string RUNRectifyf()
    {
        Rectifyf.Run();
        result = "";
        total = 0;
        PropertyInfo[] pro2 = t.GetProperties();
        foreach (PropertyInfo item in pro2)
        {
            string FieldName = item.Name;
            PropertyInfo property = t.GetProperty(FieldName);
            object o = property.GetValue(Rectifyf, null);
            string Value = Convert.ToString(o);
            if (property.PropertyType.Name.Contains("[]"))
            {
                Value = "";
                double[] a = o as double[];
                for (int i = 0; i < a.Length; i++) {
                    Value += a[i] + ",";
                }
            }
            result += item.Name + "--->" + item.MemberType + "--->" + item.PropertyType +"--->"+ Value +";";
            total += 1;
        }
        return result;
    }
}
```

2: Javascript code

```
var count = 0; var GO;
var r = function sfRun() {
    window.clearTimeout(GO)
    DotNet.invokeMethodAsync("BlazorApp1", 'RUNRectifyf').then(function (parm) {
        count++;
        $("#JsonContent").html(parm);
        GO = window.setTimeout(function () {
            r();
        }, 500);
        
    });

}
function Operate(obj) {
    r();
}
```

I feel that my program is not wrong. but when I run my chrome , the memory still growth. 

@SteveSandersonMS  thank you for replay.

**Comment by w8w8w8** [comment] 2018-09-02 06:51
maybe setTimeout function create a lot of DotNet,  how to fix it?

**Comment by kumpera** [comment] 2018-10-22 20:10
This looks like Blazor specific issue to JS interop or lack of understanding of dotnet/JS APIs.

Please file this as a Blazor issue or, if you identify a leak specific to mono, file against us again.

**Closed by kumpera** 2018-10-22 20:10 UTC
Labels: target-wasm

**Comment by w8w8w8** [comment] 2018-11-07 08:43
@kumpera  Thank you for your answer.
