### ISSUE TITLE
mcs not working on a HelloWorld application in C#, something about a magic number and ConsoleDriver

### ISSUE THREAD

**Issue by DenLilleMand** [mono/mono#6768] opened 2018-02-02 22:32 UTC
## Steps to Reproduce
I am running the latest version of archlinux, my error as explained below is related to a ConsoleDriver, and i think it could be because i don't have a full desktop environment like Gnome or any of the others. Instead i just have a xorg-server, i3 and some gtk/qt-5 packages, i can run all graphical applications just fine. 

Now i know that my issue, considering the platform i use - is a little hard to guess, but i just have absolutely no idea where to start, i don't think my error gives any hints at all as to what could be wrong, which is why any input would help a lot!. 

1. sudo pacman -Syu mono mono-tools mono-addins msbuild-bin
2. create a helloworld.cs file(with the c# code in it)
3. mcs helloworld.cs

![error](https://user-images.githubusercontent.com/8144937/35757635-581b917a-0870-11e8-9814-c76626285f37.png)

## Current Behavior

whenever i run mcs i get an exception related to a Magic number is wrong, and it looks like it is related to the ConsoleDriver, even though i already installed xterm. 

## Expected Behavior
Compile the Main.cs into a Main.exe

### On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.4.1 (makepkg/e66d9abbb27 Thu Nov  9 22:28:33 CET 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
### Stacktrace

```
Please paste the stacktrace here if available.
```
 denlillemand@denlillemand  ~/test  mcs Main.cs 
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.ConsoleDriver' threw an exception. ---> System.Exception: Magic number is wrong: 542
  at System.TermInfoReader.ReadHeader (System.Byte[] buffer, System.Int32& position) [0x00028] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.TermInfoReader..ctor (System.String term, System.String filename) [0x0005f] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.TermInfoDriver..ctor (System.String term) [0x00055] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.ConsoleDriver.CreateTermInfoDriver (System.String term) [0x00000] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.ConsoleDriver..cctor () [0x0004d] in <a84b655e5e6a49ee96b338ec792f5580>:0 
   --- End of inner exception stack trace ---
  at System.Console.SetupStreams (System.Text.Encoding inputEncoding, System.Text.Encoding outputEncoding) [0x00007] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.Console..cctor () [0x0008e] in <a84b655e5e6a49ee96b338ec792f5580>:0 
   --- End of inner exception stack trace ---
  at Mono.CSharp.Driver.Main (System.String[] args) [0x00019] in <2b1e99ce45b54209bdcdab138d9758ae>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.ConsoleDriver' threw an exception. ---> System.Exception: Magic number is wrong: 542
  at System.TermInfoReader.ReadHeader (System.Byte[] buffer, System.Int32& position) [0x00028] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.TermInfoReader..ctor (System.String term, System.String filename) [0x0005f] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.TermInfoDriver..ctor (System.String term) [0x00055] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.ConsoleDriver.CreateTermInfoDriver (System.String term) [0x00000] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.ConsoleDriver..cctor () [0x0004d] in <a84b655e5e6a49ee96b338ec792f5580>:0 
   --- End of inner exception stack trace ---
  at System.Console.SetupStreams (System.Text.Encoding inputEncoding, System.Text.Encoding outputEncoding) [0x00007] in <a84b655e5e6a49ee96b338ec792f5580>:0 
  at System.Console..cctor () [0x0008e] in <a84b655e5e6a49ee96b338ec792f5580>:0 
   --- End of inner exception stack trace ---
  at Mono.CSharp.Driver.Main (System.String[] args) [0x00019] in <2b1e99ce45b54209bdcdab138d9758ae>:0

**Comment by DenLilleMand** [comment] 2018-02-02 22:34
Just to clear up that it is not the applications syntax that has anything to do with it: 

![app](https://user-images.githubusercontent.com/8144937/35757934-9e752d6a-0871-11e8-8705-5ccd18459a60.png)

**Comment by lewurm** [comment] 2018-02-02 22:46
Thanks for your report. This is a duplicate of https://github.com/mono/mono/issues/6752

**Closed by lewurm** 2018-02-02 22:46 UTC
