### ISSUE TITLE
Memory leak when calling static methods with large arrays

### ISSUE THREAD

**Issue by AxlPr** [mono/mono#10126] opened 2018-08-15 13:08 UTC
## Steps to Reproduce

1.  Run the attached code as a console application.
2.  It should crash before the program completes.

[Program.zip](https://github.com/mono/mono/files/2290287/Program.zip)

### Current Behavior

Program crashes between 5-10 iterations with out of memory exception.

### Expected Behavior

Program should not run out of memory. Running with MS .Net 4.6.2 framework it doesn't run out of memory and completes.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X ] Windows

**Version Used**:

5.14.0

## Stacktrace

Unhandled Exception:
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
  at (wrapper alloc) System.Object.AllocVector(intptr,intptr)
  at MonoTest.Program.CreateLargeArrays () [0x0000b] in <fd61d313f034424b885e4cfd086f0ba5>:0
  at MonoTest.Program.Main (System.String[] args) [0x00014] in <fd61d313f034424b885e4cfd086f0ba5>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
  at (wrapper alloc) System.Object.AllocVector(intptr,intptr)
  at MonoTest.Program.CreateLargeArrays () [0x0000b] in <fd61d313f034424b885e4cfd086f0ba5>:0
  at MonoTest.Program.Main (System.String[] args) [0x00014] in <fd61d313f034424b885e4cfd086f0ba5>:0

**Comment by marek-safar** [comment] 2018-10-03 08:48
@BrzVlad any insight into this one?

**Comment by BrzVlad** [comment] 2018-10-03 09:52
@AxlPr I can't reproduce this issue with mono 5.14, amd64 on windows. Did over 1000 iterations there is no unbounded memory increase. The applications always stays below 400MB. Please run with MONO_LOG_LEVEL=debug and MONO_LOG_MASK=gc and track the heap growth and also check the total used memory of the mono process.

Maybe your system is low on memory and mono happens to use more memory than .NET due to pinning/gc policies.

**Comment by SamMonoRT** [comment] 2019-06-06 14:24
@AxlPr - is this still an issue after suggestions from BrzVlad above ?

**Comment by SamMonoRT** [comment] 2019-08-16 12:51
Closing this issue. @AxlPr - please re-open if this is still reproducible.

**Closed by SamMonoRT** 2019-08-16 12:51 UTC
Labels: area-Runtime: GC
