### ISSUE TITLE
Loading denied assemblies via `Assembly.LoadFrom` can cause issues, eg. for VSMac

### ISSUE THREAD

**Issue by radical** [mono/mono#8726] opened 2018-05-16 00:54 UTC
Usually, if an assembly depends on a known "bad"(windows specific implementation) assembly then the mono runtime can deny loading
it. But if the load is initiated explicitly like via `Assembly.LoadFrom`, then the assembly gets loaded (https://github.com/mono/mono/blob/2018-02/mono/metadata/image.c#L1363-L1365)
with a `Loading problematic image ...`.

For example, take `System.Runtime.InteropServices.RuntimeInformation.dll`. It's `RuntimeInformation.IsOSPlatform` API's response
depends on what platform it was built was for. So, a windows specific version would return true even it is running on macOS. Normally,
this gets caught and denied loading. But if it is explicitly loaded via `Assembly.LoadFrom`, then that will break
any subsequent code that depends on that API!

This can show up in VSMac, if some addin loads the bad assembly before the good copy has been loaded into the app domain. Then the
subsequent use of msbuild APIs that depend on `IsOSPlatform` break:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Build.Collections.MSBuildNameIgnoreCaseComparer' threw an exception. ---> System.EntryPointNotFoundException: GetSystemInfo
  at (wrapper managed-to-native) Microsoft.Build.Shared.NativeMethodsShared.GetSystemInfo(Microsoft.Build.Shared.NativeMethodsShared/SYSTEM_INFO&)
```

Here the windows specific code path runs on macOS, because of the `IsOSPlatform`'s result!

Related: https://github.com/mono/monodevelop/issues/4788

**Comment by radical** [comment] 2018-05-16 00:59
@lambdageek @kumpera @marek-safar @mhutch @akoeplinger

**Comment by Therzok** [comment] 2018-05-16 09:48
Nice find!

**Comment by marek-safar** [comment] 2018-05-16 12:14
@lambdageek did your context load changes fix the problem?

**Comment by marek-safar** [comment] 2018-05-17 07:26
@lambdageek I certainly prefer consistent behaviour in this case and we should use same logic as we do when loading the assembly using other API. That leaves use with only reflection context APIs behaving differently but that sounds reasonable to me.

I'd like to see this in 2018-04 because we are still testing the release and we can take it out if necessary. I agree that backporting to earlier versions (15.8 and before) might be problematic but we'd have to find a different workaround in that case.

**Comment by marek-safar** [comment] 2018-05-23 10:16
@lambdageek how confident are you to landing this to 2018-02?

**Comment by lambdageek** [comment] 2018-06-15 14:09
We had to revert the fix for this issue on `2018-06` and `2018-04`.  It's fixed on master (need at least 60f06e6ca26c28f874f67503cb58e7fb76095713 to both fix this issue and also not break MSBuild).

**Comment by mhutch** [comment] 2018-06-15 17:39
@lambageek is that a temporary revert or do we need to think about alternative workarounds for MD running on those releases?

/cc @slluis

**Comment by lambdageek** [comment] 2018-06-15 17:55
@mhutch The main motivation for the reverts was to unblock XI and XA moving to 2018-04 and to nightly CI builds of the MDK.  The corrected fix for 2018-06 is in PR #9170. I'm going to do the 2018-04 updated PR imminently.

**Comment by lambdageek** [comment] 2018-06-19 20:42
Ok, this should be fixed (again) on `2018-04` (commit f22c8b706eb8459efb6d546c9fd1e8aa3734db03) and `2018-06` (commit 9ec4d30693eb6632820574edea7e1605fe894ab6).

Closing.

**Closed by lambdageek** 2018-06-19 20:42 UTC
Labels: area-Runtime: Loader

**Comment by Therzok** [comment] 2018-06-26 10:07
What about 2018-02 (5.12 series)?

**Comment by lambdageek** [comment] 2018-06-28 15:00
We can do a backport to `2018-02`, but it is unlikely to make it into any stable release.

**Comment by slluis** [comment] 2018-06-28 15:16
@lambdageek why not? 2018-02 is part of the 15.8 release.

**Comment by lambdageek** [comment] 2018-06-28 15:57
@slluis @Therzok  Was this a regression?

Backport for `2018-02` is at #9367

/cc @luhenry

**Comment by Therzok** [comment] 2018-07-04 21:12
Our MSBuild builder just started crashing, so yes, it was a regression.
