### ISSUE TITLE
Download for Mac is 5.8.0.129, not 5.10.0

### ISSUE THREAD

**Issue by jdeibele** [mono/mono#7598] opened 2018-03-13 18:35 UTC
Screenshot shows the site saying 5.10.0 Stable but the actual download is 5.8.0.129

I didn't see a way to contact webmaster.   Apologies if I missed it.

![screen shot 2018-03-13 at 11 29 54 am](https://user-images.githubusercontent.com/264802/37362416-5cc6f6b4-26b2-11e8-911f-9c7f6bff441d.png)

**Comment by akoeplinger** [comment] 2018-03-13 18:40
That is intentional, check the note below the download button:

> The Stable channel on Mac OS X defaults to the Visual Studio release channel packages to avoid confusion with the Visual Studio for Mac releases of Mono. If you really want the stable version, you can find it [here](https://download.mono-project.com/archive/5.10.0/macos-10-universal/MonoFramework-MDK-5.10.0.160.macos10.xamarin.universal.pkg), but be aware that the stability of Visual Studio for Mac is only guaranteed with the Visual Studio channel releases.

Duplicate of https://github.com/mono/mono/issues/7452

/cc @brendanzagaeski

**Closed by akoeplinger** 2018-03-13 18:40 UTC

**Comment by marek-safar** [comment] 2018-03-14 07:28
I see how this is confusing and we need to change this. The note below is presumably not read by anyone

**Comment by akoeplinger** [comment] 2018-03-19 10:59
We made this less confusing now by providing download buttons for both versions.

**Comment by jdeibele** [comment] 2018-03-19 18:14
That's much better.   Thank you.
