### ISSUE TITLE
[runtime] Type 'System.Text.Latin1Encoding' is not marked as Serializable. On mono 5.16 with fastcgi-mono-server4

### ISSUE THREAD

**Issue by andern** [mono/mono#11237] opened 2018-10-18 12:38 UTC
## Steps to Reproduce

1. Create endpoint returning `StreamContent` as [attachment](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)
2. Host endpoint on .NET Framework 4.7.1 on Mono 5.16 with fastcgi-mono-server4
3. Call said endpoint

_It works as expected on Mono 5.14!_

### Current Behavior

HTTP Endpoints in WebAPI returning `StreamContent` as [attachment](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) fails (see stack trace below)

### Expected Behavior

I expect no runtime errors when calling the endpoint

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

Running in Docker using mono:latest (5.16.0.179 as I'm writing this)
_It does not fail on Mono 5.14_

**Version Used**:

.NET Framework 4.7.1 on mono 5.16

## Stacktrace

```
Internal error: OutputPage threw an exception System.Runtime.Serialization.SerializationException: Type 'System.Text.Latin1Encoding' in Assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers (System.RuntimeType type) [0x00045] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.FormatterServices+<>c__DisplayClass9_0.<GetSerializableMembers>b__0 (System.Runtime.Serialization.MemberHolder _) [0x00000] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) [0x00034] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.FormatterServices.GetSerializableMembers (System.Type type, System.Runtime.Serialization.StreamingContext context) [0x0005e] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo () [0x0003d] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize (System.Object obj, System.Runtime.Serialization.ISurrogateSelector surrogateSelector, System.Runtime.Serialization.StreamingContext context, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit serObjectInfoInit, System.Runtime.Serialization.IFormatterConverter converter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter objectWriter, System.Runtime.Serialization.SerializationBinder binder) [0x00158] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize (System.Object obj, System.Runtime.Serialization.ISurrogateSelector surrogateSelector, System.Runtime.Serialization.StreamingContext context, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit serObjectInfoInit, System.Runtime.Serialization.IFormatterConverter converter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter objectWriter, System.Runtime.Serialization.SerializationBinder binder) [0x00006] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize (System.Object graph, System.Runtime.Remoting.Messaging.Header[] inHeaders, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter serWriter, System.Boolean fCheck) [0x0018b] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers, System.Boolean fCheck) [0x0006e] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers) [0x00000] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph) [0x00000] in <3833a6edf2074b959d3dab898627f0ac>:0
at System.Runtime.Remoting.RemotingServices.SerializeCallData (System.Object obj) [0x00053] in <3833a6edf2074b959d3dab898627f0ac>:0
at (wrapper xdomain-invoke) Mono.WebServer.FastCgi.Responder.SendOutput(string,System.Text.Encoding)
at (wrapper remoting-invoke-with-check) Mono.WebServer.FastCgi.Responder.SendOutput(string,System.Text.Encoding)
at Mono.WebServer.FastCgi.WorkerRequest.EnsureHeadersSent () [0x0003b] in <68478cb36da347a7b92b8da413732593>:0
at Mono.WebServer.FastCgi.WorkerRequest.CloseConnection () [0x00018] in <68478cb36da347a7b92b8da413732593>:0
at System.Web.HttpResponse.Close () [0x00011] in <e2168dd7a1c34bdeb7d248883273aace>:0
at System.Web.HttpApplication.FinalErrorWrite (System.Web.HttpResponse response, System.String error) [0x00011] in <e2168dd7a1c34bdeb7d248883273aace>:0
at System.Web.HttpApplication.OutputPage () [0x000e3] in <e2168dd7a1c34bdeb7d248883273aace>:0
at System.Web.HttpApplication.PipelineDone () [0x00032] in <e2168dd7a1c34bdeb7d248883273aace>:0
```

**Comment by marek-safar** [comment] 2018-10-18 14:39
Duplicate of #10289

**Closed by marek-safar** 2018-10-18 14:39 UTC
