### ISSUE TITLE
Adding System.Drawing.Common.dll reference for XI/XA projects

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#13483] opened 2019-03-15 15:35 UTC
Since we moved types from Mono.Android.dll and Xamarin.iOS/WatchOS/TVOS.dll to System.Drawing.Common.dll user projects would fail to compile. We need to add some msbuild logic to add a reference to the assembly automatically.

We need it for xamarin-android 2018-10 and xamarin-macios 2019-02.

/cc @radical

**Comment by lewing** [comment] 2019-04-05 02:41
@radical  what is the status here?

**Comment by spouliot** [comment] 2019-05-06 14:40
This makes 60+ of our samples tests fail compilation - which means it will affect many customer projects. c.c. @chamons / @bholmes  and @marek-safar

**Comment by radical** [comment] 2019-05-07 18:49
Could you please point me to some of the samples so that I can fix and test this?

**Comment by radical** [comment] 2019-05-07 19:04
And should I test this with mono 2019-02? For both XI and XA?
And IIUC, this is not required for XM, correct?

**Comment by radical** [comment] 2019-05-07 19:12
Where do I find XI builds for 2019-02? I'm looking at https://jenkins.mono-project.com/view/All/ but I'm not sure which one corresponds to 2019-02. The change will just be in targets file, so I don't need to build XI locally.

**Comment by spouliot** [comment] 2019-05-07 19:30
@radical `2019-02` is merged in master, before `d16-2` was branched. Any build from those 2 branches can be used. You can use the latest https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/master/62f0d294293ff53496bdaa6530d6356af97e9954/643/package/xamarin.ios-12.15.0.24.pkg

You can see all samples builds from https://dev.azure.com/xamarin/internal/_build?definitionId=23
Most of them are inside xamarin repos

Here's one https://github.com/xamarin/ios-samples/tree/master/UICatalog
and the related failure https://dev.azure.com/xamarin/internal/_build/results?buildId=1547&view=ms.vss-test-web.build-test-results-tab&runId=1002404&resultId=100039&paneView=debug

**Comment by radical** [comment] 2019-05-07 21:41
I was able to reproduce and fix the iOS case and am able to build most of the projects in `ios-samples` repo (except few which need a device or are broken in other ways). But the only failing watchOS samples were complaining:
  `error : Xcode 10 does not support watchOS 1 apps. Either upgrade to watchOS 2 apps, or use an older version of Xcode`

Where can I find some watchOS and tvOS samples to test?

**Comment by radical** [comment] 2019-05-07 21:59
@akoeplinger what build of XA should I be using to fix+test this?

**Comment by radical** [comment] 2019-05-07 22:07
I added `this.StatusLabel.SetText("Activating..." + PointF.Empty);` and `using System.Drawing` to `watchOS/SimpleWatchConnectivity` sample project.
- Is that fine?
- Building with `/p:Platform=iPhoneSimulator /p:Configuration=Debug /p:CodesignEntitlements=`:
  - No errors, as it is picking up the new reference from `/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets`
- And I tried the same thing with `tvos/Hello-tvOS` sample and same results.

Does that look sane? If it does, then the single change seems to be enough.

**Comment by spouliot** [comment] 2019-05-08 01:38
> except few which need a device or are broken in other ways

@radical afaik all the samples built fine before the 2019-02 merge (c.c. @rolfbjarne) so no new code (or device) should be needed to build them.The logs, from the azdo link, should which configuration was used to build the projects, I guess it's possible that some configurations might not build.

Do you have a PR/diff we could apply to have the bot confirm the fix ?
Thanks!

**Comment by radical** [comment] 2019-05-08 04:04
@spouliot https://github.com/xamarin/xamarin-macios/pull/6011 . This is against master.

**Comment by rolfbjarne** [comment] 2019-05-08 05:35
@spouliot no, not all samples in all repos built fine, we have a blacklist of samples that don't build (one example being watchOS 1 projects).

**Closed** 2019-05-09 23:20 UTC
Labels: area-Tools: msbuild, target-xamarin-ios, task

**Comment by radical** [comment] 2019-05-21 12:59
I tested with XA by trying to use `PointF.Empty` and `System.Drawing.Color` in XA's `HelloWorld` sample. And it builds fine with XA/master, because it is adding references to all the Facades which includes `System.Drawing.Common.dll`.

`/reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Drawing.Common.dll`

So, AFAICS, we don't need to do anything on XA side for this.
