### ISSUE TITLE
Strange error when trying to run xsp server with aspx web forms using vb language

### ISSUE THREAD

**Issue by FalcoGer** [mono/mono#10066] opened 2018-08-13 13:59 UTC
## Steps to Reproduce

1. Install latest mono with `apt-get install mono-complete` on ubuntu 18.04 after setting up mono repository. (5.14.0.177) for arm64
2. Dump the following structure into /var/www/vbTest/
```
TestPage.aspx
TestPage.aspx.vb
Web.config
```

TestPage.aspx:
```
<%@ Page Language="vb" AutoEventWireup="true" CodeFile="TestPage.aspx.vb" Inherits="TestPage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            VB - TEST
            Hallo WELT!
            <br />
            Die zeit ist: <%= DateTime.Now.ToString("dd.MM.yyyy HH:mm:ss.fffff") %>
        </div>
    </form>
</body>
</html>
```

TestPage.aspx.vb
```
Imports System

' Partial Class TestPage
Public Class TestPage

    Inherits System.Web.UI.Page

    Sub Page_Load(ByVal sender As Object, e As System.EventArgs) Handles Me.Load
        Response.Write("Response write!")
    End Sub

End Class
```

Web.config:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
  Informationen zur Konfiguration Ihrer ASP.NET-Anwendung finden Sie unter
  https://go.microsoft.com/fwlink/?LinkId=169433
  -->
<configuration>
  <system.web>
    <compilation debug="true" targetFramework="4.6.1"/>
    <httpRuntime targetFramework="4.6.1"/>
    <customErrors mode="Off"></customErrors>
  </system.web>
</configuration>
```
3. start xsp4 or run through apache mod_mono
```xsp4 --port=80 --address=192.168.115.31 --applications="/:/var/www/vbTest/" --printlog```

4. attempt loading the page

![vb_bug](https://user-images.githubusercontent.com/16250196/44035973-fd18ffe6-9f10-11e8-8dcf-322b6a9aacc7.png)

### Current Behavior

c# websites work just fine, exactly the same page, just the syntax changed.
vb website display some strange error in an autogenerated file.
Building normal .vb files into programs using vbnc works just fine also.

the error code is this:
```
Application Exception
System.Web.Compilation.CompilationException
error VBNC30248: CHANGEME
Description: Error compiling a resource required to service this request. Review your source file and modify it to fix this error.

Details: error VBNC30248: CHANGEME

Error origin: Compiler

Error source file: /tmp/www-data-temp-aspnet-0/9a16994c/App_Web_x3qkon5b_2.vb

Exception stack trace:
  at System.Web.Compilation.AssemblyBuilder.BuildAssembly (System.Web.VirtualPath virtualPath, System.CodeDom.Compiler.CompilerParameters options) [0x00312] in <3e5867e3e7b34f59bf9d390804a334b1>:0 
  at System.Web.Compilation.AssemblyBuilder.BuildAssembly (System.Web.VirtualPath virtualPath) [0x00008] in <3e5867e3e7b34f59bf9d390804a334b1>:0 
  at System.Web.Compilation.BuildManager.GenerateAssembly (System.Web.Compilation.AssemblyBuilder abuilder, System.Web.Compilation.BuildProviderGroup group, System.Web.VirtualPath vp, System.Boolean debug) [0x00202] in <3e5867e3e7b34f59bf9d390804a334b1>:0 
  at System.Web.Compilation.BuildManager.BuildInner (System.Web.VirtualPath vp, System.Boolean debug) [0x00106] in <3e5867e3e7b34f59bf9d390804a334b1>:0 
Error source context:
Error lines: 1

1: #ExternalChecksum("/var/www/vbTest/TestPage.aspx","{406ea660-64cf-4c82-b6f0-42d48172a799}","0F1C73A9067089D94F1EE58271C3DC55")
2: '------------------------------------------------------------------------------
3: ' <auto-generated>
Full error source code: (click to show):
Version Information: 5.14.0.177 (tarball Mon Aug 6 09:52:34 UTC 2018); ASP.NET Version: 4.0.30319.42000
```

```
1: #ExternalChecksum("/var/www/vbTest/TestPage.aspx","{406ea660-64cf-4c82-b6f0-42d48172a799}","0F1C73A9067089D94F1EE58271C3DC55")
2: '------------------------------------------------------------------------------
3: ' <auto-generated>
4: '     This code was generated by a tool.
5: '     Runtime Version:4.0.30319.42000
6: '
7: '     Changes to this file may cause incorrect behavior and will be lost if
8: '     the code is regenerated.
9: ' </auto-generated>
10: '------------------------------------------------------------------------------
11: 
12: Option Strict Off
13: Option Explicit On
14: 
15: Imports System
16: Imports System.Collections
17: Imports System.Collections.Specialized
18: Imports System.Configuration
19: Imports System.Text
20: Imports System.Text.RegularExpressions
21: Imports System.Web
22: Imports System.Web.Caching
23: Imports System.Web.Profile
24: Imports System.Web.Security
25: Imports System.Web.SessionState
26: Imports System.Web.UI
27: Imports System.Web.UI.HtmlControls
28: Imports System.Web.UI.WebControls
29: 
30: 
31: Partial Public Class TestPage
32:     Implements System.Web.SessionState.IRequiresSessionState
33:     
34:     
35:     #ExternalSource("/var/www/vbTest/TestPage.aspx",6)
36:     Protected _bctrl_5 As Global.System.Web.UI.HtmlControls.HtmlHead
37:     
38:     #End ExternalSource
39:     
40:     
41:     #ExternalSource("/var/www/vbTest/TestPage.aspx",7)
42:     Protected _bctrl_6 As Global.System.Web.UI.HtmlControls.HtmlMeta
43:     
44:     #End ExternalSource
45:     
46:     
47:     #ExternalSource("/var/www/vbTest/TestPage.aspx",8)
48:     Protected _bctrl_7 As Global.System.Web.UI.HtmlControls.HtmlTitle
49:     
50:     #End ExternalSource
51:     
52:     
53:     #ExternalSource("/var/www/vbTest/TestPage.aspx",11)
54:     Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm
55:     
56:     #End ExternalSource
57:     
58:     Protected ReadOnly Property ApplicationInstance() As System.Web.HttpApplication
59:         Get
60:             Return CType(Me.Context.ApplicationInstance,System.Web.HttpApplication)
61:         End Get
62:     End Property
63:     
64:     Protected ReadOnly Property Profile() As System.Web.Profile.DefaultProfile
65:         Get
66:             Return CType(Me.Context.Profile,System.Web.Profile.DefaultProfile)
67:         End Get
68:     End Property
69: End Class
70: 
71: Namespace ASP
72:     
73:     Public Class testpage_aspx
74:         Inherits Global.TestPage
75:         Implements System.Web.IHttpHandler
76:         
77:         Private Shared __initialized As Boolean = false
78:         
79:         Private Shared __stringResource As Object = Nothing
80:         
81:         Private Shared __fileDependencies As Object = Nothing
82:         
83:         Private Shared __autoHandlers As Integer
84:         
85:         Public Sub New()
86:             MyBase.New
87:             Dim dependencies() As String
88:             CType(Me,Global.System.Web.UI.Page).AppRelativeVirtualPath = "~/TestPage.aspx"
89:             If (Global.ASP.testpage_aspx.__initialized = false) Then
90:                 dependencies = New String(1) {}
91:                 dependencies(0) = "~/TestPage.aspx.vb"
92:                 dependencies(1) = "~/TestPage.aspx"
93:                 Global.ASP.testpage_aspx.__fileDependencies = Me.GetWrappedFileDependencies(dependencies)
94:                 Global.ASP.testpage_aspx.__initialized = true
95:             End If
96:         End Sub
97:         
98:         <System.Obsolete()>  _
99:         Protected Overrides Property AutoHandlers() As Integer
100:             Get
101:                 Return ASP.testpage_aspx.__autoHandlers
102:             End Get
103:             Set
104:                 ASP.testpage_aspx.__autoHandlers = value
105:             End Set
106:         End Property
107:         
108:         Private Sub __BuildControlTree(ByVal __ctrl As testpage_aspx)
109:             
110:             #ExternalSource("/var/www/vbTest/TestPage.aspx",1)
111:             Me.InitializeCulture
112:             
113:             #End ExternalSource
114:             Dim __parser As System.Web.UI.IParserAccessor = CType(__ctrl,System.Web.UI.IParserAccessor)
115:             
116:             #ExternalSource("/var/www/vbTest/TestPage.aspx",1)
117:             __parser.AddParsedSubObject(New System.Web.UI.LiteralControl("<!DOCTYPE html>"&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(10)&"<html xmlns=""http://www.w3.org/1999/xhtml"">"&Global.Microsoft.VisualBasic.ChrW(10)))
118:             
119:             #End ExternalSource
120:             
121:             #ExternalSource("/var/www/vbTest/TestPage.aspx",1)
122:             Me.__BuildControl__bctrl_5
123:             
124:             #End ExternalSource
125:             
126:             #ExternalSource("/var/www/vbTest/TestPage.aspx",1)
127:             __parser.AddParsedSubObject(Me._bctrl_5)
128:             
129:             #End ExternalSource
130:             
131:             #ExternalSource("/var/www/vbTest/TestPage.aspx",1)
132:             __parser.AddParsedSubObject(New System.Web.UI.LiteralControl(""&Global.Microsoft.VisualBasic.ChrW(10)&"<body>"&Global.Microsoft.VisualBasic.ChrW(10)&"    "))
133:             
134:             #End ExternalSource
135:             
136:             #ExternalSource("/var/www/vbTest/TestPage.aspx",1)
137:             Me.__BuildControl_form1
138:             
139:             #End ExternalSource
140:             
141:             #ExternalSource("/var/www/vbTest/TestPage.aspx",1)
142:             __parser.AddParsedSubObject(Me.form1)
143:             
144:             #End ExternalSource
145:             
146:             #ExternalSource("/var/www/vbTest/TestPage.aspx",1)
147:             __parser.AddParsedSubObject(New System.Web.UI.LiteralControl(""&Global.Microsoft.VisualBasic.ChrW(10)&"</body>"&Global.Microsoft.VisualBasic.ChrW(10)&"</html>"&Global.Microsoft.VisualBasic.ChrW(10)))
148:             
149:             #End ExternalSource
150:         End Sub
151:         
152:         Private Function __BuildControl__bctrl_5() As Global.System.Web.UI.HtmlControls.HtmlHead
153:             Dim __ctrl As Global.System.Web.UI.HtmlControls.HtmlHead
154:             
155:             #ExternalSource("/var/www/vbTest/TestPage.aspx",6)
156:             __ctrl = New Global.System.Web.UI.HtmlControls.HtmlHead("head")
157:             
158:             #End ExternalSource
159:             
160:             #ExternalSource("/var/www/vbTest/TestPage.aspx",6)
161:             Me._bctrl_5 = __ctrl
162:             
163:             #End ExternalSource
164:             
165:             #ExternalSource("/var/www/vbTest/TestPage.aspx",6)
166:             Me.__BuildControl__bctrl_6
167:             
168:             #End ExternalSource
169:             Dim __parser As System.Web.UI.IParserAccessor = CType(__ctrl,System.Web.UI.IParserAccessor)
170:             
171:             #ExternalSource("/var/www/vbTest/TestPage.aspx",6)
172:             __parser.AddParsedSubObject(Me._bctrl_6)
173:             
174:             #End ExternalSource
175:             
176:             #ExternalSource("/var/www/vbTest/TestPage.aspx",6)
177:             Me.__BuildControl__bctrl_7
178:             
179:             #End ExternalSource
180:             
181:             #ExternalSource("/var/www/vbTest/TestPage.aspx",6)
182:             __parser.AddParsedSubObject(Me._bctrl_7)
183:             
184:             #End ExternalSource
185:             Return __ctrl
186:         End Function
187:         
188:         Private Function __BuildControl__bctrl_6() As Global.System.Web.UI.HtmlControls.HtmlMeta
189:             Dim __ctrl As Global.System.Web.UI.HtmlControls.HtmlMeta
190:             
191:             #ExternalSource("/var/www/vbTest/TestPage.aspx",7)
192:             __ctrl = New Global.System.Web.UI.HtmlControls.HtmlMeta()
193:             
194:             #End ExternalSource
195:             
196:             #ExternalSource("/var/www/vbTest/TestPage.aspx",7)
197:             Me._bctrl_6 = __ctrl
198:             
199:             #End ExternalSource
200:             
201:             #ExternalSource("/var/www/vbTest/TestPage.aspx",7)
202:             __ctrl.Content = "text/html; charset=utf-8"
203:             
204:             #End ExternalSource
205:             
206:             #ExternalSource("/var/www/vbTest/TestPage.aspx",7)
207:             CType(__ctrl,System.Web.UI.IAttributeAccessor).SetAttribute("http-equiv", "Content-Type")
208:             
209:             #End ExternalSource
210:             Return __ctrl
211:         End Function
212:         
213:         Private Function __BuildControl__bctrl_7() As Global.System.Web.UI.HtmlControls.HtmlTitle
214:             Dim __ctrl As Global.System.Web.UI.HtmlControls.HtmlTitle
215:             
216:             #ExternalSource("/var/www/vbTest/TestPage.aspx",8)
217:             __ctrl = New Global.System.Web.UI.HtmlControls.HtmlTitle()
218:             
219:             #End ExternalSource
220:             
221:             #ExternalSource("/var/www/vbTest/TestPage.aspx",8)
222:             Me._bctrl_7 = __ctrl
223:             
224:             #End ExternalSource
225:             Return __ctrl
226:         End Function
227:         
228:         Private Sub __Render_form1(ByVal __output As System.Web.UI.HtmlTextWriter, ByVal parameterContainer As System.Web.UI.Control)
229:             __output.Write(""&Global.Microsoft.VisualBasic.ChrW(10)&"        <div>"&Global.Microsoft.VisualBasic.ChrW(10)&"            VB - TEST"&Global.Microsoft.VisualBasic.ChrW(10)&"            Hallo WELT!"&Global.Microsoft.VisualBasic.ChrW(10)&"            <br />"&Global.Microsoft.VisualBasic.ChrW(10)&" "& _ 
230:                     "           Die zeit ist: ")
231:             
232:             #ExternalSource("/var/www/vbTest/TestPage.aspx",16)
233:             __output.Write( DateTime.Now.ToString("dd.MM.yyyy HH:mm:ss.fffff") )
234:             
235:             #End ExternalSource
236:             __output.Write(""&Global.Microsoft.VisualBasic.ChrW(10)&"        </div>"&Global.Microsoft.VisualBasic.ChrW(10)&"    ")
237:         End Sub
238:         
239:         Private Function __BuildControl_form1() As Global.System.Web.UI.HtmlControls.HtmlForm
240:             Dim __ctrl As Global.System.Web.UI.HtmlControls.HtmlForm
241:             
242:             #ExternalSource("/var/www/vbTest/TestPage.aspx",11)
243:             __ctrl = New Global.System.Web.UI.HtmlControls.HtmlForm()
244:             
245:             #End ExternalSource
246:             
247:             #ExternalSource("/var/www/vbTest/TestPage.aspx",11)
248:             Me.form1 = __ctrl
249:             
250:             #End ExternalSource
251:             
252:             #ExternalSource("/var/www/vbTest/TestPage.aspx",11)
253:             __ctrl.ID = "form1"
254:             
255:             #End ExternalSource
256:             __ctrl.SetRenderMethodDelegate(AddressOf Me.__Render_form1)
257:             Return __ctrl
258:         End Function
259:         
260:         Protected Overrides Sub FrameworkInitialize()
261:             MyBase.FrameworkInitialize
262:             Me.SetStringResourcePointer(Global.ASP.testpage_aspx.__stringResource, 0)
263:             Me.__BuildControlTree(Me)
264:             Me.AddWrappedFileDependencies(Global.ASP.testpage_aspx.__fileDependencies)
265:             Me.Request.ValidateInput
266:         End Sub
267:         
268:         Public Overrides Function GetTypeHashCode() As Integer
269:             Return 1927502828
270:         End Function
271:     End Class
272: End Namespace
```

I'm at a loss what to do. No one else seems to have this issue. I guess people just don't use VB for webforms. And even fewer on an arm64 on a raspberry pi 3.

### Expected Behavior

Page loading successfully, displaying the time and writing the response from codefile.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:
5.14.0.177

## Stacktrace

```
  at System.Web.Compilation.AssemblyBuilder.BuildAssembly (System.Web.VirtualPath virtualPath, System.CodeDom.Compiler.CompilerParameters options) [0x00312] in <3e5867e3e7b34f59bf9d390804a334b1>:0 
  at System.Web.Compilation.AssemblyBuilder.BuildAssembly (System.Web.VirtualPath virtualPath) [0x00008] in <3e5867e3e7b34f59bf9d390804a334b1>:0 
  at System.Web.Compilation.BuildManager.GenerateAssembly (System.Web.Compilation.AssemblyBuilder abuilder, System.Web.Compilation.BuildProviderGroup group, System.Web.VirtualPath vp, System.Boolean debug) [0x00202] in <3e5867e3e7b34f59bf9d390804a334b1>:0 
  at System.Web.Compilation.BuildManager.BuildInner (System.Web.VirtualPath vp, System.Boolean debug) [0x00106] in <3e5867e3e7b34f59bf9d390804a334b1>:0 
```

**Comment by BillSobel** [comment] 2018-09-14 18:15
I believe this is a dupe of 9883 (just FYI, hard bug to describe in order to search for it)

**Comment by marek-safar** [comment] 2018-09-21 12:06
Closing as duplicate of #9883

**Closed by marek-safar** 2018-09-21 12:06 UTC

**Comment by vthg2themax** [comment] 2020-05-15 23:30
VB.net doesn't work with ASP.NET WebForms on 20.04 Ubuntu official sources. Changing language on page to C# it immediately works.

**Comment by izlence** [comment] 2020-07-08 07:41
Removing --debug $MONO_OPTIONS from /usr/bin/vbnc worked for me on Ubuntu 20.04.
The result content of /usr/bin/vbnc asfollowing:

```
#!/bin/sh
exec /usr/bin/mono /usr/lib/mono/4.5/vbnc.exe "$@"
```

More info: https://mim.mbirgin.com/?c=posts&id=209

**Comment by J1mb0S1ic3** [comment] 2024-01-05 19:42
> Removing --debug $MONO_OPTIONS from /usr/bin/vbnc worked for me on Ubuntu 20.04. The result content of /usr/bin/vbnc as follow:
> 
> ```
> #!/bin/bash
> 
> for x; do
> if [[ $x = '/tmp'* ]]; then
> sed -i '1{/#Externa/d}' $x
> fi
> done
> 
> exec /usr/bin/mono /usr/lib/mono/4.5/vbnc.exe "$@"
> ```
> 
> More info: https://mim.mbirgin.com/?c=posts&id=209

Confirmed this works as a fix - using latest version of mono on ubuntu server 20.04
