### ISSUE TITLE
Windows Forms with macOS Catalina, Visual Studio and mono

### ISSUE THREAD

**Issue by thijs30** [mono/mono#16890] opened 2019-09-17 12:51 UTC
I noticed mono64 for macOS isn't compatible with Windows.Forms. Compiling an application within Visual Studio at x64 will cause mono64 to crash. Windows.Forms is only supported by mono32.

However, as from macOS Catalina 10.15 (next months update) 32-bit applications won't be supported anymore. This means it won't be possible to debug and thus develop windows form applications on Mac.

Will mono64 be updated to support Windows.Forms applications?

**Comment by filipnavara** [comment] 2019-09-17 13:32
This is already reported as https://github.com/mono/mono/issues/6701 and discussed on that issue. There are currently no plans unless someone from community steps up to do it. We maintain a fork of [System.Windows.Forms with Cocoa backend](https://github.com/emclient/mac-playground) but the support is limited and it's not a simple drop-in replacement.

**Comment by akoeplinger** [comment] 2019-10-07 14:53
Duplicate of https://github.com/mono/mono/issues/6701

**Closed by akoeplinger** 2019-10-07 14:53 UTC
