### ISSUE TITLE
CustomAttribute's typed argument value has incorrect type for enum arguments

### ISSUE THREAD

**Issue by radical** [mono/mono#10555] opened 2018-09-11 21:10 UTC
Test case:

```c#
using System;
using System.Reflection;

namespace dm_play
{
    public enum Levels { one, two, three }

    [AttributeUsage(AttributeTargets.Method)]
    public class TestAttribute : Attribute
    {
        Levels this_level;
        public TestAttribute(Levels level) => this_level = level;
    }

    public class MainClass
    {
        public static void Main(string[] args)
        {
            var mi = typeof(MainClass).FindMembers(MemberTypes.Method, BindingFlags.Instance | BindingFlags.Public, (m, criteria) => m.Name == nameof(MethodWithAttribute), null);

            foreach (CustomAttributeData cad in ((MethodInfo)(mi[0])).CustomAttributes) {
                Console.WriteLine($"attr.Type: {cad.AttributeType}");

                foreach (CustomAttributeTypedArgument cata in cad.ConstructorArguments)
                    Console.WriteLine($"-> cata: {cata.ArgumentType}, val: {cata.Value}, type of val: {cata.Value.GetType()}");
            }
        }

        [TestAttribute(Levels.two)]
        public void MethodWithAttribute() => Console.WriteLine("Hello");
    }

}
```

Expected output: (works with 5.16.0)
```
$ mono dm_play.exe
attr.Type: dm_play.TestAttribute
-> cata: dm_play.Levels, val: two, type of val: dm_play.Levels
```

Actual output: (with master)
```
 $ ~/misc/bin/mono dm_play.exe
attr.Type: dm_play.TestAttribute
-> cata: dm_play.Levels, val: 1, type of val: System.Int32
```

The `CustomAttributeTypedArgument.ArgumentType` is the same, but the `CustomAttributeTypedArgument.Value` has different types:
5.16.x: `dm_play.Levels`
master: `System.Int32`

The commit that introduced this behavior: https://github.com/mono/mono/commit/faaa9a41c66c31708b47bbd55d65de9f24c85aff

This breaks msbuild tests being run with xunit.

cc: @marek-safar @MaximLipnin

**Comment by MaximLipnin** [comment] 2018-09-12 07:04
I'm not sure if it's regression because System.Reflection namespace are moving to CoreFX sources so it's correct to assume that we should follow the CoreFX behavior in general.
The mentioned test case has the same output on CoreFX and NetFX as for actual result above:
`cata: dm_play.Levels, val: 1, type of val: System.Int32`

**Comment by marek-safar** [comment] 2018-09-12 08:58
@radical the .NET output actually what master prints
```
attr.Type: dm_play.TestAttribute
-> cata: dm_play.Levels, val: 1, type of val: System.Int32
```

so it looks like something else broke

**Comment by radical** [comment] 2018-09-12 20:51
@marek-safar You are correct.

I have a better (and more correct) test case:

```
using System;
using System.Reflection;

namespace dm_play
{
    public enum Levels { one, two, three }

    [AttributeUsage(AttributeTargets.Method)]
    public class TestAttribute : Attribute
    {
        object o;
        public TestAttribute(object o) => this.o = o;
    }

    public class MainClass
    {
        public static void Main(string[] args)
        {
            var mi = typeof(MainClass).FindMembers(MemberTypes.Method, BindingFlags.Instance | BindingFlags.Public, (m, criteria) => m.Name == nameof(MethodWithAttribute), null);

            foreach (CustomAttributeData cad in ((MethodInfo)(mi[0])).CustomAttributes)
            {
                Console.WriteLine($"attr.Type: {cad.AttributeType}");

                foreach (CustomAttributeTypedArgument cata in cad.ConstructorArguments)
                    Console.WriteLine($"-> argType: {cata.ArgumentType}, val: {cata.Value}, type of val: {cata.Value.GetType()}");
            }
        }

        [TestAttribute(Levels.two)]
        public void MethodWithAttribute() => Console.WriteLine("Hello");
    }

}

```

The change here is that now the .ctor argument for the attribute is of *type `object` instead of `Levels`*. Now:

```
.net: -> argType: dm_play.Levels, val: 1, type of val: System.Int32

5.16: -> argType: System.Object, val: two, type of val: dm_play.Levels

5.19 -> argType: System.Object, val: 1, type of val: System.Int32
```

The new behavior is closer to .net but isn't entirely correct. The `ArgumentType` is `System.Object` instead of `dm_play.Levels`.
(This causes xunit to not know that the argument was really an enum and needs to be handled accordingly.)

**Comment by MaximLipnin** [comment] 2018-09-13 12:15
@lambdageek Could you help please? Is it correct that the resolving arguments of custom attribute ctor uses a type from ctor signature and it doesn't matter what is a type of actual argument? 

https://github.com/mono/mono/blob/7e2b62cbbb35b9fe997fcaa7aaca3aa6a1668f12/mono/metadata/custom-attrs.c#L1336

**Comment by vargaz** [comment] 2018-09-13 14:37
This seems to work:
<<<<<<<<<<<<<<<<<<<
diff --git a/mono/metadata/custom-attrs.c b/mono/metadata/custom-attrs.c
index 138905412c9..8a7a2c37e9b 100644
--- a/mono/metadata/custom-attrs.c
+++ b/mono/metadata/custom-attrs.c
@@ -1332,8 +1332,12 @@ reflection_resolve_custom_attribute_data (MonoReflectionMethod *ref_method, Mono
        for (i = 0; i < mono_method_signature (method)->param_count; ++i) {
                MonoObject *obj = mono_array_get (typedargs, MonoObject*, i);
                MonoObject *typedarg;
+               MonoType *t;
 
-               typedarg = create_cattr_typed_arg (mono_method_signature (method)->params [i], obj, error);
+               t = mono_method_signature (method)->params [i];
+               if (t->type == MONO_TYPE_OBJECT && obj)
+                       t = m_class_get_byval_arg (obj->vtable->klass);
+               typedarg = create_cattr_typed_arg (t, obj, error);
                goto_if_nok (error, leave);
                mono_array_setref (typedargs, i, typedarg);
        }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by lambdageek** [comment] 2018-09-13 15:27
Is this a bug?
Here's what I get running the repro on .NET Framework on windows:
```
Z:\>Repro10555.exe
attr.Type: dm_play.TestAttribute
-> cata: dm_play.Levels, val: 1, type of val: System.Int32
```

**Closed** 2018-09-16 17:13 UTC
Labels: area-BCL: mscorlib
