### ISSUE TITLE
Serialization error in nightly build

### ISSUE THREAD

**Issue by jaredpar** [mono/mono#10945] opened 2018-10-02 21:28 UTC
## Steps to Reproduce
This was found attempting to get the C# semantic tests running on Mono

1. Clone https://github.com/jaredpar/roslyn
1. Check out the branch `repro/mono-serialize`
1. Make sure mono is on your path
1. Run `./build.sh --restore --build`
1. Run `./build/scripts/test.sh Debug mono Microsoft.CodeAnalysis.CSharp.Symbo` 

### Actual Behavior
This will run the Symbol unit tests only and eventually Mono will throw an exception trying to call `ITestCase.Traits` across `AppDomain` instances. The error is a `NullReferenceException` during serialization 

### Expected Behavior
The xunit process runs to completion 

## On which platforms did you notice this

This was discovered on Ubuntu 18.04. I'm using the latest nightly mono as described by the Download page

https://www.mono-project.com/download/nightly/#download-lin

```
Mono JIT compiler version 5.19.0.290 (tarball Tue Sep  4 10:59:48 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(4)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Stacktrace and full details 

```
    [FATAL ERROR] System.NullReferenceException
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        
        
        Server stack trace: 
          at System.Runtime.Serialization.FormatterServices.GetParentTypes (System.RuntimeType parentType, System.RuntimeType[]& parentTypes, System.Int32& parentTypeCount) [0x0001f] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers (System.RuntimeType type) [0x00089] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.FormatterServices+<>c__DisplayClass9_0.<GetSerializableMembers>b__0 (System.Runtime.Serialization.MemberHolder _) [0x00000] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) [0x00034] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.FormatterServices.GetSerializableMembers (System.Type type, System.Runtime.Serialization.StreamingContext context) [0x0005e] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo () [0x0003d] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize (System.Object obj, System.Runtime.Serialization.ISurrogateSelector surrogateSelector, System.Runtime.Serialization.StreamingContext context, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit serObjectInfoInit, System.Runtime.Serialization.IFormatterConverter converter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter objectWriter, System.Runtime.Serialization.SerializationBinder binder) [0x00158] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize (System.Object obj, System.Runtime.Serialization.ISurrogateSelector surrogateSelector, System.Runtime.Serialization.StreamingContext context, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit serObjectInfoInit, System.Runtime.Serialization.IFormatterConverter converter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter objectWriter, System.Runtime.Serialization.SerializationBinder binder) [0x00006] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write (System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo objectInfo, System.Runtime.Serialization.Formatters.Binary.NameInfo memberNameInfo, System.Runtime.Serialization.Formatters.Binary.NameInfo typeNameInfo) [0x00101] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize (System.Object graph, System.Runtime.Remoting.Messaging.Header[] inHeaders, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter serWriter, System.Boolean fCheck) [0x001d3] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers, System.Boolean fCheck) [0x0006e] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers) [0x00000] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph) [0x00000] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Remoting.RemotingServices.SerializeCallData (System.Object obj) [0x00053] in <5a872f306a874e34bfe4796f739b7324>:0 
          at (wrapper xdomain-dispatch) Xunit.Sdk.TestMethodTestCase.get_Traits(object,byte[]&,byte[]&)
        
        Exception rethrown at [0]: 
          at (wrapper xdomain-invoke) Xunit.Sdk.TestMethodTestCase.get_Traits()
          at MessageSinkMessageExtensions.Dispatch[TMessage] (Xunit.Abstractions.IMessageSinkMessage message, System.Collections.Generic.HashSet`1[T] messageTypes, Xunit.MessageHandler`1[TMessage] callback) [0x0001a] in <7906e2ced2224c19a10a02057b1365de>:0 
          at (wrapper remoting-invoke-with-check) Xunit.MessageSinkAdapter.OnMessageWithTypes(Xunit.Abstractions.IMessageSinkMessage,System.Collections.Generic.HashSet`1<string>)
          at (wrapper xdomain-dispatch) Xunit.MessageSinkAdapter.OnMessageWithTypes(object,byte[]&,byte[]&)
        
        Exception rethrown at [1]: 
          at (wrapper xdomain-invoke) Xunit.MessageSinkAdapter.OnMessageWithTypes(Xunit.Abstractions.IMessageSinkMessage,System.Collections.Generic.HashSet`1<string>)

```

**Comment by jaredpar** [comment] 2018-10-02 21:28
Note: this appears to be a regression between the stable and nightly Mono feeds. These tests all run fine in stable but fail as soon as I move to nightly.

**Comment by marek-safar** [comment] 2018-10-03 07:49
@kg could you look into this one

**Comment by kg** [comment] 2018-10-03 08:54
Started looking at it earlier, will try to come up with a fix

**Comment by kg** [comment] 2018-10-06 23:08
I spent most of the week on this and am completely stumped:
* BinaryFormatter is failing to serialize a dict<string, list<string>> containing one key/value pair, where the value is a list with one string
* It fails for different string values
* It is almost 100% reproducible but not 100%
* Threading is not required for it to fail, and there is a lock around the only bits of shared state it uses (the formatter and its surrogate selector)
* Reproducing all the relevant logic in a reduced test case - either by hand or via remoting - does not reproduce the issue
* The code responsible for serializing the data is pretty simple. I've ruled out every failure theory I can come up with
* Deserializing the bundle immediately after serializing it (in the same domain) fails, just like in the destination domain, so it isn't a problem specific to crossing domains

My only guess is that this is some sort of corruption issue related to the fact that the strings are coming directly out of reflection metadata (to be specific, custom attributes that specify traits for xunit test cases). But the strings look totally valid, and we're not getting any sort of heap corruption crashes or garbage data when examining the managed objects... The trait data looks correct, also.

We haven't touched any of the involved formatter code in ages as far as I can tell, so if we broke this it's somehow broken by changes in some related system. I'll try to bisect it but it's tricky since the process of building and running the tests is 15-30 minutes per go.

**Comment by kg** [comment] 2018-10-12 01:15
This appears to have been regressed by 9dc6c344ac34a470fa0f4fc411e357f7eaf577fd from my bisect.

**Comment by kg** [comment] 2018-10-12 23:33
I did some tracing in the custom modifier comparisons:

```
    Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.GenericConstraintTests.ImplicitImplementation [SKIP]
      Test supported only on CLR
has_cmods mismatch: 0 1
cmod rejected types for equality that were otherwise equal:
'System.Int32'
'System.Int32'
  cmods[0] = 'IsLong'
cmod count mismatch: 2 1
cmod rejected types for equality that were otherwise equal:
'System.Int32'
  cmods[0] = 'IsConst'
  cmods[1] = 'IsLong'
'System.Int32'
  cmods[0] = 'IsConst'
cmod count mismatch: 2 1
cmod rejected types for equality that were otherwise equal:
'System.Int32'
  cmods[0] = 'IsConst'
  cmods[1] = 'IsLong'
'System.Int32'
  cmods[0] = 'IsConst'
has_cmods mismatch: 1 0
cmod rejected types for equality that were otherwise equal:
'System.Int32'
  cmods[0] = 'IsLong'
'System.Int32'
has_cmods mismatch: 1 0
cmod rejected types for equality that were otherwise equal:
'System.Int32'
  cmods[0] = 'IsLong'
'System.Int32'
has_cmods mismatch: 1 0
cmod rejected types for equality that were otherwise equal:
'System.Int32'
  cmods[0] = 'IsLong'
'System.Int32'
has_cmods mismatch: 1 0
cmod rejected types for equality that were otherwise equal:
'System.Int32'
  cmods[0] = 'IsLong'
```

In earlier testing they were actually ```System.Int32&```. I don't know how to find out which test this is happening in because the unit runner appears to have no way to get it to print test names. Something about these equality mismatches is thoroughly breaking the reflection or serialization infrastructure so it never works right again.

**Comment by kg** [comment] 2018-10-26 11:11
@jaredpar, if you use latest mono those hangs should be gone now. I suspect we may have regressed some other cmod related tests, though I did not see any failures when I ran the test suite locally.

**Comment by jaredpar** [comment] 2019-01-28 17:19
Shouldn't this bug be Open given this is still reproducing?

**Comment by marek-safar** [comment] 2019-01-28 17:43
Yep, reopening

**Comment by marek-safar** [comment] 2019-02-18 13:58
Closing this again as it was confirmed as misconfiguration on Roslyn side

**Closed by marek-safar** 2019-02-18 13:58 UTC
Labels: area-Runtime: Metadata, epic: Roslyn Tests, regression
