### ISSUE TITLE
RPM conflicts between msbuild and mono-devel CentOS packages.

### ISSUE THREAD

**Issue by cmolinar** [mono/mono#6757] opened 2018-02-02 14:20 UTC
## Steps to Reproduce

1. Configure http://download.mono-project.com/repo/centos7 as your Yum repository.
2. yum install msbuild monodevelop

## Current Behavior
The RPM transaction fails due to msbuild and mono-devel bringing in the same file.

## Expected Behavior
Packages install successfully.

### On which platforms did you notice this

[ ] macOS
[*] Linux
[ ] Windows

**Version Used**:
CentOS 7.3
msbuild-1:15.4+xamarinxplat.2017.09.14.16.14-0.xamarin.4.epel7.noarch
mono-devel-5.8.0.108-0.xamarin.2.epel7.x86_64

### Stacktrace

```
DEBUG util.py:439:  Transaction check error:
DEBUG util.py:439:    file /usr/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets conflicts between attempted installs of msbuild-1:15.4+xamarinxplat.2017.09.14.16.14-0.xamarin.4.epel7.noarch and mono-devel-5.8.0.108-0.xamarin.2.epel7.x86_64
DEBUG util.py:439:  Error Summary
DEBUG util.py:439:  -------------
DEBUG util.py:577:  Child return code was: 1
```

**Comment by cmolinar** [comment] 2018-02-02 14:39
It seems mono-devel-5.8.0.108-0.xamarin.2.epel7.x86_64 has been removed from the repository and latest version is 5.4.1.7-0.xamarin.2.epel7 again which does not have the issue.
If pulling 5.8.0.108-0 is related to this issue then this can be closed.

**Comment by necuz** [comment] 2018-02-06 09:29
This is still (or again?) an issue.

**Comment by directhex** [comment] 2018-02-06 14:43
I know the cause of the issue, and am in the process of resolving it - the wrong version of msbuild (an old version from August) was promoted from beta to stable, whereas what we wanted is a build from November, which is needed for Mono 5.8 compatibility

**Closed** 2018-02-06 15:36 UTC
Labels: area-Packaging

**Comment by akoeplinger** [comment] 2018-02-06 15:57
This should work now, you may need to run `yum clean expire-cache` to refresh the package repo cache.

**Comment by nealef** [comment] 2018-02-06 16:38
Is/are there new srpms?


This should work now, you may need to run yum clean expire-cache to refresh the package repo cache

**Comment by directhex** [comment] 2018-02-06 19:24
msbuild-1:15.4+xamarinxplat.2017.11.27.11.23-0.xamarin.1.epel7.noarch ?

**Comment by hiradyazdan** [comment] 2019-04-05 14:01
I have an issue with mono 5.16+ that has msbuild 15.0 (/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/MSBuild.dll), but when running mono to get the version of msbuild it gives the latest preview version (16.0.42-preview+g804bde742b). Could this be related to this issue here? This causes conflicts between my class libraries and mono runtime I suspect. This is on OSX by the way.

**Comment by directhex** [comment] 2019-04-08 17:53
Nothing in this issue is related to OSX, and MSBuild versioning is sorta broken (a bit like Mono assemblies go in a 4.5/ directory even though they're 4.7.2). The version reported by msbuild is accurate, the install directory can be ignored.
