### ISSUE TITLE
Instructions for downloading on CentOS could be improved

### ISSUE THREAD

**Issue by JSoet** [mono/mono#16025] opened 2019-08-05 07:54 UTC
## Steps to Reproduce
This is just a report for an improvement to the documentation that I noticed...

I tried to install mono on CentOS and followed the instructions here:
https://www.mono-project.com/download/stable/#download-lin-centos

However when running the first command `rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"` 
I got the error `error: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF: key 1 not an armored public key.`

I was able to figure out that I just needed to go to that link myself, and copy the key into a text file and then do `rpm --import <textFile>` but maybe that could be mentioned on the page as well (or if there is something wrong with the link and the same issue happens for others, then maybe that could be fixed)

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by Floffy75** [comment] 2019-08-05 12:14
This has been a nuisance for me too for some days. It would be great if it was fixed. Thanks for the info about the workaround (key directly in text file) though. That solved my immediate issue.

**Comment by gohelh-adsk** [comment] 2019-08-06 15:59
Vote +1 to fix this issue.  Duplicate issue #15955

**Comment by chicolatino** [comment] 2019-08-11 19:41
Using wget -O also has the same issue.  The fix is what @JSoet metioned: open link in browser, save file, import file.

**Comment by tommai78101** [comment] 2019-08-12 05:00
I can no longer use the workaround posted by @JSoet. Saving the file and then using the `rpm --import` on the text file no longer is accepted.

I'm on CentOS 7.

**Comment by Ansen** [comment] 2019-08-12 11:42
I have same err

**Comment by amirvaza** [comment] 2019-08-12 12:11
> I can no longer use the workaround posted by @JSoet. Saving the file and then using the `rpm --import` on the text file no longer is accepted.
> 
> I'm on CentOS 7.

Open in browser
Copy the content into a file
rpm --import file

Works.

**Comment by Ansen** [comment] 2019-08-12 12:28
key: copy from browser
key2: use curl -o to download

key is ok, key2 import failed.

![image](https://user-images.githubusercontent.com/676412/62864921-a4facd00-bd3f-11e9-9e32-e01a15a47dc1.png)

**Comment by theoneneoxu** [comment] 2019-08-12 23:41
Please help fix the issue. All our release versions of docker image scripts have the rpm command. We rely on the rpm to make all previous versions work.

**Comment by stevegoossens** [comment] 2019-08-13 22:37
Using a suggestion in #9891 I did the following to resolve this:
```
wget https://download.mono-project.com/repo/xamarin.gpg
rpm --import xamarin.gpg
# you could probably the above two steps in one: rpm --import https://download.mono-project.com/repo/xamarin.gpg
```

my `yum install` command (including various packages including `mono-core` and `mono-devel`) that previously failed due to a missing gpg key then succeeded:
```
(...snip...)
Install  5 Packages (+19 Dependent packages)

Total size: 102 M
Installed size: 410 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/epel/packages/mediainfo-19.07-1.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-11.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Is this ok [y/N]: y
(...snip...)
```

**Comment by duncanjwatson** [comment] 2019-08-14 15:49
I was able to make it work by downloading the armored key, then importing into gpg, then exporting an armored key and finally importing into rpm.

`curl -o key.txt "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
gpg --import key.txt
gpg --armor --export releng@xamarin.com>xamarin.txt
rpm --import xamarin.txt`

**Comment by directhex** [comment] 2019-10-08 16:17
Closing, this is a duplicate of https://github.com/mono/mono/issues/15955

**Closed by directhex** 2019-10-08 16:17 UTC
Labels: documentation, os-linux
