### ISSUE TITLE
F# interactive raises 'mono_class_has_static_metadata (klass)' error when using Marshal methods

### ISSUE THREAD

**Issue by alphanumericpassword** [mono/mono#8539] opened 2018-05-02 05:09 UTC
## Steps to Reproduce

Execute the following in Visual Studio for Mac F# interactive on Mono 5.8.1 (also occurs in Rider, but I do not use Rider regularly except in this instance to recreate the issue):
```
>   open System
     open System.IO
     open System.Runtime.InteropServices

>   [<Struct; StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)>]
     type GifHeader = {
     [<MarshalAs(UnmanagedType.ByValTStr, SizeConst = 3)>]
     signature: string
     [<MarshalAs(UnmanagedType.ByValTStr, SizeConst = 3)>]
     version: string
     logicalWidth: int16
     logicalHeight: int16
     }

>   Marshal.SizeOf(typeof<GifHeader>)
```

### Current Behavior

Fails with error:
`* Assertion at class-accessors.c:138, condition 'mono_class_has_static_metadata (klass)' not met`

### Expected Behavior

`Marshal.SizeOf(typeof<GifHeader>)` should return the size in bytes of the struct.
This example works perfectly on Windows 10 with Visual Studio 2017 and .NET Framework 4.7.1

This is severely affecting my Visual Studio experience on Mac, since I cant prototype my work. I have tried to explore the Mono.Unix namespace for an alternative but I can't find an equivalent usage.

## On which platforms did you notice this

[**X**] macOS
[ ] Linux
[ ] Windows

**Version Used**: 5.8.1 (Visual Studio for Mac Release Channel)

**Comment by lewurm** [comment] 2018-05-02 09:15
Thanks for your report! I think that's a duplicate of https://bugzilla.xamarin.com/show_bug.cgi?id=41130 and thus fixed via https://github.com/mono/mono/pull/7055

It's going to be included in the 5.14 (`2018-04`) release, could you try with that? Here's the latest build of the `2018-04` branch: https://xamjenkinsartifact.azureedge.net/build-package-osx-mono/2018-04/63/fd09fd9d44432b1c68a9b34854c5f6f89ffc9a13/MonoFramework-MDK-5.14.0.70.macos10.xamarin.universal.pkg

**Comment by alphanumericpassword** [comment] 2018-05-02 19:36
That worked, but now there are more problems down the line - string marshaling using the MarshalAs attribute doesn't work on Mono/Mac like it does for Windows/.NET Framework. If I leave the attribute `[<MarshalAs(UnmanagedType.ByValTStr, SizeConst = 3)>] signature: string` in the structure, then it will fail as described below by doing the following in FSI:

```
> let buf: byte[] = Array.zeroCreate <| Marshal.SizeOf(typeof<GifHeader>) 
> let gifStream = new FileStream(gifPath, FileMode.Open, FileAccess.Read)
> gifStream.Read(buf, 0, buf.Length)
> let handle: GCHandle = GCHandle.Alloc(buf, GCHandleType.Pinned)
> Marshal.PtrToStructure(handle.AddrOfPinnedObject(), typeof<GifHeader>) :?> GifHeader
_ _ _ _ _ _ _ _ _ _ _ 
 System.NullReferenceException: Object reference not set to an instance of an object
   at (wrapper managed-to-native) System.Object.__icall_wrapper_ves_icall_string_new_wrapper(intptr)
   at (wrapper unknown) FSI_0001+GifHeader.PtrToStructure(intptr,object)
   at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal.PtrToStructure(intptr,System.Type)
   at <StartupCode$FSI_0009>.$FSI_0009.main@ () [0x00014] in <3559b7a807d845d9af9715905a5a1cef>:0 
   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <17f5177733084096b17badd9e32426e5>:0 
```
_Just a disclaimer, I am not 100% sure of the header sizes, I am still playing around with marshaling, but on Windows that just gives me wrong data, not errors._

If I try to use a byte[] instead of a string, and ByValArray instead of ByValTStr, then it throws:
```
 System.Runtime.InteropServices.MarshalDirectiveException: Structure field of type Byte[] can't be marshalled as LPArray
   at (wrapper unknown) FSI_0010+GifHeader.PtrToStructure(intptr,object)
   at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal.PtrToStructure(intptr,System.Type)
   at <StartupCode$FSI_0015>.$FSI_0015.main@ () [0x00014] in <3559b7a807d845d9af9715905a5a1cef>:0 
   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <17f5177733084096b17badd9e32426e5>:0 
```
For this one I don't know why it is referencing the LPArray when I am trying to use ByValArray. Is there a platform difference in default marshaling?

If I marshal the struct without the MarshalAs attributes then it works as expected. Does this need a new issue tracker or do you think this is related? I figured it would be related since it is referencing `System.Reflection.MonoMethod.InternalInvoke`.

**Comment by marek-safar** [comment] 2018-05-02 20:17
Could you please create a new issue for the marshalling problem?

**Closed** 2018-05-02 21:21 UTC
Labels: area-Runtime: Reflection
