### ISSUE TITLE
IOException "Write fault on path" when piping output into head

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#18448] opened 2020-01-14 13:51 UTC
## Steps to Reproduce

1. Run `MONO_OPTIONS=--debug ikdasm /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/mcs.exe | head`
2. Observe IOException

If you don't pipe into `head` then it works.

Sounds similar to https://github.com/mono/mono/pull/17336 as in the new Span overload for StreamWriter shows up in the stacktrace.

I checked Mono 6.6, 6.4 and 6.0, it's broken there too. But it works in Mono 5.20, though it has about a 10 seconds hang before exiting so maybe we were just lucky with our previous implementation.

### Current Behavior

```
$ MONO_OPTIONS=--debug ikdasm /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/mcs.exe | head

// Metadata version: v4.0.30319
.module extern fusion
.module extern libc
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System.Core

Unhandled Exception:
System.IO.IOException: Write fault on path /Users/alexander/dev/mono/[Unknown]
  at System.IO.FileStream.WriteInternal (System.Byte[] src, System.Int32 offset, System.Int32 count) [0x000be] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:658
  at System.IO.FileStream.Write (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00090] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:614
  at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x00080] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/IO/StreamWriter.cs:335
  at System.IO.StreamWriter.WriteSpan (System.ReadOnlySpan`1[T] buffer, System.Boolean appendNewLine) [0x0016b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/IO/StreamWriter.cs:516
  at System.IO.StreamWriter.WriteLine (System.String value) [0x00006] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/IO/StreamWriter.cs:530
  at System.IO.TextWriter+SyncTextWriter.WriteLine (System.String value) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/IO/TextWriter.cs:817
  at (wrapper synchronized) System.IO.TextWriter+SyncTextWriter.WriteLine(string)
  at Ildasm.LineWriter.WriteLine (System.String str, System.Object[] args) [0x00040] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/ikdasm/LineWriter.cs:100
  at Ildasm.Disassembler.WriteAssemblyManifest (Ildasm.LineWriter lw) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/ikdasm/Disassembler.cs:2155
  at Ildasm.Disassembler.Save (System.IO.TextWriter writer) [0x0003d] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/ikdasm/Disassembler.cs:226
  at Ildasm.Program.Main (System.String[] args) [0x003c7] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/ikdasm/Program.cs:176
```
### Expected Behavior

No exception

## On which platforms did you notice this

[ X ] macOS
[ ] Linux
[ ] Windows

**Version Used**: Mono JIT compiler version 6.8.0.61 (2019-10/18920a83f42 Mon Dec  2 06:59:32 EST 2019)

**Comment by akoeplinger** [comment] 2020-01-14 13:53
Hmm this seems to be the same issue as https://github.com/mono/mono/issues/18279, however I don't think it's behaving as designed (it worked in earlier Mono). /cc @baulig @steveisok

**Comment by Nabile-Rahmani** [comment] 2020-01-31 01:30
I stumbled on this as well, and madelson raises a good point about how .NET Core doesn't raise an exception in this case.

But then again it's not the first time .NET Core overlooked behaviour for Linux, so I'm just left wondering which makes the most sense knowing it breaks on stuff like `head`, as was said: dropping data because the stream is closed, or throwing an exception that will be unhandled by most .NET programs.

**Comment by steveisok** [comment] 2020-01-31 01:56
There was a general consensus that the mono behavior was the correct one.  We should file an issue in dotnet/runtime.

**Comment by steveisok** [comment] 2020-01-31 01:57
duplicate of https://github.com/mono/mono/issues/18279

**Closed by steveisok** 2020-01-31 01:56 UTC
Labels: area-BCL: mscorlib, regression
