### ISSUE TITLE
Apparent Hang Around Child Processes

### ISSUE THREAD

**Issue by jonpryor** [mono/mono#12323] opened 2019-01-08 21:08 UTC
The Xamarin.Android team is experiencing "random" hangs on Jenkins from mono, apparently around process exit.

For example, [consider this build log fragment][0] (with timestamps):

	23:37:48   Build succeeded.
	23:37:48       0 Warning(s)
	23:37:48       0 Error(s)
	23:37:48
	23:37:48   Time Elapsed 01:23:14.60
	02:37:48 Build timed out (after 180 minutes). Marking the build as aborted.

The "Build succeeded" message comes from an `msbuild` invocation.
Once `msbuild` finished, we would expect it's process to exit.
*It didn't*.  Instead, the underlying `mono` process is *not* exiting,
presumably deadlocked, until the overall job times out and is killed.

In order to assist in tracking down this hang, @lewurm provided the Xamarin.Android team with a new system mono with additional logging: https://github.com/xamarin/xamarin-android/commit/70530ab1a9ba077817a63ca4617f3e427e5c9594

I do not know if this new mono was actually helpful; regardless, it was replaced as part of the [mono/2018-08 bump](https://github.com/xamarin/xamarin-android/commit/3897e86a7fdd3c0696c6264a7f65b9ff2ffebfbe), and the system mono that Xamarin.Android currently uses does not contain the additional logging.

This hang is causing ~20%+ of our master builds to hang and timeout, with every "brown" build in the **Build History** section being a timeout: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/

**Related**:

  * https://github.com/xamarin/xamarin-android/pull/2357

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1237/console

## Steps to Reproduce

1. Build Xamarin.Android on Jenkins
2. Get (un)lucky
3. Build hangs!

### Current Behavior

20% or more of the Xamarin.Android master builds experience a timeout.

### Expected Behavior

No hangs from mono.

## On which platforms did you notice this

- [X] macOS
- [ ] Linux
- [ ] Windows

**Version Used**:

Mono 5.18.0.162, as provided from: https://xamjenkinsartifact.azureedge.net/build-package-osx-mono/2018-08/128/bc9d709e704fb157eaf4935cb67d272f154cff75/MonoFramework-MDK-5.18.0.162.macos10.xamarin.universal.pkg

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by lewurm** [comment] 2019-01-09 13:58
More thoughts can be seen in this PR, especially this comment:
https://github.com/xamarin/xamarin-android/pull/2440#issuecomment-444668798

**Comment by jonpryor** [comment] 2019-01-09 15:49
Also note that *some* of the thoughts that @lewurm [mentioned](
https://github.com/mono/mono/issues/12323#issuecomment-452705431) are now out-of-date.

Before commit https://github.com/xamarin/xamarin-android/commit/13a692511ad77c1494c2e9aaff84d7d60efb0de0 xamarin-android would run some unit tests by generating a shell script which would contain `msbuild` invocations, and execute that shell script from `msbuild`.  There would thus be a process tree of:

    msbuild (mono) > sh (parallel-targets.sh) > msbuild (mono)

This is why @lewurm's [comment](https://github.com/xamarin/xamarin-android/pull/2440#issuecomment-444668798) mentions `sh`.

Starting with xamarin/xamarin-android@13a69251, the intermediate `parallel-targets.sh` has been replaced with a `<RunParallelTargets/>` task, which uses `System.Diagnostics.Process` to create the child processes.  The process tree now becomes:

    msbuild (mono) > msbuild (mono)

**Comment by jonpryor** [comment] 2019-01-09 16:47
@mjbond-msft is writing a `Jenkinsfile`-based build for xamarin-android: https://github.com/xamarin/xamarin-android/tree/jenkinsfile-pipeline

What's interesting is that the two most recent builds using `Jenkinsfile` has suffered a timeout when executing unit tests: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pipe-eval/

For example:

  * https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pipe-eval/104/flowGraphTable/
  * https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pipe-eval/104/execution/node/119/log/

The `make run-all-tests` log contains:

```
21:15:12   Results (nunit2) saved as TestResult-Java.Interop-Tests.xml
21:51:25 Sending interrupt signal to process
```

**Comment by marek-safar** [comment] 2019-01-23 16:40
I can reproduce something similar locally which looks like a hang after internal SIGABRT.

Full log at https://gist.github.com/marek-safar/f27b1318f3930cf0085769dd17fdc23a

@luhenry who can address this issue?

**Comment by luhenry** [comment] 2019-01-23 18:00
@marek-safar we will need more information from your repro to have any clue what's going wrong. From the stacktrace you provide, it seems to be a bug in `malloc` itself which points to memory corruption.

**Comment by lambdageek** [comment] 2019-01-23 18:21
I've seen this *kind* of stacktrace before with hybrid suspend on OSX - if two threads call `malloc` - and one is preemptively suspended while the other is coop suspended, the coop-suspended thread can get stuck because osx `malloc` uses a lock internally.  If the first thread was suspended while it held the lock, the other one will deadlock.

The problem is that this stacktrace doesn't look like that.  There ought to be a second thread suspended inside malloc or free or something.  And there isn't.

**Comment by lambdageek** [comment] 2019-01-28 21:37
I think this has been fixed on 2018-10 and later with https://github.com/mono/mono/pull/10793.  I'm going to see if we can port that back to 2018-08.

**Comment by lambdageek** [comment] 2019-01-29 19:17
Even with the fix for 10793 backported to 2018-08, I got another hang.  Investigating...

**Comment by marek-safar** [comment] 2019-03-12 08:08
Does it still happen with Mono 2018-10?

**Comment by marek-safar** [comment] 2019-05-30 09:48
Closing, please reopen if you can still experience this issue

**Closed by marek-safar** 2019-05-30 09:48 UTC
Labels: area-Runtime: PAL, target-xamarin-android
