### ISSUE TITLE
BigInteger.Parse is wrong, exceeds Span<char> boundaries

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19239] opened 2020-03-16 17:07 UTC
_From @joshlang on Saturday, March 14, 2020 11:12:43 PM_

```
var slice = "355982374923475".AsSpan(0, 1);
Console.WriteLine(slice.ToString());
Console.WriteLine(BigInteger.Parse(slice));
```

In .net core, output:
```
3
3
```

In blazor, output:
```
3
355982374923475
```

This might belong in the mono repo, but we found it in our client-side blazor app, so I'm reporting it here.  

_Copied from original issue: dotnet/aspnetcore#19863_

**Comment by joshlang** [comment] 2020-03-18 00:17
FormatProvider.Number.cs on line 568:
```
fixed (char* stringPointer = &MemoryMarshal.GetReference(str))
{
    char* p = stringPointer;
    if (!ParseNumber(ref p, options, ref number, sb, numfmt, parseDecimal)
        || (p - stringPointer < str.Length && !TrailingZeros(str, (int)(p - stringPointer))))
    {
        return false;
    }
}
```

The span is being converted into a simple pointer, then tossed into `ParseNumber` which has no idea how long the string is

**Comment by joshlang** [comment] 2020-03-19 17:34
Ok, so...

I'd like this fixed, obviously... but I'm also completely new to this repo.  It doesn't build after a simple pull into visual studio, and while there's lotsa documentation about how to set up the environment and all that............ it could take days.  

I'd still like to contribute.

So consider this a ghetto pull request :D 

All changes are in `System.Numerics` -> `FormatProvider.Number.cs`

Replace `MatchChars` (2 methods) with:
```
private static int MatchChars(ReadOnlySpan<char> p, string str)
{
    return MatchChars(p, str.AsSpan());
}

private static int MatchChars(ReadOnlySpan<char> p, ReadOnlySpan<char> str)
{
    Debug.Assert(p != null && str != null);

    if (str.Length == 0)
    {
        return -1;
    }

    int index = 0;

    // We only hurt the failure case
    // This fix is for French or Kazakh cultures. Since a user cannot type 0xA0 as a
    // space character we use 0x20 space character instead to mean the same.
    while (p[index] == str[index] || (str[index] == '\u00a0' && p[index] == '\u0020'))
    {
        if (++index == str.Length)
        {
            return index;
        }
    }
    return -1;
}
```

Replace `ParseNumber` with:
```
private static unsafe bool ParseNumber(ReadOnlySpan<char> str, out int index, NumberStyles options, ref NumberBuffer number, StringBuilder sb, NumberFormatInfo numfmt, bool parseDecimal)
{
    const int StateSign = 0x0001;
    const int StateParens = 0x0002;
    const int StateDigits = 0x0004;
    const int StateNonZero = 0x0008;
    const int StateDecimal = 0x0010;
    const int StateCurrency = 0x0020;
                
    index = 0;
    if (str.Length == 0)
    {
        return false;
    }

    number.scale = 0;
    number.sign = false;
    string decSep;                  // Decimal separator from NumberFormatInfo.
    string groupSep;                // Group separator from NumberFormatInfo.
    string currSymbol = null;       // Currency symbol from NumberFormatInfo.

    bool parsingCurrency = false;
    if ((options & NumberStyles.AllowCurrencySymbol) != 0)
    {
        currSymbol = numfmt.CurrencySymbol;
        // The idea here is to match the currency separators and on failure match the number separators to keep the perf of VB's IsNumeric fast.
        // The values of decSep are setup to use the correct relevant separator (currency in the if part and decimal in the else part).
        decSep = numfmt.CurrencyDecimalSeparator;
        groupSep = numfmt.CurrencyGroupSeparator;
        parsingCurrency = true;
    }
    else
    {
        decSep = numfmt.NumberDecimalSeparator;
        groupSep = numfmt.NumberGroupSeparator;
    }

    int state = 0;
    bool bigNumber = (sb != null); // When a StringBuilder is provided then we use it in place of the number.digits char[50]
    int maxParseDigits = bigNumber ? int.MaxValue : NumberMaxDigits;

    int next;
    char ch = str[0];

    char* dig = number.digits;

    while (true)
    {
        // Eat whitespace unless we've found a sign which isn't followed by a currency symbol.
        // "-Kr 1231.47" is legal but "- 1231.47" is not.
        if (!IsWhite(ch) || (options & NumberStyles.AllowLeadingWhite) == 0 || ((state & StateSign) != 0 && ((state & StateCurrency) == 0 && numfmt.NumberNegativePattern != 2)))
        {
            if ((((options & NumberStyles.AllowLeadingSign) != 0) && (state & StateSign) == 0) && ((next = MatchChars(str.Slice(index), numfmt.PositiveSign)) != -1 || ((next = MatchChars(str.Slice(index), numfmt.NegativeSign)) != -1 && (number.sign = true))))
            {
                state |= StateSign;
                index = next - 1;
            }
            else if (ch == '(' && ((options & NumberStyles.AllowParentheses) != 0) && ((state & StateSign) == 0))
            {
                state |= StateSign | StateParens;
                number.sign = true;
            }
            else if (currSymbol != null && (next = MatchChars(str.Slice(index), currSymbol)) != -1)
            {
                state |= StateCurrency;
                currSymbol = null;

                // We already found the currency symbol. There should not be more currency symbols. Set
                // currSymbol to NULL so that we won't search it again in the later code path.
                index = next - 1;
            }
            else
            {
                break;
            }
        }
        ch = str[++index];
    }

    int digCount = 0;
    int digEnd = 0;
    while (true)
    {
        if ((ch >= '0' && ch <= '9') || (((options & NumberStyles.AllowHexSpecifier) != 0) && ((ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F'))))
        {
            state |= StateDigits;

            if (ch != '0' || (state & StateNonZero) != 0 || (bigNumber && ((options & NumberStyles.AllowHexSpecifier) != 0)))
            {
                if (digCount < maxParseDigits)
                {
                    if (bigNumber)
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        dig[digCount++] = ch;
                    }

                    if (ch != '0' || parseDecimal)
                    {
                        digEnd = digCount;
                    }
                }
                if ((state & StateDecimal) == 0)
                {
                    number.scale++;
                }
                state |= StateNonZero;
            }
            else if ((state & StateDecimal) != 0)
            {
                number.scale--;
            }
        }
        else if (((options & NumberStyles.AllowDecimalPoint) != 0) && ((state & StateDecimal) == 0) && ((next = MatchChars(str.Slice(index), decSep)) != -1 || ((parsingCurrency) && (state & StateCurrency) == 0) && (next = MatchChars(str.Slice(index), numfmt.NumberDecimalSeparator)) != -1))
        {
            state |= StateDecimal;
            index = next - 1;
        }
        else if (((options & NumberStyles.AllowThousands) != 0) && ((state & StateDigits) != 0) && ((state & StateDecimal) == 0) && ((next = MatchChars(str.Slice(index), groupSep)) != -1 || ((parsingCurrency) && (state & StateCurrency) == 0) && (next = MatchChars(str.Slice(index), numfmt.NumberGroupSeparator)) != -1))
        {
            index = next - 1;
        }
        else
        {
            break;
        }
        ch = str[++index];
    }

    bool negExp = false;
    number.precision = digEnd;
    if (bigNumber)
    {
        sb.Append('\0');
    }
    else
    {
        dig[digEnd] = '\0';
    }

    if ((state & StateDigits) != 0)
    {
        if ((ch == 'E' || ch == 'e') && ((options & NumberStyles.AllowExponent) != 0))
        {
            int temp = index;
            ch = str[++index];
            if ((next = MatchChars(str.Slice(index), numfmt.PositiveSign)) != -1)
            {                            
                ch = str[index = next];
            }
            else if ((next = MatchChars(str.Slice(index), numfmt.NegativeSign)) != -1)
            {
                ch = str[index = next];
                negExp = true;
            }
            if (ch >= '0' && ch <= '9')
            {
                int exp = 0;
                do
                {
                    exp = exp * 10 + (ch - '0');
                    ch = str[++index];
                    if (exp > 1000)
                    {
                        exp = 9999;
                        while (ch >= '0' && ch <= '9')
                        {
                            ch = str[++index];
                        }
                    }
                } while (ch >= '0' && ch <= '9');
                if (negExp)
                {
                    exp = -exp;
                }
                number.scale += exp;
            }
            else
            {
                index = temp;
                ch = str[index];
            }
        }
        while (true)
        {
            if (!IsWhite(ch) || (options & NumberStyles.AllowTrailingWhite) == 0)
            {
                if (((options & NumberStyles.AllowTrailingSign) != 0 && ((state & StateSign) == 0)) && ((next = MatchChars(str.Slice(index), numfmt.PositiveSign)) != -1 || (((next = MatchChars(str.Slice(index), numfmt.NegativeSign)) != -1) && (number.sign = true))))
                {
                    state |= StateSign;
                    index = next - 1;
                }
                else if (ch == ')' && ((state & StateParens) != 0))
                {
                    state &= ~StateParens;
                }
                else if (currSymbol != null && (next = MatchChars(str.Slice(index), currSymbol)) != -1)
                {
                    currSymbol = null;
                    index = next - 1;
                }
                else
                {
                    break;
                }
            }
            ch = str[++index];
        }
        if ((state & StateParens) == 0)
        {
            if ((state & StateNonZero) == 0)
            {
                if (!parseDecimal)
                {
                    number.scale = 0;
                }
                if ((state & StateDecimal) == 0)
                {
                    number.sign = false;
                }
            }
            return true;
        }
    }
    return false;
}
```

And finally, replace `TryStringToNumber` with:
```
internal static unsafe bool TryStringToNumber(ReadOnlySpan<char> str, NumberStyles options, ref NumberBuffer number, StringBuilder sb, NumberFormatInfo numfmt, bool parseDecimal)
{
    Debug.Assert(numfmt != null);

    return 
        !ParseNumber(str, out int index, options, ref number, sb, numfmt, parseDecimal) ||
        (index < str.Length && !TrailingZeros(str, index));
}
```

The gist is to replace usage of pointers with `ReadOnlySpan<char>` instead.

`unsafe` was still required because of the dependency on NumberBuffer's pointer.

Unfortunately, I couldn't test this.  But hopefully it's a head-start for someone familiar with the repo.

**Comment by baulig** [comment] 2020-04-13 09:29
It looks like this has been fixed in corefx here: https://github.com/dotnet/corefx/commit/73a3cf567a7b02ce4f984f5b791da19812fd8aa9.

**Comment by baulig** [comment] 2020-04-13 09:30
You can easily reproduce this with desktop Mono, so it's not a wasm issue.

**Comment by baulig** [comment] 2020-04-13 09:39
Confirmed with Desktop Mono that backporting this CoreFX PR will fix it: https://github.com/mono/corefx/pull/397.

**Closed** 2020-04-13 16:31 UTC
Labels: area-BCL: System.Numerics, target-wasm
