### ISSUE TITLE
System.IO.Compression.FileSsystem tests fail on iOS platforms

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#12376] opened 2019-01-11 11:22 UTC
On Xamarin.iOS we have started executing the tests provided in the test assemblies from the Mono SDK. Some of the tests fail because the required files for them are missing. Following PR https://github.com/xamarin/xamarin-macios/pull/5374 those tests are ignored. Please take a look at the new added ignore file to know which tests had to be ignored and the reasons.

**Comment by akoeplinger** [comment] 2019-02-18 18:59
Duplicate of https://github.com/mono/mono/issues/12354

**Closed by akoeplinger** 2019-02-18 18:59 UTC
Labels: area-SDK: Packaging
