### ISSUE TITLE
Mono no longer passes NULL to dlopen handler when a p/invoke uses the __Internal library name

### ISSUE THREAD

**Issue by grendello** [mono/mono#17693] opened 2019-11-04 15:02 UTC
`Xamarin.Android` installs a fallback `dlopen` handler with Mono to look up symbols defined in XA's runtime which otherwise would not be resolved. One of such special casses are p/invokes into the XA runtime which use code similar to:

```C#
[DllImport ("__Internal", CallingConvention = CallingConvention.Cdecl)]
 internal extern static void monodroid_free (IntPtr ptr);
```

The above call will be resolved by [this dlopen handler](https://github.com/xamarin/xamarin-android/blob/62641b947a7f3c7ddded6a74024f09402934bca9/src/monodroid/jni/monodroid-glue.cc#L1059) to exist in the XA runtime. It used to be that Mono, when it saw
the `__Internal` "library", would pass a `NULL` pointer to the handler. However, sometime in the recent times (somewhere in the Mono `2019-08` branch)  it's changed and [this code fails,](https://github.com/xamarin/xamarin-android/blob/62641b947a7f3c7ddded6a74024f09402934bca9/src/monodroid/jni/monodroid-glue.cc#L1064-L1068) producing the following exception:

```
11-04 12:27:54.899  3339  3339 W monodroid: static void *xamarin::android::internal::MonodroidRuntime::monodroid_dlopen(const char *, int, char **, void *) called
11-04 12:27:54.900  3339  3339 W monodroid:   name == lib__Internal; flags == 0x3
11-04 12:27:55.722  3339  3339 E mono    :
11-04 12:27:55.722  3339  3339 E mono    : Unhandled Exception:
11-04 12:27:55.722  3339  3339 E mono    : System.DllNotFoundException: __Internal assembly:<unknown assembly> type:<unknown type> member:(null)
11-04 12:27:55.722  3339  3339 E mono    :   at (wrapper managed-to-native) Android.Runtime.JNIEnv.monodroid_timing_start(string)
```

As shown above, Mono now passes the `lib__Internal` name instead of `NULL`.

All of this, however, happens **only** in `Xamarin.Android` AppBundle integration tests, other contexts don't produce this failure, it is unfortunately unclear why as of this moment.

**Comment by filipnavara** [comment] 2019-11-04 16:30
Missing `return` here?
https://github.com/mono/mono/blob/3fa5f6c66e5d87e25425f2ced2c21d546aaf3cfe/mono/metadata/native-library.c#L628

**Comment by jonathanpeppers** [comment] 2019-11-04 17:47
This might be related to: https://github.com/xamarin/xamarin-android/issues/3736

I was hitting this error after just doing this in `xamarin-android`:
```
xabuild .\samples\HelloWorld\HelloWorld.csproj /t:Install /bl /p:Configuration=Release /p:AndroidPackageFormat=aab /p:AndroidSupportedAbis=x86
```
What was weird, is the OS kept restarting the app in a loop, and eventually it started successfully. It might also be timing related?

**Comment by CoffeeFlux** [comment] 2019-11-04 22:54
It shouldn't return there, though it should goto the end of the function to propagate the error instead of trying to mangle the name. That won't actually fix the issue though, which is that `mono_dl_open(NULL, flags, error_msg)` is returning NULL.

Apparently `dlopen(NULL, flags)` is broken on bionic and that's why we use the fallback handler, but I don't see any reason that shouldn't still be working. The `mono_dl_open_file` call returns NULL, and then we try the fallback handler.

Something funky might be happening with its registration? Maybe a race between registration and the first __Internal call? The other possibility is that it's a bug somewhere in the monodroid fallback handler or interop code... It's unfortunate we can't reproduce this on anything but CI.

I'll add a goto so it stops trying to mangle the __Internal, but that won't solve the actual problem.

**Comment by grendello** [comment] 2019-11-04 22:59
@CoffeeFlux XA runtime returns `NULL` because it tries to look for the function in a library called `lib__Internal.so` (it gets `lib__Internal` in the `name` parameter) - it expects all the `__Internal` call lookups to pass `NULL` in the `name` parameter.

**Comment by CoffeeFlux** [comment] 2019-11-04 23:06
Again, I really don't think adding that is going to fix anything. You'll notice that everything in the for loop that follows it is conditional on `!module`, meaning that if `internal_module` was returning a non-null value it would never try to mangle the name. The issue is that the `mono_dl_open` call fails, and only *after* that are you seeing the `lib__Internal` nonsense. When I add the goto it will make the lib__Internal go away, but pinvoke resolution should still fail.

**Comment by CoffeeFlux** [comment] 2019-11-04 23:44
PR'd the goto, and I'll backport it as well. If it fixes the issue I'll be eating my hat, and if it doesn't maybe it'll be clearer what's going on. Either way, should move things forward.

**Comment by CoffeeFlux** [comment] 2019-11-07 17:03
Confirmed to be an issue on X-A's end. Closing.

**Closed by CoffeeFlux** 2019-11-07 17:03 UTC
Labels: area-Runtime: Loader

**Comment by grendello** [comment] 2019-11-07 19:57
@CoffeeFlux You don't need to eat your hat :), the real issue was https://github.com/xamarin/xamarin-android/pull/3888
