### ISSUE TITLE
[roslyn] runtime assertion when running MultipleTypeForwardersToTheSameAssemblyShouldNotResultInMultipleForwardError

### ISSUE THREAD

**Issue by kg** [mono/mono#10629] opened 2018-09-14 22:59 UTC
```
* Assertion at metadata.c:1094, condition `index < meta->heap_blob.size' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) [0x0000c] in <70987d71b3104e2390e4e64aec5a9e36>:0
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x0006a] in <70987d71b3104e2390e4e64aec5a9e36>:0
  at System.Reflection.MethodBase.Invoke (object,object[]) [0x00000] in <70987d71b3104e2390e4e64aec5a9e36>:0
  at Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager/<>c__DisplayClass32_0.<Execute>b__0 () [0x00054] in <57bce63f6c6e43b094553651d8349789>:0
  at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Capture (System.Action,int,string&,string&) [0x0003e] in <57bce63f6c6e43b094553651d8349789>:0
  at Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.Execute (string,string[],System.Nullable`1<int>,string&) [0x0006b] in <57bce63f6c6e43b094553651d8349789>:0
  at (wrapper remoting-invoke-with-check) Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.Execute (string,string[],System.Nullable`1<int>,string&) [0x00036] in <57bce63f6c6e43b094553651d8349789>:0
  at (wrapper xdomain-dispatch) Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.Execute (object,byte[]&,byte[]&,string,string[],string&) [0x00023] in <57bce63f6c6e43b094553651d8349789>:0
  at (wrapper xdomain-invoke) Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.Execute (string,string[],System.Nullable`1<int>,string&) <0x0023e>
  at (wrapper remoting-invoke-with-check) Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.Execute (string,string[],System.Nullable`1<int>,string&) [0x00000] in <57bce63f6c6e43b094553651d8349789>:0
  at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Execute (string,string[],string) <0x0019b>
  at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit (string,System.Nullable`1<int>,string[],System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>,Microsoft.CodeAnalysis.Emit.EmitOptions,Microsoft.CodeAnalysis.Test.Utilities.Verification,Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[]) <0x00157>
  at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit (Microsoft.CodeAnalysis.Compilation,System.Collections.Generic.IEnumerable`1<Roslyn.Test.Utilities.ModuleData>,System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>,Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[],string,System.Nullable`1<int>,string[],System.Action`1<Microsoft.CodeAnalysis.PEAssembly>,System.Action`1<Microsoft.CodeAnalysis.IModuleSymbol>,Microsoft.CodeAnalysis.Emit.EmitOptions,Microsoft.CodeAnalysis.Test.Utilities.Verification) <0x00143>
  at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon (Microsoft.CodeAnalysis.Compilation,System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>,System.Collections.Generic.IEnumerable`1<Roslyn.Test.Utilities.ModuleData>,System.Action`1<Microsoft.CodeAnalysis.IModuleSymbol>,System.Action`1<Microsoft.CodeAnalysis.PEAssembly>,System.Action`1<Microsoft.CodeAnalysis.IModuleSymbol>,Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[],string,System.Nullable`1<int>,string[],Microsoft.CodeAnalysis.Emit.EmitOptions,Microsoft.CodeAnalysis.Test.Utilities.Verification) <0x00213>
  at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify (Microsoft.CodeAnalysis.Compilation,System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>,System.Collections.Generic.IEnumerable`1<Roslyn.Test.Utilities.ModuleData>,System.Action`1<Microsoft.CodeAnalysis.CSharp.Symbols.ModuleSymbol>,System.Action`1<Microsoft.CodeAnalysis.PEAssembly>,System.Action`1<Microsoft.CodeAnalysis.CSharp.Symbols.ModuleSymbol>,Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[],string,System.Nullable`1<int>,string[],Microsoft.CodeAnalysis.Emit.EmitOptions,Microsoft.CodeAnalysis.Test.Utilities.Verification) <0x000ab>
  at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify (Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestSource,System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.MetadataReference>,System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>,System.Collections.Generic.IEnumerable`1<Roslyn.Test.Utilities.ModuleData>,System.Action`1<Microsoft.CodeAnalysis.CSharp.Symbols.ModuleSymbol>,System.Action`1<Microsoft.CodeAnalysis.PEAssembly>,System.Action`1<Microsoft.CodeAnalysis.CSharp.Symbols.ModuleSymbol>,Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[],string,System.Nullable`1<int>,string[],Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions,Microsoft.CodeAnalysis.CSharp.CSharpParseOptions,Microsoft.CodeAnalysis.Emit.EmitOptions,Roslyn.Test.Utilities.TargetFramework,Microsoft.CodeAnalysis.Test.Utilities.Verification) <0x00113>
  at Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationErrorTests.MultipleTypeForwardersToTheSameAssemblyShouldNotResultInMultipleForwardError () <0x007cf>
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <0x00085>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) [0x0000c] in <70987d71b3104e2390e4e64aec5a9e36>:0
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x0006a] in <70987d71b3104e2390e4e64aec5a9e36>:0
  at System.Reflection.MethodBase.Invoke (object,object[]) [0x00000] in <70987d71b3104e2390e4e64aec5a9e36>:0
  at Xunit.Sdk.TestInvoker`1<TTestCase_REF>.CallTestMethod (object) <0x00052>
```

**Comment by kg** [comment] 2018-09-14 23:16
Aleksey pointed out that I missed the native backtrace:
```
/proc/self/maps:
40293000-40303000 rwxp 00000000 00:00 0 
403f6000-40496000 rwxp 00000000 00:00 0 
40765000-40775000 rwxp 00000000 00:00 0 
4082e000-408de000 rwxp 00000000 00:00 0 
40a91000-40b31000 rwxp 00000000 00:00 0 
40d91000-40da1000 rwxp 00000000 00:00 0 
40e6c000-40e8c000 rwxp 00000000 00:00 0 
40ebc000-40ecc000 rwxp 00000000 00:00 0 
40edc000-40efc000 rwxp 00000000 00:00 0 
40f0c000-40f1c000 rwxp 00000000 00:00 0 
40fc7000-410a7000 rwxp 00000000 00:00 0 
410b1000-41194000 rwxp 00000000 00:00 0 
412ef000-413af000 rwxp 00000000 00:00 0 
41679000-426c0000 rwxp 00000000 00:00 0 
55fc4df18000-55fc4e351000 r-xp 00000000 08:01 1450822                    /home/kate/.mono/bin/mono-sgen
55fc4e550000-55fc4e557000 r--p 00438000 08:01 1450822                    /home/kate/.mono/bin/mono-sgen
55fc4e557000-55fc4e55c000 rw-p 0043f000 08:01 1450822                    /home/kate/.mono/bin/mono-sgen
55fc4e55c000-55fc4e573000 rw-p 00000000 00:00 0 
55fc4f5a2000-55fc53ea0000 rw-p 00000000 00:00 0                          [heap]
7f08bf3f0000-7f08bf470000 rw-p 00000000 00:00 0 
7f08bf474000-7f08bf4f4000 rw-p 00000000 00:00 0 
7f08bf4f8000-7f08bf578000 rw-p 00000000 00:00 0 
7f08bf57c000-7f08bf5fc000 rw-p 00000000 00:00 0 
7f08bf774000-7f08bf7f4000 rw-p 00000000 00:00 0 
7f08bf7f8000-7f08bf878000 rw-p 00000000 00:00 0 
Memory around native instruction pointer (0x7f092b6c1fff):
0x7f092b6c1fef  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7f092b6c1fff  48 81 c4 88 00 00 00 44 89 c0 5b c3 0f 1f 44 00  H......D..[...D.
0x7f092b6c200f  00 48 8b 15 61 5e 36 00 f7 d8 64 89 02 eb ca 66  .H..a^6...d....f
0x7f092b6c201f  90 85 ff 78 0c f7 df e9 e5 02 00 00 0f 1f 44 00  ...x..........D.

Native stacktrace:

        mono(+0x127f6a) [0x55fc4e03ff6a]
        mono(+0x1281e0) [0x55fc4e0401e0]
        mono(+0xbf805) [0x55fc4dfd7805]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0x110c0) [0x7f092bc560c0]
        /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7f092b6c1fff]
        /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f092b6c342a]
        mono(+0x2e7c24) [0x55fc4e1ffc24]
        mono(+0x2fe75e) [0x55fc4e21675e]
        mono(monoeg_assertion_message+0x96) [0x55fc4e216b66]
        mono(+0x1f0f0d) [0x55fc4e108f0d]
        mono(mono_assembly_get_assemblyref+0x30) [0x55fc4e0b3270]
        mono(mono_assembly_load_reference+0x123) [0x55fc4e0b7173]
        mono(+0x1a6296) [0x55fc4e0be296]
        mono(+0x1a639e) [0x55fc4e0be39e]
        mono(mono_class_from_typeref_checked+0x1b4) [0x55fc4e0be574]
        mono(mono_class_get_checked+0x115) [0x55fc4e0be945]
        mono(+0x1f4dcd) [0x55fc4e10cdcd]
        mono(mono_metadata_parse_method_signature_full+0x10e) [0x55fc4e10d43e]
        mono(mono_method_signature_checked+0x252) [0x55fc4e0f4df2]
        mono(+0x1dd68c) [0x55fc4e0f568c]
        mono(+0x1dd762) [0x55fc4e0f5762]
        mono(+0x1ddd12) [0x55fc4e0f5d12]
        mono(+0x1dde77) [0x55fc4e0f5e77]
        mono(+0x2c314) [0x55fc4df44314]
        mono(+0x6aae6) [0x55fc4df82ae6]
        mono(+0x12d660) [0x55fc4e045660]
        mono(+0x12f6d4) [0x55fc4e0476d4]
        mono(+0x41117) [0x55fc4df59117]
        mono(+0x4251d) [0x55fc4df5a51d]
        mono(+0x20ce10) [0x55fc4e124e10]
        mono(+0x219830) [0x55fc4e131830]
        mono(+0x1cb137) [0x55fc4e0e3137]
        [0x404167bb]
Entering thread summarizer from 7f092c770740
Waiting for signalled thread 7f09032c6700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Entering thread summarizer from 7f09032c6700
Self-reporting for thread 7f09032c6700. Registered summarizing thread right now is 7f09032c6700
Waiting for signalled thread 7f09032c6700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f09032c6700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f09032c6700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f09032c6700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f09032c6700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f09032c6700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Entering thread summarizer from 7f08eaa23700
Waiting for signalled thread 7f08eaa23700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Self-reporting for thread 7f08eaa23700. Registered summarizing thread right now is 7f08eaa23700
Waiting for signalled thread 7f08eaa23700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f08eaa23700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f08eaa23700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f08eaa23700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Entering thread summarizer from 7f0901feb700
Self-reporting for thread 7f0901feb700. Registered summarizing thread right now is 7f0901feb700
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0901feb700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Waiting for signalled thread 7f0922689700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Waiting for signalled thread 7f0922689700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Waiting for signalled thread 7f0922689700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Entering thread summarizer from 7f0922689700
Self-reporting for thread 7f0922689700. Registered summarizing thread right now is 7f0922689700
Waiting for signalled thread 7f0922689700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Waiting for signalled thread 7f0922287700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Entering thread summarizer from 7f0922287700
Self-reporting for thread 7f0922287700. Registered summarizing thread right now is 7f0922287700
Waiting for signalled thread 7f0922287700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0922287700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0922287700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0922287700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0922287700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Waiting for signalled thread 7f08ebcf7700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Entering thread summarizer from 7f08ebcf7700
Self-reporting for thread 7f08ebcf7700. Registered summarizing thread right now is 7f08ebcf7700
Waiting for signalled thread 7f08ebcf7700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Waiting for signalled thread 7f08ea621700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Entering thread summarizer from 7f08ea621700
Self-reporting for thread 7f08ea621700. Registered summarizing thread right now is 7f08ea621700
Waiting for signalled thread 7f08ea621700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Waiting for signalled thread 7f08ea621700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f08ea621700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Entering thread summarizer from 7f090ad37700
Self-reporting for thread 7f090ad37700. Registered summarizing thread right now is 7f090ad37700
Waiting for signalled thread 7f092893c700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x0
Entering thread summarizer from 7f092893c700
Self-reporting for thread 7f092893c700. Registered summarizing thread right now is 7f092893c700
Waiting for signalled thread 7f092893c700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x0
Waiting for signalled thread 7f092893c700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x0
Waiting for signalled thread 7f092893c700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x0
Waiting for signalled thread 7f092893c700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x0
Entering thread summarizer from 7f0910578700
Self-reporting for thread 7f0910578700. Registered summarizing thread right now is 7f0910578700
Entering thread summarizer from 7f090aaa3700
Self-reporting for thread 7f090aaa3700. Registered summarizing thread right now is 7f090aaa3700
Waiting for signalled thread 7f090aaa3700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Entering thread summarizer from 7f08ea822700
Waiting for signalled thread 7f08ea822700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Self-reporting for thread 7f08ea822700. Registered summarizing thread right now is 7f08ea822700
Waiting for signalled thread 7f08ea822700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f08ea822700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Entering thread summarizer from 7f0922488700
Self-reporting for thread 7f0922488700. Registered summarizing thread right now is 7f0922488700
Waiting for signalled thread 7f0922488700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Waiting for signalled thread 7f0922488700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0922488700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0922488700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
Waiting for signalled thread 7f0922488700 to collect stacktrace. Status: MONO_SUMMARY_EMPTY
. Thread state: 0x4
Entering thread summarizer from 7f0922086700
Waiting for signalled thread 7f0922086700 to collect stacktrace. Status: MONO_SUMMARY_EXPECT
. Thread state: 0x4
Self-reporting for thread 7f0922086700. Registered summarizing thread right now is 7f0922086700
Waiting for signalled thread 7f0922086700 to collect stacktrace. Status: MONO_SUMMARY_EXAMINE
. Thread state: 0x4
* Assertion at mini-exceptions.c:1430, condition `frame->ji && frame->type != FRAME_TYPE_TRAMPOLINE' not met

/home/kate/Projects/mono/acceptance-tests/external/roslyn/build/scripts/tests.sh: line 56:  9656 Aborted                 ${runner} "${xunit_console}" "${file_name[@]}" -xml "${log_file}"
Assembly /home/kate/Projects/mono/acceptance-tests/external/roslyn/Binaries/Debug/UnitTests/CSharpCompilerSymbolTest/net461/Roslyn.Compilers.CSharp.Symbol.UnitTests.dll failed
Running mono /home/kate/Projects/mono/acceptance-tests/external/roslyn/Binaries/Debug/UnitTests/CSharpCompilerSyntaxTest/net461/Roslyn.Compilers.CSharp.Syntax.UnitTests.dll
```

**Comment by lambdageek** [comment] 2020-01-15 19:21
Duplicate of https://github.com/mono/mono/issues/10332

Resolved by https://github.com/mono/mono/pull/18313

**Closed by lambdageek** 2020-01-15 19:21 UTC
Labels: area-Runtime: Metadata, epic: Roslyn Tests
