### ISSUE TITLE
Cannot use DebugType=embedded in normal csproj

### ISSUE THREAD

**Issue by Therzok** [mono/mono#19066] opened 2020-02-27 15:22 UTC
## Steps to Reproduce

1. Create a project
2. Assign DebugType to embedded
3. Observe portable is written

### Current Behavior

[Microsoft.CSharp.Mono.targets](https://github.com/mono/msbuild/blob/c6ea25c52b1c5c5c142a53674aae2d03952cd136/src/Tasks/Microsoft.CSharp.Mono.targets#L31-L46) overrides the `DebugType` value.

### Expected Behavior

It should let either embedded or portable be valid options.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
➜  ~ mono --version
Mono JIT compiler version 6.10.0.87 (2019-12/b33fa1d00ed Wed Feb 26 21:46:15 EST 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Workarounds

If you set the DebugType in a targets file that's imported _after_ the Mono one, you can successfully build with embedded PDBs.

**Comment by Therzok** [comment] 2020-02-27 15:24
cc @radical @marek-safar

**Comment by Therzok** [comment] 2020-02-27 15:25
cc @radical @marek-safar

**Comment by marek-safar** [comment] 2020-02-27 17:02
The problem is in the msbuild target where we force to override everything to portable this is wrong.

/cc @radical

**Comment by radical** [comment] 2020-02-27 18:10
We needed to do that earlier. If embedded works fine now, then we can remove the override. What branches should this be done for?

**Comment by Therzok** [comment] 2020-02-27 18:29
The fix for embedded pdbs is in master, 2020-02, 2019-12.

**Comment by radical** [comment] 2020-02-27 19:19
Waiting on:

- [ ] msbuild xplat-master PR (used by mono master+2020-02) - https://github.com/mono/msbuild/pull/345
- [ ] msbuild mono-2019-12 PR
- [ ] mono bump for master
- [ ] mono bump for 2020-02
- [ ] mono bump for 2019-12

**Comment by radical** [comment] 2020-03-03 16:25
All the PRs have been merged.

**Closed by radical** 2020-03-03 16:25 UTC
Labels: area-Tools: msbuild
