### ISSUE TITLE
Incorrect behavior for Take/Skip/Concat combination

### ISSUE THREAD

**Issue by eatdrinksleepcode** [mono/mono#6560] opened 2018-01-17 19:10 UTC
## Steps to Reproduce

```
var inputs = new [] { "left", "right" };
var outputs = inputs.Take(1)
                    .Concat(Enumerable.Repeat((object)"middle", 1))
                    .Concat(inputs.Skip(1)).ToArray();
foreach(var item in outputs) {
	Console.WriteLine(item);
}
```
## Current Behavior

```
left
middle
left
```

## Expected Behavior

```
left
middle
right
```

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

5.4.1.7

## Notes

_This is a regression_: the same code works correctly under Mono 4.8.1.

Note the cast to ```object``` inside the ```Enumerable.Repeat```. This is necessary to reproduce the bug; without the cast, the code works correctly.

**Comment by akoeplinger** [comment] 2018-01-18 02:24
I can repro in Mono 5.4.1.6 and 5.8.0.115, but not in 5.10.0.20 so it looks like this was already fixed.

@marek-safar do you remember a specific fix for this or was it part of a corefx bump?

**Comment by marek-safar** [comment] 2018-01-19 15:32
Tracked it down as following regression https://github.com/dotnet/corefx/issues/23680

**Comment by eatdrinksleepcode** [comment] 2018-01-20 02:50
Yeah that's definitely it. Thanks for tracking that down.

**Closed** 2018-01-22 11:27 UTC
Labels: area-BCL: System.Core, regression
