### ISSUE TITLE
[Blazor] 32 bit enum flag values upon reflection

### ISSUE THREAD

**Issue by danroth27** [mono/mono#13881] opened 2019-04-05 16:54 UTC
_From @friendlyanon on Monday, 31 December 2018 21:18:31_

### Describe the bug
A flag enum inheriting from `long` can't have all its values reflected upon that are wider than 32 bits.  
Getting the value of the enum works as expected.

### To Reproduce
1. Create Standalone Blazor project `EnumTest`
2. Add file `Test.cs` with the contents of [this gist](https://gist.github.com/friendlyanon/7a174bb36a1cacfd2f56545192e40f2b/72ea2ca7d6488cf4e1fcc96046b6afcea10429c6)
3. In `Startup.cs` add `Test.PrintEnums();` to the `Configure` method

### Expected behavior
Prints
```
enum01
enum01
1 bit
enum02
enum02
2 bits
enum03
enum03
3 bits
...
enum62
enum62
62 bits
enum63
enum63
63 bits
enum64
enum64
64 bits
```

### Additional context
Blazor version: `0.7.0`
.NET Core: `2.1.502` - `c74ce8f29f`

_Copied from original issue: aspnet/aspnetcore#6205_

**Comment by kjpou1** [comment] 2019-04-09 09:03
@friendlyanon @danroth27

I am not able to recreate an error using a pure wasm project.  I noticed that you are using Blazor version 0.7.0 and there have been considerable enhancements since that version.  Could you try with a recent Blazor version.

Here is the output from my test mono wasm project with no errors.

```
Loaded: System.Drawing.Common.dll
Loaded: System.Web.Services.dll
Loaded: WasmCoreObjects.dll
Loaded: WebAssembly.Bindings.dll
Loaded: WebAssembly.Net.Http.dll
Loaded: WebAssembly.Net.WebSockets.dll
Loaded: System.Drawing.Common.pdb
Loaded: System.Net.Http.pdb
Loaded: System.pdb
Loaded: System.Web.Services.pdb
Loaded: WasmCoreObjects.pdb
Loaded: WebAssembly.Bindings.pdb
Loaded: WebAssembly.Net.Http.pdb
Loaded: WebAssembly.Net.WebSockets.pdb
Loaded: System.dll
Loaded: System.Net.Http.dll
Loaded: mscorlib.pdb
Loaded: mscorlib.dll
initializing mono runtime
DEBUGGING ENABLED
>>mono_wasm_runtime_ready
﻿ enum01
 enum01
 1 bit
 enum02
 enum02
 2 bits
 enum03
 enum03
 3 bits
 enum04
 enum04
 4 bits
 enum05
 enum05
 5 bits
 enum06
 enum06
 6 bits
 enum07
 enum07
 7 bits
 enum08
 enum08
 8 bits
 enum09
 enum09
 9 bits
 enum10
 enum10
 10 bits
 enum11
 enum11
 11 bits
 enum12
 enum12
 12 bits
 enum13
 enum13
 13 bits
 enum14
 enum14
 14 bits
 enum15
 enum15
 15 bits
 enum16
 enum16
 16 bits
 enum17
 enum17
 17 bits
 enum18
 enum18
 18 bits
 enum19
 enum19
 19 bits
 enum20
 enum20
 20 bits
 enum21
 enum21
 21 bits
 enum22
 enum22
 22 bits
 enum23
 enum23
 23 bits
 enum24
 enum24
 24 bits
 enum25
 enum25
 25 bits
 enum26
 enum26
 26 bits
 enum27
 enum27
 27 bits
 enum28
 enum28
 28 bits
 enum29
 enum29
 29 bits
 enum30
 enum30
 30 bits
 enum31
 enum31
 31 bits
 enum32
 enum32
 32 bits
 enum33
 enum33
 33 bits
 enum34
 enum34
 34 bits
 enum35
 enum35
 35 bits
 enum36
 enum36
 36 bits
 enum37
 enum37
 37 bits
 enum38
 enum38
 38 bits
 enum39
 enum39
 39 bits
 enum40
 enum40
 40 bits
 enum41
 enum41
 41 bits
 enum42
 enum42
 42 bits
 enum43
 enum43
 43 bits
 enum44
 enum44
 44 bits
 enum45
 enum45
 45 bits
 enum46
 enum46
 46 bits
 enum47
 enum47
 47 bits
 enum48
 enum48
 48 bits
 enum49
 enum49
 49 bits
 enum50
 enum50
 50 bits
 enum51
 enum51
 51 bits
 enum52
 enum52
 52 bits
 enum53
 enum53
 53 bits
 enum54
 enum54
 54 bits
 enum55
 enum55
 55 bits
 enum56
 enum56
 56 bits
 enum57
 enum57
 57 bits
 enum58
 enum58
 58 bits
 enum59
 enum59
 59 bits
 enum60
 enum60
 60 bits
 enum61
 enum61
 61 bits
 enum62
 enum62
 62 bits
 enum63
 enum63
 63 bits
 enum64
 enum64
 64 bits

>> Total Memory Exit WASM: 33554432

```

**Comment by kjpou1** [comment] 2019-04-11 03:49
Am closing this for now as can not reproduce the error using master wasm.  If this is still causing an error please reopen this or a new issue.

**Closed by kjpou1** 2019-04-11 03:49 UTC
Labels: target-wasm
