### ISSUE TITLE
App terminates : "Failed to Stop app: An error occured on client IDB4100448 while executing a reply for topic xvs/idb/4.10.0.448/stop-app"

### ISSUE THREAD

**Issue by ganorkargaurav** [mono/mono#9262] opened 2018-06-22 06:21 UTC
Description-
VS throwing  error in Debug mode while clicked on stop app "Failed to Stop app: An error occured on client IDB4100448 while executing a reply for topic xvs/idb/4.10.0.448/stop-app"

## Steps to Reproduce
1-Download the attached sample and Set Startup project as "iOS.Debugging"
2- Connect XMA 
3-Clean the solution
4-Select target device as iOS device
5-from iOS.Debugging ,Open MultitaskingBreakpoint.cs and add breakpoint to line number 10 and 12
6-Deploy the app on Device
7-On device , Click on Multitasking Breakpoint and Click on button to hit the breakpoint on VS
8-After hitting breakpoint click on Stop and Observe the behavioir

### Current Behavior
VS throwing  error in Debug mode while clicked on stop app "Failed to Stop app: An error occured on client IDB4100448 while executing a reply for topic xvs/idb/4.10.0.448/stop-app"

### Expected Behavior
VS should not throw error in debug mode and debug mode should be closed for VS 

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x ] Windows
**Reproducible**
50%

**Version Used**:

Screencast link- (Open in IE or Edge)
http://xqa.blob.core.windows.net/video/ScreenRecording.mp4-6d2e665c2ebf458292edf278da16f890.mp4

## Stacktrace
Resolved pending breakpoint at 'WriteBluetoothWorkItem.cs:56,1' to void .Core.Services.StartCharacteristicWorkItem.<ExecuteAsync>d_2.MoveNext () [0x00018].
[0x1b4820b40] The instruction pointer of the currently executing method(.Core.ViewModels.MainViewModel/<ConnectToSensorServices>d_39:MoveNext ()) is not on the recorded stack. This is likely due to a runtime bug. The 4 frames are as follow: 
2018-05-20 14:01:44.868 XamFormsMvxTemplateiOS[4628:2324578] error: * Assertion at /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/external/mono/mono/mini/debugger-agent.c:4702, condition `method_in_stack' not met
The app has been terminated.

**Output logs**
(http://xqa.blob.core.windows.net/gist/Output-Pane-Log-Debug---27ed9aa1c5444c1ba2e74f85e03c703f.txtOutput-Pane-Log-Xamarin---a350d6d81bb649a6a9744dab8b166b55.txt)
**Xamarin Logs**
http://xqa.blob.core.windows.net/gist/Output-Pane-Log-Xamarin---a350d6d81bb649a6a9744dab8b166b55.txt
**Xamarin diagnostics** 
http://xqa.blob.core.windows.net/gist/Output-Pane-Log-XamarinDiagnostics---505a8bb6a1c94b808a46642f315a585b.txt
**ZipLogs**
http://xqa.blob.core.windows.net/gist/ZipLogs.zip
**IDE logs**
http://xqa.blob.core.windows.net/gist/2018-05-30_01-50-35.6992.Ide.log.180530015514-0e1552cb90104735ba66a7b21c9a58a7.txt
**Build logs**
http://xqa.blob.core.windows.net/gist/log-a862fa66fea44876b981b69a4eedecf9.txt

**Issue Also reproducible on 15.8 Preview 2 builds**

**Comment by lewurm** [comment] 2018-07-03 21:50
duplicate of https://github.com/mono/mono/issues/8627 ?

**Comment by marek-safar** [comment] 2018-07-09 19:15
@ganorkargaurav could you attach the sample?

**Comment by lewurm** [comment] 2018-09-03 10:34
I'm closing this because it appears to be a duplicate of https://github.com/mono/mono/issues/8627

**Closed by lewurm** 2018-09-03 10:34 UTC
Labels: area-Debugger
