### ISSUE TITLE
HttpWebRequest consumes a lot of memory and never frees it

### ISSUE THREAD

**Issue by raman-sidarakin-epam** [mono/mono#7135] opened 2018-02-20 11:08 UTC
## Steps to Reproduce

1. Compile sample of code, provided below. It just creating HttpWebRequests and getting response periodically.
2. Run it using mono 5.2.0.224 on macOS 10.12+ and observe memory consumption via 'Acivity Monitor.app'

```
namespace HttpsMonoLeak
{
    using System;
    using System.IO;
    using System.Net;
    using System.Threading;

    class Program
    {
        static void Main(string[] args)
        {
            uint count = 0;
            int delay = 500;
            string address = "https://httpbin.org";
            string method = "GET";

            while (true)
            {
                delay = 500;

                HttpWebRequest request = HttpWebRequest.CreateHttp(address);
                request.Method = method;
                request.KeepAlive = false;

                try
                {
                    using (var response = request.GetResponse() as HttpWebResponse)
                    using (var stream = response.GetResponseStream())
                    using (var reader = new StreamReader(stream))
                    {
                        Console.WriteLine(count++ + " " + address + " : " + (reader.ReadToEnd()).Length);
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(count++ + " " + address + " : ");
                    Console.WriteLine(e);
                    delay = 10000;
                }

                Thread.Sleep(delay);
            }
        }
    }
}

```
## Current Behavior

Activity monitor shows intensively increasing memory consumption (about +3MB every 7-10 seconds). It will continue eat memory until OutOfMemoryException occurs. Also behavior the same, when i've tried different versions of mono.

I've tried to profile the program with the log profiler and noticed, that `Mono.Net.Security.BufferOffsetSize2:Reset()` and `Mono.AppleTls.AppleTlsContext:NativeReadCallback()` calls the most expensive regarding memory.

If I'm placing GC.Collect() before this line of code in my example: `Thread.Sleep(delay);`, then memory consumption stays stable and not increasing over the time.

## Expected Behavior

Example app, that periodically sends HttpWebRequest and gets response shouldn't eat all available memory of my machine.

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Tried on these versions of mono:
5.2.0.224
5.8.0.108
5.10.0.129 (Preview)

### Stacktrace

```
N/A
```

**Comment by EgorBo** [comment] 2018-02-20 11:51
Looks like the issue doesn't reproduce on master (5.13, new web stack)
But it does reproduce on 5.4

**Comment by marek-safar** [comment] 2018-02-20 13:53
I cannot reproduce the issue with Mono 5.10.0.15 on Mac. After well over 3000 iterations the memory is back to approximately 19.5 MBs.

**Comment by raman-sidarakin-epam** [comment] 2018-02-20 14:20
@marek-safar, thanks for answering. 
I've installed mono 5.10.0 again and it works correctly for me as well now. When memory consumption near to 35mb, then it returns to 17mb.
My assumption, that it was my mistake, when I've tested this example on different versions of mono. I think we can close this issue.

**Comment by marek-safar** [comment] 2018-02-20 14:22
Thanks for the confirmation, closing the issue.

**Closed by marek-safar** 2018-02-20 14:22 UTC
Labels: area-BCL: System, needs more info
