### ISSUE TITLE
mono_magic_trampoline being called more than expected

### ISSUE THREAD

**Issue by fanyang-mono** [mono/mono#17334] opened 2019-10-15 16:24 UTC
## Steps to Reproduce
Follow the instructions from the following page to get the flame graph on linux
https://paper.dropbox.com/doc/Profile-Mono-with-TechEmpower-benchmarks--AmsEtz3lCaMVH~kMyVQxA1CBAg-ryHeobv8okzUs1Fa9TfBG

### Current Behavior
Currently, mono_magic_trampoline is being called more than expected.
<img width="1312" alt="Screen Shot 2019-10-15 at 12 21 43 PM" src="https://user-images.githubusercontent.com/52458914/66850310-87680080-ef46-11e9-83ed-a02f04c4b626.png">

### Expected Behavior
mono_magic_trampoline should take a small port of time of the whole program.

## On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

**Version Used**:
mono/master on Oct 7, 2019

**Comment by lewurm** [comment] 2019-10-16 16:09
I added some logging to `mono_magic_trampoline`, and those two methods showed up as a call target during HTTP requests repeatedly:

```
System.Threading.Interlocked:Exchange_T<System.Net.Sockets.SocketAsyncContext/BufferMemoryReceiveOperation> (System.Net.Sockets.SocketAsyncContext/BufferMemoryReceiveOperation&,System.Net.Sockets.SocketAsyncContext/BufferMemoryReceiveOperation&,System.Net.Sockets.SocketAsyncContext/BufferMemoryReceiveOperation&)

System.Threading.Interlocked:Exchange_T<System.Action> (System.Action&,System.Action&,System.Action&)
```
Or short, `System.Threading.Interlocked:Exchange_T<T> (T&, T&, T&)`.

The runtime couldn't patch the _caller_, as explained and addressed in this PR: https://github.com/mono/mono/pull/17341 , so it would over and over end up in the magic trampoline.

However, we should never need to patch it because its caller (`Exchange<T>`) is supposed to be intrinsified by their callers. There was a mismatch regarding type signatures, which was fixed by https://github.com/mono/mono/pull/17338

Closing it as a duplicate of https://github.com/mono/mono/issues/17335

**Closed by lewurm** 2019-10-16 16:09 UTC
Labels: area-Runtime: Performance, task
