### ISSUE TITLE
WebAssembly: TimeZone issues related to Mono?

### ISSUE THREAD

**Issue by chassq** [mono/mono#8443] opened 2018-04-24 20:50 UTC
See https://github.com/aspnet/Blazor/issues/663 for details. Hoping this can be resolved somehow.

**Comment by migueldeicaza** [comment] 2018-04-26 17:46
This is a duplicate of this issue:

https://github.com/mono/mono/issues/8443

**Closed by migueldeicaza** 2018-04-26 17:46 UTC
Labels: area-BCL: mscorlib, target-wasm

**Comment by chassq** [comment] 2018-04-26 17:48
Which one was the duplicate issue? #8443 is the closed issue.

**Comment by migueldeicaza** [comment] 2018-04-26 17:55
My bad: https://github.com/mono/mono/issues/6368

**Comment by chassq** [comment] 2018-04-26 18:15
Thanks!
