### ISSUE TITLE
Invalid instruction generated by regex runtime when using dapper

### ISSUE THREAD

**Issue by borgdylan** [mono/mono#7828] opened 2018-03-26 09:57 UTC
When using Hangfire an by extension Dapper, the regex runtime in mono is making an invalid instruction which is making the call to CreateDelegate fail.

```
Application startup exception: System.InvalidProgramException: Invalid IL code in (wrapper dynamic-method) System.Text.RegularExpressions.CompiledRegexRunner:FindFirstChar6 (System.Text.RegularExpressions.RegexRunner): IL_0021: bge       IL_0332


  at (wrapper managed-to-native) System.Delegate.CreateDelegate_internal(System.Type,object,System.Reflection.MethodInfo,bool)
  at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) [0x002f0] in /home/dylan/Desktop/git/mono/mcs/class/corlib/System/Delegate.cs:286 
  at System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure) [0x00000] in /home/dylan/Desktop/git/mono/mcs/class/corlib/System/Delegate.cs:301 
  at System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method) [0x00000] in /home/dylan/Desktop/git/mono/mcs/class/corlib/System/Delegate.cs:306 
  at System.Reflection.Emit.DynamicMethod.CreateDelegate (System.Type delegateType) [0x00029] in /home/dylan/Desktop/git/mono/mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs:175 
  at System.Text.RegularExpressions.CompiledRegexRunnerFactory.CreateInstance () [0x00005] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/CompiledRegexRunnerFactory.cs:25 
  at System.Text.RegularExpressions.Regex.Run (System.Boolean quick, System.Int32 prevlen, System.String input, System.Int32 beginning, System.Int32 length, System.Int32 startat) [0x0005c] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:1004 
  at System.Text.RegularExpressions.Regex.IsMatch (System.String input, System.Int32 startat) [0x0000e] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:619 
  at System.Text.RegularExpressions.Regex.IsMatch (System.String input) [0x0000e] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:603 
  at Dapper.SqlMapper.GetLiteralTokens (System.String sql) [0x0000e] in <63a8cc06dfb842f1823bc51677815d4b>:0 
  at Dapper.SqlMapper.GetCacheInfo (Dapper.SqlMapper+Identity identity, System.Object exampleParameters, System.Boolean addToCache) [0x0007c] in <63a8cc06dfb842f1823bc51677815d4b>:0 
  at Dapper.SqlMapper+<QueryImpl>d__136`1[T].MoveNext () [0x00075] in <63a8cc06dfb842f1823bc51677815d4b>:0 
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in /home/dylan/Desktop/git/mono/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:1164 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in /home/dylan/Desktop/git/mono/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:88 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30 
  at Dapper.SqlMapper.Query[T] (System.Data.IDbConnection cnn, System.String sql, System.Object param, System.Data.IDbTransaction transaction, System.Boolean buffered, System.Nullable`1[T] commandTimeout, System.Nullable`1[T] commandType) [0x0003c] in <63a8cc06dfb842f1823bc51677815d4b>:0 
  at Hangfire.PostgreSql.PostgreSqlConnection.GetAllEntriesFromHash (System.String key) [0x00035] in <fffd65c6cfa9476589e18fb16c03227a>:0 
  at Hangfire.RecurringJobManager.AddOrUpdate (System.String recurringJobId, Hangfire.Common.Job job, System.String cronExpression, Hangfire.RecurringJobOptions options) [0x000b6] in <9a531424b2e740ba9386e067e53e78dc>:0 
  at Hangfire.RecurringJobManagerExtensions.AddOrUpdate (Hangfire.IRecurringJobManager manager, System.String recurringJobId, Hangfire.Common.Job job, System.String cronExpression, System.TimeZoneInfo timeZone, System.String queue) [0x0004e] in <9a531424b2e740ba9386e067e53e78dc>:0 
  at Hangfire.RecurringJob.AddOrUpdate (System.Linq.Expressions.Expression`1[TDelegate] methodCall, System.String cronExpression, System.TimeZoneInfo timeZone, System.String queue) [0x00028] in <9a531424b2e740ba9386e067e53e78dc>:0
```

**Comment by lewurm** [comment] 2018-03-26 10:05
I think it's this regex: https://github.com/StackExchange/Dapper/blob/07fe543f1530b33818c9ce989bf0672e145c954d/Dapper/SqlMapper.cs#L2239

I can't get it to fail though. Do you know what the input to the matcher is?

**Comment by lewurm** [comment] 2018-03-26 10:15
seems to be an known issue: https://bugzilla.xamarin.com/show_bug.cgi?id=25671

**Comment by lewurm** [comment] 2018-03-26 10:20
@marek-safar is this code "overriden" by some corefx import?
https://github.com/mono/mono/blob/e610e443cd67c78c2aeabef4209e380226dd65d5/mcs/class/referencesource/System/regex/system/text/regularexpressions/Regex.cs#L1408-L1420

**Comment by lewurm** [comment] 2018-03-26 10:21
@borgdylan it would be useful to know what version and on what platform you experience this problem

**Comment by borgdylan** [comment] 2018-03-26 11:02
I experienced this on Linux x64 with the latest code form the master branch. Commit e7ba41d14c7e1dc6e860e6e9c5a3db05686d2c5a is known to me as NOT exhibiting the issue. Thsi seems to have been intoruduced during this month.

**Comment by borgdylan** [comment] 2018-03-26 11:04
Also, I have managed to reproduce this with all mono code of the last two weeks. I was too busy to report it. I noticed that there were imports from corefx in this timeframe. I am not sure if regex was worked on during said imports.

**Comment by borgdylan** [comment] 2018-03-26 11:08
I confirm that there was corefx work done by Egor. Commit: https://github.com/mono/mono/commit/695acd0a0b909df0733f74156587f1a38db4b2b0

**Comment by borgdylan** [comment] 2018-03-26 15:50
@lewurm that commit leaves out the file you mentioned. I am not sure if such a patch was made to new code.

**Comment by lewurm** [comment] 2018-03-26 15:54
@EgorBo can you have a look at this please?

**Comment by EgorBo** [comment] 2018-03-27 10:55
@marek-safar @lewurm  @borgdylan I could not reproduce https://bugzilla.xamarin.com/show_bug.cgi?id=25671 so I decided it's fixed by the corefx import + lots of runtime changes since the bug was submitted, looks like we need to ignore the flag again..

**Comment by marek-safar** [comment] 2018-03-27 11:09
@borgdylan could you help us to repro the issue ?

**Comment by borgdylan** [comment] 2018-03-27 11:27
If there is a branch I can pull, I will try recompiling and installing the "fixed" mono so as to run it against the project that manifests the issue.

**Comment by borgdylan** [comment] 2018-03-27 11:27
I cannot give away any code since it is all under NDA.

**Comment by marek-safar** [comment] 2018-03-27 11:56
Sure but I think it should be reproducible with Regex.IsMatch input you use in your `GetLiteralTokens` method

**Comment by borgdylan** [comment] 2018-03-27 12:06
That is within a library used by another library I use. ANy direct use of regex by myself is not triggering teh issue.

**Comment by borgdylan** [comment] 2018-03-27 12:08
In other words I am not the code owner of whatever is calling the regex runtime at the point of failure.

**Comment by borgdylan** [comment] 2018-03-29 06:51
ping

**Comment by marek-safar** [comment] 2018-03-29 06:59
@borgdylan I could not reproduce with blind repro, any help with repro would be greatly appreciated. Could you build Mono BCL with Console.WriteLine debug info?

**Comment by borgdylan** [comment] 2018-03-29 07:11
Yes, is there a flag or should I inject code manually to print stuff to console?

**Comment by marek-safar** [comment] 2018-03-29 07:12
There is no flag, you need to do the work yourself

**Comment by borgdylan** [comment] 2018-03-29 07:13
Are debug symbols built for libraries taken from corefx? The issue is happening in aprocess I can debug within VS Code.

**Comment by borgdylan** [comment] 2018-03-29 07:13
In the past I got exception messages wth line numbers sicne I build manually from git.

**Comment by marek-safar** [comment] 2018-03-29 07:14
Yes, the code is identical to corefx master from about 2 months ago but that should not matter for the entry point values

**Comment by borgdylan** [comment] 2018-03-29 07:15
I will attempt debugging and give you the values that the regex.ismatch call is getting

**Comment by borgdylan** [comment] 2018-03-29 07:39
So Dapper is running regex over whole blobs of SQL and Npgsql is runnign regex over connection string tokens. The last regex matxh attempt before teh crash is:

input =
```WITH "inputvalues" AS (
        SELECT @id "id", @data "data", NOW() AT TIME ZONE 'UTC' "lastheartbeat"
), "updatedrows" AS (
        UPDATE "hangfire"."server" "updatetarget"
        SET "data" = "inputvalues"."data", "lastheartbeat" = "inputvalues"."lastheartbeat"
        FROM "inputvalues"
        WHERE "updatetarget"."id" = "inputvalues"."id"
        RETURNING "updatetarget"."id"
)
INSERT INTO "hangfire"."server"("id", "data", "lastheartbeat")
SELECT "id", "data", "lastheartbeat" FROM "inputvalues" "insertvalues"
WHERE NOT EXISTS (
        SELECT 1
        FROM "updatedrows"
        WHERE "updatedrows"."id" = "insertvalues"."id"
);```
, pattern = ```(?<![\p{L}\p{N}_])\{=([\p{L}\p{N}_]+)\}```

**Comment by borgdylan** [comment] 2018-03-29 07:42
Also, this is happening every few launches and not each time suggesting some kind of race condition in teh regex runtime or something that is using.

**Comment by borgdylan** [comment] 2018-03-29 07:44
I am trying a build of mono where UseOptionC() returns false always and see if it mitigates the bug.

**Comment by borgdylan** [comment] 2018-03-29 07:47
I cannot repro the issue anyore if UseOptionC is implemented as follows:

```
protected bool UseOptionC()
        {
            return false;
            //return (roptions & RegexOptions.Compiled) != 0;
        }
```

**Comment by borgdylan** [comment] 2018-03-29 07:48
I confirm that this has to be patches again to get stable operationon mono.

**Comment by borgdylan** [comment] 2018-03-29 07:54
This is the patch. Feel free to use it. I release this patch under the license MIT/X11
```
diff --git a/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs b/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs
index d078cda53a..4b3d81b9bf 100644
--- a/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs
+++ b/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs
@@ -307,7 +307,7 @@ namespace System.Text.RegularExpressions
 
 #if FEATURE_COMPILED
         /// <summary>
-        /// This method is here for perf reasons: if the call to RegexCompiler is NOT in the 
+        /// This method is here for perf reasons: if the call to RegexCompiler is NOT in the
         /// Regex constructor, we don't load RegexCompiler and its reflection classes when
         /// instantiating a non-compiled regex.
         /// </summary>
@@ -1081,7 +1081,11 @@ namespace System.Text.RegularExpressions
 
         protected bool UseOptionC()
         {
-            return (roptions & RegexOptions.Compiled) != 0;
+            //return false always for now, the runtime is not liking teh instruction streams made when using compiled regex
+            //see: https://github.com/mono/mono/issues/7828
+
+            return false;
+            //return (roptions & RegexOptions.Compiled) != 0;
         }
 
         /*
```

**Comment by borgdylan** [comment] 2018-03-30 16:48
ping

**Comment by borgdylan** [comment] 2018-04-03 07:12
ping

**Comment by borgdylan** [comment] 2018-04-04 08:01
Tried the latest master branch code that should ahve compiled regex disabled. The issue still persists i.e. it is not truly disabled. Another issue with linq expressions has also sprung up.

**Closed** 2018-04-06 19:02 UTC
Labels: area-BCL: System, regression
