### ISSUE TITLE
Debugger terminates unexpectedly with error "the instruction pointer of the currently executing method (METHOD_NAME) is not on the recorded stack"

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#10449] opened 2018-09-03 10:15 UTC
_From @DaRosenberg on June 28, 2018 19:0_

### Steps to Reproduce

Happens intermittently **but very frequently** while stepping through the code in the debugger, of an iOS app running in the iOS simulator of the connected Mac. Not sure when exactly this started happening, but my guess would be it started with the 15.7 release.

### Expected Behavior

N/A - debugging should simply work.

### Actual Behavior

When stepping through code in the debugger (hitting F10 or F11) the app and the debugging session terminates unexpectedly. The Debug output window shows:

```
[0x70000346d000] The instruction pointer of the currently executing method (METHOD_NAME) is not on the recorded stack. This is likely due to a runtime bug. The 1 frames are as follow: 
2018-06-28 20:45:00.176 IDeliverable.Retrospect.Xamarin.iOS[33333:8198052] error: * Assertion at /Users/builder/data/lanes/5944/64fece5f/source/xamarin-macios/external/mono/mono/mini/debugger-agent.c:4702, condition `method_in_stack' not met
```

### Environment

```
Microsoft Visual Studio Professional 2017 
Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

Microsoft Visual Studio Tools for Applications 2017   00369-60000-00001-AA734
Microsoft Visual Studio Tools for Applications 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40511.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40424.0
Azure Functions and Web Jobs Tools

C# Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeRush for Roslyn   18.1.5.0
DevExpress CodeRush for Roslyn package.

CodeRush for Roslyn Tool Windows   18.1.5.0
DevExpress CodeRush for Roslyn Tool Windows package.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

EditorConfig Language Service   1.17.237
Language service for .editorconfig files.

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

File Nesting   2.6.84
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   2.4.2.1331
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Service Fabric Tools for Visual Studio   2.1
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.11027.3
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.212
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 14.0.800.98

Syntax Highlighting Pack   2.8.133
Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Visual Basic Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 56f97a8dd4353d897336941f3e644423b87c794f.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27703.2018
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.10.0.448 (4373404db)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.270 (82d750d12)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.178 (408d357)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

[msbuild.log](https://github.com/xamarin/xamarin-macios/files/2146588/msbuild.log)

### Example Project (If Possible)

Cannot share unfortunately.

_Copied from original issue: xamarin/xamarin-macios#4362_

**Comment by DaRosenberg** [comment] 2018-09-03 10:25
@lewurm That's good news. What does `2018-02` mean in terms of product releases?

**Comment by lewurm** [comment] 2018-09-03 10:32
`2018-02` is used in Visual Studio 15.8 / Xamarin.iOS 11.15. not sure for when the next update is scheduled for. @rolfbjarne ?

**Comment by rolfbjarne** [comment] 2018-09-03 10:34
@lewurm current stable (XI d15-8) is already using `2018-02`.

**Comment by lewurm** [comment] 2018-09-03 10:49
@DaRosenberg ok, so the latest update of 15.8 should contain the mentioned PR. Specifically, you need at least 11.14.0.14 of Xamarin.iOS.

I'm closing this because it appears to be a duplicate of #8627

**Closed by lewurm** 2018-09-03 10:49 UTC

**Comment by DaRosenberg** [comment] 2018-09-03 10:53
@lewurm OK, makes sense. Thanks!

**Comment by DaRosenberg** [comment] 2018-09-03 10:55
@sfmskywalker We should not be seeing this issue anymore now!
