### ISSUE TITLE
Remove obsolete features from the runtime

### ISSUE THREAD

**Issue by kumpera** [mono/mono#9300] opened 2018-06-25 16:17 UTC
Tracking issue for runtime features we can and most likely will remove as part of the next major release version (e.g. Mono 6.0)

The separate issue exists for BCL and tool tracking #6523.

## Confirmed
- [ ] Tasklets 
- [ ] Profiler classical arguments/model
- [ ] All sandboxing technologies - CAS and CoreCLR security model
- [ ] Sgen split nursery
- [ ] Precise stack scanning
- [ ] Old and New GC bridges (leave only tarjan)
- [ ] Mono.SIMD acceleration
- [ ] -O=-float32

## Candidates to be reviewed

This is a laundry list of things that I believe should be considered and discussed. 

Broken features 
- [ ] MONO_OPT_SHARED
- [ ] Extended basic blocks

Runtime API
- [ ] Wrongly exposed functions that are not usable (IE, some of those dealing with generics)

Runtime ports:
- [ ] Sparc
- [ ] Mips

**Comment by rjvdboon** [comment] 2018-06-25 22:48
can I add Large Array support (i.e. `configure --enable-big-arrays`), as far as I know it is not working anyway

**Comment by jaykrell** [comment] 2018-06-26 15:22
--enable-big-arrays does compile/link. Does it not work? .NET does have array.LongLength as well.
Precise stack scanning we want in future?

**Comment by kumpera** [comment] 2018-06-26 20:10
@jaykrell we can resurrect the precise stack scanning code in the future if we ever decide to bring it back. The interpreter is a great example of how feasible this approach is.

**Comment by kumpera** [comment] 2018-06-26 20:21
Let me cc the good mix of people to review specifics.
Everyone, what do you think about the removal of the specifics I'm listing below:

@vargaz  Tasklets, precise scanning, shared and extended bbs
@BrzVlad precise scanning, tasklets and the non-default bridges
@alexrp @rodrmoya old profiler arguments
@spouliot sandboxing technologies
@migueldeicaza @marek-safar sandboxing tech, runtime API functions and mips/sparc ports

**Comment by BrzVlad** [comment] 2018-06-26 20:45
@kumpera +precise scanning (I think it's far from even compiling at this point), +split nursery (unfortunately never seen gains with it as far as I tested), maybe still keep the new bridge as fallback since I think we just switched from it just 1-2 years ago.

**Comment by alexrp** [comment] 2018-06-26 20:45
Unless the profiler team needs the old arguments support, I'm all for removing it.

**Comment by vargaz** [comment] 2018-06-26 22:34
So shared is used by icalls, they need to stop using it before it can be removed. Alternatively, some code parts which support shared but not used by icalls, like generic stuff can be removed.

**Comment by rodrmoya** [comment] 2018-06-27 15:36
For the profiler old args, the Xamarin profiler already checks runtime version in all supported platforms, and uses the new ones if the version is new enough, so it should be ok to remove the old arguments

**Comment by filipnavara** [comment] 2018-07-20 14:18
Any opinion on MONO_IOMAP as possible candidate on the list?

Arguments for removal:
- It's not cover by unit tests
- The code is very inefficient, often calling `mono_portability_find_file` more than once for the same file during one API call
- Memory mapped files already don't respect it
- CoreFX doesn't have it and thus sharing the file I/O code could be troublesome

**Comment by jeromelaban** [comment] 2018-07-31 11:57
Removing the "new" android bridge needs this issue to be fixed, as we are having instabilities on some armv8 devices for large Xamarin.Android applications (https://bugzilla.xamarin.com/show_bug.cgi?id=54120). The "new" bridge is slower, but does not have this instability.

**Comment by AlexRixhardson** [comment] 2019-12-12 19:09
Since MONO_IOMAP was removed (see https://github.com/mono/mono/issues/15845), what is the equivalent replacement for it? What should we use now, if we want to access files in a case insensitive manner, e.g. to map URLs that are manually typed into a browser (with random cases) to their corresponding view files?

**Comment by jbatt33** [comment] 2020-02-18 15:05
> Since MONO_IOMAP was removed (see #15845), what is the equivalent replacement for it? What should we use now, if we want to access files in a case insensitive manner, e.g. to map URLs that are manually typed into a browser (with random cases) to their corresponding view files?

Since we can not control API calls from third party libraries, this is causing compatibility issues since moving to the newer versions of Mono. Reconsider providing this feature, it could be moved over to a build configuration option instead of a runtime environment check.

**Comment by akoeplinger** [comment] 2020-02-18 15:11
As I mentioned in https://github.com/mono/mono/issues/15845#issuecomment-567126255 we don't have control over it as we're using the corefx code now.

If you rely on this feature I'd recommend proposing it at https://github.com/dotnet/runtime for future .NET 5 work.

**Comment by flibitijibibo** [comment] 2020-04-21 20:08
Was an issue for IOMAP ever filed at `runtime` or `corefx`? We ran into this with some FNA projects, and upon closer inspection it looks like the issue is solely in managed code, whoever broke the feature thankfully didn't take the time to remove it from the CLR or even Mono's README (!) so there's a surprisingly clear path to reintroduce this, but I don't want to start from scratch if someone has already investigated it since 6.0's release.

**Comment by akoeplinger** [comment] 2020-04-21 22:23
I can't find an issue in dotnet/runtime for porting over IOMAP, you could file one if you want.
Note that even though the code might still be there in Mono hooking up those code paths to the new managed implementation might be quite complicated.

**Comment by flibitijibibo** [comment] 2020-04-21 23:20
Looks like we just have to drag the work over to this file:

https://github.com/dotnet/runtime/blob/master/src/libraries/Native/Unix/System.Native/pal_io.c

Will file an issue tomorrow...

**Comment by flibitijibibo** [comment] 2020-04-22 18:12
Issue has been filed, with a WIP patch included: https://github.com/dotnet/runtime/issues/35299

**Comment by akoeplinger** [comment] 2022-10-04 12:28
We removed most of the listed features from the mono runtime in the dotnet/runtime, closing this here.

**Closed by akoeplinger** 2022-10-04 12:28 UTC
Labels: task
