### ISSUE TITLE
Failed assertion crash in Mono threadpool-io.c when starting Couchbase Lite replication using CreateNLSocket on arm64-v8a Xamarin Android

### ISSUE THREAD

**Issue by bdgza** [mono/mono#14848] opened 2019-06-06 16:06 UTC
## Steps to Reproduce

1. Open the attached solution "TravelSample" in Visual Studio 2019 for Mac / Visual Studio 2019, with Xamarin installed.
2. Run the TravelSample.Android project on a 64-bit Android device with Android 9 installed (I use a Samsung A8 (2018) with consistent results).
3. Tap the "SIGN IN" button.
4. Assertion fails and crash.

[mobile-travel-sample-arm64-v8a.zip](https://github.com/mono/mono/files/3262438/mobile-travel-sample-arm64-v8a.zip)

### Current Behavior

When running the Xamarin.Android app on a 64-bit capable device using arm64-v8a, when the Couchbase Lite replicator starts there is a hard crash in mono:
> Assertion at /Users/builder/jenkins/workspace/xamarin-android-d16-0/xamarin-android/external/mono/mono/metadata/threadpool-io.c:368, condition `fd >= 0’ not met

When the project only enables the armeabi-v7a everything performs normally. But 32-bit apps will no longer be served to 64-bit capable devices by the Google Play Store from 1 August 2019.

Confirmed to crash every time on Samsung A8 (2018) (Samsung SM-A530F) running latest Samsung security pack (Android 9 "Pie"). We are unable to confirm if it is related to Android Pie or only to 64-bit.

### Expected Behavior

The Couchbase Lite replicator should be able to start a replication under arm64-v8a on 64-bit capable Android devices without a crash in Mono.

## On which platforms did you notice this

[X] Xamarin.Android (64-bit devices, arm64-v8a)

**Version Used**: Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit), Visual Studio 2019 for Mac 8.0.8, Xamarin.Android 9.2.3.0.
Also: Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit), Visual Studio 2017 for Mac 7.8.1, Xamarin.Android 9.1.8.0.
Also: Mono ??, Mono.Android 9.3.0.22, Visual Studio 2019 16.1.1, Xamarin.Android 9.3.0.22.

## Stacktrace

> [Mono] Searching for 'CreateNLSocket'.
> [Mono] Probing 'CreateNLSocket'.
> [Mono] Found as 'CreateNLSocket'.
> Thread started: <Thread Pool> #11
> [] * Assertion at /Users/builder/jenkins/workspace/xamarin-android-d16-0/xamarin-android/external/mono/mono/metadata/threadpool-io.c:368, condition `fd >= 0' not met
[libc] Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 13859 (Thread Pool I/O), pid 13464 > (me.TravelSample)

**Comment by borrrden** [comment] 2019-06-07 08:38
I have a feeling that this issue will be hard to track down and it has happened a few times before:

[Reference 1](https://forums.xamarin.com/discussion/82376/native-exception-threadpool-ms-io-c-344-condition-fd-0-not-met-libmonosgen-2-0-so)
[Reference 2](https://forums.xamarin.com/discussion/63285/assertion-at-threadpool-ms-io-c-370-condition-fd-0-not-met) (from me a few years ago)
[Reference 3](https://bugzilla.xamarin.com/show_bug.cgi?id=39879) The linked bug from my forum post

So in the meantime I have a few questions:

1. What is actually going on when this assertion fails?
2. Is there anything that can be done to avoid it?

**Comment by jaykrell** [comment] 2019-06-07 23:24
1. As a start, put similar assert in `ves_icall_System_IOSelector_Add`.
2. `mono_memory_barrier` in `ves_icall_System_IOSelector_Add` appears unnecessariy. all reads and writes are guarded by a lock. Right?

**Comment by jaykrell** [comment] 2019-06-07 23:49
Strictly speaking, but hard to imagine it matters, there is an incorrect union use of here. I fixed that along with adding asserts.

**Comment by softworkz** [comment] 2019-06-13 04:57
Hi, 

we're experiencing the same issue with our Xamarin Android application. We're not using Couchbase in any way.

Those are the last log lines before death:

```
06-13 00:22:18.259 D/Mono    ( 9880): DllImport error loading library '/System/Library/Frameworks/SystemConfiguration.framework/libSystemConfiguration': 'dlopen failed: library "/System/Library/Frameworks/SystemConfiguration.framework/libSystemConfiguration" not found'.
06-13 00:22:18.259 W/Mono    ( 9880): DllImport unable to load library 'dlopen failed: library "/System/Library/Frameworks/SystemConfiguration.framework/libSystemConfiguration" not found'.
06-13 00:22:18.261 D/Mono    ( 9880): DllImport attempting to load: '__Internal'.
06-13 00:22:18.261 D/Mono    ( 9880): DllImport loaded library '(null)'.
06-13 00:22:18.261 D/Mono    ( 9880): DllImport searching in: '__Internal' ('(null)').
06-13 00:22:18.261 D/Mono    ( 9880): Searching for 'CreateNLSocket'.
06-13 00:22:18.261 D/Mono    ( 9880): Probing 'CreateNLSocket'.
06-13 00:22:18.261 D/Mono    ( 9880): Found as 'CreateNLSocket'.
06-13 00:22:18.281 F/        ( 9880): * Assertion at /Users/builder/jenkins/workspace/xamarin-android-d16-1/xamarin-android/external/mono/mono/metadata/threadpool-io.c:368, condition `fd >= 0' not met
06-13 00:22:18.282 F/libc    ( 9880): Fatal signal 6 (SIGABRT), code -6 in tid 9987 (Thread Pool I/O)

```

It's the same assertion failure: `condition `fd >= 0' not met`

Also, same like in case of the original report, everything is working fine when packaging the app as 32 bit only.


What's the status of this issue and is there anything we can do to help tracing this down?

**Comment by jaykrell** [comment] 2019-06-13 05:42
Git blame, says something about 5187b0bdaaff56936d697b0753dad51e7498991d.
But hard to be sure of anything.
 1. Do you have that change?
 2. What did it look like before?
 3. How does this lead to fd < 0?

Maybe should move that code back to "all icall" and not split up, maybe that will help.
Would be nice to also link mono with -z now to gain confidence.

**Comment by softworkz** [comment] 2019-06-13 05:55
So far, we've been using VS 2017 to build, which has been working well.

Now, one of our assemblies needs System.IO.Pipelines

This cannot be used with VS 2017 due to the following bug:

xamarin/xamarin-android#1879
xamarin/xamarin-android@bf2b59c

(because System.IO.Pipelines is using ValueTask<T>)

The bug about ValueTask hasn't been fixed for VS 2017 - only for 2019!

That means, we need to switch to 2019, but with 2019 we're experiencing the bug that this conversation is about: **fd >= 0' not met**


It's similar to the Couchpotato issue in multiple ways:
- Same assertion failure before crash
- No problem when building a 32 bit APK
- The application is starting successfully and only crashing at a later time  
(in our case, it's simply a start page that allows launching our app as a service, during that launch it's crashing)

**Comment by softworkz** [comment] 2019-06-13 05:57
Effectively, those two bugs have driven us into a dead end right now..

**Comment by jaykrell** [comment] 2019-06-13 06:58
Oh, the dlopen/dlsym stuff, looks like it works out successfully (`Found as 'CreateNLSocket'.`) and then the failure.

**Comment by softworkz** [comment] 2019-06-13 07:17
Jay - thank you very much for the (more than) quick response!

Your commit looks like a potential fix for the issue; yet in this case (at least), we're ordinary consumers of the Xamarin/Android project system. Hence the question:
What is my next step? ;-)

**Comment by softworkz** [comment] 2019-06-13 23:53
What I meant is - how can we make use of the fix? Do we need to wait for a new Visual Studio 2019 version - or some Xamarin update?

**Comment by CoffeeFlux** [comment] 2019-06-19 20:39
@softworkz can you upload a sample that will trigger the bug? I've got the Couchbase one from OP but a second example would potentially be helpful :)

**Comment by lambdageek** [comment] 2019-06-19 21:03
@softworkz are you able to reproduce the assert in an `x86_64` emulatator, by the way - that would be much easier for us to debug.

**Comment by CoffeeFlux** [comment] 2019-06-19 22:06
I've produced a more minimal example here: 
[couchbase.crash.attempt.zip](https://github.com/mono/mono/files/3308039/couchbase.crash.attempt.zip)

**Comment by softworkz** [comment] 2019-06-19 22:24
> @softworkz can you upload a sample that will trigger the bug? I've got the Couchbase one from OP but a second example would potentially be helpful :)

The problem is that we needed an instant solution instead of something that will work at some point in the future. Nobody had answered my question about how (and how fast) the changes here will take until they'll be available for use.

Meanwhile I found a workaround to get compilation working with VS 2017.
In our case this didn't work due to the required ValueTask implementation (a dependency of System.IO.Pipelines), which is included in **System.Tasks.Extensions** nuget package.

The last version of the **System.Tasks.Extensions** package that "worked" (in a way allowing compilation) was 4.4.0. But the assembly included in 4.4.0 is too old for **System.IO.Pipelines**, so it failed during runtime.

The problem is that all **System.Tasks.Extensions** packages after 4.4.0 are authored in a way expecting the file being part of the runtime - which is not the case for Mono, though. (or at least the mono version that is used by Xamarin/VS2017).

So what I did was to modify the **System.Tasks.Extensions** 4.5.1 package to be like 4.4.0 package - which in turn causes the assembly to be included during build. 

Now our project compiles with VS 2017 and **System.IO.Pipelines** are working well during runtime.

**Comment by CoffeeFlux** [comment] 2019-06-19 22:28
You'd be waiting on a Xamarin update probably, but I can't offer any advice without first locating and fixing the bug. Even if you've found a workaround to use VS 17, I'd greatly appreciate if you could upload a sample that I can use to repro the bug so I can fix it for future releases.

**Comment by bdgza** [comment] 2019-06-19 22:30
Using VS 2017 for Mac made no difference for me, it still crashed all the same.

**Comment by softworkz** [comment] 2019-06-19 22:50
> You'd be waiting on a Xamarin update probably, but I can't offer any advice without first locating and fixing the bug. Even if you've found a workaround to use VS 17, I'd greatly appreciate if you could upload a sample that I can use to repro the bug so I can fix it for future releases.

I'm afraid, but time constraints don't allow me to do so. We've always been building with VS 2017, so this is resolved for us at this time.
What I can offer though, is to test this once you got a fix!

**Comment by borrrden** [comment] 2019-06-19 23:33
@bdgza The issue would lie in the Xamarin framework, not in a specific version of VS (except that it includes a specific version of Xamarin by default).  Xamarin frameworks are updated independently of the actual Visual Studio program so if you installed VS 2017 and left the Xamarin framework as it was I imagine the issue would still be present.  It used to be pretty easy to downgrade on Mac but I don't know the current state of affairs in that department.

**Comment by CoffeeFlux** [comment] 2019-06-24 22:26
What's going on here is that the return type for `CreateNLSocket` in the runtime is `int`, while in managed it's listed as `IntPtr`. In managed, it's then converted and compared [here](https://github.com/mono/mono/blob/b2124dab0150eb6f4bc4a9905a5f01a8385ec767/mcs/class/System/System.Net.NetworkInformation/NetworkChange.cs#L370) and will _not_ equal -1, so it doesn't just return false and proceeds to fail the assertion in the runtime.

It was hitting this on Android specifically because of the way CreateNLSocket was defined – on platforms without `netlink.h` it always just returned -1. I use the past tense because due to what I suspect is a version bump, this issue is actually fixed in VS4M 8.2 Preview which uses Mono 5.20, and the issue should be resolved by upgrading. 

With that said, for correctness's sake (and because the function could theoretically error and return -1 even with the proper implementation) I'll PR a proper fix to the return type tomorrow, along with a corresponding test. I don't think we'll backport it, but the issue shouldn't show up going forward.

**Comment by softworkz** [comment] 2019-06-24 22:35
I'm glad you found the problem, thanks for looking into it!

Would you be able to tell which MONO versions we will be unable to use then?

With which version was the bug introduced and in which version will it be fixed?

**Comment by CoffeeFlux** [comment] 2019-06-25 19:26
Not sure how far back this bug goes, but probably a long time. I think you should be good on Mono 5.20 or later, and the proper fix will land whenever we next branch (2019-08).

**Closed** 2019-06-26 19:41 UTC
Labels: area-Runtime: Threading
