### ISSUE TITLE
typeof(object).GetMember("") does not return an empty array

### ISSUE THREAD

**Issue by slozier** [mono/mono#16010] opened 2019-08-03 20:01 UTC
Might be caused by the change in https://github.com/mono/mono/pull/11003?

## Steps to Reproduce

```C#
typeof(object).GetMember("").Length;
```

### Current Behavior

The array contains `.ctor` so the `Length` is 1.

### Expected Behavior

The array should be empty?

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.0.0.313 (tarball Sun Jul 14 09:57:59 UTC 2019)

**Comment by marek-safar** [comment] 2019-08-05 15:08
@slozier is it regression?

/cc @steveisok

**Comment by slozier** [comment] 2019-08-05 17:16
@marek-safar I believe so since our test just started failing in CI recently. I tried with 5.20.1.34 and it returns an empty array. With the latest .NET Framework and .NET Core we also get an empty array.

**Comment by steveisok** [comment] 2019-08-05 17:44
https://github.com/mono/mono/pull/11003 likely did it. 

Reason being, the prefix check falls through to:

https://github.com/mono/mono/blame/93a6bc31511decdf93357e78fb2a1a14bf7c76c1/mcs/class/referencesource/mscorlib/system/rttype.cs#L2389-L2405

And since it's an empty string, that check returns true and it'll think it can pluck from the array the runtime gave it.  Which, in this case it's the default constructor method.

**Comment by steveisok** [comment] 2019-08-06 04:29
After some more review, looks like I was wrong.  I'm not sure how far back this goes.  

In this method:

https://github.com/mono/mono/blame/93a6bc31511decdf93357e78fb2a1a14bf7c76c1/mcs/class/referencesource/mscorlib/system/rttype.cs#L2861-L2871

The callers expect null to equal "*".  The problem is that we are treating "" the same.  I'll have a PR ready in the morning.

**Comment by akoeplinger** [comment] 2019-08-09 10:25
Fixed by https://github.com/mono/mono/pull/16054

**Closed by akoeplinger** 2019-08-09 10:25 UTC
Labels: area-BCL: mscorlib, regression
