### ISSUE TITLE
Type.GetInterface fails to find implemented interface when `ignoreCase: true` is used

### ISSUE THREAD

**Issue by joncham** [mono/mono#6579] opened 2018-01-18 18:28 UTC
## Steps to Reproduce

1. Run code below

```
using System;
using System.Collections.Generic;

public class Foo
{
    public static int Main(string[] args)
    {
        Console.WriteLine((typeof(Dictionary<string, object>).GetInterface("System.Collections.IDictionary", true) != null));
        return 0;
    }
}
```

## Current Behavior

Output: False

## Expected Behavior

// .NET returns True
Output: True

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ x] Windows

**Version Used**:

Recent mono master (perhaps a few weeks old)

### Stacktrace

```
Please paste the stacktrace here if available.
```

**Comment by lambdageek** [comment] 2018-01-18 22:41
The problem is specifically the `ignoreCase: true` argument of `RuntimeType.GetInterface(string fullname, bool ignoreCase)`.  If the call in the repro is `GetInterface ("System.Collections.IDictionary", false)` we get the expected answer.

The problem is likely https://github.com/mono/mono/blob/117468d740a1dc0eea58cc2b020185cf5c5f8b7d/mcs/class/referencesource/mscorlib/system/rttype.cs#L3417
by the time that comparison is done, `ignoreCase` is `true` and `name` is the lowercased version of the class name (not including the namespace).

**Comment by zaytsev-victor** [comment] 2018-01-23 05:51
@lambdageek Can I take it?

**Comment by marek-safar** [comment] 2018-01-23 08:29
@zaytsev-victor sure, nobody is assigned to the issue so it's free to grab

**Comment by luhenry** [comment] 2018-01-23 17:09
@zaytsev-victor I am assigning myself just so I can more easily follow up on the bug, not to actually work on it, so please feel free to provide a PR linking back to this issue with the fix. Thank you again very much for contributing to Mono! And if you are stuck on anything, feel free to ping us back here.

**Comment by lambdageek** [comment] 2018-02-06 18:37
@zaytsev-victor how's it going? Are you still interested in giving this a try? Anything that we can help with?

**Comment by KonH** [comment] 2018-03-05 15:06
@lambdageek can I take this issue? (is GitHub issues rules described anywhere? can't find it on http://www.mono-project.com/community/contributing/ pages)

**Comment by lambdageek** [comment] 2018-03-05 15:45
@KonH sure, please go ahead.  Thanks!

I don't think we have formal rules around GH issues.  I think it's alright to mention on the Issue that you'd like to work on it, and then just link to the issue when you make a pull request.

**Comment by KonH** [comment] 2018-03-06 16:24
@lambdageek 
I really interesting to contribute, but faced to infrastructure issues and information overdose unfortunately.

I made repo with repro code https://github.com/KonH/MonoIssues/tree/master/6579
Also, in replaceTest I built test version of mscorlib, where I made changes which can be easily detected in simple code. But when I build it, another runtime is used and changed library is ignored:

```
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319

Unhandled Exception:
System.MissingFieldException: Field 'System.Array.IsNewAssembly' not found.
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingFieldException: Field 'System.Array.IsNewAssembly' not found.

```
OS:
macOS Sierra 10.12.6

Mono:

```
Mono JIT compiler version 5.10.0.141 (2017-12/e87d1235da1 Mon Feb 26 16:43:46 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

**Main question is:**
How can I properly replace mscorlib for testing? Is full mcs compiling is required for it?

When I tried to compile it, it failed (autoconf automake libtool pkg-config cmake installed):

```
./autogen.sh --prefix=/usr/local
make
make install
```
Output here - https://gist.github.com/KonH/da6c5d0230803d70df137cd15c439338

Sorry for newby questions anyway.

**Comment by lambdageek** [comment] 2018-03-06 16:45
@KonH A couple suggestions

1. It looks like you added a field to `System.Array`.  This is, I think, the cause of the rest of your problems - Mono has an assertion that System.Array doesn't contain any fields.  If you just want to do an experiment to see if your new version of mscorlib is being created, I'd suggest adding a method to one of the classes in the `Mono` namespace (ie somewhere in `mcs/class/corlib/Mono/*.cs`).

2. I usually don't bother installing Mono that I build from source to run simple tests.  This is what I do:
   ```
   export GITROOT=<directory where I have Mono sources checked out>
   cd $GITROOT
   ./autogen.sh --prefix=/opt/mono-master # prefix doesn't really matter - I'm not going to install
   make get-monolite-latest # only if I don't have a working mono on my path somewhere
   make
   cd /where/my/test/lives
   MONO_PATH=$GITROOT/mcs/class/lib/net_4_x $GITROOT/mono/mono/mini/mono Repro.exe
   ```

  The `MONO_PATH` should be enough for mono to find the mscorlib from your build tree.

3. Once you have some code that you're happy with, the tests for corlib live in `mcs/class/corlib/Test/*/*.cs`   You can add a failing test with something like:

   ```csharp
      [Test]
      public void MyFailingTest () {
         // Test description
         // Link to GH issue
         Assert.IsTrue (false);
      }
   ```
   and I usually run them with: `make -C mcs/class/corlib check` (this will compile the test assembly and run all the tests in it - might take a while).

**Comment by KonH** [comment] 2018-03-07 15:36
@lambdageek 
Thanks, it works! Now I understand it better.
I made fix here - https://github.com/KonH/mono/commit/4fd1190ee7f151a288d2e6cb94362308ad41b576 (and formatting fixed in next commit)
And test added in this commit - https://github.com/KonH/mono/commit/dc57d0b751cf1a370d8816b8731767ee0e2f65b9
Can you please review it or I can send PR with this commits?

**Comment by lambdageek** [comment] 2018-03-07 15:42
Thanks @KonH 

Please open a PR - we do reviews and testing using GitHub.

(Because of how github works, it's usually a good idea to make a branch in your clone with a name other than 'master' before sending a PR - that was you can commit changes in the branch and keep master in sync with upstream mono master)

**Closed** 2018-03-07 22:59 UTC
Labels: area-BCL: mscorlib, good first issue, help wanted
