### ISSUE TITLE
[DevCom] X509Certificate exception in VS2019 Preview 2 for Xamarin.Forms Android and Xamarin.Android projects

### ISSUE THREAD

**Issue by grendello** [mono/mono#12817] opened 2019-02-06 13:49 UTC
Developer Community issue: https://developercommunity.visualstudio.com/content/problem/442312/x509certificate-exception-in-vs2019-preview-2-for.html

Original post:

```
We use an X509Certificate in our tool and we've noticed a crash since VS 2019 Preview 2 that occurs regularly for Xamarin.Forms projects targeting Android as well as Xamarin.Android. When we try to create our certificate:

X509Certificate appCert = new X509Certificate(pubCertBytes);

We see a runtime exception:

Unhandled Exception:

System.PlatformNotSupportedException: Cannot get ISystemDependencyProvider. occurred

The same code works fine in VS2017 or VS2019 Preview 1 so it seems like it's an issue with the newest versions of VS2019.
```

**Comment by marek-safar** [comment] 2019-02-07 08:17
@baulig please follow up on this issue

**Comment by baulig** [comment] 2019-02-20 22:35
Duplicate of https://github.com/xamarin/xamarin-android/issues/2679.

**Closed by baulig** 2019-02-20 22:35 UTC
Labels: area-BCL: System, target-xamarin-android
