### ISSUE TITLE
Error when debugging

### ISSUE THREAD

**Issue by ShreyaSharmaMS** [mono/mono#8848] opened 2018-05-23 18:50 UTC
## Steps to Reproduce
1. Hit a breakpoint and click "Step Over" 

### Current Behavior
When debugging with the android designer, the debugger randomly crashes with this output: 

```
[0x700010f7c000] The instruction pointer of the currently executing method(Xamarin.AndroidDesigner.Resources.Ast.ResourceRepository:ParseResourceFile (System.Collections.Generic.ICollection`1<Xamarin.AndroidDesigner.Resources.Ast.IResource>,Xamarin.AndroidDesigner.IO.IAbstractFile,bool)) is not on the recorded stack. This is likely due to a runtime bug. The 1 frames are as follow:
    2018-05-23 13:36:54.526 mono64[2449:697819] error: * Assertion at debugger-agent.c:4716, condition `method_in_stack' not met
    Stacktrace:
    
    at <unknown> <0xffffffff>
        at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1213
        at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x0001f] in <17f5177733084096b17badd9e32426e5>:0
            
            Native stacktrace:
            
            0   mono64                              0x000000010a8dadf8 mono_handle_native_crash + 264
            1   libsystem_platform.dylib            0x00007fff50dd0f5a _sigtramp + 26
            2   ???                                 0x000000011816a558 0x0 + 4699104600
            3   libsystem_c.dylib                   0x00007fff50b6e1ae abort + 127
            4   libxammac.dylib                     0x0000000112826210 _ZL12log_callbackPKcS0_S0_iPv + 64
            5   mono64                              0x000000010ab05e33 monoeg_g_logv + 83
            6   mono64                              0x000000010ab06097 monoeg_assertion_message + 199
            7   mono64                              0x000000010a917c06 ss_update + 646
            8   mono64                              0x000000010a8fed4e process_breakpoint + 894
            9   mono64                              0x000000010a8fe95e mono_debugger_agent_breakpoint_from_context + 158
            10  ???                                 0x000000010acbf07f 0x0 + 4476104831
            11  ???                                 0x0000000146450bf0 0x0 + 5473897456
            12  ???                                 0x000000014644f72b 0x0 + 5473892139
            13  ???                                 0x000000014644ac49 0x0 + 5473872969
            14  ???                                 0x0000000146449e35 0x0 + 5473869365
            15  ???                                 0x0000000146448f6b 0x0 + 5473865579
            16  ???                                 0x00000001125e8fab 0x0 + 4603154347
            17  ???                                 0x00000001125acf03 0x0 + 4602908419
            18  ???                                 0x00000001125c681b 0x0 + 4603013147
            19  ???                                 0x00000001125c062b 0x0 + 4602988075
            20  mono64                              0x000000010a82cf38 mono_jit_runtime_invoke + 1416
            21  mono64                              0x000000010aa1c82
```

## On which platforms did you notice this
[X] macOS
[ ] Linux
[ ] Windows

**Version Used**: 
```
Mono JIT compiler version 5.14.0.90 (2018-04/4785686a4de Tue May 22 11:18:54 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

**Comment by lewurm** [comment] 2018-07-03 21:51
duplicate of https://github.com/mono/mono/issues/8627 ?

**Comment by lewurm** [comment] 2018-09-03 10:34
I'm closing this because it appears to be a duplicate of https://github.com/mono/mono/issues/8627

**Closed by lewurm** 2018-09-03 10:34 UTC
Labels: area-Debugger
