### ISSUE TITLE
DebuggerTests.StackTraceInNative flaky (Exception of type 'Mono.Debugger.Soft.VMDisconnectedException' was thrown.)

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#11516] opened 2018-11-02 08:27 UTC
## Steps to Reproduce

1. Submit a PR.

### Current Behavior

Random failures.
e.g.

https://github.com/mono/mono/pull/11466
https://jenkins.mono-project.com/job/test-mono-pull-request-coop/9741/

https://jenkins.mono-project.com/job/test-mono-pull-request-coop/9741/testReport/junit/(root)/DebuggerTests/StackTraceInNative/

```
Error Message
TearDown : Mono.Debugger.Soft.VMDisconnectedException : Exception of type 'Mono.Debugger.Soft.VMDisconnectedException' was thrown.
Stacktrace
--TearDown
  at Mono.Debugger.Soft.Connection.disconnected_check () [0x00018] in /mnt/jenkins/workspace/test-mono-pull-request-coop/mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs:1323 
  at Mono.Debugger.Soft.Connection.SendReceive (Mono.Debugger.Soft.Connection+CommandSet command_set, System.Int32 command, Mono.Debugger.Soft.Connection+PacketWriter packet) [0x000e5] in /mnt/jenkins/workspace/test-mono-pull-request-coop/mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs:1636 
  at Mono.Debugger.Soft.Connection.SendReceive (Mono.Debugger.Soft.Connection+CommandSet command_set, System.Int32 command) [0x00000] in /mnt/jenkins/workspace/test-mono-pull-request-coop/mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs:1644 
  at Mono.Debugger.Soft.Connection.VM_Resume () [0x00000] in /mnt/jenkins/workspace/test-mono-pull-request-coop/mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs:1741 
  at Mono.Debugger.Soft.VirtualMachine.Resume () [0x00006] in /mnt/jenkins/workspace/test-mono-pull-request-coop/mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs:125 
  at MonoTests.DebuggerTests.TearDown () [0x0001c] in /mnt/jenkins/workspace/test-mono-pull-request-coop/mcs/class/Mono.Debugger.Soft/Test/dtest.cs:385 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /mnt/jenkins/workspace/test-mono-pull-request-coop/mcs/class/corlib/System.Reflection/MonoMethod.cs:325 
```

### Expected Behavior

Success.

## On which platforms did you notice this

Linux

**Comment by lewurm** [comment] 2018-11-02 09:50
duplicate of https://github.com/mono/mono/issues/9036 ?

**Closed as completed** 2018-12-04 18:26 UTC

**Comment by jaykrell** [comment] 2018-12-04 21:10
Another instance:  https://jenkins.mono-project.com/job/test-mono-pull-request-interpreter/12554/parsed_console/log.html
