### ISSUE TITLE
Add the module filename to any stack frames in the crash report

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11918] opened 2018-12-04 11:17 UTC
We need to add the module filename to any stack frames in the crash report.  Currently, we only place the MVID (module version id) as the identifier in crash reports, which means if we cannot resolve the MVID then we have no information about the frame at all (see SymbolizedReport.json…the second frame is not resolved).  Here’s the raw form from the un-symbolized report:

```
        {
          "is_managed" : "true",
          "guid" : "81BA78C8-DC79-4B7F-9F7B-530C53DB0F84",
          "token" : "0x6001763",
          "native_offset" : "0x482",
          "il_offset" : "0x00093"
        },
```

We must have the module name here to ensure the crash report is trendable between versions.  For example, let’s say that the attached issue is caused by Foo.dll.  This module will have a different MVID if it has been updated between versions.  This means that when we ship two versions of Visual Studio for Mac with the same issue in it, we will create two different failure buckets…causing us to not count hits of this issue correctly (and potentially miss a high impact issue because it was spread to multiple failures).

/cc @leculver

**Comment by leculver** [comment] 2018-12-04 16:49
The end result should probably look something like this:

        {
          "is_managed" : "true",
          "guid" : "81BA78C8-DC79-4B7F-9F7B-530C53DB0F84",
          "token" : "0x6001763",
          "native_offset" : "0x482",
          "il_offset" : "0x00093",
          "filename": "foo.dll",
          "sizeofimage": "0x12345678",
          "timestamp": 0x87654321
        },

We don't need the full filepath (so not "/usr/lib/foo.dll"), just the module name ("foo.dll") so that we know where the frame came from in case we can't symbolize the result.  We should still leave in the guid, since other tools use it now.

**Comment by alexanderkyte** [comment] 2018-12-19 03:35
Looks like a duplicate of https://github.com/mono/mono/issues/11919

**Comment by alexanderkyte** [comment] 2019-01-07 16:40
Fixed by https://github.com/mono/mono/pull/12126

**Comment by alexanderkyte** [comment] 2019-01-15 16:39
Fix is on https://github.com/mono/mono/pull/12125

**Closed** 2019-01-25 20:22 UTC
Labels: area-Runtime: Crash Reporting, task
