### ISSUE TITLE
WebClient does not provide HTTP content on 403 forbidden status

### ISSUE THREAD

**Issue by sharkfoo** [mono/mono#11072] opened 2018-10-10 18:30 UTC
[ClientCompare.zip](https://github.com/mono/mono/files/2465935/ClientCompare.zip)

## Steps to Reproduce
On Windows...
1. Extract ClientCompare.zip and load ClientCompare.sln into visual studio and rebuild all
2. Open a console and run Client.CompareHost.exe
3. Open another console and run ClientCompare.exe
4. Observe on windows that both WebClient and HttpClient provide the HTTP content returned from the WebAPI
```
PS C:\Users\pearson1\source\repos\ClientCompare\ClientCompare\bin\Debug> .\ClientCompare.exe
====================WEBCLIENT=========================
RESULT: Forbidden
CONTENT: {"version":"1.0.0","httpStatusCode":403,"errors":[{"code":"62863","message":"The app platform is not supported
on this device."}]}
===================HTTPCLIENT=========================
RESULT: Forbidden
CONTENT: {"version":"1.0.0","httpStatusCode":403,"errors":[{"code":"62863","message":"The app platform is not supported
on this device."}]}
```

On Linux...
1.  Copy the ClientCompare directory to a Linux/Mono machine.
2. Open a console and run /usr/bin/mono ./Client.CompareHost.exe
3. Open another console and run /usr/bin/mono ./ClientCompare.exe
4. Observe that WebClient does not provide the HTTP content from the WebAPI response.
```
root@local-connector-mono-1-WPP1:~# /usr/bin/mono ./ClientCompare.exe
====================WEBCLIENT=========================
RESULT: Forbidden
CONTENT: null
===================HTTPCLIENT=========================
RESULT: Forbidden
CONTENT: {"version":"1.0.0","httpStatusCode":403,"errors":[{"code":"62863","message":"The app platform is not supported on this device."}]}
```

### Current Behavior
WebClient does not provide the HTTP content from a 403 response.

### Expected Behavior
WebClient should provide the HTTP content from a 403 response, as it does on windows .net framework and int he HttpClient.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:
```
root@local-connector-mono-1-WPP1:~# mono --version
Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:24:32 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)
```

**Comment by xfortin-devolutions** [comment] 2018-10-10 19:42
I've encountered the same issue while using the AWSSDK.

I'd add that it is also occurring with 400 (Bad Request) and 404 (Not Found). I think it would be fair to assume that this occur with the entire 4xx spectrum or status code (though I haven't confirmed myself).

I'm reproducing it in macOS.

This is not an issue in Mono 5.10.

**Comment by marek-safar** [comment] 2018-10-12 13:19
It should be stable in few weeks but you can already get it from preview channel https://www.mono-project.com/download/preview/

**Comment by sharkfoo** [comment] 2018-10-16 20:20
I tried to reproduce using the stable, preview, and nightly repositories for debian and the issue has not been fixed in any of them.

stable-stretch: 5.16.0.179
preview-stretch: 5.16.0.147
nightly-stretch: 5.19.0.290

preview did not have version 5.18.

**Comment by sharkfoo** [comment] 2018-10-17 17:08
The repository must have been updated and I was able to test this against preview-stretch for debian amd64 5.18.0.147.  This issue has not been fixed in that release.

**Comment by akoeplinger** [comment] 2018-10-19 11:18
@baulig could you please take a look at this? apparently it's not fixed in 5.18.

**Comment by sharkfoo** [comment] 2018-11-16 17:34
> @baulig could you please take a look at this? apparently it's not fixed in 5.18.

Let me know if you need additional help reproducing the issue.

**Comment by marek-safar** [comment] 2018-11-20 16:34
I can still reproduce the issue today with master. The issue is in the way how we handle the returned response stream and we hit this check https://github.com/mono/mono/blob/e9987df5bda67cba41fd4962cb377507f9cb72c9/mcs/class/System/System.Net/WebConnectionStream.cs#L117

**Comment by coffmarp** [comment] 2019-02-27 17:24
I am still able to reproduce this. This seems related to the closed issue #10645

```
static void Main(string[] args)
        {
            try
            {
                string s = new WebClient().UploadString(new Uri("https://github.com/api/invalidendpoint"), "");
                Console.WriteLine(s);
            }
            catch (WebException webException)
            {
                var stream = webException.Response.GetResponseStream();

                using (var reader = new StreamReader(stream))
                {
                    try
                    {
                        Console.WriteLine(reader.ReadToEnd());
                    }
                    catch (Exception e)
                    {
                       Console.WriteLine(e);
                    }
                }

            }
        }
```

The last working versions of mono I found were the 5.10 versions

Running it on the latest mono version on macOS results in the following.

```
$ mono -V
Mono JIT compiler version 5.20.0.225 (2018-10/ea3e93b191f Mon Feb 25 13:56:16 EST 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
$ mono test.exe 
System.Net.WebException: The request was canceled
  at System.Net.WebOperation.CheckThrowDisposed (System.Boolean throwIt, System.Runtime.ExceptionServices.ExceptionDispatchInfo& field) [0x00029] in <b5770dddf7a049e4a3f693b1ca2b5796>:0 
  at System.Net.WebOperation.ThrowIfClosedOrDisposed (System.Threading.CancellationToken cancellationToken) [0x00011] in <b5770dddf7a049e4a3f693b1ca2b5796>:0 
  at System.Net.WebOperation.ThrowIfClosedOrDisposed () [0x00006] in <b5770dddf7a049e4a3f693b1ca2b5796>:0 
  at System.Net.WebConnectionStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00019] in <b5770dddf7a049e4a3f693b1ca2b5796>:0 
  at System.IO.StreamReader.ReadBuffer () [0x00028] in <6d83221bea054562936f2f38bd41deeb>:0 
  at System.IO.StreamReader.ReadToEnd () [0x00052] in <6d83221bea054562936f2f38bd41deeb>:0 
  at testing.Program.Main (System.String[] args) [0x00050] in <2c4f5f4aa4e64ecc87e738600bdb557d>:0
  ```

**Comment by marek-safar** [comment] 2019-03-01 10:58
@baulig what is your estimate on this one?

**Comment by carvalho-oak** [comment] 2019-03-24 15:23
System.Net.WebException has been thrown
`Value cannot be null. Parameter name: src`

```
=== Visual Studio Enterprise 2019 Preview for Mac ===

Version 8.0 Preview (8.0 build 2931)
Installation UUID: 4c4a8851-cc12-4f80-847b-b7a729c3292a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.1.8.0 (Visual Studio Enterprise)
Android SDK: /Users/carloscarvalho/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.1

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/carloscarvalho/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-03-15 21:58:58 UTC

=== Xamarin Designer ===

Version: 4.17.4.407
Hash: 2897b5f8c
Branch: remotes/origin/d16-0
Build date: 2019-03-15 18:29:24 UTC

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.16 (Visual Studio Enterprise)
Hash: 2dc06c71
Branch: 
Build date: 2019-02-12 23:09:50-0500

=== Xamarin.iOS ===

Version: 12.2.1.16 (Visual Studio Enterprise)
Hash: 2dc06c71
Branch: d15-9
Build date: 2019-02-12 23:09:50-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800002931
Git revision: 36acb974fd4576544398d2eba261d6416b309fa6
Build date: 2019-03-19 01:19:42+00
Build branch: master
Xamarin extensions: 4fb9d9fd52d8b071a61f6062d07b60c54e1c5af3

=== Operating System ===

Mac OS X 10.14.3
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Thu Dec 20 20:46:53 PST 2018
    root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

**Comment by steveisok** [comment] 2019-07-30 14:40
I've confirmed this works in 6.4.  Fix was https://github.com/mono/mono/pull/15220

**Closed by steveisok** 2019-07-30 14:40 UTC
Labels: area-BCL: System, regression
