### ISSUE TITLE
System.ServiceModel tests fail on iOS/TvOS/WatchOS

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#12417] opened 2019-01-14 15:57 UTC
We have started executing the ServiceModel tests that are provided from the test dlls in the Mono SDK. Some of the tests fail on ios/watchos and tvOS, we have added the required ignores in PR https://github.com/xamarin/xamarin-macios/pull/5384 

Please take a look at the new ignore files that contain the failing tests and the reasons to be ignored.

**Comment by akoeplinger** [comment] 2019-02-18 19:05
Duplicate of https://github.com/mono/mono/issues/12354

**Closed by akoeplinger** 2019-02-18 19:05 UTC
Labels: area-SDK: Packaging
