### ISSUE TITLE
NRE in nuint JIT code when compiled with csc and has a "special" name

### ISSUE THREAD

**Issue by chamons** [mono/mono#6658] opened 2018-01-24 21:00 UTC
## Steps to Reproduce

1. git clone git@github.com:chamons/filed-bug-test-cases.git
2. cd filed-bug-test-cases/csc_op_inc/
3. make

## Current Behavior

If we compile nuint into a "special" assembly name, such as Xamarin.Mac.dll or builtin-types.dll with csc, we crash in the generated code.

## Expected Behavior

Not crashing. :)

### On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.8.0.103 (2017-10/1359c52fc6e Wed Dec 20 10:52:54 EST 2017)

### Stacktrace

```
$ make
First we use mcs and it works
mcs /nologo -out:builtin-types.dll -target:library -debug -unsafe Prim.cs
csc /nologo -t:exe -out:Test_mcs_Builtin.exe -r:builtin-types.dll Test.cs	
mono Test_mcs_Builtin.exe
0
1
Now we use a non-special name with csc and it works
csc /nologo -out:not-builtin-types.dll -target:library -debug -unsafe Prim.cs
csc /nologo -t:exe -out:Test_Not.exe -r:not-builtin-types.dll Test.cs	
mono Test_Not.exe
0
1
Now we try csc and a special name and it fails
csc /nologo -out:builtin-types.dll -target:library -debug -unsafe Prim.cs
csc /nologo -t:exe -out:Test_Builtin.exe -r:builtin-types.dll Test.cs	
mono Test_Builtin.exe
0

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at System.nuint.op_Increment (System.nuint v) [0x00001] in <d9ba165d44514eeaa3adcbaf843bd8a2>:0 
  at Test.MainClass.Main (System.String[] args) [0x00016] in <a020da5131e94407b6499bd6853fb575>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at System.nuint.op_Increment (System.nuint v) [0x00001] in <d9ba165d44514eeaa3adcbaf843bd8a2>:0 
  at Test.MainClass.Main (System.String[] args) [0x00016] in <a020da5131e94407b6499bd6853fb575>:0 
make: *** [all] Error 1
```

**Comment by lewurm** [comment] 2018-01-24 21:14
`op_Increment` isn't implemented atm: https://github.com/mono/mono/blob/a369eb8fb0bf4c561390fc31ec0217f83222eb0e/mono/mini/mini-native-types.c#L247

looks like roslyn generated different code

**Comment by lambdageek** [comment] 2018-01-24 21:26
What's weird is that it's enough to just compile `builtin-types.dll` with roslyn:
- `mcs builtin-types.dll; csc test.exe` no crash
- `csc builtin-types.dll; csc test.exe` crash

There's some suspicious IL differences in the two builtin-types.dlls, but none of those methods should be getting called, AFAIK...

```
     .method public static hidebysig specialname 
            default int32 op_Explicit (valuetype System.nint v)  cil managed 
     {
-        // Method begins at RVA 0x2290
-       // Code size 17 (0x11)
+        // Method begins at RVA 0x2260
+       // Code size 13 (0xd)
        .maxstack 1
        .locals init (
                int32   V_0)
        IL_0000:  nop 
-       IL_0001:  ldarga.s 0
-       IL_0003:  ldfld int64 System.nint::v
-       IL_0008:  conv.i4 
-       IL_0009:  stloc.0 
-       IL_000a:  br IL_000f
+       IL_0001:  ldarg.0 
+       IL_0002:  ldfld int64 System.nint::v
+       IL_0007:  conv.i4 
+       IL_0008:  stloc.0 
+       IL_0009:  br.s IL_000b
 
-       IL_000f:  ldloc.0 
-       IL_0010:  ret 
+       IL_000b:  ldloc.0 
+       IL_000c:  ret 
     } // end of method nint::op_Explicit
```
(`-` is mcs-compiled builtin-types.dll, `+` is csc-compiled)

**Comment by vargaz** [comment] 2018-01-24 22:13
This is caused by an ldarg+ldfld opcode combination, which csc emits. 29428d951637ff85b593ea5c9cc5d5236579906d adds an optimization which works around the problem, maybe we should backport that to 2017-10.

**Comment by marek-safar** [comment] 2018-01-25 09:20
@chamons could you switch to mono-2017-12 branch which should be soon merged to master or do you need this for 15-6 release?

**Comment by chamons** [comment] 2018-01-25 15:11
@spouliot please comment - If 2017-12 is going to master in next few weeks that may be fine.

**Comment by migueldeicaza** [comment] 2018-01-25 16:31
Chris, I do not understand, for which release would this be needed?

**Comment by chamons** [comment] 2018-01-25 16:42
@migueldeicaza This is only currently needed for branch to test out default interfaces. 

https://github.com/xamarin/xamarin-macios/pull/3246

since nuint will be compiled with csc for the platform assemblies.

If that work went swimmingly and was in great shape we hoped to land it in master as well, but it isn't absolutely required.

In any case, that work is blocked until I can bump the working branch to use 2017-12 or have a set of patches to PR to work around this. A lot of tests fail when nuint doesn't work.

**Comment by marek-safar** [comment] 2018-01-26 09:40
@chamons you should be able to rebase your work on top of mono-2017-12 ios branch. As we have only a fix which workarounds the problem I'd just do it that way instead of making service release for  15.6

**Comment by chamons** [comment] 2018-01-26 17:13
So the mcs->csc work sits on top of the PMCS removal work, which is a _huge_ set of patches. Rebasing on top of a branch without those changes might be painful. 

Let's talk next week if nothing else.

**Comment by spouliot** [comment] 2018-02-15 03:49
2017-12 was merged in master, but https://github.com/xamarin/xamarin-macios/pull/3393 still fails (post merge)
was https://github.com/mono/mono/commit/29428d951637ff85b593ea5c9cc5d5236579906d back ported to 2017-12 ?

**Comment by lewurm** [comment] 2018-02-15 06:40
we will also need to backport 73eb0cc2fd9301ce3481d55267ace85c2882187f to `2017-12`

**Comment by lewurm** [comment] 2018-02-15 10:20
backport: https://github.com/mono/mono/pull/7062

**Comment by akoeplinger** [comment] 2018-02-20 13:16
@lewurm https://github.com/mono/mono/pull/7062 was merged, can this be closed again?

**Comment by lewurm** [comment] 2018-02-20 18:03
I would like the XI team to confirm the fix before closing. /cc @spouliot @chamons

**Comment by lewurm** [comment] 2018-02-20 18:04
the fix should be in `xamarin-macios/master` since this PR: https://github.com/xamarin/xamarin-macios/pull/3535

**Comment by chamons** [comment] 2018-02-20 18:07
LGTM. My PR that was hitting this:

https://github.com/xamarin/xamarin-macios/pull/3393

has a handful of failures, instead of nearly every test in the world failing.

**Closed** 2018-02-20 18:07 UTC
Labels: area-Runtime: JIT, target-xamarin-ios
