### ISSUE TITLE
[2019-12] [iOS] [armv7] undefined symbol ___multi3 on Release (LLVM) 

### ISSUE THREAD

**Issue by lewurm** [mono/mono#18560] opened 2020-01-23 21:46 UTC
when buliding `mscorlib Part 1` on iOS 32bit/Release I get the following build error:
```
22:33:20.1656140   Undefined symbols for architecture armv7: (TaskId:67)
22:33:20.1789650 MTOUCH : error MT5210: Native linking failed, undefined symbol: ___multi3. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/lewurm/work/xi-2019-12/xamarin-macios/tests/xharness/tmp-test-dir/mscorlib Part 1415/mscorlib Part 1.csproj]
22:33:20.1793290 MTOUCH : warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker [/Users/lewurm/work/xi-2019-12/xamarin-macios/tests/xharness/tmp-test-dir/mscorlib Part 1415/mscorlib Part 1.csproj]
22:33:20.1794000 MTOUCH : error MT5202: Native linking failed. Please review the build log. [/Users/lewurm/work/xi-2019-12/xamarin-macios/tests/xharness/tmp-test-dir/mscorlib Part 1415/mscorlib Part 1.csproj]
22:33:20.1795240     "___multi3", referenced from: (TaskId:67)
22:33:20.1795460         _monotouch_corlib_xunit_test_part1_System_Threading_Tasks_Tests_ParallelForTests_RunSimpleParallelFor64AddTest_long in monotouch_corlib_xunit-test.part1.dll-llvm.o (TaskId:67)
22:33:20.1795720         _monotouch_corlib_xunit_test_part1_System_Threading_Tasks_Tests_ParallelForTests_RunSimpleParallelFor64AverageAggregation_long in monotouch_corlib_xunit-test.part1.dll-llvm.o (TaskId:67)
22:33:20.1795930   ld: symbol(s) not found for architecture armv7 (TaskId:67)
22:33:20.1796280 clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/lewurm/work/xi-2019-12/xamarin-macios/tests/xharness/tmp-test-dir/mscorlib Part 1415/mscorlib Part 1.csproj]
22:33:20.1796480     (TaskId:67)
22:33:21.0904970   The command exited with code 1. (TaskId:67)
22:33:21.0912040   Output Property: _CompiledArchitectures=ARMv7 (TaskId:67)
22:33:21.0912510 Done executing task "MTouch" -- FAILED. (TaskId:67)
```

**Comment by imhameed** [comment] 2020-01-27 19:06
I guess we're not including any support code from compiler-rt: https://github.com/llvm/llvm-project/blob/0ba22f51d128bee9d69756c56c4678097270e10b/compiler-rt/lib/builtins/multi3.c

We'd need to link this in, at least.

**Comment by SamMonoRT** [comment] 2020-01-27 20:41
@vargaz - This seems like a regression, any thoughts on this one ?

**Comment by lewurm** [comment] 2020-01-28 13:34
It would be interesting to know what code pattern causes this dependency. The test is here: https://github.com/mono/corefx/blob/7c9e2158925339a5a96ff8d09d21c600a0b27e5a/src/System.Threading.Tasks.Parallel/tests/ParallelForTests.cs#L372-L396

/cc @EgorBo

**Comment by marek-safar** [comment] 2020-01-28 16:22
@vargaz what is your take on this?

**Comment by vargaz** [comment] 2020-01-28 16:23
Can we create a testcase out of the test ?

**Comment by spouliot** [comment] 2020-01-29 16:46
Nothing really new but "32bits device bot" confirms it happens on a subset of mscorlib (what's in `Part 1`) in release (so LLVM) mode.

http://xamarin-storage/jenkins/xamarin-macios/pull-request/b660546b2f601af89769b29bac28598009dbbc56/3422522/device-tests/jenkins-results/tests/index.html

```
-AssemblyBuildTarget: SDK framework (release) (BuildFailure)
Project file: /Users/xamarinqa/agent/_work/9/s/tests/xharness/tmp-test-dir/mscorlib Part 1371/mscorlib Part 1.csproj 
Platform: iPhone Configuration: Release32 
Candidate devices:
    XQAiPad4a (Version: 10.3.3)
Build duration: 00:05:11.7507727 
Time Elapsed: mscorlib Part 1 - (waiting time : 00:00:00 , running time : 04:37:17.8840736) 
Main log
Build log Binlog download
19:49:58.7176700 MTOUCH : error MT5210: Native linking failed, undefined symbol: ___multi3. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/xamarinqa/agent/_work/9/s/tests/xharness/tmp-test-dir/mscorlib Part 1371/mscorlib Part 1.csproj] 
19:49:58.7184610 MTOUCH : error MT5202: Native linking failed. Please review the build log. [/Users/xamarinqa/agent/_work/9/s/tests/xharness/tmp-test-dir/mscorlib Part 1371/mscorlib Part 1.csproj] 
19:49:58.7194210 clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/xamarinqa/agent/_work/9/s/tests/xharness/tmp-test-dir/mscorlib Part 1371/mscorlib Part 1.csproj] 
19:50:00.1647440 MTOUCH : error MT5210: Native linking failed, undefined symbol: ___multi3. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/xamarinqa/agent/_work/9/s/tests/xharness/tmp-test-dir/mscorlib Part 1371/mscorlib Part 1.csproj] 
19:50:00.1647690 MTOUCH : error MT5202: Native linking failed. Please review the build log. [/Users/xamarinqa/agent/_work/9/s/tests/xharness/tmp-test-dir/mscorlib Part 1371/mscorlib Part 1.csproj] 
19:50:00.1648360 clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/xamarinqa/agent/_work/9/s/tests/xharness/tmp-test-dir/mscorlib Part 1371/mscorlib Part 1.csproj] 
```

and
```
19:49:58.7191290   Undefined symbols for architecture armv7: (TaskId:64)
19:49:58.7191870     "___multi3", referenced from: (TaskId:64)
19:49:58.7192420         _monotouch_corlib_xunit_test_part1_System_Threading_Tasks_Tests_ParallelForTests_RunSimpleParallelFor64AddTest_long in monotouch_corlib_xunit-test.part1.dll-llvm.o (TaskId:64)
19:49:58.7192980         _monotouch_corlib_xunit_test_part1_System_Threading_Tasks_Tests_ParallelForTests_RunSimpleParallelFor64AverageAggregation_long in monotouch_corlib_xunit-test.part1.dll-llvm.o (TaskId:64)
19:49:58.7193530   ld: symbol(s) not found for architecture armv7 (TaskId:64)
19:49:58.7194210 clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/xamarinqa/agent/_work/9/s/tests/xharness/tmp-test-dir/mscorlib Part 1371/mscorlib Part 1.csproj]
19:49:58.7194940     (TaskId:64)
```


Same build failure can be seen in

```
Release (BuildFailure)
```
and
```
Release: UseThumb (BuildFailure)
```

This does not happen in xamarin-macios/master so it's unlikely to be a change from a recent Xcode Version.

**Comment by lewurm** [comment] 2020-01-30 13:59
repro on linux/armhf:
```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

public class Repro {
        public static void Main (string []args) {
                Console.WriteLine ("meh: " + RunSimpleParallelFor64AddTest (1024));
        }

        public static long RunSimpleParallelFor64AddTest(long count)
        {
                long expectCounter = 0;
                for (long i = 0; i < count; i++)
                {
                        expectCounter += i;
                }

                long counter = 0;

                // run inside of a separate task mgr to isolate impacts to other tests.
                Task t = Task.Run(
                        delegate
                        {
                                Parallel.For(0L, count, (x) => Interlocked.Add(ref counter, x));
                        });
                t.Wait();


                if (expectCounter != counter)
                        throw new Exception ("wrong result");
                return counter;
        }
}
```

```console
$  MONO_PATH=`pwd`/mcs/class/lib/build-linux/ ./mono/mini/mono-sgen --aot=llvm repro-gh18560.exe
Mono Ahead of Time compiler - compiling assembly /mono/repro-gh18560.exe
AOTID E93809B2-17E5-89F9-29E3-65604A8E0B8F
Executing opt: "opt" -f -O2 -disable-tail-calls -place-safepoints -spp-all-backedges -o "mono_aot_2jaeYu/temp.opt.bc" "mono_aot_2jaeYu/temp.bc"
Executing llc: "llc"  -enable-implicit-null-checks -disable-fault-maps -march=arm -mattr=+vfp2,-neon,+d16 -float-abi=hard -asm-verbose=false -disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=mono_aot_repro_gh18560_eh_frame -disable-tail-calls -relocation-model=pic -filetype=obj -o "mono_aot_2jaeYu/temp-llvm.o" "mono_aot_2jaeYu/temp.opt.bc"
Compiled: 11/11
Executing the native assembler: "as"   -mfpu=vfp3 -o /tmp/mono_aot_mc4CMP.o /tmp/mono_aot_mc4CMP
Executing the native linker: gcc --shared -Wl,-Bsymbolic -o /mono/repro-gh18560.exe.so.tmp "mono_aot_2jaeYu/temp-llvm.o" /tmp/mono_aot_mc4CMP.o
Stripping the binary: "strip" --strip-symbol=\$a --strip-symbol=\$d /mono/repro-gh18560.exe.so.tmp
JIT time: 21 ms, Generation time: 92 ms, Assembly+Link time: 58 ms.
$ MONO_PATH=`pwd`/mcs/class/lib/build-linux/ ./mono/mini/mono-sgen repro-gh18560.exe
./mono/mini/mono-sgen: symbol lookup error: /mono/repro-gh18560.exe.so: undefined symbol: __multi3
```
---------------------------------
The problem is the loop computing `expectCounter`. LLVM IR we generate for it:
```
BB4:                                              ; preds = %BB5, %BB2
  %6 = phi i64 [ 0, %BB2 ], [ %t70, %BB5 ]
  %7 = phi i64 [ 0, %BB2 ], [ %t60, %BB5 ]
  %8 = bitcast i32* %3 to i64*
  %9 = getelementptr i64, i64* %8, i32 1
  %t77 = load i64, i64* %9
  %10 = icmp slt i64 %6, %t77
  %t80 = zext i1 %10 to i32
  %11 = trunc i32 %t80 to i8
  %t30 = zext i8 %11 to i32
  %12 = icmp ne i32 %t30, 0
  br i1 %12, label %BB5, label %BB6

BB5:                                              ; preds = %BB4
  %t60 = add i64 %7, %6
  %t70 = add i64 %6, 1
  br label %BB4
```
After `opt` the loop is eliminated:
```
BB5.lr.ph:                                        ; preds = %BB2
  %5 = add i64 %arg_count, -1
  %6 = zext i64 %5 to i65
  %7 = add i64 %arg_count, -2
  %8 = zext i64 %7 to i65
  %9 = mul i65 %6, %8
  %10 = lshr i65 %9, 1
  %11 = trunc i65 %10 to i64
  %12 = add i64 %11, %arg_count
  %13 = add i64 %12, -1
  br label %BB
```
which is nice, but due to overflow semantics it uses an _`i65`_, which will be expanded to `i128` by the LLVM codegen. Therefore, `mul i65` is really a `mul i128` which is either
* a call into `compiler-rt`: https://github.com/dotnet/llvm-project/blob/adeaa08e7bbc9aba5d67cb16c2b348be12deb000/llvm/include/llvm/CodeGen/RuntimeLibcalls.def#L50
* or, it will be lowered to multiple instructions by this: https://github.com/dotnet/llvm-project/blob/adeaa08e7bbc9aba5d67cb16c2b348be12deb000/llvm/lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp#L2353-L2430

Now the `multi3` builtin is explicitly excluded on iOS armv7 (and apparently also on Linux): https://github.com/dotnet/llvm-project/blob/adeaa08e7bbc9aba5d67cb16c2b348be12deb000/compiler-rt/lib/builtins/Darwin-excludes/ios-armv7.txt#L44

Some other backends disable the `compiler-rt`, e.g. https://github.com/dotnet/llvm-project/blob/adeaa08e7bbc9aba5d67cb16c2b348be12deb000/llvm/lib/Target/X86/X86ISelLowering.cpp#L1632

Doing the same for the ARM backend in `ARMISelLowering.cpp` fixes the problem. The relevant generated code turns from:
```
00000258    00 10 c6 e2     sbc r1, r6, #0
0000025c    67 ff ff eb     bl  ___multi3
00000260    a1 10 b0 e1     lsrs    r1, r1, #1
00000264    60 00 a0 e1     rrx r0, r0
00000268    82 1f 81 e1     orr r1, r1, r2, lsl #31
```
to
```
0000023c    00 10 c5 e2     sbc r1, r5, #0
00000240    02 20 5a e2     subs    r2, r10, #2
00000244    90 92 83 e0     umull   r9, r3, r0, r2
00000248    91 32 a4 e0     umlal   r3, r4, r1, r2
0000024c    00 20 c5 e2     sbc r2, r5, #0
00000250    90 32 a4 e0     umlal   r3, r4, r0, r2
00000254    91 42 20 e0     mla r0, r1, r2, r4
00000258    a3 10 b0 e1     lsrs    r1, r3, #1
0000025c    69 20 a0 e1     rrx r2, r9
00000260    80 0f 81 e1     orr r0, r1, r0, lsl #31
```
-----------------
This might be the fix already. However, some open questions:
* Does it also happen on upstream clang/llvm? It might be an upstream bug.
* Why does it happen _now_? Is the test new? Why does it not happen on our CI on the armhf AOT+LLVM lane? I can clearly repro it on my linux device.

**Comment by vargaz** [comment] 2020-01-30 14:13
Nice work.
Is it possible that opt does this optimization because the data layout is not set correctly on this platform, i.e.
the value of MONO_ARCH_LLVM_TARGET_LAYOUT is not correct ?

**Comment by vargaz** [comment] 2020-01-30 14:16
Could you attach the input .bc file, it can be retained by running the aot compiler with --aot=save-temps ?

**Comment by lewurm** [comment] 2020-01-30 17:41
[mono_aot_KH6Rrt.zip](https://github.com/mono/mono/files/4135426/mono_aot_KH6Rrt.zip)

`MONO_ARCH_LLVM_TARGET_LAYOUT` is a good hint, will have a look at the docs.

**Comment by lewurm** [comment] 2020-01-30 18:10
llvm only repro https://gist.github.com/lewurm/15220ff734c222540ff68b8ddf9a5b0b

**Comment by imhameed** [comment] 2020-03-06 00:49
I started looking at this.

The reproducing C# source can be simplified to:
```
public static long indvar_test(long count) {
    long counter = 0;
    for (long i = 0; i < count; ++i) {
        counter += i;
    }
    return counter;
}
```

The IndVarSimplify pass ends up replacing this loop with a closed sequence of instructions with widened intermediate values. This isn't an issue on 64-bit targets, but 32-bit targets don't have any 128-bit support code in compiler-rt (the exclusion lists in Darwin-excludes are apparently there to squelch warnings):
https://github.com/dotnet/llvm-project/blob/60293630cb227f866a1726076adbe72398953dbc/compiler-rt/lib/builtins/multi3.c#L17
https://github.com/dotnet/llvm-project/blob/60293630cb227f866a1726076adbe72398953dbc/compiler-rt/lib/builtins/int_types.h#L63
https://github.com/dotnet/llvm-project/commit/f14b3f10a8715d4dfca60e913655baf0576360b2#diff-c6a218792f93f0590deef6bad6ba5557

There's an upstream bug report for this: https://bugs.llvm.org/show_bug.cgi?id=20871. This resulted in this x86-specific hack: https://reviews.llvm.org/D38668 and https://github.com/dotnet/llvm-project/commit/fcf27188d7530a9931ba59e6231463c0acf0e8ba

It'd be simplest to mirror this hack for ARM. I'm also interested in better understanding SCEV in LLVM; it'd be nice to have a better fix for this.

**Comment by imhameed** [comment] 2020-09-09 17:34
Should be fixed by https://github.com/mono/mono/pull/20365. I'm able to build the aforementioned repros with LLVM for an iPhone 5 now.

**Closed by imhameed** 2020-09-09 17:34 UTC
Labels: area-Runtime: AOT
