### ISSUE TITLE
WebSockets support

### ISSUE THREAD

**Issue by danroth27** [mono/mono#9567] opened 2018-07-14 23:51 UTC
_From @YandyZaldivar on July 14, 2018 17:44_

There is this issue #20 tracking SignalR client support.

I am opening this to follow a standard client WebSockets implementation. Maybe it comes from Mono making `System.Net.WebSockets` available, a separate package/api using JavaScript interop or a new API for Blazor.

Is there any projection on this already?

_Copied from original issue: aspnet/Blazor#1135_

**Comment by danroth27** [comment] 2018-07-14 23:51
This should really be provided by the Mono folks.

**Comment by danroth27** [comment] 2018-07-14 23:52
@kumpera

**Comment by danroth27** [comment] 2018-10-24 20:52
@kjpou1 Any thoughts on when support for websockets might get added to mono.wasm?

**Comment by kjpou1** [comment] 2018-10-25 12:37
@danroth27 We will need to look at it and then prioritise it.

**Comment by kjpou1** [comment] 2018-10-25 12:58
@danroth27 Set up issue for WebSocket support https://github.com/mono/mono/issues/11375

**Comment by kjpou1** [comment] 2018-10-25 13:11
Never mind closed the other as a duplicate of this.

**Comment by kjpou1** [comment] 2018-10-25 13:11
WebSocket support would be great.

What would be needed is to write a wrapper around the javascript [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) API like what was written for `HttpClientHandler` and the `Fetch` API.

**Comment by kjpou1** [comment] 2018-10-25 13:17
Also, not sure about SignalR but can javascript WebSocket API communicate with SignalR?

I was just wondering if anybody has tried the communication between the two of them.  JavaScript does not have support for native sockets so it would be good to know as a first step.

**Comment by danroth27** [comment] 2018-10-25 15:02
@kjpou1 SignalR is primarily based on WebSockets (although it supports a couple other HTTP based fallback transports as well). We ship a SignalR JavaScript client that uses the browser WebSocket API, and folks in the community have already implemented [a .NET wrapper using JS interop](https://github.com/BlazorExtensions/SignalR). We also ship a .NET SignalR client library, and folks in the community have [enabled it in Blazor as well](https://github.com/csnewman/BlazorSignalR) by replacing the transport layer to use the browser WebSocket API via JS interop as well.

**Comment by christoph68** [comment] 2018-10-25 20:22
@kjpou1 
> WebSocket support would be great.
> 
> What would be needed is to write a wrapper around the javascript [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) API like what was written for `HttpClientHandler` and the `Fetch` API.

This seems article got my attention: [WebAssembly Demystified](https://floooh.github.io/2017/06/09/webassembly-demystified.html)
"Can I access sockets, files, native API X… from WebAssembly?"
"No, WebAssembly runs inside the browser sandbox and can only access Web APIs (just like Javascript). However, the emscripten SDK provides wrappers for many common native APIs which simplifies porting existing C/C++ code over (for instance sockets-to-WebSockets, GL-to-WebGL, OpenAL-to-WebAudio, and some more…)."
Here it implies that emscripten libs can target WebAssembly [Introducing HumbleNet](https://hacks.mozilla.org/2017/06/introducing-humblenet-a-cross-platform-networking-library-that-works-in-the-browser):
"You can find pre-built redistributables at https://humblenet.github.io. These include binaries for Linux, macOS, Windows, a C# wrapper, Unity3D plugin, and emscripten (for targeting asm.js or WebAssembly)."

So it is possible to have the Websockets without interop in WASM?

**Comment by kjpou1** [comment] 2018-10-26 03:52
From everything I have been able to gather is that the emscripten library provides API's that will simplify in the porting of application.  The raw socket and TCP sockets are actually "emulated" meaning that they all use `WebSocket` protocol underneath.   I think UDP sockets are out of the question with web sockets as well, could be wrong here.  The server/clients that one would communicate with would therefore have to understand the WebSocket protocol.

Have not seen HumbleNet and will take a look at it.  Thanks for the link.

**Comment by YandyZaldivar** [comment] 2018-10-26 04:51
Thank you for starting to consider this issue. If possible I would like to know what approach will you be taking in advance for this implementation, for example if you plan to expose the same .NET API available for client side WebSockets in the `System.Net.WebSockets` namespace?

This information would be very useful since I can start coding right now relying on this API.

This project https://github.com/bridgedotnet/Bridge did a similar task exposing the exact client side API available in `System.Net.WebSockets`. I think this path, even if using JS interop is the most clean, portable and fast solution. After this, then you can consider if it makes sense to emulate raw TCP sockets falling back to WebSockets and which existing projects will actually benefit from it.

**Comment by kjpou1** [comment] 2018-10-26 05:08
Will be looking at the `System.Net.WebSockets` namespace.

**Comment by christoph68** [comment] 2018-10-26 07:01
@kjpou1 Thanks for clarification, as you can see I am not an expert in those fields. Surely UDP is out of question. Websockets are standard and expected. Await them kind of desperately.

**Comment by kjpou1** [comment] 2019-01-30 15:04
WebSocket support is implemented here: https://github.com/mono/mono/pull/12615

**Closed by kjpou1** 2019-01-30 15:04 UTC
Labels: target-wasm, task

**Comment by josuuribe** [comment] 2019-06-18 21:55
So... does it mean it’s possible to use WebSocket in Blazor client like a C# library? I have tried WebAssembly.Net.WebSockets nuget package in a Blazor Client App without success, the socket stays as “Connecting”

**Comment by danroth27** [comment] 2019-06-18 21:57
@josuuribe Not yet - we need to do https://github.com/aspnet/AspNetCore/issues/10489 first.
