### ISSUE TITLE
Xamarin System.Text.Json.JsonSerializer error after VS update to Mono 6.12.0.122 (VS 2019 Mac Update  8.8.9)

### ISSUE THREAD

**Issue by janjouni** [mono/mono#20894] opened 2021-03-04 13:52 UTC
## Steps to Reproduce

1. In your Xamarin shared project create an System.Net.Http.HttpClient
2. use GetFromJsonAsync<T> in this client to deserialize answer from API (Method in namespace System.Net.Http.Json)
3. Get Error: System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializer' threw an exception.

### Current Behavior

after the update, the behavior is as described above

### Expected Behavior

Framework should deserialize Models as expected as before

## On which platforms did you notice this

[ X] macOS
[ ] Linux
[ ] Windows

**Version Used**: 6.12.0.122

## Stacktrace

System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializer' threw an exception. ---> System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpa…}

Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)
  at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan`1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00000] in <3e024d1008104aac9fe12198f4c68344>:0 
  at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00033] in <3e024d1008104aac9fe12198f4c68344>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <3e024d1008104aac9fe12198f4c68344>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <3e024d1008104aac9fe12198f4c68344>:0 
  at System.Text.Json.JsonSerializer..cctor () [0x00042] in <3e024d1008104aac9fe12198f4c68344>:0

**Comment by Bang0123** [comment] 2021-03-08 14:02
We experience the same issue, currently using workaround posted in issue: [20805](https://github.com/mono/mono/issues/20805#issuecomment-791440473)

**Comment by marek-safar** [comment] 2021-03-19 15:27
Duplicate of #20805

**Closed by marek-safar** 2021-03-19 15:27 UTC
Labels: duplicate
