### ISSUE TITLE
monodis crashes disassembling rosyln

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#8900] opened 2018-05-26 22:47 UTC
## Steps to Reproduce

1. cd external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.7.0/tools
2. for a in *.dll; do monodis $a > $a.txt

### Current Behavior

Segmentation fault: 11

### Expected Behavior

No segmentation fault.

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.10.1.47 (2017-12/8eb8f7d5e74 Fri Apr 13 20:18:12 EDT 2018)

I need to try with head.

**Comment by jaykrell** [comment] 2018-05-26 23:00
head

```

jaymac1:tools jay$ for a in *.dll; do echo $a; /s/mono8/mono/dis/monodis $a > $a.txt; done
Microsoft.Build.Tasks.CodeAnalysis.dll
Segmentation fault: 11
Microsoft.CodeAnalysis.Scripting.dll
Segmentation fault: 11


 lldb /s/mono8/mono/dis/monodis Microsoft.Build.Tasks.CodeAnalysis.dll

	IL_0005:  call Could not load signature of Microsoft.CodeAnalysis.BuildTasks.CommandLineBuilderExtension:AppendSwitchIfNotNull due to: Could not load file or assembly 'Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Process 86595 stopped
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc)
    frame #0: 0x0000000100012886 monodis`get_method_core(m=0x000000010180f000, token=100663419, fullsig=1, container=0x0000000000000000) at get.c:1948
   1945	
   1946		mh = mono_get_method_checked (m, token, NULL, (MonoGenericContext *) container, error);
   1947		if (mh) {
-> 1948			if (mono_method_signature (mh)->is_inflated)
   1949				container = mono_method_get_generic_container (((MonoMethodInflated *) mh)->declaring);
   1950			esname = get_escaped_name (mh->name);
   1951			sig = dis_stringify_type (m, m_class_get_byval_arg (mh->klass), TRUE);
Target 0: (monodis) stopped.
(lldb) bt
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc)
  * frame #0: 0x0000000100012886 monodis`get_method_core(m=0x000000010180f000, token=100663419, fullsig=1, container=0x0000000000000000) at get.c:1948
    frame #1: 0x00000001000127da monodis`get_method(m=0x000000010180f000, token=100663419, container=0x0000000000000000) at get.c:2031
    frame #2: 0x0000000100018aad monodis`disassemble_cil(m=0x000000010180f000, mh=0x0000000101032bd0, container=0x0000000000000000) at dis-cil.c:156
    frame #3: 0x000000010000abb6 monodis`dis_code(m=0x000000010180f000, token=100663416, rva=15865, container=0x0000000000000000) at main.c:698
    frame #4: 0x000000010000a23a monodis`dis_method_list(klass_name="CommandLineBuilderExtension", m=0x000000010180f000, start=112, end=124, type_container=0x0000000000000000) at main.c:908
    frame #5: 0x00000001000096c9 monodis`dis_type(m=0x000000010180f000, n=27, is_nested=0, forward=0) at main.c:1269
    frame #6: 0x0000000100008619 monodis`dis_types(m=0x000000010180f000, forward=0) at main.c:1495
    frame #7: 0x0000000100006e37 monodis`disassemble_file(file="Microsoft.Build.Tasks.CodeAnalysis.dll") at main.c:1659
    frame #8: 0x000000010000649c monodis`main(argc=2, argv=0x00007fff5fbff9e0) at main.c:2056
 
-> 1948			if (mono_method_signature (mh)->is_inflated)
   1949				container = mono_method_get_generic_container (((MonoMethodInflated *) mh)->declaring);
   1950			esname = get_escaped_name (mh->name);
   1951			sig = dis_stringify_type (m, m_class_get_byval_arg (mh->klass), TRUE);
Target 0: (monodis) stopped.
(lldb) p mh
(MonoMethod *) $0 = 0x00000001010302f0
(lldb) p *mh
(MonoMethod) $1 = {
  flags = 131
  iflags = 0
  token = 100663419
  klass = 0x0000000101030080
  signature = 0x0000000000000000
  name = 0x00000001005f1d36 "AppendSwitchIfNotNull"
  inline_info = 0
  inline_failure = 0
  wrapper_type = 0
  string_ctor = 0


 lldb /s/mono8/mono/dis/monodis Microsoft.CodeAnalysis.Scripting.dll
similar

* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc)
    frame #0: 0x0000000100012886 monodis`get_method_core(m=0x0000000100802a00, token=100663898, fullsig=1, container=0x0000000000000000) at get.c:1948
   1945	
   1946		mh = mono_get_method_checked (m, token, NULL, (MonoGenericContext *) container, error);
   1947		if (mh) {
-> 1948			if (mono_method_signature (mh)->is_inflated)
   1949				container = mono_method_get_generic_container (((MonoMethodInflated *) mh)->declaring);
   1950			esname = get_escaped_name (mh->name);
   1951			sig = dis_stringify_type (m, m_class_get_byval_arg (mh->klass), TRUE);
Target 0: (monodis) stopped.
(lldb) p *mh
(MonoMethod) $0 = {
  flags = 129
  iflags = 0
  token = 100663898
  klass = 0x000000010083eec8
  signature = 0x0000000000000000
  name = 0x00000001005f030a "<.ctor>b__2_0"
  i
```

**Comment by borgdylan** [comment] 2018-05-28 09:35
Monodis segfaults on many modern binaries. Try using ikdasm instead which in my experience works in more cases.

**Comment by migueldeicaza** [comment] 2018-05-30 18:04
Right - the issue is that monodis uses the same APIs that the Mono runtime does, this can mean a number of things:

* The loader as implemented by monodis is not as comprehensive as what the Mono runtime does
* monodis is not doing something the Mono runtime does
* the mono runtime will have a problem loading that code.

The first two are sort of expected, the last one is an indicator of a real problem.  We would need to figure out whether this is one of the first two, or the last one - the last one should be fixed.

**Comment by jaykrell** [comment] 2018-05-30 19:15
https://github.com/mono/mono/pull/8901 gives some indication as to the causes, as it was enough to make it through all those files.
Does monodis actually load dependencies? That seems wrong, if it does.

**Comment by jaykrell** [comment] 2018-10-09 08:14
It no longer crashes on whatever is the current Microsoft.Build.Tasks.CodeAnalysis.dll.
Microsoft.CodeAnalysis.Scripting.dll it still does though.

**Comment by jaykrell** [comment] 2018-10-09 08:20
It looks like it has to do with .netcore and assembly forwardining. i.e. in this case System.Runtime.Loader.

**Comment by marek-safar** [comment] 2018-10-09 23:55
We prefer ikdasm which should be able to handle this

**Closed by marek-safar** 2018-10-09 23:55 UTC
Labels: area-Tools: monodis
