### ISSUE TITLE
POST/PUT request without Content-Length Header crashes the Process and HttpListener

### ISSUE THREAD

**Issue by rayalex** [mono/mono#10435] opened 2018-09-01 10:40 UTC
I'm running a simple ASP.NET WebAPI 2 application on top of OWIN, which is self hosted. I've noticed it's possible to crash the process when sending POST/PUT request without any body (nor `content-length` header) to the web server. If `content-length` is provided (even if the value is `0`), everything works as expected.

## Steps to Reproduce

1. Run the attached example. It will start a HTTP server on port 9000
2. Execute `curl -X POST http://localhost:9000/`
3. Process will crash when run on Mono.

[OwinSelfHost.zip](https://github.com/mono/mono/files/2342286/OwinSelfHost.zip)

This only seems to happen under Mono. Running it with .NET Framework on Windows does not reproduce the issue.

I've tested with previous Mono versions (both 4 and 5) and issue still persists).

I've provided `Dockerfile` for convenience, if it makes testing any easier. Build with `docker build -t osh_test .` and run with `docker run -p 9000:9000 osh_test`. 

### Current Behavior

- Server returns `411 Length Required`
- Process crashes

### Expected Behavior

Should return `411 Length Required` without crashing the process.

## On which platforms did you notice this

[ ] macOS (can't test)
[x] Linux
[ ] Windows (did not test with Mono on Windows)

**Version Used**: `Mono JIT compiler version 5.14.0.177 (tarball Mon Aug  6 09:07:45 UTC 2018)`

## Stacktrace

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <b3d41b23de534128a4f18a6e1312f79c>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.End () [0x0001c] in <e7813d814d4e40949b02ef34297e89ba>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End () [0x00010] in <e7813d814d4e40949b02ef34297e89ba>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End (System.Exception ex) [0x0001e] in <e7813d814d4e40949b02ef34297e89ba>:0 
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestAsync>d__5.MoveNext () [0x001f9] in <e7813d814d4e40949b02ef34297e89ba>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestsAsync>d__0.MoveNext () [0x00202] in <e7813d814d4e40949b02ef34297e89ba>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) <0x7efdbab7c7f0 + 0x0003a> in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) <0x7efdbaafbf80 + 0x0002a> in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x7efdbaaf6d40 + 0x001a2> in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x7efdbaafbf30 + 0x00025> in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x7efdbaafbdb0 + 0x00005> in <2943701620b54f86b436d3ffad010412>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <b3d41b23de534128a4f18a6e1312f79c>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.End () [0x0001c] in <e7813d814d4e40949b02ef34297e89ba>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End () [0x00010] in <e7813d814d4e40949b02ef34297e89ba>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End (System.Exception ex) [0x0001e] in <e7813d814d4e40949b02ef34297e89ba>:0 
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestAsync>d__5.MoveNext () [0x001f9] in <e7813d814d4e40949b02ef34297e89ba>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestsAsync>d__0.MoveNext () [0x00202] in <e7813d814d4e40949b02ef34297e89ba>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) <0x7efdbab7c7f0 + 0x0003a> in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) <0x7efdbaafbf80 + 0x0002a> in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x7efdbaaf6d40 + 0x001a2> in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x7efdbaafbf30 + 0x00025> in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x7efdbaafbdb0 + 0x00005> in <2943701620b54f86b436d3ffad010412>:0 
```

**Comment by omfgicbf** [comment] 2019-02-13 08:55
I am able to reproduce this using Mono 5.18.0.240 on Windows 

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <5fd52b0ea5a441e9a1b8e9a8d20586bc>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.End () [0x0001c] in <535659fbfd7d4672862060b6ea8a4879>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End () [0x00010] in <535659fbfd7d4672862060b6ea8a4879>:0
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.End (System.Exception ex) [0x0001e] in <535659fbfd7d4672862060b6ea8a4879>:0
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener.ProcessRequestAsync (System.Net.HttpListenerContext context) [0x0019c] in <535659fbfd7d4672862060b6ea8a4879>:0
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener.ProcessRequestsAsync () [0x00197] in <535659fbfd7d4672862060b6ea8a4879>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <08dddd7e1b69412492b591625ff22e77>:0
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <08dddd7e1b69412492b591625ff22e77>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <08dddd7e1b69412492b591625ff22e77>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <08dddd7e1b69412492b591625ff22e77>:0
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <08dddd7e1b69412492b591625ff22e77>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <08dddd7e1b69412492b591625ff22e77>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <08dddd7e1b69412492b591625ff22e77>:0
```

Is there a way to work-around this? I can't seem to catch this exception, which is a bit of an issue, as it brings down the process.

**Comment by rayalex** [comment] 2019-02-13 10:15
@omfgicbf I was unable to find a solution within Mono and unfortunately haven't had the time to debug the issue and offer a PR so far.

Possible workaround would be placing a proxy (e.g. HAProxy) in front of the server to sanitize the request and make sure necessary Header is provided.

**Comment by omfgicbf** [comment] 2019-02-14 23:58
@rayalex Thanks, I've done that and it's working for the moment.

I spent some more time trying to catch the exception (or even just detect the condition and throw something else beforehand) but couldn't get anything to work.

I'm probably missing something, but isn't this a big deal? It seems anyone using Mono from at least 5.4 through 5.18, on Windows or Linux, and using OWIN, cannot prevent someone from crashing their process using a (pretty simple) specially crafted request.

FWIW, the endpoint doesn't even need to exist, posting to any URI will cause the issue.

**Comment by rayalex** [comment] 2019-02-15 18:09
@omfgicbf I don't think we're missing anything, in hindsight I should have been more diligent when reporting this 😅 

@marek-safar @baulig I'm not sure if you guys are the right people to tag here, but can we maybe assign a priority to this one considering the implications of the issue?

**Comment by baulig** [comment] 2019-02-15 19:06
Does CoreFx / .NET Core have the same problem?  If it does, then could you please report it there?

Since the code bases are very similar, I think it would make most sense to first get this fixed in CoreFx because then can can just copy their version.

**Comment by omfgicbf** [comment] 2019-02-16 02:51
@baulig I was unable to reproduce in .NET Core, however, it seems that the issue is somehow related to Katana. Perhaps this should be raised over in AspNetKatana? Though they may not pick it up as the issue does not occur when running with .NET Framework.

`OwinHttpListener.ProcessRequestAsync` eats exceptions raised during processing, and calls `End` on the `OwinHttpListenerContext` (which eventually leads to the issue above, as it tries to set the StatusCode on a disposed `HttpListenerResponse`)

I enabled trace in Katana so I could see the exception it was catching and got the following:-

```
Microsoft.Owin.Host.HttpListener.OwinHttpListener Error: 0 : Exception during request processing.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <61fc939e2db84816b8d11371d5b9d4b0>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.SetStatusCode () [0x00037] in <535659fbfd7d4672862060b6ea8a4879>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.PrepareResponse (System.Boolean mayHaveBody) [0x00016] in <535659fbfd7d4672862060b6ea8a4879>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.CompleteResponseAsync () [0x00000] in <535659fbfd7d4672862060b6ea8a4879>:0 
  at Microsoft.Owin.Host.HttpListener.OwinHttpListener+<ProcessRequestAsync>d__30.MoveNext () [0x000e3] in <535659fbfd7d4672862060b6ea8a4879>:0 
    ProcessId=12568
    DateTime=2019-02-16T01:48:10.5947023Z
```

It seems that `OwinHttpListenerResponse` is encountering the same issue of a disposed `HttpListenerResponse`, earlier in the pipeline. Perhaps there is some difference in the Mono implementation of `HttpListenerResponse` or `HttpListenerContext` that causes an early disposal when used by Katana?

**Comment by Tratcher** [comment] 2020-04-24 22:23
Hey folks, I'm the Katana dev and this was just brought to my attention via https://github.com/aspnet/AspNetKatana/issues/350.

I have not reproduced this but the reports from these two issues are pretty consistent:
- The client commits a protocol violation by sending a POST request without Content-Length or Transfer-Encoding.
- HttpListener rejects the request with a 411 Length Required. So far so good, that's what it's supposed to do and it matches Http.Sys' behavior.
- HttpListener.GetContextAsync surfaces an already disposed HttpListenerContext object. This seems to be the root bug, it should have dropped this request from the queue rather than surfacing it to the caller.
- Katana/Microsoft.Owin tries to send a normal response, HttpListenerContext throws an ODE.
- Katana catches the ODE and tries to send a 500 response which promptly throws another ODE and crashes the server.

@baulig do you want to sync up with me and we can try to reproduce this together?

**Comment by powerumc** [comment] 2020-04-28 02:01
I tested it.

HttpListener already closes the Response object, closes the HTTP Client connection, and then sets the value of Response.StatusCode again. If so, an ObjectDisposedException is thrown.

```cs
using System;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace MonoConsoleApp1
{
    internal class Program
    {
        public static async Task Main(string[] args)
        {
            using (var listener = new HttpListener())
            {
                listener.Prefixes.Add("http://localhost:8080/");
                Console.WriteLine("Ready...");
                
                listener.Start();
                while (listener.IsListening)
                {
                    var context = await listener.GetContextAsync();
                    var buffer = Encoding.UTF8.GetBytes("hello world");
                    context.Response.ContentLength64 = buffer.Length;
                    await context.Response.OutputStream.WriteAsync(buffer, 0, buffer.Length);
                }

                listener.Stop();
            }
        }
    }
}
```

And `curl -X POST http://localhost:8080/`

```text
Unhandled Exception:System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.  at System.Net.HttpListenerResponse.set_ContentLength64 (System.Int64 value) [0x00013] in <b44
73693dd3c4d45883c574a53529fbe>:0 
  at MonoConsoleApp1.Program.Main (System.String[] args) [0x000ff] in <60aed05f157f4c0c81f93d9221c9a2ec>:0 
  at MonoConsoleApp1.Program.<Main> (System.String[] args) [0x0000c] in <60aed05f157f4c0c81f93d9221c9a2ec>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed obj
ect.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_ContentLength64 (System.Int64 value) [0x00013] in <b44
73693dd3c4d45883c574a53529fbe>:0 
  at MonoConsoleApp1.Program.Main (System.String[] args) [0x000ff] in <60aed05f157f4c0c81f93d92
21c9a2ec>:0 
  at MonoConsoleApp1.Program.<Main> (System.String[] args) [0x0000c] in <60aed05f157f4c0c81f93d9221c9a2ec>:0
```

![before-mono-httplistener](https://user-images.githubusercontent.com/1943755/80438641-a0af2800-893f-11ea-9869-0e34d58e1192.gif)

**Closed** 2020-04-28 13:37 UTC
Labels: area-BCL: System
