### ISSUE TITLE
XSP4 not starting with 6.8.0.96

### ISSUE THREAD

**Issue by MHBrand61** [mono/mono#18507] opened 2020-01-19 14:45 UTC
I am using mono develop for a webservice. This seems to be broken with 6.8.0.96
XSP4 is not starting with the latest mono on ubuntu 18.04
Trying to start xsp4 results in
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'Mono.WebServer.XSP.Server:<>f__mg$cache1' (3) due to: Could not resolve type with token 0100000b from typeref (expected class 'Mono.Security.Protocol.Tls.PrivateKeySelectionCallback' in assembly 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756') assembly:Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756 type:Mono.Security.Protocol.Tls.PrivateKeySelectionCallback member:(null)
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'Mono.WebServer.XSP.Server:<>f__mg$cache1' (3) due to: Could not resolve type with token 0100000b from typeref (expected class 'Mono.Security.Protocol.Tls.PrivateKeySelectionCallback' in assembly 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756') assembly:Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756 type:Mono.Security.Protocol.Tls.PrivateKeySelectionCallback member:(null)

**Comment by akoeplinger** [comment] 2020-01-20 09:18
Duplicate of https://github.com/mono/mono/issues/18500

**Closed by akoeplinger** 2020-01-20 09:18 UTC

**Comment by simonegli8** [comment] 2025-06-26 13:08
I'm having the same error in Ubuntu 24, and therefore I try to build xsp from 4.7.1 source release, but compilation gives an error
```
/bin/bash: ../libtool: No such file or directory
make[1]: *** [Makefile:479: libfpm_helper_la-fpm_helper.lo] Error 127
make: *** [Makefile:431: all-recursive] Error 1
```
