### ISSUE TITLE
RaspberryPi armhf: GetIPProperties() fails with OverflowException

### ISSUE THREAD

**Issue by xiic** [mono/mono#11589] opened 2018-11-07 08:49 UTC
`GetIPProperties()` fails _sometimes_ (in about 50% of all cases) with an OverflowException.

# Stacktrace
```
System.TypeInitializationException: The type initializer for 'System.Net.NetworkInformation.UnixIPInterfaceProperties' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Text.RegularExpressions.Regex' threw an exception. ---> System.OverflowException: TimeSpan overflowed because the duration is too long.
  at System.TimeSpan.Interval (System.Double value, System.Int32 scale) <0x74a03bb8 + 0x0010c> in <c3c5f4bb011a4af8b925b0d39ee12396>:0
  at System.TimeSpan.FromMilliseconds (System.Double value) <0x74a03cf4 + 0x0001b> in <c3c5f4bb011a4af8b925b0d39ee12396>:0
  at System.Text.RegularExpressions.Regex..cctor () [0x0001c] in <9b672a45b19f4d52b5f28f32c0c91d97>:0
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at System.Net.NetworkInformation.UnixIPInterfaceProperties..cctor () [0x00000] in <9b672a45b19f4d52b5f28f32c0c91d97>:0
   --- End of inner exception stack trace ---
  at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor (System.Net.NetworkInformation.LinuxNetworkInterface iface, System.Collections.Generic.List`1[T] addresses) [0x00000] in <9b672a45b19f4d52b5f28f32c0c91d97>:0
  at System.Net.NetworkInformation.LinuxNetworkInterface.GetIPProperties () [0x00008] in <9b672a45b19f4d52b5f28f32c0c91d97>:0
  at NetmaskTest.Main () [0x00011] in <89d83b92f5474a50a7dc9b30cc07e08a>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Net.NetworkInformation.UnixIPInterfaceProperties' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Text.RegularExpressions.Regex' threw an exception. ---> System.OverflowException: TimeSpan overflowed because the duration is too long.
  at System.TimeSpan.Interval (System.Double value, System.Int32 scale) <0x74a03bb8 + 0x0010c> in <c3c5f4bb011a4af8b925b0d39ee12396>:0
  at System.TimeSpan.FromMilliseconds (System.Double value) <0x74a03cf4 + 0x0001b> in <c3c5f4bb011a4af8b925b0d39ee12396>:0
  at System.Text.RegularExpressions.Regex..cctor () [0x0001c] in <9b672a45b19f4d52b5f28f32c0c91d97>:0
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at System.Net.NetworkInformation.UnixIPInterfaceProperties..cctor () [0x00000] in <9b672a45b19f4d52b5f28f32c0c91d97>:0
   --- End of inner exception stack trace ---
  at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor (System.Net.NetworkInformation.LinuxNetworkInterface iface, System.Collections.Generic.List`1[T] addresses) [0x00000] in <9b672a45b19f4d52b5f28f32c0c91d97>:0
  at System.Net.NetworkInformation.LinuxNetworkInterface.GetIPProperties () [0x00008] in <9b672a45b19f4d52b5f28f32c0c91d97>:0
  at NetmaskTest.Main () [0x00011] in <89d83b92f5474a50a7dc9b30cc07e08a>:0
```

# Example
```
using System;
using System.Net.NetworkInformation;

public class NetmaskTest
{
        static public void Main ()
        {
                foreach (var ni in NetworkInterface.GetAllNetworkInterfaces())
                {
                        ni.GetIPProperties();
                        Console.WriteLine("OK");
                }
        }
}
```

# Platform
Raspberry Pi 3B+ with Raspbian 9 (Stretch)
* `lscpu`: Architecture: armv7l
* `dpkg --print-architecture`: armhf

# Mono
Installation according to https://www.mono-project.com/download/stable/#download-lin-raspbian
```
$ mono --version
Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 12:22:11 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)
```

**Comment by lewurm** [comment] 2018-11-07 09:09
@xiic thanks for your report. It's a duplicate of https://github.com/mono/mono/issues/11095

**Closed by lewurm** 2018-11-07 09:09 UTC

**Comment by xiic** [comment] 2018-11-07 10:17
Thanks for the pointer, the suggested workaround (`apt-get remove mono-llvm-support && dpkg-reconfigure libmono-corlib4.5-cil`) works. Now just waiting for the fix...
