### ISSUE TITLE
Rewrite versions.py as a C# script

### ISSUE THREAD

**Issue by expertmm** [mono/mono#6204] opened 2017-12-08 02:20 UTC
During make (using patch that fixes <https://github.com/mono/mono/issues/6197>), mono is not liking when system's default python is python3 (the `python` executable in path refers to python3 on some distros nowadays)--try checking for python2 (maybe with if file exists $(command -v python2) or checking whether python2 exists in path or something), before using python binary directly which would result in this:
```
make[2]: Entering directory '/home/owner/GitHub/mono/acceptance-tests'
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
  File "versions.py", line 11
    print "Not found"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Not found")?
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/owner/GitHub/mono/acceptance-tests'
make[2]: Entering directory '/home/owner/GitHub/mono'
make[2]: Leaving directory '/home/owner/GitHub/mono'
make[1]: Leaving directory '/home/owner/GitHub/mono'
```

if you need to make the change in shell script manually such as autogen.sh you may want to add something like:
```
this_python=python
this_python2=$(command -v python2)
if [ -f "$this_python2" ]; then
  #if you don't put quotes around $this_python in the line above, blank will return true due to wierd bash behavior
  this_python=$this_python2
fi
```
where this_python is the actual environment variable that could somehow be used later where it is currently assumed to be path's `python`

**Comment by alexanderkyte** [comment] 2017-12-11 18:27
Can we give our references to python and ruby throughout the codebase the same treatment? Figuring out which version of a VM is required to run a script in a couple of years is going to be even harder.

**Comment by migueldeicaza** [comment] 2017-12-11 19:14
Since we have such a tiny dependency on Python (scripts/submodules/versions.py), we should just rewrite this in C# and save ourselves the pain.

It looks like it is just used to process the `mono/acceptance-tests/SUBMODULES.json`

**Comment by akoeplinger** [comment] 2017-12-11 19:27
genmdesc was recently rewritten in Python as well so we can't really get rid of it for the build: https://github.com/mono/mono/pull/6140

**Comment by vargaz** [comment] 2017-12-13 13:11
We should avoid depending on mono to build the runtime.  Will fix the script so it runs on python3.

**Comment by vargaz** [comment] 2017-12-13 13:13
It looks like it was already fixed.

**Comment by migueldeicaza** [comment] 2017-12-13 15:38
We already need a working system Mono to build Mono.

**Comment by expertmm** [comment] 2017-12-13 17:26
please test against the mono provided by `make get-monolite-latest`

**Comment by akoeplinger** [comment] 2017-12-14 02:40
@migueldeicaza we only need a working Mono for the class library build, not the runtime build (where genmdesc is used right now).

Given the original issue was fixed almost two years ago by https://github.com/mono/mono/pull/2864 I'm closing this for now, thanks :)

**Closed by akoeplinger** 2017-12-14 02:40 UTC
Labels: area-Infrastructure

**Comment by expertmm** [comment] 2017-12-22 23:27
Then why did it happen on the git version as mentioned in the original post?

**Comment by akoeplinger** [comment] 2018-01-02 17:10
@expertmm it works for me with today's git master and Python 3.6.3. If you still see a problem please open a new issue and specify python version + git commit.

**Comment by poikilos** [comment] 2018-12-06 15:11
@akoeplinger you have given your version of Python 3 but have not explicitly stated you confirmed it is the default on your system (such as via `python --version`)

**Comment by akoeplinger** [comment] 2018-12-06 15:41
@poikilos it should work with both python 2 and 3.
