### ISSUE TITLE
Can no-longer open URLs with System.Diagnostics.Process.Start()

### ISSUE THREAD

**Issue by mavit** [mono/mono#19836] opened 2020-05-24 13:53 UTC
## Steps to Reproduce

```c#
using System.Diagnostics;

public class ProcessStart
{
    public static void Main(string[] args)
    {
        Process.Start("https://www.mono-project.com/");
    }
}
```

### Current Behavior

Calling `System.Diagnostics.Process.Start()` on a URL throws an exception containing the message `Cannot find the specified file`.

### Expected Behavior

In earlier Mono versions, the URL was passed to `xdg-open` which opened the URL in the user's preferred web browser.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

The issue [is seen](https://bugzilla.redhat.com/show_bug.cgi?id=1839410) on Fedora 32 (which has the following Mono version):

```
Mono JIT compiler version 6.6.0.161 (tarball Wed Feb  5 07:34:41 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

The issue is not present on Fedora 31:

```
Mono JIT compiler version 5.20.1.34 (tarball Mon Oct 14 05:16:35 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

## Stacktrace

```
Unhandled Exception:
System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00129] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at System.Diagnostics.Process.Start () [0x00038] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001e] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at System.Diagnostics.Process.Start (System.String fileName) [0x00006] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at ProcessStart.Main (System.String[] args) [0x00000] in <d39a2c4d79a54779ba47e4b3fcb2e079>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00129] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at System.Diagnostics.Process.Start () [0x00038] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001e] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at System.Diagnostics.Process.Start (System.String fileName) [0x00006] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at ProcessStart.Main (System.String[] args) [0x00000] in <d39a2c4d79a54779ba47e4b3fcb2e079>:0 
```

**Comment by tpokorra** [comment] 2020-05-25 04:53
I can confirm this issue with the latest Mono 6.8 from Xamarin on Fedora 31.
I used a clean Fedora 31 with package `xdg-utils` and text-browser `lynx`, and installed Mono from the Xamarin Repo:

```
Mono JIT compiler version 6.8.0.123 (tarball Mon May 11 19:47:40 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

Same output:

```
Unhandled Exception:
System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00102] in <8a0944092ae944f79161e3ab1237b7dd>:0 
  at System.Diagnostics.Process.Start () [0x00032] in <8a0944092ae944f79161e3ab1237b7dd>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <8a0944092ae944f79161e3ab1237b7dd>:0 
  at System.Diagnostics.Process.Start (System.String fileName) [0x00006] in <8a0944092ae944f79161e3ab1237b7dd>:0 
  at ProcessStart.Main (System.String[] args) [0x00000] in <e6a8edd843924b58a3b39a29f0777fbb>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00102] in <8a0944092ae944f79161e3ab1237b7dd>:0 
  at System.Diagnostics.Process.Start () [0x00032] in <8a0944092ae944f79161e3ab1237b7dd>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <8a0944092ae944f79161e3ab1237b7dd>:0 
  at System.Diagnostics.Process.Start (System.String fileName) [0x00006] in <8a0944092ae944f79161e3ab1237b7dd>:0 
  at ProcessStart.Main (System.String[] args) [0x00000] in <e6a8edd843924b58a3b39a29f0777fbb>:0 
```

**Comment by mavit** [comment] 2020-06-20 18:45
A similar change in behaviour is seen when calling `System.Diagnostics.Process.Start()` on a non-executable file:

```csharp
using System.Diagnostics;

public class ProcessStart
{
    public static void Main(string[] args)
    {
        Process.Start("/etc/passwd");
    }
}
```

Previously this would have caused the file to be opened in the users preferred text editor, but now we see the following error:

```
Unhandled Exception:
System.ComponentModel.Win32Exception (0x80004005): Access denied
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00129] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at System.Diagnostics.Process.Start () [0x00038] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001e] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at System.Diagnostics.Process.Start (System.String fileName) [0x00006] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at ProcessStart.Main (System.String[] args) [0x00000] in <0459da18f0404b3eb7b68c670d5e2c37>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ComponentModel.Win32Exception (0x80004005): Access denied
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00129] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at System.Diagnostics.Process.Start () [0x00038] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001e] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at System.Diagnostics.Process.Start (System.String fileName) [0x00006] in <13e87ee1a85d4b5e8544328288bab252>:0 
  at ProcessStart.Main (System.String[] args) [0x00000] in <0459da18f0404b3eb7b68c670d5e2c37>:0 
```

**Comment by tpokorra** [comment] 2021-01-10 06:26
Since we did not get a reply here, I had another look.
This is a duplicate of https://github.com/mono/mono/issues/17204

**Closed** 2021-02-10 01:01 UTC

**Comment by dreua** [comment] 2021-02-10 08:00
@CoffeeFlux thank you for the fix!

Are there plans on a Bugfix release? Can someone share the fixed versions here once they are out?

@mavit could you give me the commands to compile and run your reproducer?

**Comment by mavit** [comment] 2021-02-10 11:39
> could you give me the commands to compile and run your reproducer?

```bash
mcs example.cs
mono example.exe
```

**Comment by CoffeeFlux** [comment] 2021-02-10 13:00
It's been backported. Getting a build out is purely dependent on the packaging infrastructure.
