### ISSUE TITLE
[netcore] Native crash in System.Runtime.Handles.Tests on macOS

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#17224] opened 2019-10-08 11:04 UTC
## Steps to Reproduce

1. Build mono-netcore on macOS
2. Run System.Runtime.Handles.Tests
3. It crashes

### Current Behavior

```
alexander:~/dev/mono/netcore$ make run-tests-corefx-System.Runtime.Handles.Tests

***************** System.Runtime.Handles.Tests *********************
cd corefx/tests/extracted/System.Runtime.Handles.Tests && \
	MONO_ENV_OPTIONS="--debug" COMPlus_DebugWriteToStdErr=1 /Users/alexander/dev/mono/netcore/./dotnet exec \
		--runtimeconfig System.Runtime.Handles.Tests.runtimeconfig.json --additional-deps System.Runtime.Handles.Tests.deps.json \
		--fx-version "5.0.0-alpha1.19476.2" xunit.console.dll System.Runtime.Handles.Tests.dll \
		-html ../../TestResult-System.Runtime.Handles.Tests.html -xml ../../TestResult-System.Runtime.Handles.Tests-netcore-xunit.xml \
		-notrait category=nonosxtests @../../../../CoreFX.issues.rsp \

Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET Core 5.0.0-alpha1.19476.2)
  Discovering: System.Runtime.Handles.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Handles.Tests (found 13 of 14 test cases)
  Starting:    System.Runtime.Handles.Tests (parallel test collections = on, max threads = 8)
  Finished:    System.Runtime.Handles.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Handles.Tests  Total: 13, Errors: 0, Failed: 0, Skipped: 0, Time: 0.170s

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x107bf56b4 - /Users/alexander/dev/mono/netcore/shared/Microsoft.NETCore.App/5.0.0-alpha1.19476.2/libcoreclr.dylib : dump_native_stacktrace
	0x107bf5611 - /Users/alexander/dev/mono/netcore/shared/Microsoft.NETCore.App/5.0.0-alpha1.19476.2/libcoreclr.dylib : mono_dump_native_crash_info
	0x107af107f - /Users/alexander/dev/mono/netcore/shared/Microsoft.NETCore.App/5.0.0-alpha1.19476.2/libcoreclr.dylib : mono_handle_native_crash
	0x107bde879 - /Users/alexander/dev/mono/netcore/shared/Microsoft.NETCore.App/5.0.0-alpha1.19476.2/libcoreclr.dylib : altstack_handle_and_restore
	0x107dace15 - /Users/alexander/dev/mono/netcore/shared/Microsoft.NETCore.App/5.0.0-alpha1.19476.2/libcoreclr.dylib : mono_w32handle_close
	0x107c64245 - /Users/alexander/dev/mono/netcore/shared/Microsoft.NETCore.App/5.0.0-alpha1.19476.2/libcoreclr.dylib : ves_icall_System_Threading_Events_CloseEvent_internal
	0x10bf292f8 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x70000d735000 from 0x70000d2ac000
Pkilling 0x10e4db5c0 from 0x70000d2ac000
Pkilling 0x70000d532000 from 0x70000d2ac000
Pkilling 0x70000db3b000 from 0x70000d2ac000
Pkilling 0x70000ed56000 from 0x70000d2ac000
Pkilling 0x70000d938000 from 0x70000d2ac000
Could not exec mono-hang-watchdog, expected on path '/usr/local/etc/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x70000d2ac000
error: The type initializer for 'System.Xml.Xsl.Xslt.QilGenerator' threw an exception.
make: *** [run-tests-corefx-System.Runtime.Handles.Tests] Error 4
```

### Expected Behavior

No crash.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**: master

**Comment by akoeplinger** [comment] 2019-10-08 11:26
It looks like https://github.com/mono/mono/pull/17213 causes this to be surfaced as an error, I see earlier builds with the same crash dump but exit code 0.

**Comment by filipnavara** [comment] 2019-10-08 12:54
It's kinda obvious what happens. The test code here:

https://github.com/dotnet/corefx/blob/95e35e10d7c52a7eea38c2ae6402d29e2a01efc6/src/System.Runtime.Handles/tests/SafeWaitHandle.cs#L19-L25

...creates an invalid `SafeWaitHandle` and when the finalizer runs it crashes inside the `ReleaseHandle` code. Admittedly the test is incorrect in the first place and should reset the `SafeWaitHandle` to a safe value.

**Comment by MaximLipnin** [comment] 2020-01-28 11:39
The issue is fixed in https://github.com/dotnet/corefx/pull/41636. I have no repro (https://github.com/dotnet/runtime/commit/6f6c94dbb2259deb083eefb755698cc8e0f0a4ce)

**Closed** 2020-01-28 11:43 UTC
Labels: area-netcore: Runtime
