### ISSUE TITLE
Interpreter crashes with SIGSEGV when running mscorlib tests

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7623] opened 2018-03-15 08:30 UTC
## Steps to Reproduce

1. Clone https://github.com/marek-safar/mono/tree/corefx-string
2. Build mono
3. Run mscorlib tests

## Current Behavior

https://jenkins.mono-project.com/job/test-mono-pull-request-interpreter/3837/parsed_console/log_content.html#WARNING1

## Expected Behavior

No crash

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

### Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment] 2018-03-15 08:30
@lewurm is this known issue/limitation?

**Comment by lewurm** [comment] 2018-03-15 14:34
The issue is a missing null check in the `corert` implementation. This code causes a crash:

```csharp
new String ((sbyte*) null, 0, 1, Encoding.Default);
```
while this doesn't:
```csharp
new String ((sbyte*) null, 0, 1, null);
```

In the latter case the managed code does an explicit null check:
https://github.com/mono/corert/blob/ceff4fb1748c26be30a4100f28f97e46dbe294f2/src/System.Private.CoreLib/src/System/String.cs#L248

when `enc != null` though, we hit this code:
https://github.com/mono/corert/blob/ceff4fb1748c26be30a4100f28f97e46dbe294f2/src/System.Private.CoreLib/src/System/String.cs#L290
which doesn't check `value` for `null`, and calls `memcpy` with it. This causes `memcpy` to access an invalid address and therefore we get a segmentation fault. The previous implementation was explicitly checking for `null` in this case:
https://github.com/marek-safar/mono/commit/784eb16f2620bc19fd2afd5e8445c21977a53415#diff-74e62620847c130335ec496857147b73L873

@marek-safar is okay with adding it back.

Why doesn't it crash with the JIT though? Because implicit null checking. Since the segmentation fault happens in managed code, the crash handler assumes it must be a `NullReferenceException` and thus throws such. We don't have such mechanism in place for the interpreter. Hard crashing isn't nice though, so we should do something similar (although it shouldn't throw a `NullReferenceException` imho, but that is a separate issue).

**Comment by luhenry** [comment] 2018-05-08 18:46
@lewurm @BrzVlad this should be revisited following the discussion on https://github.com/dotnet/corefx/pull/29571. We should probably have an explicit null check for `ldind`, even if it won't protect us against other invalid addresses (like `0x1` for example). In the longer term, we should otherwise firgure out a way to, in the SIGSEGV handler, check if we are currently executing a managed method in the interpreter and act accordingly.

**Comment by lewurm** [comment] 2019-06-03 15:44
This was fixed by https://github.com/mono/mono/pull/8647

**Closed by lewurm** 2019-06-03 15:44 UTC
Labels: area-Runtime: Interpreter
