### ISSUE TITLE
[MacSDK] pkg-config is 32-bit only

### ISSUE THREAD

**Issue by alexischr** [mono/mono#13804] opened 2019-04-02 20:54 UTC
Something has changed in how pkg-config is built, and instead of the expected lipo-ed 32-bit/64-bit Mach-O executable, we only get the 32-bit build.

For example:

* Download the latest 2018-10 package: https://xamjenkinsartifact.azureedge.net/build-package-osx-mono/2018-10/242/15d050a79274d3ad80fb273b38affff000da37e5/MonoFramework-MDK-5.20.1.10.macos10.xamarin.universal.pkg

* Install

* `$ file /Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config`:
    * `/Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config: Mach-O executable i386`

The pkg-config tarball/version hasn't changed so this is possibly because of XCode updates on the bots.

**Comment by akoeplinger** [comment] 2019-04-08 09:53
Fixed by https://github.com/mono/mono/pull/13805

**Comment by akoeplinger** [comment] 2019-04-26 21:14
I just saw the same issue with this mono which was built after the fix:

```
Mono JIT compiler version 6.0.0.184 (2019-02/3a8f93b9a47 Thu Apr 18 09:17:09 EDT 2019)
```

**Comment by alexischr** [comment] 2019-05-06 20:35
I have so far been unable to reproduce. @directhex do you have any insight on this issue or how to debug it? I am still not sure - it may be a bockbuild issue or an issue with pkg-config's build.

**Comment by directhex** [comment] 2019-05-09 14:18
It seems to be doing the right thing, in the build logs?

e.g. 

```
07:23:14  pkg-config 0.27
07:23:14  
07:23:14  pkg-config->start_build:
07:23:14  	pkg-config 0.27 <http://pkg-config.freedesktop.org/releases/pkg-config-0.27.tar.gz> md5: 3a4c9feab14b6719afd8904945d9b4e4)
07:23:14  
07:23:14  pkg-config->do_build:
07:23:14  	Building (arch: darwin-32)
07:23:14  
07:23:14  	@	./configure --prefix="/Library/Frameworks/Mono.framework/Versions/6.0.0" --with-internal-glib --build=i386-apple-darwin13.0.0 --disable-dependency-tracking --cache-file=[1m@[0mexternal/bockbuild/builds/pkg-config-darwin-32.cache ac_cv_func_basename_r=no ac_cv_func_clock_getres=no ac_cv_func_clock_gettime=no ac_cv_func_clock_settime=no ac_cv_func_dirname_r=no ac_cv_func_getentropy=no ac_cv_func_mkostemp=no ac_cv_func_mkostemps=no ac_cv_func_timingsafe_bcmp=no
07:24:03  	@	make -j4
07:24:07  	@	make install DESTDIR=[1m@[0mexternal/bockbuild/scratch/pkg-config-x86.install
07:24:07  
07:24:07  darwin->postprocess:
07:24:07  	stage_textfiles: 0 items
07:24:07  	stage_binaries: 1 items
07:24:08  
07:24:08  pkg-config->do_build:
07:24:08  	Building (arch: darwin-64)
07:24:08  
07:24:08  	@	./configure --prefix="/Library/Frameworks/Mono.framework/Versions/6.0.0" --with-internal-glib --build=x86_64-apple-darwin13.0.0 --disable-dependency-tracking --cache-file=[1m@[0mexternal/bockbuild/builds/pkg-config-darwin-64.cache ac_cv_func_basename_r=no ac_cv_func_clock_getres=no ac_cv_func_clock_gettime=no ac_cv_func_clock_settime=no ac_cv_func_dirname_r=no ac_cv_func_getentropy=no ac_cv_func_mkostemp=no ac_cv_func_mkostemps=no ac_cv_func_timingsafe_bcmp=no
07:24:56  	@	make -j4
07:25:01  	@	make install DESTDIR=[1m@[0mexternal/bockbuild/scratch/pkg-config-x64.install
07:25:01  
07:25:01  darwin->postprocess:
07:25:01  	stage_textfiles: 0 items
07:25:01  	stage_binaries: 1 items
07:25:02  lipo pkg-config
07:25:02  
07:25:02  pkg-config->deploy_package:
07:25:02  	13 files, 2.00MB
```

in 6.0.0.223 https://jenkins.mono-project.com/view/Releases/job/build-package-osx-mono/job/2019-02/199/

**Comment by alexischr** [comment] 2019-05-20 22:13
Yeah it seems to be an intermittent bug, that package is fine and locally I could not reproduce. @akoeplinger do you have a link to a recent broken package?

**Comment by alexischr** [comment] 2019-05-29 16:16
Reopening - present in https://xamjenkinsartifact.azureedge.net/build-package-osx-mono/2019-02/245/a2088cb38118af0e3df01278802b7789bd308886/MonoFramework-MDK-6.0.0.271.macos10.xamarin.universal.pkg

**Comment by jaykrell** [comment] 2019-05-29 16:22
Just guessing, should:
```
--build=x86_64-apple-darwin13.0.0
```

be `--host` or `--target`?

Usually `--host` is what you care about.
`--build` is the current machine and fairly irrelevant, except as a default for the others.
`--target` is for only compilers, i.e. that output code.
`--host` is for non-compilers and compilers.

http://jingfenghanmax.blogspot.com/2010/09/configure-with-host-target-and-build.html

**Comment by alexischr** [comment] 2019-05-30 06:11
@jaykrell I think tha should be fine to test (adding `--target` but not removing `--build` for sanity's sake) - however the issue confusingly does not show up in my attempts at building the package, either on my own workstation or one of our CI machines:

```
file /Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config64
/Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config64: Mach-O executable i386
file ~/mono/external/bockbuild/stage/bin/pkg-config64
/Users/alexischr/mono/external/bockbuild/stage/bin/pkg-config64: Mach-O 64-bit executable x86_64
```
But as you said, it's a default for the others, so I am not sure it will make a difference.

**Comment by jaykrell** [comment] 2019-05-30 06:14
Also, autoconf version maybe a factor? Can we capture/compare generated/copied configure/config.sub and config.log?

Is there a CI or Jenkins lane that built the bad one, with logs?

**Comment by jaykrell** [comment] 2019-05-30 11:05
Wild guess? Old cache file???
```
diff --git a/bockbuild/darwinprofile.py b/bockbuild/darwinprofile.py
index 4363991..051445a 100644
--- a/bockbuild/darwinprofile.py
+++ b/bockbuild/darwinprofile.py
@@ -150,8 +150,8 @@ class DarwinProfile (UnixProfile):
         configure_cache =  '%s/%s-%s.cache' % (self.bockbuild.build_root, package.name, arch)
         package.aux_files.append (configure_cache)

-        package.local_configure_flags.extend(
-            ['--cache-file=%s' % configure_cache])
+        #package.local_configure_flags.extend(
+        #    ['--cache-file=%s' % configure_cache])
```

**Comment by jaykrell** [comment] 2019-06-10 21:46
If adding —host fixes it, consider removing —build then.
Letting —build be detected should be ok.
It shouldn’t affect eventual output, when —host is explicit.
Right?

**Comment by directhex** [comment] 2019-06-12 19:26
Why are we still shipping pkg-config to users?

We're telling people to use `csc` instead of `mcs` so the `-pkg:foo` syntax goes away

MSBuild doesn't support pkg-config references (xbuild did)

And I'm pretty sure VS doesn't support pkg-config resolution any more?

**Comment by alexischr** [comment] 2019-06-17 15:43
@alanmcgovern you were the person who brought this to our attention, could you explain where we depend on it?

**Comment by alexischr** [comment] 2019-06-17 18:11
At this point the speculative fix seems to have worked, as the latest packages have the right architecture. I will leave this open for another week and see if we have relapsed.

**Comment by akoeplinger** [comment] 2019-07-24 22:05
Unfortunately this still happens...

E.g. the Mono package built today in https://xamjenkinsartifact.azureedge.net/build-package-osx-mono/2019-06/118/0cd93e984cb62a0fa86a5671180d3e66dc815fc7/MonoFramework-MDK-6.4.0.134.macos10.xamarin.universal.pkg has:

```
$ file /Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config64
/Library/Frameworks/Mono.framework/Versions/Current/bin/pkg-config64: Mach-O executable i386
```

**Comment by akoeplinger** [comment] 2019-07-24 22:10
Ah, looks like the fix wasn't backported to earlier branches, the backport comments in https://github.com/mono/bockbuild/pull/98#issuecomment-502748195 didn't work and looks like this fell through the cracks.

**Comment by lambdageek** [comment] 2019-07-24 22:13
So looking at:
https://github.com/mono/bockbuild/blob/f04877cd480f25c7fe22268e03bb6fac5d6028c8/bockbuild/darwinprofile.py#L135-L149

Questions:
1.  Is it possible we're in the 'darwin-universal' case and that the compiler somehow settles on 32-bit builds if you give `local_gcc_flags` both arches?
2. Note that for the `darwin-64` case we're passing two arguments in a single string: `package.local_gcc_flags = ['-arch x86_64 -m64']` whereas in `darwin-32` we pass two separate args.  Could that make a difference somehow?

**Comment by akoeplinger** [comment] 2019-07-24 22:24
I backported the PR to 2019-02 and up, let's hope it does really fix the issue :)

@lambdageek regarding your second point, that shouldn't matter since we're concatenating the array elements so the end result is the same.

**Comment by akoeplinger** [comment] 2019-07-31 19:39
I haven't seen this anymore in the latest 2019-06 packages so let's hope it's fixed for good now :)

**Comment by mrward** [comment] 2019-08-15 20:36
There still seems to be a problem with the 2019-06 branch. I built a Xamarin.Mac project with VS Mac using Mono 6.4.0.165 and got a warning about pkg-config64 not being optimised for the Mac.

Installing the latest Mono 6.4 from the 2019-06 branch available today, removed the pkg-config64 file to ensure it was being replaced, and it seems that pkg-config64 is 32-bit.

```
file /Library/Frameworks/Mono.framework/Commands/pkg-config64
/Library/Frameworks/Mono.framework/Commands/pkg-config64: Mach-O executable i386

mono --version
Mono JIT compiler version 6.4.0.169 (2019-06/4a855304725 Wed Aug 14 14:40:14 EDT 2019)
```

**Comment by rolfbjarne** [comment] 2019-08-16 16:39
I can confirm, this still happens with the tip of 2019-06, and customers are running into it to (https://dev.azure.com/devdiv/DevDiv/_workitems/edit/961683).

**Comment by akoeplinger** [comment] 2019-08-30 10:52
I switched pkg-config to be 64bit only with https://github.com/mono/bockbuild/pull/116 which should fix this once and for all.

It's included in these Mono versions:
- 2019-02 / 20aebce - Mono 6.0.0.333
- 2019-06 / 7ef99c0 - Mono 6.4.0.186
- 2019-08 / 23cc371 - Mono 6.6.0.48

**Closed by akoeplinger** 2019-08-30 10:52 UTC
Labels: area-Packaging
