### ISSUE TITLE
 Getting message body from HTTP 409 Conflict chunked response fails

### ISSUE THREAD

**Issue by jpgustaf** [mono/mono#10461] opened 2018-09-04 09:19 UTC
## Steps to Reproduce

1. Try to read message body  (using HttpWebRequest.GetResponse() and StreamReader) from 409 Conflict -response when Transfer-encoding chunked is enabled (for example from http://www.ekkuli.net/conflict_call.php)

Code example below:
```
String webAddr = "http://www.ekkuli.net/conflict_call.php";
var httpWebRequest = (HttpWebRequest)WebRequest.Create(webAddr);
httpWebRequest.ContentType = "application/json; charset=utf-8";
httpWebRequest.Method = "POST";
httpWebRequest.ServicePoint.Expect100Continue = false;
httpWebRequest.Accept = "application/json";
httpWebRequest.KeepAlive = true;

try {
    using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream())) {
        String myJson = "{ \"method\" : \"just testing\" }";
        streamWriter.Write(myJson);
        streamWriter.Flush();
     }

     var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();

     using (var streamReader = new StreamReader(httpResponse.GetResponseStream())) {
         var responseText = streamReader.ReadToEnd(); 
      }
}  catch (WebException ex) { // Catch 409 Conflict response
        // Try to get message body from 409 Response
        var s = ex.Response.GetResponseStream();
        var sr = new System.IO.StreamReader(s);
        var content = sr.ReadToEnd(); // <----This throws "Error getting response stream (ReadAsync): ReceiveFailure Value cannot be null" exception
}

```
### Current Behavior
When trying to read response with StreamReader `var content = sr.ReadToEnd(); ` it throws "Error getting response stream (ReadAsync): ReceiveFailure Value cannot be null" exception.

'If Transfer-encoding: Chunked' and content-length header is returned instead, everything works fine.

### Expected Behavior
StreamReader should be able to read message body from 409 Conflict -response even when 'Transfer-encoding: Chunked' is enabled

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit) (for Visual Studio)
.NET Core Runtime Version: 2.1.2 / SDK Version: 2.1.302
Xamarin.iOS:  11.14.0.13

**Comment by Obvious1992** [comment] 2018-09-05 11:06
The cause of this error should be the same as for the following issue: https://github.com/mono/mono/issues/9511#issuecomment-418661100

**Comment by marek-safar** [comment] 2018-09-06 11:39
@baulig please have a look

**Comment by baulig** [comment] 2018-09-12 18:28
This is working perfectly fine with latest master.

I found an issue with reading the error response, though: https://github.com/mono/mono/pull/10574.

**Comment by baulig** [comment] 2018-09-12 18:31
Tested with:

- master: `5.19.0 (master/d7337904202 Tue Sep 11 17:13:12 CEST 2018)`
- `5.16.0.119 (2018-06/0955dd23071 Wed Aug 22 07:57:34 EDT 2018)`
- `5.18.0.36 (2018-08/faac90015cd Wed Aug 22 07:22:48 EDT 2018)`

both with your test case and my new test that I added to the web-tests: https://github.com/xamarin/web-tests/commit/e8d610c9ba3cff725e5802f64045459a52e5b3e6.

**Comment by matheussouza97** [comment] 2018-09-13 15:09
Hello, In a Console Application the error has been fixed. But it's still happening on Xamarin.iOS

**Mono 5.19.0.364 (master/c2a94b3bab1) (64-bit)**

**Console Application**
![screenshot at sep 13 11-57-16](https://user-images.githubusercontent.com/14929125/45497236-aac1ea00-b74d-11e8-8b72-d73409eecc20.png)

**Xamarin.iOS**
![screenshot at sep 13 12-06-09](https://user-images.githubusercontent.com/14929125/45497237-aac1ea00-b74d-11e8-8356-8131b5b51563.png)


Notice that it's the same code.

**Comment by baulig** [comment] 2018-09-14 12:32
Just spent some time testing this with Xamarin.iOS and can confirm that it will be fixed with 2018-08 (you will need to manually compile `xamarin-macios/mono-2018-08` because there is no package available yet).

**Comment by baulig** [comment] 2018-09-14 12:38
@matheussouza97 It is not "the same code" because Xamarin.iOS is compiled with a specific Mono release branch which only receives critical bug fixes.  At the moment, `xamarin-macios/master` is still tracking 2018-04, so you are essentially looking into the past.

It is currently being updated to 2018-08, but there are not packages yet.

**Comment by matheussouza97** [comment] 2018-09-14 12:48
Is there any forecast for these packages to be released?

**Comment by marek-safar** [comment] 2018-09-14 13:26
The preview of Xamarin.iOS with 2018-08 Mono version should be out in few months (this year)

**Comment by matheussouza97** [comment] 2018-09-14 13:42
Ok, Thanks for helping.

**Closed** 2018-09-14 14:15 UTC
Labels: area-BCL: System
