### ISSUE TITLE
"Missing thread BusyHelper" in profiler test suite

### ISSUE THREAD

**Issue by kumpera** [mono/mono#7050] opened 2018-02-14 21:33 UTC
Found during CI.

Looks like this:

```

MONO_PATH=/mnt/jenkins/workspace/test-mono-pull-request-i386/mcs/class/lib/net_4_x perl ./ptestrunner.pl ../..
Checking test-alloc.exe with report,legacy,calls,alloc ...
Checking test-busy.exe with report,legacy,calls,alloc ...
Checking test-busy.exe with report,legacy,sample ...
Error: Missing thread BusyHelper.
Total errors: 1
```

**Comment by kumpera** [comment] 2018-02-14 21:34
Found on https://github.com/mono/mono/pull/7038

amd64-fullaot -> https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-fullaot/7931/

**Comment by kumpera** [comment] 2018-02-14 22:38
Ugg, I posted the wrong link and now that the Job was retried I no idea how to recover it. Sorry.

**Comment by kumpera** [comment] 2018-02-14 22:43
Found it https://jenkins.mono-project.com/view/Pull%20requests/job/test-mono-pull-request-i386/11469/

**Comment by alexrp** [comment] 2018-02-18 11:04
Can't seem to reproduce locally and it seems exceedingly rare on Jenkins. My best guess would be some kind of race condition in the runtime causing the thread name event to not be delivered as expected, as the profiler itself doesn't treat those events any differently from others.

**Comment by alexrp** [comment] 2018-02-22 06:10
Another instance: https://jenkins.mono-project.com/job/test-mono-pull-request-armel/11020/parsed_console/log_content.html#WARNING1

**Comment by kumpera** [comment] 2018-02-22 18:29
Found in #7195

Linux i386: https://jenkins.mono-project.com/job/test-mono-pull-request-i386/11700

**Comment by kumpera** [comment] 2018-02-22 18:33
Found in #7195 

Linux armhf: https://jenkins.mono-project.com/job/test-mono-pull-request-armhf/11120

**Comment by alexrp** [comment] 2018-02-22 23:38
One interesting thing about this test case is that it sets the name of the `BusyHelper` thread from the main thread, as opposed to doing it from the newly started thread. So there are two things that *could* be happening:

1. The thread ID passed to the `thread_name` callback is, for whatever reason, not yet initialized properly, so `mprof-report` can't associate the thread name event with the thread.
2. The log buffer of the main thread is not being flushed properly on shutdown, so the event doesn't get emitted in the log file at all.

Will need to investigate more.

**Comment by alexrp** [comment] 2018-03-10 11:20
I haven't seen this on CI for the past two weeks and I'm not able to reproduce it either. I'll close this for now, let's reopen if it appears again.

**Closed by alexrp** 2018-03-10 11:20 UTC
Labels: area-Profiler, flaky bug
