### ISSUE TITLE
Win32Exception on System.Diagnostics.Process.Start() in Mono 6.6.0.113

### ISSUE THREAD

**Issue by erik4711** [mono/mono#17204] opened 2019-10-07 12:49 UTC
## Steps to Reproduce

1. Build a .NET Framework project that does
`System.Diagnostics.Process.Start(someFileOrFolderPath)`
2. Run the application in Linux using Mono 6.6.0.113

### Current Behavior
When attempting to open a folder:

> System.ComponentModel.Win32Exception : Cannot find the specified file

```
Unhandled Exception:
System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00102] in <b5b0f745c94249ea83fff435264d7c59>:0 
  at System.Diagnostics.Process.Start () [0x00032] in <b5b0f745c94249ea83fff435264d7c59>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <b5b0f745c94249ea83fff435264d7c59>:0 
  at System.Diagnostics.Process.Start (System.String fileName) [0x00006] in <b5b0f745c94249ea83fff435264d7c59>:0 
  at ConsoleApp1.Program.Main (System.String[] args) [0x0001c] in <47b51f4d614149f3ab22c83af5242dd6>:0 
```

When attemtping to open a file (for example a text file or image):

> System.ComponentModel.Win32Exception : Access denied
```
Unhandled Exception:
System.ComponentModel.Win32Exception (0x80004005): Access denied
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00102] in <b5b0f745c94249ea83fff435264d7c59>:0 
  at System.Diagnostics.Process.Start () [0x00032] in <b5b0f745c94249ea83fff435264d7c59>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <b5b0f745c94249ea83fff435264d7c59>:0 
  at System.Diagnostics.Process.Start (System.String fileName) [0x00006] in <b5b0f745c94249ea83fff435264d7c59>:0 
  at ConsoleApp1.Program.Main (System.String[] args) [0x0001c] in <af87dece210d42ccab40381983d94652>:0 
```

### Expected Behavior

A folder should be opened in the default file manager (like Thunar) when opening a folder with:
`System.Diagnostics.Process.Start(directoryPath)`
Files should be opened in their default editors or viewers when attempting to open a file with:
`System.Diagnostics.Process.Start(filePath)`

System.Diagnostics.Process.Start() works as expected (i.e. the file or folder is opened) in Linux when using Mono 4.6.2 or 5.18.0.240, but throws a Win32Exception when using Mono 6.6.0.113.

## On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 6.6.0.113 (tarball Sun Oct  6 10:42:20 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by erik4711** [comment] 2019-10-08 13:39
Is this Win32Exception somehow related to the `MONO_FEATURE_PROCESS_START` setting? If so, how can this setting be controlled so that Process.Start can be used also in the latest build of Mono?

**Comment by HebaruSan** [comment] 2020-01-07 16:22
I'm seeing this as well. Is it related to dotnet/corefx#10361 ? The relationship between Mono and corefx isn't very clear, maybe Mono is shipping old code from when this was broken in corefx?

**Comment by mikkeljohnsen** [comment] 2020-03-09 14:38
When will this be fixed ?

I has been broken of ages now.

**Comment by erik4711** [comment] 2020-03-09 15:11
Why has this issue labeled as a "proposal" rather than a "bug"?

**Comment by mikkeljohnsen** [comment] 2020-03-09 19:05
It is definitely a bug, it is also broken on macOS: https://github.com/mono/mono/issues/16320

**Comment by mikkeljohnsen** [comment] 2020-03-14 20:08
Could we get this changed from Proposal to Regression ?

**Comment by mikkeljohnsen** [comment] 2020-05-18 10:06
Is mono completely abandoning desktop and is only Xamarin.Forms now.

How can this bug not have any priority ?

It breaks all possibilities for opening and starting external files/apps.

**Comment by cameronwhite** [comment] 2020-07-27 12:03
I'm not sure why this is tagged as a proposal? This is a regression that users will need to work around (for example, Pinta will need to ship a workaround for its next release: https://bugs.launchpad.net/pinta/+bug/1888883)

**Comment by erik4711** [comment] 2020-07-27 18:06
> This is a regression that users will need to work around

@cameronwhite Why should we work around the bug? Is there a reason why we shouldn't expect it to get fixed in Mono?

Also, to my knowledge there is no alternative to System.Diagnostics.Process.Start in Mono. So what's the workaround?

**Comment by cameronwhite** [comment] 2020-07-27 18:34
> @cameronwhite Is there a reason why we shouldn't expect it to get fixed in Mono?
> 
> Also, what's the recommended workaround?

Perhaps my wording was confusing, I agree that this should be fixed in Mono (although that is up to the Mono development team). I was just mentioning that this seems to have been tagged incorrectly as a proposal, while it's actually a regression that forces users to implement workarounds in order to avoid encountering this error.

**Comment by erik4711** [comment] 2020-09-23 12:24
NetworkMiner 2.6 now includes a workaround for this issue. See the helper function below, which replaces Process.Start with one of the native GUI applications for opening a file or path in Mono.

See the file `SharedUtils/SystemHelper.cs` in [NetworkMiner's source code](https://www.netresec.com/?page=NetworkMinerSourceCode) for the full implementation.

```cs
public static void ProcessStart(string path) {
    if (IsRunningOnMono()) {
        if (path.Contains(' ') && path[0] != '\'' && path[0]!='\"') {
            path = "\"" + path + "\"";
        }

        foreach (string app in new[] { "xdg-open", "gnome-open", "kfmclient", "open", "explorer.exe" }) {
            System.Diagnostics.ProcessStartInfo psi = new System.Diagnostics.ProcessStartInfo(app, path);
            psi.ErrorDialog = false;
            try {
                Logger.Log("Attempting to open " + path + " with " + app, Logger.EventLogEntryType.Information);
                System.Diagnostics.Process.Start(psi);
            }
            catch (System.ComponentModel.Win32Exception) {
                continue;
            }
            break;
        }
    }
    else {
        if (System.IO.File.Exists(path))
            System.Diagnostics.Process.Start(path);
        else if (System.IO.Directory.Exists(path)) {
            if (path.Contains(' ') && path[0] != '\"')
                path = "\"" + path + "\"";

            System.Diagnostics.Process.Start("explorer.exe", path);
        }
        else
            System.Diagnostics.Process.Start(path);
    }
}
```

**Comment by tpokorra** [comment] 2021-01-10 06:25
> 10361

see also https://github.com/dotnet/runtime/issues/17938

**Comment by rhertzog** [comment] 2021-02-04 13:23
@CoffeeFlux Can you look into this?

I'm just doing his because @akoeplinger asked to tag you in the report in https://github.com/mono/mono/commit/5d088cf0de7f3e50e3547dba361af4401e938dd4#r44599921 (since you introduced the regression in the first place)

It would be nice to see this bug fixed.

**Comment by CoffeeFlux** [comment] 2021-02-04 13:42
Yeah sorry, I meant to get to this a while ago but it fell off my radar. I'll fix it and backport.

**Closed** 2021-02-10 01:01 UTC
Labels: proposal
