### ISSUE TITLE
Can't cross-compile 5.16.0.179: libmono_system_native built on the wrong platform

### ISSUE THREAD

**Issue by mikaelj** [mono/mono#11744] opened 2018-11-20 09:35 UTC
## Steps to Reproduce

* Build host: x86_64
* Target: Cortex A9 (arm-gnueabi)

0. Patch configure.ac to remove patrs that fails because of similar problems as https://github.com/mono/mono/issues/11588

1. Change latest buildroot to use mono 5.16.0.179
2. ./configure

        /configure --target=arm-buildroot-linux-gnueabi --host=arm-buildroot-linux-gnueabi
        --build=x86_64-pc-linux-gnu --prefix=/usr --exec-prefix=/usr --sysconfdir=/etc
        --localstatedir=/var --program-prefix="" --disable-gtk-doc --disable-gtk-doc-html --disable-doc
        --disable-docs --disable-documentation --with-xmlto=no --with-fop=no
        --disable-dependency-tracking --enable-ipv6 --disable-nls --disable-static --enable-shared
        --with-mcs-docs=no --with-ikvm-native=no
        --enable-minimal=profiler,aot,logging,attach,full_messages,reflection_emit_save,simd
        --disable-mcs-build --enable-static --disable-btls --with-sigaltstack=yes --enable-small-config=yes

3. make

### Current Behavior

Error:

    Making all in metadata
      CCLD     libmono-system-native.la
      CC       libmonoruntime_config_la-mono-config-dirs.lo
      CC       libmonoruntime_la-console-unix.lo
      CC       libmonoruntime_la-w32process-unix-bsd.lo
      CC       libmonoruntime_la-w32process-unix.lo
      CC       libmonoruntime_la-w32process-unix-osx.lo
      CC       libmonoruntime_la-w32mutex-unix.lo
      CC       libmonoruntime_la-w32semaphore-unix.lo
      CC       libmonoruntime_la-w32event-unix.lo
    In file included from w32process-unix-bsd.c:6:0:
    w32process-unix-internals.h:55:1: warning: ‘mono_w32process_module_equals’ defined but not used [-Wunused-function]
     mono_w32process_module_equals (gconstpointer a, gconstpointer b)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    w32process-unix-internals.h:44:1: warning: ‘mono_w32process_module_free’ defined but not used [-Wunused-function]
     mono_w32process_module_free (MonoW32ProcessModule *module)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from w32process-unix-osx.c:6:0:
    w32process-unix-internals.h:55:1: warning: ‘mono_w32process_module_equals’ defined but not used [-Wunused-function]
     mono_w32process_module_equals (gconstpointer a, gconstpointer b)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    w32process-unix-internals.h:44:1: warning: ‘mono_w32process_module_free’ defined but not used [-Wunused-function]
     mono_w32process_module_free (MonoW32ProcessModule *module)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      CC       libmonoruntime_la-w32process-unix-haiku.lo
      CC       libmonoruntime_la-w32socket-unix.lo
      CC       libmonoruntime_la-w32process-unix-default.lo
    ../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_errno.o: file not recognized: File format not recognized
    collect2: error: ld returned 1 exit status
    Makefile:1356: recipe for target 'libmono-system-native.la' failed
    make[5]: *** [libmono-system-native.la] Error 1

### Expected Behavior

Mono building. Works for 5.14.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**: 5.16.0.179

**Comment by ajlennon** [comment] 2019-01-26 11:58
Hi all,

I'm seeing the same thing with 5.18.x and 5.16.x as I try to build meta-mono. Has anybody got any pointers on what's gone wrong? Thanks.

e.g. http://jenkins.dynamicdevices.co.uk:8080/job/meta-mono/56/console

Cheers,

Alex

**Comment by lewurm** [comment] 2019-01-30 12:03
@alexischr is this a duplicate of https://github.com/mono/mono/issues/9951 ?

**Comment by ShonkyCH** [comment] 2019-02-01 11:20
> @alexischr is this a duplicate of #9951 ?

They may be related, but fixing #9951 's specific issue only got a bit further. It then hit this issue.

**Comment by alexischr** [comment] 2019-02-05 12:55
This seems to be true for other cross-compilation configurations. I am investigating. /cc @marek-safar (this is affecting Xamarin.Android 2018-10 integration)

**Comment by ShonkyCH** [comment] 2019-03-06 08:19
Pretty simple problem here it looks like. I'm not sure how to submit a pull request since the problem files don't exist in the repo (and shouldn't)

Basically in all the tarballs since 5.16.0.179 at least all the way to the latest current 5.18.0.268 there are some x86-64 object files included that shouldn't be. They're not in the repo, so I'm guessing that the release process is not correctly removing them from the tree before archiving everything up. Perhaps a make clean or similar is not working.

```
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networking.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_io.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_networking.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_io.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_maphardwaretype.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_memory.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_random.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_tcpstate.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_errno.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_networkstatistics.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_maphardwaretype.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_memory.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_random.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_tcpstate.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_errno.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networkstatistics.o
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_random.lo
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_maphardwaretype.lo
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_memory.lo
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_io.lo
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_tcpstate.lo
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networking.lo
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_errno.lo
./mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networkstatistics.lo
```

Delete these and they should be rebuilt with the correct compiler. Seems to work ok, simply forcing a recompile in Yocto this way.

**Comment by lewurm** [comment] 2019-03-06 09:33
I think this issue was fixed by https://github.com/mono/mono/pull/11509 (thus duplicate of https://github.com/mono/mono/issues/11501 )

**Closed by lewurm** 2019-03-06 09:33 UTC
Labels: area-Build

**Comment by mikaelj** [comment] 2019-03-08 09:19
@lewurm Great news! 

Will there be a 5.16 or a 5.18 release with fix?

**Comment by ajlennon** [comment] 2019-03-08 10:19
Great news guys! I'll get some builds spun up on my Jenkins box to test out for meta-mono

**Comment by lewurm** [comment] 2019-03-11 19:02
@mikaelj it's included starting with 5.18

**Comment by mikaelj** [comment] 2019-03-13 12:12
@lewurm According to mono-project.com, the latest package to downolad is the (broken) 5.18.0.268.

**Comment by lewurm** [comment] 2019-03-13 12:27
The fix is included in >= 5.18.0.271

@akoeplinger @directhex any idea why there aren't newer tarballs available (for 2018-08)?

**Comment by directhex** [comment] 2019-03-13 16:01
@lewurm only 5.20 and 6.1 are on an automatic-build cycle for tarballs, currently. So the answer is "because nobody asked Jo"

**Comment by directhex** [comment] 2019-03-15 14:51
Shipping a 5.18 with the fix right now.

**Comment by directhex** [comment] 2019-03-15 15:27
https://download.mono-project.com/sources/mono/mono-5.18.1.0.tar.bz2 includes this fix.

**Comment by angeloc** [comment] 2019-04-23 10:16
This bug is really not closed, I'm encoutering the error with the latest release:

```
ls build/mono-5.20.1.19//external/corefx/src/Native/Unix/System.Native/.libs/
libmono_native_la-pal_errno.o            libmono_native_la-pal_networking.o
libmono_native_la-pal_io.o               libmono_native_la-pal_networkstatistics.o
libmono_native_la-pal_maphardwaretype.o  libmono_native_la-pal_random.o
libmono_native_la-pal_memory.o           libmono_native_la-pal_tcpstate.o
```

**Comment by mikaelj** [comment] 2019-04-23 10:56
My solution for Buildroot, excerpt from mono.mk:

    # fix broken tarballs with old cruft, which is not cleaned by makefiles. (e.g. 5.20.1.19)
    define MONO_REMOVE_BAD_OBJECT_FILES
    	rm -rf `find $(@D)/external -path '*\.libs'`
    	rm -rf `find $(@D)/external -path '*\.deps'`
    	rm -f `find $(@D)/external -path '*\.o'`
    	rm -f `find $(@D)/external -path '*\.so'`
    	rm -f `find $(@D)/external -path '*\.lo'`
    	rm -f `find $(@D)/external -path '*\.Plo'`
    	rm -f `find $(@D)/external -name '\.dirstamp'`
    endef
    
    MONO_POST_EXTRACT_HOOKS += MONO_REMOVE_BAD_OBJECT_FILES

**Comment by cmcqueen** [comment] 2019-07-25 07:56
I'm trying the following in `mono_5.18.%.bbappend` file to try to fix this issue:

    # The source package erroneously contains some build output files from a
    # build for x86. These need to be deleted.
    
    remove_build_output_files() {
        find ${S} \( -name "*.o" -o -name "*.lo" \) -exec rm -f {} \;
    }
    
    python do_unpack_append() {
        bb.build.exec_func('remove_build_output_files', d)
    }
