### ISSUE TITLE
[Mono.Debugger.Soft] Connections are not properly closed

### ISSUE THREAD

**Issue by jbevain** [mono/mono#7377] opened 2018-03-02 00:06 UTC
For a Mono process with the soft debugger on, running on port 4567:

```csharp
static void Main(string[] args)
{
	var vm = VirtualMachineManager.Connect(new IPEndPoint(IPAddress.Loopback, 4567));
	vm.Detach();

	vm = VirtualMachineManager.Connect(new IPEndPoint(IPAddress.Loopback, 4567));
	vm.Detach();

	Console.ReadLine();
}
```

We're seeing two threads that are still running and waiting:

![threads](https://user-images.githubusercontent.com/79284/36876357-751d2262-1d69-11e8-96b8-96e6277bc9e6.png)

Both threads are waiting on `Receive` with this stacktrace:

```
Not Flagged		21928	6	Worker Thread	SDB Receiver

System.dll!System.Net.Sockets.Socket.Receive
[Managed to Native Transition]	 
System.dll!System.Net.Sockets.Socket.Receive(byte[] buffer, int offset, int size, System.Net.Sockets.SocketFlags socketFlags)	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.TcpConnection.TransportReceive(byte[] buf, int buf_offset, int len)	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.Receive(byte[] buf, int buf_offset, int len)	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.ReadPacket()	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.ReceivePacket()	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.receiver_thread_main()	 
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	 
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	 
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	 
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	 
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	 
```

The way I look at it in `VirtualMachine.Detach`

```csharp
public void Detach () {
	conn.VM_Dispose ();
	conn.Close ();
	notify_vm_event (EventType.VMDisconnect, SuspendPolicy.None, 0, 0, null, 0);
}
```

VM_Dispose tells the debuggee that we're disposing, and then `Connection.Close` sets the `closed` flag to true. Nothing interrupts the `receiver_thread_main` loop which is waiting.

We've fixed it by switching the calls:

```csharp
conn.Close ()
conn.VM_Dispose()
```

This way we're setting the closed flag to true, sending and reading the reply to `VM_Dispose`, and exiting the `receiver_thread_main`.

@vargaz, what do you think?

**Comment by vargaz** [comment] 2018-03-02 04:31
Looks good, please send a PR.

**Comment by akoeplinger** [comment] 2018-03-22 11:02
Reopening since the PR was reverted.

**Comment by vargaz** [comment] 2018-03-22 11:06
I think we need another approach to break the read loop in the connection thread.

**Comment by sailro** [comment] 2018-03-23 22:02
@vargaz do you have more information to share about those random crashes allegedly caused by the previous update?

**Comment by vargaz** [comment] 2018-03-23 23:16
It is definitely caused by this patch. It can be reproduced by running make check in mcs/class/Mono.Debugger.Soft on osx. The tests will not fail, because the crash happens during shutdown, but you can see the native stack traces etc.
If I have to guess, sending the VM_Disconnect message after closing the connection somehow confuses the debugger agent code.

**Comment by vargaz** [comment] 2018-03-23 23:16
Its possible that there were recent changes in mono which caused this to surface, so older runtimes would work fine.

**Comment by vargaz** [comment] 2018-03-25 17:21
It looks like an interaction with 540ef385faa230bc226c7a83bfabd0730520911e. The connection is broken, we hit this code:

	if (!attach_failed && command_set == CMD_SET_VM && command == CMD_VM_DISPOSE && !(vm_death_event_sent || mono_runtime_is_shutting_down ())) {
		DEBUG_PRINTF (2, "[dbg] Detached - restarting clean debugger thread.\n");
		start_debugger_thread ();
	}

so we recursively create new debugger threads which race with the runtime shutdown, leading to all kinds of assertions/crashes.

**Comment by marek-safar** [comment] 2018-04-18 01:14
@vargaz what's the resolution on this issue?

**Comment by vargaz** [comment] 2018-04-18 01:17
Its still open since the proposed fix had to be reverted.

**Closed** 2019-06-06 14:12 UTC
Labels: area-Debugger

**Comment by srxqds** [comment] 2019-09-25 03:36
> For a Mono process with the soft debugger on, running on port 4567:
> 
> ```cs
> static void Main(string[] args)
> {
> 	var vm = VirtualMachineManager.Connect(new IPEndPoint(IPAddress.Loopback, 4567));
> 	vm.Detach();
> 
> 	vm = VirtualMachineManager.Connect(new IPEndPoint(IPAddress.Loopback, 4567));
> 	vm.Detach();
> 
> 	Console.ReadLine();
> }
> ```
> 
> We're seeing two threads that are still running and waiting:
> 
> ![threads](https://user-images.githubusercontent.com/79284/36876357-751d2262-1d69-11e8-96b8-96e6277bc9e6.png)
> 
> Both threads are waiting on `Receive` with this stacktrace:
> 
> ```
> Not Flagged		21928	6	Worker Thread	SDB Receiver
> 
> System.dll!System.Net.Sockets.Socket.Receive
> [Managed to Native Transition]	 
> System.dll!System.Net.Sockets.Socket.Receive(byte[] buffer, int offset, int size, System.Net.Sockets.SocketFlags socketFlags)	 
> Mono.Debugger.Soft.dll!Mono.Debugger.Soft.TcpConnection.TransportReceive(byte[] buf, int buf_offset, int len)	 
> Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.Receive(byte[] buf, int buf_offset, int len)	 
> Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.ReadPacket()	 
> Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.ReceivePacket()	 
> Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.receiver_thread_main()	 
> mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	 
> mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	 
> mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	 
> mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	 
> mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	 
> ```
> 
> The way I look at it in `VirtualMachine.Detach`
> 
> ```cs
> public void Detach () {
> 	conn.VM_Dispose ();
> 	conn.Close ();
> 	notify_vm_event (EventType.VMDisconnect, SuspendPolicy.None, 0, 0, null, 0);
> }
> ```
> 
> VM_Dispose tells the debuggee that we're disposing, and then `Connection.Close` sets the `closed` flag to true. Nothing interrupts the `receiver_thread_main` loop which is waiting.
> 
> We've fixed it by switching the calls:
> 
> ```cs
> conn.Close ()
> conn.VM_Dispose()
> ```
> 
> This way we're setting the closed flag to true, sending and reading the reply to `VM_Dispose`, and exiting the `receiver_thread_main`.
> 
> @vargaz, what do you think?

hi, how can you debugger mono with visual studio on windows?
can you help me?

**Comment by thaystg** [comment] 2019-09-25 12:52
Hi, @srxqds , why do you want to do this?

**Comment by srxqds** [comment] 2019-09-26 02:55
> Hi, @srxqds , why do you want to do this?

I want make vs debugger we embeded mono. But I don't know is there already a vs debugger asix plugin.

**Comment by joj** [comment] 2019-09-26 15:49
@srxqds depending on embedded to what, the original developer might have included debugger support. If this is something you're developing, we do have this: https://github.com/xamarin/vs-mono-debugger-sample as a sample on how to integrate debugger support into your project system. The sample was developed by us and originally use by some of our teams, but it might be slightly outdated now.
