### ISSUE TITLE
libmonobdwgc-2.mono_class_vtable_full exception causing Android Unity game crash

### ISSUE THREAD

**Issue by roointan** [mono/mono#12983] opened 2019-02-13 12:12 UTC
I'm a developer of a mobile game, and we have Crashlytics in our game.
For the latest release for Android, we are having crash reports.
Any advice on how to find the root cause, and fix the problem is appreciated.

## Steps to Reproduce
I don't still know how to reproduce this exception, because we are just receiving exception logs in Crashlytics.

This error happens on a wide range of Anroid devices with different OS versions and device brands.

### Current Behavior
we have game crash logs on players devices.

### Expected Behavior
no crash!

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

[X] Android!   (Unity game)

**Version Used**:
I don't know which version of mono Unity is using, but we are using Unity 2017.4.1f1

## Stacktrace

```
Caused by java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000054
Build fingerprint: 'samsung/j7veltedx/j7velte:8.1.0/M1AJQ/J701FXXU6BRL1:user/release-keys'
Revision: '3'
pid: 10762, tid: 11403, name: UnityMain  >>> com.tod.xameen <<<
r0 00000000  r1 00000000  r2 00000001  r3 00000000
r4 d2145c4c  r5 00000001  r6 12f94a00  r7 12c80138
r8 00000000  r9 e674d600  sl 130bd128  fp d07ed36c
ip cfb4fbc4  sp d07ed350  lr cf9cf30c  pc cf9cf354  cpsr 0000004d

   at libmonobdwgc-2.mono_class_vtable_full(mono_class_vtable_full:180)
   at libmonobdwgc-2.mono_array_new_checked(mono_array_new_checked:132)
   at libmonobdwgc-2.mono_array_new(mono_array_new:40)
   at libunity.00520150(Unknown Source)
```

**Comment by lambdageek** [comment] 2019-02-26 23:44
@roointan Thanks for the bug report!.  As I understand it, Unity 2017.4 only had experimental support for new mono.  You may wish to try 2018.3.  Additionally, it is more effective to report Unity issues to their bug tracker https://unity3d.com/unity/qa/bug-reporting 

Please don't hesitate to let me know if you believe I've closed it in error.

**Closed by lambdageek** 2019-02-26 23:44 UTC
Labels: area-Runtime: Metadata

**Comment by jhughes2112** [comment] 2019-12-09 21:57
This is happening to us in Unity 2018.4.12 LTS, on Android.

Caused by java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000050
Build fingerprint: 'XXXXXXXXXXXXXX'
Revision: '6'
pid: 17469, tid: 19865, name: UnityMain  >>> XXXXXXXXXXXXXXXX <<<
    r0 00000000  r1 88199898  r2 00000001  r3 00000000
    r4 8b593c2c  r5 00000001  r6 00000000  r7 8ce88b90
    r8 00000000  r9 9fdbee00  sl 8ce88978  fp 8ce886e4
    ip 88b74bc8  sp 8ce886c8  lr 8898567c  pc 889856c4  cpsr 00004d99

       at libmonobdwgc-2.mono_class_vtable_full(mono_class_vtable_full:196)
       at libmonobdwgc-2.mono_array_new_checked(mono_array_new_checked:148)
       at libmonobdwgc-2.mono_array_new(mono_array_new:40)
       at libunity.006a8c1c()
       at libunity.006a94c8()
       at libunity.006a5dcc()
       at base.00001397()
