### ISSUE TITLE
Running tests from `sdks/ios` that use `System.Native` is not currently supported.

### ISSUE THREAD

**Issue by srxqds** [mono/mono#12309] opened 2019-01-08 02:39 UTC
1.  cd sdks/ios
2. make run-ios-dev-corlib

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

## Stacktrace

(lldb)     safequit
Process 37839 detached
*** test-runner output ***
NUnitLite 1.0.0 (.NET 4.5 Debug)
Copyright 2013, Charlie Poole

Runtime Environment -
    OS Version: Unix 17.7.0.0
  Mono Version: 4.0.50524.0

System.TypeInitializationException: The type initializer for 'System.Random' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: System.Native
  at (wrapper managed-to-native) Interop+Sys.GetReadDirRBufferSize()
  at Interop+Sys..cctor () <0x1018f8818 + 0x00000> in <ce7da5a299c844beb1323f9f9e5b6056>:0 
   --- End of inner exception stack trace ---
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) <0x1018f8378 + 0x00010> in <ce7da5a299c844beb1323f9f9e5b6056>:0 
  at System.Random.GenerateGlobalSeed () <0x1018f8248 + 0x00006> in <ce7da5a299c844beb1323f9f9e5b6056>:0 
  at System.Random..cctor () <0x1018f8098 + 0x00000> in <ce7da5a299c844beb1323f9f9e5b6056>:0 
   --- End of inner exception stack trace ---
  at NUnitLite.Runner.CommandLineOptions.get_InitialSeed () <0x1018f7b60 + 0x00016> in <8799ff55b00b47d9bd900f0309a23b6a>:0 
  at NUnitLite.Runner.TextUI.Execute (System.String[] args) <0x1010f6cf8 + 0x0027a> in <8799ff55b00b47d9bd900f0309a23b6a>:0 
make: *** [run-ios-dev-corlib] Error 1

**Comment by scooper91** [comment] 2019-01-08 09:50
I'm seeing a similar issue this morning when trying to update `ca-certificates-mono`.

```
> sudo apt install ca-certificates-mono
Setting up mono-gac (5.23.0.217-0nightly2+ubuntu1804b1) ...                                                         
* Installing 1 assembly from libnunit-console-runner2.6.3-cil into Mono                                                                                           
                                                                                                                                                                                                                   
Unhandled Exception:                                                                                                                                     
System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: /usr/lib/../lib/libmono-system-native.so                                                  
  at (wrapper managed-to-native) Interop+Sys.GetReadDirRBufferSize()          
  at Interop+Sys..cctor () [0x00000] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0                                                                                      
   --- End of inner exception stack trace ---                                                                                                                                                                    
  at System.IO.FileSystem.FileExists (System.String fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.FileSystem.DirectoryExists (System.String fullPath, Interop+ErrorInfo& errorInfo) [0x00000] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0                                                  
  at System.IO.FileSystem.DirectoryExists (System.String fullPath) [0x00000] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0                                 
  at System.IO.Directory.Exists (System.String path) [0x00019] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0                    
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions opti
ons) [0x000c1] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0                                                                                                              
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <5a18ef8
51b9a4f01af8dd2d6a62334b7>:0                                                                                        
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) [0x00055] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) [0x00007] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.StreamReader..ctor (System.String path) [0x00000] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
  at Mono.Security.StrongNameManager.LoadConfig (System.String filename) [0x00011] in <3a923c71eadd4808933c58432aadf487>:0
  at Mono.Tools.Driver.LoadConfig (System.Boolean quiet) [0x00044] in <3a923c71eadd4808933c58432aadf487>:0
  at Mono.Tools.Driver.Main (System.String[] args) [0x0034a] in <3a923c71eadd4808933c58432aadf487>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: /usr/lib/../lib/libmono-system-native.so
  at (wrapper managed-to-native) Interop+Sys.GetReadDirRBufferSize()
  at Interop+Sys..cctor () [0x00000] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
   --- End of inner exception stack trace ---
  at System.IO.FileSystem.FileExists (System.String fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.FileSystem.DirectoryExists (System.String fullPath, Interop+ErrorInfo& errorInfo) [0x00000] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.FileSystem.DirectoryExists (System.String fullPath) [0x00000] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.Directory.Exists (System.String path) [0x00019] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions opti
ons) [0x000c1] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <5a18ef8
51b9a4f01af8dd2d6a62334b7>:0
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) [0x00055] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) [0x00007] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at System.IO.StreamReader..ctor (System.String path) [0x00000] in <5a18ef851b9a4f01af8dd2d6a62334b7>:0
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
  at Mono.Security.StrongNameManager.LoadConfig (System.String filename) [0x00011] in <3a923c71eadd4808933c58432aadf487>:0
  at Mono.Tools.Driver.LoadConfig (System.Boolean quiet) [0x00044] in <3a923c71eadd4808933c58432aadf487>:0
  at Mono.Tools.Driver.Main (System.String[] args) [0x0034a] in <3a923c71eadd4808933c58432aadf487>:0
E: installing Assembly /usr/lib/cli/nunit-console-runner-2.6.3/nunit-console-runner.dll failed
E: Installation of libnunit-console-runner2.6.3-cil with /usr/share/cli-common/runtimes.d/mono failed
* Installing 1 assembly from libnunit-core2.6.3-cil into Mono
```

**Comment by baulig** [comment] 2019-01-08 11:14
Running any tests from `sdks/ios` that use `System.Native` is not currently supported (and won't be until the 2018-10 integration is done).

**Comment by baulig** [comment] 2019-01-08 11:19
The Ubuntu issue is likely a packaging / installation issue and unrelated to `sdks/ios`.

**Comment by baulig** [comment] 2019-01-08 13:41
The problem is that `System.Native` is not currently supported at all in Xamarin.iOS or Xamarin.Mac.

Making changes in the `sdks/ios` directory won't change that - you might get the those tests to pass, but that'd essentially be a false positive as no user application would work.  Those require tooling changes in `mmp` and `mtouch`.

This was supposed to be done with the 2018-10 monthly integration of `xamarin-macios` - which ran into problems and delays and has still not been merged yet (https://github.com/xamarin/xamarin-macios/pull/4904).

On top of that, I will also not call `System.Native` to be "supported" in XI / XM until it passes the `xamarin-macios` test suite (which uses the same tooling that an end user would see).  The tests in `sdks/ios` use some shell script to bypass this tooling and manually create an app package.

Once that PR in xamarin-macios has been merged, then we can look at fixing the tests in the `sdks` directory.

**Comment by baulig** [comment] 2019-01-08 13:44
@scooper91 Thanks.

Unfortunately, I don't know much about how we're building packages for Ubuntu, but maybe @directhex could help?  If you could point me to the script that's being run during this `apt install ca-certificates-mono`, then I could investigate whether it is a packaging error or something else.

**Comment by scooper91** [comment] 2019-01-08 14:10
@baulig I've made an issue here for the behaviour I am seeing: https://github.com/mono/mono/issues/12316

**Closed** 2019-11-12 01:53 UTC
Labels: area-Build
