### ISSUE TITLE
[Debugging] Cannot see array values in Locals window

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19410] opened 2020-04-01 15:47 UTC
When debugging, there is no way to expand and see array values in the `Locals` window:
![image](https://user-images.githubusercontent.com/34246760/78157769-3fa23c00-73f5-11ea-9984-13cf4591c52c.png)

Furthermore, trying to evaluate a single element of an array using indexer fails:
![image](https://user-images.githubusercontent.com/34246760/78157837-5ba5dd80-73f5-11ea-966b-b28cd21625bd.png)

**Comment by lewing** [comment] 2020-04-02 16:42
Should be addressed by https://github.com/mono/mono/issues/19410

**Comment by lewing** [comment] 2020-04-04 19:56
https://github.com/mono/mono/issues/19443

**Comment by lewing** [comment] 2020-04-17 02:25
duplicate of https://github.com/mono/mono/issues/19229

**Closed by lewing** 2020-04-17 02:25 UTC
Labels: area-Debugger, target-wasm
