### ISSUE TITLE
System.Data tests fail on iOS platforms

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#12384] opened 2019-01-11 15:56 UTC
On Xamarin.iOS we have started executing the System.Data tests provided by the SDK, we have to issue regarding them:

1. There are some missing files needed by the tests.
2. We yet do not have a test dll for the watch.

We are ignoring those tests that are failing due to the missing files missing types on wackos. Please look at https://github.com/xamarin/xamarin-macios/pull/5379/files which shows the ignored tests.

**Comment by akoeplinger** [comment] 2019-02-18 19:04
Duplicate of https://github.com/mono/mono/issues/12354.

2018-10 does include the test assembly for the monotouch_watch profile.

**Closed by akoeplinger** 2019-02-18 19:04 UTC
Labels: area-SDK: Packaging
