### ISSUE TITLE
[2019-12][iOS] System.Tests.ValueTupleTests failures on iOS / release

### ISSUE THREAD

**Issue by spouliot** [mono/mono#18274] opened 2019-12-20 20:53 UTC
## Steps to Reproduce

1. Run mscorlib unit tests on devices (64 bits) under Release

### Current Behavior

```
[FAIL] System.Tests.ValueTupleTests.ValueTupleSerialization 
[FAIL] System.Tests.ValueTupleTests.ValueTupleSerialization Test name: System.Tests.ValueTupleTests.ValueTupleSerialization 
[FAIL] System.Tests.ValueTupleTests.ThreeTuples 
[FAIL] System.Tests.ValueTupleTests.ThreeTuples Test name: System.Tests.ValueTupleTests.ThreeTuples 
Tests run: 110768 Passed: 97195 Inconclusive: 0 Failed: 2 Ignored: 13447
```

and

```
[FAIL] System.Tests.ValueTupleTests.ValueTupleSerialization 
[FAIL] System.Tests.ValueTupleTests.ValueTupleSerialization Test name: System.Tests.ValueTupleTests.ValueTupleSerialization 
[FAIL] System.Tests.ValueTupleTests.ThreeTuples 
[FAIL] System.Tests.ValueTupleTests.ThreeTuples Test name: System.Tests.ValueTupleTests.ThreeTuples 
[FAIL] System.Tests.ValueTupleTests.SevenTuples 
[FAIL] System.Tests.ValueTupleTests.SevenTuples Test name: System.Tests.ValueTupleTests.SevenTuples 
Tests run: 110768 Passed: 97194 Inconclusive: 0 Failed: 3 Ignored: 13447```

### Expected Behavior

No failure.

## On which platforms did you notice this

[x] iOS
[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

2019-12
This does not happen on 2019-10

## Stacktrace

Logs (build / execution) are available from
http://xamarin-storage/jenkins/xamarin-macios/pull-request/a0c657a850b5eefbe5709d2b6fe6804009dc4f0f/3334590/device-tests/jenkins-results/tests/index.html

**Comment by spouliot** [comment] 2019-12-20 20:54
c.c. @SamMonoRT for 2019-12

**Comment by spouliot** [comment] 2019-12-20 20:55
Similar failures happens on tvOS too (only release)
http://xamarin-storage/jenkins/xamarin-macios/pull-request/a0c657a850b5eefbe5709d2b6fe6804009dc4f0f/3334592/device-tests/jenkins-results/tests/index.html

```
[FAIL] System.Tests.ValueTupleTests.ThreeTuples 
[FAIL] System.Tests.ValueTupleTests.ThreeTuples Test name: System.Tests.ValueTupleTests.ThreeTuples 
[FAIL] System.Tests.ValueTupleTests.ValueTupleSerialization 
[FAIL] System.Tests.ValueTupleTests.ValueTupleSerialization Test name: System.Tests.ValueTupleTests.ValueTupleSerialization 
[FAIL] System.Tests.ValueTupleTests.SevenTuples 
[FAIL] System.Tests.ValueTupleTests.SevenTuples Test name: System.Tests.ValueTupleTests.SevenTuples 
Tests run: 110762 Passed: 97204 Inconclusive: 0 Failed: 3 Ignored: 13431
```

```
[FAIL] System.Tests.ValueTupleTests.ThreeTuples 
[FAIL] System.Tests.ValueTupleTests.ThreeTuples Test name: System.Tests.ValueTupleTests.ThreeTuples 
[FAIL] System.Tests.ValueTupleTests.ValueTupleSerialization 
[FAIL] System.Tests.ValueTupleTests.ValueTupleSerialization Test name: System.Tests.ValueTupleTests.ValueTupleSerialization 
[FAIL] System.Tests.ValueTupleTests.SevenTuples 
[FAIL] System.Tests.ValueTupleTests.SevenTuples Test name: System.Tests.ValueTupleTests.SevenTuples 
Tests run: 110762 Passed: 97204 Inconclusive: 0 Failed: 3 Ignored: 13431
```

**Comment by SamMonoRT** [comment] 2020-01-10 19:27
imhameed will take a look early next week.

**Comment by lewurm** [comment] 2020-01-16 22:51
duplicate of https://github.com/mono/mono/issues/18455

**Closed by lewurm** 2020-01-16 22:51 UTC
Labels: target-xamarin-ios
