### ISSUE TITLE
[2019-06][iOS] mono-native-compat tests fail on iOS 64 Today extensions

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#15506] opened 2019-07-02 10:15 UTC
When running the mono-native-compat tests on an iOS 64b today extension the following tests fail on Release and Debug modes:

> [FAIL] NativePlatformTest.PlatformType : System.EntryPointNotFoundException : mono_native_get_platform_type 
> [FAIL] NativePlatformTest.TestInitialize : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] Introspection.CheckSymbols : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] Introspection.TestInvoke : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] NativePlatformConfig.PlatformType : System.EntryPointNotFoundException : mono_native_get_platform_type 
> Tests run: 6 Passed: 1 Inconclusive: 0 Failed: 5 Ignored: 0

Tests do pass in master with mono 2016-02 and in the other configurations (AssemblyBuildTarget: SDK framework (release) etc..)

Details:

* [Build log](https://gist.github.com/mandel-macaque/c4049417e2f826011dba6223432cb084)
* [Run log](https://gist.github.com/mandel-macaque/901007a4851b4633c9ea672fdeb584ed)

**Comment by akoeplinger** [comment] 2019-07-02 10:21
This is almost certainly a duplicate of https://github.com/mono/mono/issues/15507 so let's track it there.

**Closed by akoeplinger** 2019-07-02 10:21 UTC
