### ISSUE TITLE
HttpClient broken for certain URLs

### ISSUE THREAD

**Issue by rawnsley** [mono/mono#11455] opened 2018-10-30 12:12 UTC
## Steps to Reproduce

1. Instantiate HttpClient
2. Call HttpClient.GetAsync on target URL
3. Wait for timeout
```
csharp> LoadAssembly("System.Net.Http");                                                                                                            
csharp> var httpClient = new System.Net.Http.HttpClient();                                                                                          
csharp> httpClient.GetAsync("https://cdn1.360cities.net/pano/hanyluz/01061142_pano_360.jpg/cube/up/tile/512/2/1/1.jpg").Result.IsSuccessStatusCode; 
```
There are lots of URLs that fail in this way and I can provide more examples if required. This did not happen on previous versions of Mono.

Problem originally found on Xamarin.Android, but also broken in REPL on OSX.

Occasionally the download works the first time and then fails the second. It's possible that there was a CDN miss in the first GET and a hit in the second, which would lead to slightly different header signatures.

### Current Behavior

The attached file shows a REPL session for downloading two files:

1. https://cdn1.360cities.net/pano/hanyluz/01061142_pano_360.jpg/cube/up/tile/512/2/1/0.jpg
2. https://cdn1.360cities.net/pano/hanyluz/01061142_pano_360.jpg/cube/up/tile/512/2/1/1.jpg

The first file downloads fine, but the second file causes a timeout exception to be thrown after the default timeout period (5 minutes).

[mono-httpclient-fail-repl.txt](https://github.com/mono/mono/files/2529512/mono-httpclient-fail-repl.txt)

### Expected Behavior

Both files should download without exceptions.

## On which platforms did you notice this

[X] macOS
[X] Xamarin.Android
[ ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.12.0.309

## Stacktrace

```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000ba] in <81ba78c8dc794b7f9f7b530c53db0f84>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x0001d] in <81ba78c8dc794b7f9f7b530c53db0f84>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <c117eea4a0fb4f8f83914627d25c83b5>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <c117eea4a0fb4f8f83914627d25c83b5>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <c117eea4a0fb4f8f83914627d25c83b5>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x0000f] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at <InteractiveExpressionClass>.Host (System.Object& $retval) [0x00010] in <d179cfe6a44b41c19bc9a7f733e9bc52>:0 
  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object& result, System.Boolean& result_set) [0x00038] in <07e2db84775442fb863641d4ce942e71>:0 
  at Mono.CSharpShell.Evaluate (System.String input) [0x00000] in <d7f359da1a4a4012a4bf3d49720b6be4>:0 
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000ba] in <81ba78c8dc794b7f9f7b530c53db0f84>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x0001d] in <81ba78c8dc794b7f9f7b530c53db0f84>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <c117eea4a0fb4f8f83914627d25c83b5>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <c117eea4a0fb4f8f83914627d25c83b5>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <71f4e3d7d65e42b0a699d02e59766d3c>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <c117eea4a0fb4f8f83914627d25c83b5>:0 <---
```

**Comment by EgorBo** [comment] 2018-12-04 20:08
I can reproduce it on 5.12 (macOS) in REPL but can't reproduce in 5.16 and master. I guess it was fixed by Martin

**Closed** 2018-12-17 12:47 UTC
Labels: area-BCL: System.Net.Http, regression
