### ISSUE TITLE
FileSystemWatcher throws System.InvalidOperationException: object_op ---> System.BadImageFormatException: Method has no body

### ISSUE THREAD

**Issue by petlof** [mono/mono#12557] opened 2019-01-22 10:07 UTC
With Mono 5.18 on Debian I'm getting the below exception when using FileSystemWatcher and EnableRaisingEvents.

If i do 
export MONO_MANAGED_WATCHER=dummy 
then things works (I guess because of falling back to not use the CoreFX implementation?)

===

[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: object_op ---> System.BadImageFormatException: Method has no body
at System.IO.CoreFX.FileSystemWatcher.StartRaisingEvents () [0x0001c] in <7c5dc4c30b744f07bb1c2f01ee859535>:0
at System.IO.CoreFX.FileSystemWatcher.StartRaisingEventsIfNotDisposed () [0x00019] in <7c5dc4c30b744f07bb1c2f01ee859535>:0
at System.IO.CoreFX.FileSystemWatcher.set_EnableRaisingEvents (System.Boolean value) [0x0001d] in <7c5dc4c30b744f07bb1c2f01ee859535>:0
at (wrapper remoting-invoke-with-check) System.IO.CoreFX.FileSystemWatcher.set_EnableRaisingEvents(bool)
at System.IO.CoreFXFileSystemWatcherProxy+<>c.b__9_0 (System.IO.CoreFX.FileSystemWatcher internal_fsw, System.IO.FileSystemWatcher fsw) [0x00048] in <7c5dc4c30b744f07bb1c2f01ee859535>:0
at System.IO.CoreFXFileSystemWatcherProxy.Operation (System.Action4[T1,T2,T3,T4] map_op, System.Action2[T1,T2] object_op, System.Object handle, System.Action2[T1,T2] cancel_op) [0x00184] in <7c5dc4c30b744f07bb1c2f01ee859535>:0 --- End of inner exception stack trace --- at System.IO.CoreFXFileSystemWatcherProxy.Operation (System.Action4[T1,T2,T3,T4] map_op, System.Action2[T1,T2] object_op, System.Object handle, System.Action2[T1,T2] cancel_op) [0x001a6] in <7c5dc4c30b744f07bb1c2f01ee859535>:0
at System.IO.CoreFXFileSystemWatcherProxy.StartDispatching (System.Object handle) [0x00004] in <7c5dc4c30b744f07bb1c2f01ee859535>:0
at System.IO.FileSystemWatcher.Start () [0x0001b] in <7c5dc4c30b744f07bb1c2f01ee859535>:0
at System.IO.FileSystemWatcher.set_EnableRaisingEvents (System.Boolean value) [0x0003d] in <7c5dc4c30b744f07bb1c2f01ee859535>:0
at (wrapper remoting-invoke-with-check) System.IO.FileSystemWatcher.set_EnableRaisingEvents(bool)

**Comment by baulig** [comment] 2019-01-29 05:54
I vaguely remember having seen `System.BadImageFormatException: Method has no body` in the context of a P/Invoke'd library not being found.  Is it possible that we don't install the native library on linux @alexischr?

**Comment by alexischr** [comment] 2019-01-29 21:56
Yeah this sounds very much like an exception caused by the native library missing. @petlof Are you using the official package (from https://www.mono-project.com/download/stable/#download-lin)?

**Comment by alexischr** [comment] 2019-02-12 21:47
This has showed up on Android when there were problems loading the library other than the library file missing. CentOS may have similar constraints on dynamic loading/linking. I am suspecting you may need this commit: https://github.com/mono/mono/pull/12963/commits/fcbbd95e9b49f47495fcd6c94ac49362519064f5
and/or a variation of this one: https://github.com/mono/mono/pull/12963/commits/955f873549d509f250bed19485038c2eaf6b39ac applied to CentOS

But let's ensure that the package is not just missing the file. Could you see if you have `lib/libmono-native.so` installed as part of your Mono package?

**Comment by petlof** [comment] 2019-02-13 07:32
/usr/lib64/libmono-system-native.so
/usr/lib64/libmono-profiler-aot.so
/usr/lib64/libmono-btls-shared.so
/usr/lib64/libmonoboehm-2.0.so
/usr/lib64/libmono-profiler-log.so
/usr/lib64/libmono-llvm.so
/usr/lib64/libmonosgen-2.0.so
/usr/lib64/libmono-profiler-coverage.so
/usr/lib64/libmono-2.0.so

**Comment by marek-safar** [comment] 2019-02-19 14:45
@petlof we believe we have a fix already in for Mono 5.20. Could you re-test it for us?

**Comment by deserthacker** [comment] 2019-02-26 20:25
This looks similar to a crash we are seeing in 5.18.0.240, is there a class issue across releases?

**Comment by AndirNotes** [comment] 2019-04-11 17:22
I've got the same problem with mono 5.20 in OSX High Sierra.

**Comment by AndirNotes** [comment] 2019-04-12 09:00
Details:
Mono 5.18.1.3
```
cd /Library/Frameworks/Mono.framework/
find . -name *libmono-system*
./Versions/5.18.1/lib/libmono-system-native.la
./Versions/5.18.1/lib/libmono-system-native.0.dylib.dSYM
./Versions/5.18.1/lib/libmono-system-native.0.dylib.dSYM/Contents/Resources/DWARF/libmono-system-native.0.dylib
./Versions/5.18.1/lib/libmono-system-native.0.dylib
./Versions/5.18.1/lib/libmono-system-native.a
./Versions/5.18.1/lib/libmono-system-native.dylib
```

Mono 5.20.1.19
```
cd /Library/Frameworks/Mono.framework/
find . -name *libmono-system*
--No results--
```

**Comment by AndirNotes** [comment] 2019-05-19 07:04
@alexischr, Hi, 

Sorry to bother you. 
Could we expect fixes for this in 5.20.xxx Mac release? It's quite a blocker.
Some progress info would be appreciated!

**Comment by anon17** [comment] 2019-07-02 12:25
I have it on 5.20.1.19
```
/usr/lib64/libmono-native.so.0
/usr/lib64/libmono-native.so.0.0.0
```

**Comment by anon17** [comment] 2019-07-04 13:51
That was rpm distro, on a debian derivative 5.20.1.19 works fine. Looks somehow distro dependent?

**Comment by anon17** [comment] 2019-07-05 09:48
Non-working system:
```
Mono: DllImport attempting to load: '/usr/lib64/libmono-native.so'.
Mono: DllImport error loading library '/usr/lib64/libmono-native.so': '/usr/lib64/libmono-native.so: cannot open shared object file: No such file or directory'.
Mono: DllImport error loading library '/usr/lib64/libmono-native.so': '/usr/lib64/libmono-native.so: cannot open shared object file: No such file or directory'.
Mono: DllImport error loading library '/usr/lib64/libmono-native.so': '/usr/lib64/libmono-native.so: cannot open shared object file: No such file or directory'.
Mono: DllImport error loading library '/usr/lib64/libmono-native.so': '/usr/lib64/libmono-native.so: cannot open shared object file: No such file or directory'.
Mono: DllImport unable to load library '/usr/lib64/libmono-native.so: cannot open shared object file: No such file or directory'.
log4net:ERROR Failed to initialize configuration file watcher for file [/tmp/app/test.config]
System.InvalidOperationException: object_op ---> System.BadImageFormatException: Method has no body
```
```
/usr/lib64/libmono-native.so.0
/usr/lib64/libmono-native.so.0.0.0
```
No libmono-native.so indeed.

Working system:
```
Mono: DllImport attempting to load: '/usr/lib/../lib/libmono-native.so'.
Mono: DllImport loaded library '/usr/lib/../lib/libmono-native.so'.
Mono: DllImport searching in: '/usr/lib/../lib/libmono-native.so' ('/usr/lib/../lib/libmono-native.so').
Mono: Searching for 'SystemNative_INotifyInit'.
Mono: Probing 'SystemNative_INotifyInit'.
Mono: Found as 'SystemNative_INotifyInit'.
```
```
/usr/lib/libmono-native.so
/usr/lib/libmono-native.so.0
/usr/lib/libmono-native.so.0.0.0
```
Packager's problem?

**Comment by anon17** [comment] 2019-07-05 09:58
Created symlink `/usr/lib64/libmono-native.so` and now it works.

**Comment by cmcqueen** [comment] 2019-07-30 04:18
On a Yocto build, I also found this issue. I found it can be fixed by modifying `/etc/mono/config` to change this line:

        <dllmap dll="System.Native" target="$mono_libdir/libmono-system-native.so" os="!windows" />

to:

        <dllmap dll="System.Native" target="$mono_libdir/libmono-system-native.so.0" os="!windows" />

**Comment by SamMonoRT** [comment] 2020-07-23 13:03
Closing old issue, will triage if re-opened with proper repro steps on latest builds

**Closed by SamMonoRT** 2020-07-23 13:03 UTC
Labels: area-BCL: System, needs more info
