### ISSUE TITLE
Nuget error on Linux

### ISSUE THREAD

**Issue by mkrueger** [mono/mono#13169] opened 2019-02-25 08:23 UTC
While compiling monodevelop it fails to update the nugets:

```
The SSL connection could not be established, see inner exception.
  Specified cast is not valid.
  GET https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='Microsoft.CodeAnalysis.CSharp'&semVerLevel=2.0.0
Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/4.9.0/index.json.
  The SSL connection could not be established, see inner exception.
  Specified cast is not valid.
```

It seems to have something to do with commit 2f411750acfd2132f9b4970ef8cf11d9a0f62df9
Using a build af70768885ef3d403db534ed1bd8af798cbc80e0 or prior nuget works. Master of today fails as well.

**Comment by marek-safar** [comment] 2019-02-25 09:00
@baulig this looks like regression from ssl change

**Comment by baulig** [comment] 2019-02-25 19:01
Without a full stack trace or some logging, there is nothing I can do about this.

**Comment by marek-safar** [comment] 2019-03-01 11:06
@mkrueger could you share steps how to reproduce it?

**Comment by baulig** [comment] 2019-06-07 17:29
This was in "needs more info" state for over 3 months, closing.

**Closed by baulig** 2019-06-07 17:29 UTC
Labels: area-BCL: System, needs more info, regression
