### ISSUE TITLE
InvalidOperationException thrown from AsyncTaskMethodBuilder<VoidResult>.SetException

### ISSUE THREAD

**Issue by Therzok** [mono/mono#15739] opened 2019-07-18 12:51 UTC
## Steps to Reproduce

1. N/A - see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935138
2. 
3. 

### Current Behavior

AsyncResult seems to be crashing when an exception is set.

### Expected Behaviour

The exception is set, and nothing is thrown from the async state machine.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:

6.0.0.296 (126), 6.0.0.311 (17), 6.0.0.309 (8), 6.0.0.310 (5), 6.0.0.306 (5), 6.0.0.302 (4), 6.0.0.176 (3), 6.0.0.313 (1), 6.0.0.307 (1), 6.0.0.300 (1), 6.0.0.265 (1), 6.0.0.249 (1)

## Stacktrace

```
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(Exception)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException(Exception)
System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs)
System.Net.Sockets.SocketAsyncEventArgs.Complete()
System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception,Int32,SocketFlags)
System.Net.Sockets.MultipleConnectAsync.AsyncFail(Exception)
System.Net.Sockets.MultipleConnectAsync.InternalConnectCallback(Object,SocketAsyncEventArgs)
System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs)
System.Net.Sockets.SocketAsyncEventArgs.Complete()
System.Net.Sockets.Socket.<>c.<.cctor>b__XXX(IAsyncResult)
System.Net.Sockets.SocketAsyncResult.<>c.<Complete>b__XXX(Object)
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue.Dispatch()
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

```
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(Exception)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException(Exception)
System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs)
System.Net.Sockets.SocketAsyncEventArgs.Complete()
System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception,Int32,SocketFlags)
System.Net.Sockets.MultipleConnectAsync.AsyncFail(Exception)
System.Net.Sockets.MultipleConnectAsync.Fail(Boolean,Exception)
System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult,Boolean)
System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult)
System.Runtime.Remoting.Messaging.AsyncResult.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue.Dispatch()
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

```
Please paste the stack trace here if available.
```

**Comment by lambdageek** [comment] 2019-07-18 16:02
This is https://github.com/mono/mono/issues/15211

**Comment by baulig** [comment] 2019-07-18 17:19
Closing as a duplicate of https://github.com/mono/mono/issues/15211 to keep all the information about this issue in one single place; I linked the DevDiv work item there.

**Closed by baulig** 2019-07-18 17:19 UTC
Labels: area-BCL: System.Net.Http
