### ISSUE TITLE
Yum on CentOS7 sporadically installs older mono-devel 6.8.0 version of mono packages rather than 6.12.0.

### ISSUE THREAD

**Issue by BrianMouncer** [mono/mono#21774] opened 2024-05-16 21:47 UTC
## Steps to Reproduce

pull the docker image for centos:7
install the mono projects yum repository.
update yum and install the mono-devel package, and check the version.
Usually you will get version 6.12.0.xxx but for a 24 hour period last week, and again today, we are getting 6.8.0.xxx version of the mono-devel package, which breaks other build tools, like cmake and nuget.exe

++ rpmkeys --import '[http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'](http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF%27)
+++ rpm -E '%{rhel}'
++ centos_version=7
++ curl https://download.mono-project.com/repo/centos7-stable.repo
++ tee /etc/yum.repos.d/mono-centos7-stable.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
++ yum install -y mono-devel
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: repo1.sea.innoscale.net
 * epel: ziply.mm.fcix.net
 * extras: mirrors.sonic.net
 * updates: mirrors.xtom.com
Resolving Dependencies
--> Running transaction check
---> **Package mono-devel.x86_64 0:6.8.0-2.el7 will be installed**

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

We are running into yum install issues too, but we cannot even get 6.8.0.107.

We build some projects on CentOS7, and our nuget commands are failing because mono is not getting installed consistently.
On working builds yum will install "Package mono-devel.x86_64 0:6.12.0.107-0.xamarin.9.epel7", however last week and again today, 6.12 is no longer found in the repo, and yum installs the older "Package mono-devel.x86_64 0:6.8.0-2.el7 will be installed" instead", which breaks later calls to nuget.exe...

**Comment by BrianMouncer** [comment] 2024-05-16 21:58
if it helps, we do parallel/distributed builds on several ubuntu docker contains, and mono-devel installs the 6.12.0 version of the packages there every time, including the same windows of time when yum is failing on the centos7 docker container. 

Get:163 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 mono-xbuild all 6.12.0.200-0xamarin2+ubuntu2004b1 [486 kB]
Get:164 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 mono-devel all 6.12.0.200-0xamarin2+ubuntu2004b1 [24.0 MB]
Get:165 http://archive.ubuntu.com/ubuntu focal/main amd64 liberror-perl all 0.17029-1 [26.5 kB]


Thanks

**Comment by directhex** [comment] 2024-05-17 12:46
I can't reproduce this locally. In your console logs, does it look like it is considering 6.12 but deciding 6.8 is easier to resolve in the dependency tree, or is it entirely failing to pull metadata for our repo? e.g. do you have:

```
(3/5): mono-centos7-stable/primary_db                        | 1.7 MB  00:00:00
```

in your yum output?

**Comment by BrianMouncer** [comment] 2024-05-17 17:04
seems to be working reliably again today.
it was failing 100 yesterday morning, and faling maybe 90% in the after noon.

So far this morning I have had several successful builds, and no failures to install mono.

as to your meta data question, I do not see that exact line in the yum output...
I do see we pull data from yum.repos.d/mono-centos7-stable.repo

here is the head of the yum install for mono-devel package.

 **++ curl https://download.mono-project.com/repo/centos7-stable.repo
2024-05-17T04:44:58.3728641Z ++ tee /etc/yum.repos.d/mono-centos7-stable.repo**
2024-05-17T04:44:58.3753117Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2024-05-17T04:44:58.3753504Z                                  Dload  Upload   Total   Spent    Left  Speed
2024-05-17T04:44:58.3753815Z 
2024-05-17T04:44:58.6564507Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2024-05-17T04:44:58.6565022Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2024-05-17T04:44:58.6577087Z ++ yum install -y mono-devel
2024-05-17T04:44:58.7585412Z Loaded plugins: fastestmirror, ovl
2024-05-17T04:44:58.8011187Z Loading mirror speeds from cached hostfile
2024-05-17T04:44:58.8040128Z  * base: ziply.mm.fcix.net
2024-05-17T04:44:58.8044500Z  * epel: ziply.mm.fcix.net
2024-05-17T04:44:58.8054908Z  * extras: centos-distro.1gservers.com
2024-05-17T04:44:58.8056669Z  * updates: mnvoip.mm.fcix.net
2024-05-17T04:44:59.0367045Z Resolving Dependencies
2024-05-17T04:44:59.0368167Z --> Running transaction check
2024-05-17T04:44:59.0368565Z ---> Package mono-devel.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.0444231Z --> Processing Dependency: mono-core = 6.8.0-2.el7 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2585823Z --> Processing Dependency: mono(Commons.Xml.Relaxng) = 4.0.0.0 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2586608Z --> Processing Dependency: mono(Mono.Cecil) = 0.11.0.0 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2587203Z --> Processing Dependency: mono(Mono.CodeContracts) = 4.0.0.0 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2589552Z --> Processing Dependency: mono(Mono.CompilerServices.SymbolWriter) = 4.0.0.0 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2591661Z --> Processing Dependency: mono(Mono.Profiler.Log) = 4.0.0.0 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2593649Z --> Processing Dependency: mono(Mono.Security) = 4.0.0.0 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2596870Z --> Processing Dependency: mono(System.ServiceModel.Internals) = 0.0.0.0 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2606807Z --> Processing Dependency: mono(monodoc) = 1.0.0.0 for package: mono-devel-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2614501Z --> Running transaction check
2024-05-17T04:44:59.2615156Z ---> Package mono-core.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.2640440Z --> Processing Dependency: mono(System.ComponentModel.DataAnnotations) = 4.0.0.0 for package: mono-core-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2650625Z --> Processing Dependency: mono(System.Data.DataSetExtensions) = 4.0.0.0 for package: mono-core-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2659318Z --> Processing Dependency: mono(System.Runtime.Serialization) = 4.0.0.0 for package: mono-core-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2661003Z --> Processing Dependency: mono(System.ServiceProcess) = 4.0.0.0 for package: mono-core-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2669113Z --> Processing Dependency: mono(System.Web) = 4.0.0.0 for package: mono-core-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2672297Z --> Processing Dependency: libgdiplus for package: mono-core-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2680479Z ---> Package mono-wcf.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.2697429Z --> Processing Dependency: mono(System.Web.Extensions) = 4.0.0.0 for package: mono-wcf-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2705337Z ---> Package monodoc.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.2719094Z --> Running transaction check
2024-05-17T04:44:59.2720740Z ---> Package libgdiplus.x86_64 0:2.10-10.el7 will be installed
2024-05-17T04:44:59.2750272Z --> Processing Dependency: libexif.so.12()(64bit) for package: libgdiplus-2.10-10.el7.x86_64
2024-05-17T04:44:59.2770516Z ---> Package mono-data.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.2784441Z ---> Package mono-extras.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.2797775Z --> Processing Dependency: mono(System.Windows.Forms) = 4.0.0.0 for package: mono-extras-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2805279Z ---> Package mono-mvc.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.2820514Z ---> Package mono-web.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.2842062Z --> Processing Dependency: mono(Mono.Data.Sqlite) = 4.0.0.0 for package: mono-web-6.8.0-2.el7.x86_64
2024-05-17T04:44:59.2849524Z --> Running transaction check
2024-05-17T04:44:59.2850043Z ---> Package libexif.x86_64 0:0.6.22-2.el7_9 will be installed
2024-05-17T04:44:59.2852130Z ---> Package mono-data-sqlite.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.2862478Z ---> Package mono-winforms.x86_64 0:6.8.0-2.el7 will be installed
2024-05-17T04:44:59.3259627Z --> Finished Dependency Resolution
2024-05-17T04:44:59.3356807Z 
2024-05-17T04:44:59.3357056Z Dependencies Resolved
2024-05-17T04:44:59.3372594Z 
2024-05-17T04:44:59.3373145Z ================================================================================
2024-05-17T04:44:59.3374402Z  Package                Arch         Version                Repository     Size
2024-05-17T04:44:59.3374814Z ================================================================================
2024-05-17T04:44:59.3375178Z Installing:
2024-05-17T04:44:59.3375715Z  mono-devel             x86_64       6.8.0-2.el7            epel          6.4 M
2024-05-17T04:44:59.3376015Z Installing for dependencies:
2024-05-17T04:44:59.3376502Z  libexif                x86_64       0.6.22-2.el7_9         updates       423 k
2024-05-17T04:44:59.3377035Z  libgdiplus             x86_64       2.10-10.el7            epel          163 k
2024-05-17T04:44:59.3377417Z  mono-core              x86_64       6.8.0-2.el7            epel           19 M
2024-05-17T04:44:59.3377690Z  mono-data              x86_64       6.8.0-2.el7            epel          4.8 M
2024-05-17T04:44:59.3378150Z  mono-data-sqlite       x86_64       6.8.0-2.el7            epel          103 k
2024-05-17T04:44:59.3378433Z  mono-extras            x86_64       6.8.0-2.el7            epel          463 k
2024-05-17T04:44:59.3378707Z  mono-mvc               x86_64       6.8.0-2.el7            epel          485 k
2024-05-17T04:44:59.3378977Z  mono-wcf               x86_64       6.8.0-2.el7            epel          921 k
2024-05-17T04:44:59.3379246Z  mono-web               x86_64       6.8.0-2.el7            epel          2.5 M
2024-05-17T04:44:59.3379518Z  mono-winforms          x86_64       6.8.0-2.el7            epel          1.6 M
2024-05-17T04:44:59.3379792Z  monodoc                x86_64       6.8.0-2.el7            epel           19 M
2024-05-17T04:44:59.3379880Z 
2024-05-17T04:44:59.3380015Z Transaction Summary
2024-05-17T04:44:59.3380219Z ================================================================================
2024-05-17T04:44:59.3380435Z Install  1 Package (+11 Dependent packages)
2024-05-17T04:44:59.3380519Z 
2024-05-17T04:44:59.3380677Z Total download size: 55 M
2024-05-17T04:44:59.3380837Z Installed size: 141 M
2024-05-17T04:44:59.3380993Z Downloading packages:
2024-05-17T04:44:59.7702624Z --------------------------------------------------------------------------------
2024-05-17T04:44:59.7703167Z Total                                              128 MB/s |  55 MB  00:00     
2024-05-17T04:44:59.7798050Z Running transaction check
2024-05-17T04:44:59.7911190Z Running transaction test
2024-05-17T04:44:59.8118296Z Transaction test succeeded
2024-05-17T04:44:59.8118950Z Running transaction
2024-05-17T04:45:00.1504310Z   Installing : libexif-0.6.22-2.el7_9.x86_64                               1/12 
2024-05-17T04:45:00.4366809Z   Installing : libgdiplus-2.10-10.el7.x86_64                               2/12 
2024-05-17T04:45:00.5309922Z   Installing : mono-data-sqlite-6.8.0-2.el7.x86_64                         3/12 
2024-05-17T04:45:00.7197884Z   Installing : mono-extras-6.8.0-2.el7.x86_64                              4/12 
2024-05-17T04:45:01.2447878Z   Installing : mono-winforms-6.8.0-2.el7.x86_64                            5/12 
2024-05-17T04:45:01.3241476Z   Installing : mono-data-6.8.0-2.el7.x86_64                                6/12 
2024-05-17T04:45:01.6029941Z   Installing : mono-mvc-6.8.0-2.el7.x86_64                                 7/12 
2024-05-17T04:45:01.7801151Z   Installing : mono-web-6.8.0-2.el7.x86_64                                 8/12 
2024-05-17T04:45:03.5491481Z   Installing : mono-wcf-6.8.0-2.el7.x86_64                                 9/12 
2024-05-17T04:45:05.6355835Z   Installing : mono-core-6.8.0-2.el7.x86_64                               10/12 
2024-05-17T04:45:05.6356479Z Mono Certificate Store Sync - version 6.8.0.123
2024-05-17T04:45:05.6356830Z Populate Mono certificate store from a concatenated list of certificates.
2024-05-17T04:45:05.6357358Z Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
2024-05-17T04:45:05.6357525Z

**Comment by directhex** [comment] 2024-05-17 17:51
> here is the head of the yum install for mono-devel package.

So it's not considering our repo at all - it's only finding the el7 packages (ours have xamarin in the version).

Try throwing in an explicit "yum update" before the "yum install", that should force it to refresh its metadata

**Comment by BrianMouncer** [comment] 2024-05-22 15:44
I can't tell if that resolved the package install problem, because it is working with or without the changes right now.
I can confirm that adding the yum update call does result in resolving the package version with xamaring in the version, so hopefully that will prevent future problems.

++ curl https://download.mono-project.com/repo/centos7-stable.repo
++ tee /etc/yum.repos.d/mono-centos7-stable.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   189  100   189    0     0   1016      0 --:--:-- --:--:-- --:--:--  1021
[mono-centos7-stable]
name=mono-centos7-stable
baseurl=https://download.mono-project.com/repo/centos7-stable/
enabled=1
gpgcheck=1
gpgkey=https://download.mono-project.com/repo/xamarin.gpg
++ **yum update -y -q**
++ yum install -y mono-devel
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.vcea.wsu.edu
 * epel: mirrors.xmission.com
 * extras: ziply.mm.fcix.net
 * updates: mirror.steadfastnet.com
Resolving Dependencies
--> Running transaction check
---> Package **mono-devel.x86_64 0:6.12.0.107-0.xamarin.9.epel7** will be installed
--> Processing Dependency: mono-data-oracle = 6.12.0.107 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono-core = 6.12.0.107 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono(Microsoft.Build.Tasks.Core) = 15.1.0.0 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono-winforms = 6.12.0.107 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono(Microsoft.Build.Utilities.Core) = 15.1.0.0 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono-data = 6.12.0.107 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono-web = 6.12.0.107 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono(Microsoft.Build.Framework) = 15.1.0.0 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono-extras = 6.12.0.107 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: mono(Mono.Profiler.Log) = 4.0.0.0 for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Processing Dependency: libgdiplus-devel for package: mono-devel-6.12.0.107-0.xamarin.9.epel7.x86_64
--> Running transaction check

**Comment by akoeplinger** [comment] 2024-05-27 12:10
Looks like it is working now so closing the issue, thanks!

**Closed by akoeplinger** 2024-05-27 12:10 UTC
