### ISSUE TITLE
LLVM 6.0 AOT assertion failure (linux)

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#8791] opened 2018-05-21 17:37 UTC
## Steps to Reproduce

1. Build monollvm 6.0 with  assertions enabled.
2. Build mono against monollvm 6.0.
3. make -C mcs/class/System.XML  run-test

### Current Behavior

CSC     [testing_aot_full] full_System.Xml_test.dll
/s/monollvm/lib/CodeGen/AsmPrinter/MonoException.cpp:643: virtual void llvm::MonoException::beginInstruction(const llvm::MachineInstr*): Assertion `0' failed.

### Expected Behavior

No assertion failures.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

Assert(0) should be avoided.
Use some other expression, like assert(index == foo.size()) here.

**Comment by vargaz** [comment] 2018-05-22 02:11
Can't reproduce this.

**Comment by imhameed** [comment] 2019-09-04 08:30
Just a note: I've encountered this specific assertion failure when using the LLVM 6 (and 9) JIT backend with assertions enabled.

**Comment by SamMonoRT** [comment] 2019-09-26 18:17
@SamMonoRT - one of the issues preventing upgrade to LLVM 9.0. Need this fixed. Work on this scheduled for early-mid October timeframe.

**Comment by vargaz** [comment] 2019-10-03 20:01
This should be fixed on the release_90-2 branch by:
https://github.com/mono/llvm/commit/69997c65e9d039b458ffc0059768e2fa6d47f03c

**Closed** 2019-10-23 18:26 UTC
Labels: area-Runtime: JIT
