### ISSUE TITLE
System.IO.Compression tests fail on iOS platforms

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#12356] opened 2019-01-10 16:07 UTC
We have started executing the tests from the test dlls that are present in the Mono SDK. In those dlls there are some tests that fail because the tests expect a file that is not present in the system. Please take a look at the new file https://github.com/xamarin/xamarin-macios/pull/5373 which states the ignored tests and the reason.

**Comment by akoeplinger** [comment] 2019-02-18 18:58
Duplicate of https://github.com/mono/mono/issues/12354

**Closed by akoeplinger** 2019-02-18 18:58 UTC
Labels: area-SDK: Packaging
