### ISSUE TITLE
iOS: interpreter asserts at launch in 32-bit mode (FIXME: ftnptr_arg page trampolines)

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#9871] opened 2018-08-03 14:47 UTC
## Steps to Reproduce

1. Checkout & build the `mono-2018-06` branch from xamarin-macios
2. Run `make -C tests runner`
3. Run the `mini/iOS Unified 32-bits - device/Debug (interpreter)` test.
4. Execute and run all the tests

### Current Behavior

    error: FIXME: ftnptr_arg page trampolines
    critical: Stacktrace:

    critical:   at <unknown> <0xffffffff>
    critical:   at (wrapper managed-to-native) object.__icall_wrapper_ves_icall_mono_delegate_ctor_interp (object,object,intptr) <0xffffffff>
    critical:   at System.Type..cctor () [0x00000] in /work/maccore/mono-master/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/type.cs:47
    critical:   at (wrapper runtime-invoke) object.runtime_invoke_direct_void (object,intptr,intptr,intptr) [0x0001e] in <7970bf545bef4c1da5f632987a90aac8>:0
    critical:   at <unknown> <0xffffffff>
    critical:   at ObjCRuntime.Runtime.Initialize (ObjCRuntime.Runtime/InitializationOptions*) [0x00000] in /work/maccore/mono-master/xamarin-macios/src/ObjCRuntime/Runtime.cs:189
    critical:   at (wrapper runtime-invoke) <Module>.runtime_invoke_direct_void_Runtime/InitializationOptions* (object,intptr,intptr,intptr) [0x00020] in <72b594d01e774b2db12fff9404c49d4d>:0
    Memory around native instruction pointer (0x20733c5c):

### Expected Behavior

No crash

**Comment by marek-safar** [comment] 2018-08-03 15:58
@BrzVlad could you look into that while Bernard is away?

**Comment by BrzVlad** [comment] 2018-08-03 16:21
I have untested code to fix this, but the reason it wasn't included was that interp + arm was not supported. I don't know if anything changed around that. I can fix this particular assert the other week (since I'll be FTO too), but I don't know if anything will work. @lewurm ?

**Comment by lewurm** [comment] 2018-08-03 16:50
32bit was never supported, so at least it isn't a regression. I can have a look after vacation; I do have a 32bit iOS device so I can test/debug it.

@BrzVlad please submit the PR that fixes the assert and mark it do-not-merge, I'll take it over from there.

**Comment by SamMonoRT** [comment] 2022-05-09 20:20
Closing this old mono\mono issue we haven't had a need to fix(or was already fixed and not marked correctly) that for 2+ years now. Please re-open if we need to revisit this again.

**Closed by SamMonoRT** 2022-05-09 20:20 UTC
Labels: area-Runtime: Interpreter
