### ISSUE TITLE
[msbuild] Xamarin.iOS.Tasks.NativeReferencesNoEmbedding fails on iOS

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#14876] opened 2019-06-07 14:09 UTC
After bumping mono to the latests 2019-02 (hash: c22486e39d129cb8117177a6f9c768e69fc4ebaa) the msbuild tests fail with:

`Xamarin.iOS.Tasks.NativeReferencesNoEmbedding("iPhoneSimulator").ShouldNotUnnecessarilyRebuildBindingProject(True): Binding project build did not create package?`

Full tests failure can be found here: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/10198/Test_20Report/

This is related with PR https://github.com/xamarin/xamarin-macios/pull/6221 which cannot be landed until this is fixed.

**Comment by radical** [comment] 2019-06-08 00:11
@mandel-macaque Can you reproduce this? I'm trying with the checkout from the PR, built with `./configure && make world` and running the tests with `make -C tests test-ios-tasks`. But it passes, the target runs as expected :/

**Comment by mandel-macaque** [comment] 2019-06-10 09:59
@radical the results are from the bots, might be that the min VSMac that we are using there is the real issue.

**Comment by mandel-macaque** [comment] 2019-06-10 15:29
We have reverted the max mono and tests pass: https://github.com/xamarin/xamarin-macios/pull/6221

**Comment by radical** [comment] 2019-06-10 20:00
I will open a PR and try to debug this on CI itself, since I can't reproduce this locally :/

**Comment by radical** [comment] 2019-06-11 02:06
This should be fixed with https://github.com/xamarin/xamarin-macios/pull/6238 as all the msbuild tests pass now.

**Closed by radical** 2019-06-11 02:06 UTC
Labels: area-Tools: msbuild, regression, target-xamarin-ios
