### ISSUE TITLE
XmlSerializer Leaving Nodes Serialized

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#16473] opened 2019-08-26 08:28 UTC
_From @AceCoderLaura on Mon, 26 Aug 2019 02:45:31 GMT_

### Steps to Reproduce

1. Use the below two files in a Xamarin.iOS project
#### AppDelegate.cs (Compile)
```
using Foundation;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.Serialization;
using System.Xml;
using System.Xml.Serialization;
using UIKit;
using Xamarin.Forms.Platform.iOS;

namespace Adapt.Presentation.iOS
{
    [Register("AppDelegate")]
    public class AppDelegate : FormsApplicationDelegate
    {
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            try
            {
                var stream = System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("Adapt.Presentation.Xivic.iOS.Some.xml");
                var reader = new StreamReader(stream);
                var doc = reader.ReadToEnd();
                var deserialized = DeserializeMyObject(doc);
                if (deserialized.Contents[0] is XmlNode[]) throw new Exception("Failed to deserialize.");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Debugger.Break();
            return true;
        }

        private static WhereList DeserializeMyObject(string markup)
        {
            var serializer = new XmlSerializer(typeof(WhereList));
            return (WhereList)serializer.Deserialize(new StringReader(markup));
        }
    }

    public class WhereList
    {
        public List<object> Contents { get; set; }
    }

    /// <summary>
    /// Represents a query Where Clause
    /// </summary>
    [XmlInclude(typeof(WhereClauseType))]
    [XmlInclude(typeof(List<string>))]
    [XmlInclude(typeof(int))]
    [XmlInclude(typeof(string))]
    [XmlInclude(typeof(decimal))]
    [XmlInclude(typeof(double))]
    [XmlInclude(typeof(bool))]
    public class WhereClause
    {
        public object LeftExpression { get; set; }

        public WhereClauseType WhereClauseType { get; set; } = WhereClauseType.Equals;

        public object RightExpression { get; set; }
    }

    /// <summary>
    /// The SQL Comparison operator to be used for the where clause expression
    /// </summary>
    [DataContract]
    public enum WhereClauseType
    {
        Is,
        Equals,
        Like
    }
}
```

#### Some.xml (EmbeddedResource)
```
<WhereList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Contents>
        <anyType xsi:type="WhereClause">
            <LeftExpression xsi:type="xsd:string">TaskInfo.StatusKey</LeftExpression>
            <WhereClauseType>Equals</WhereClauseType>
            <RightExpression xsi:type="xsd:string">[StatusDef].[CodeKey]</RightExpression>   
        </anyType>
    </Contents>
</WhereList>
```

### Expected Behavior
The xml is deserialized into the provided types

### Actual Behavior
The `WhereClause` object is returned as an array of `XmlNode`

#### Windows IDE
```
JetBrains Rider 2019.2.1
Build #RD-192.5895.1276, built on August 18, 2019
Licensed to Laura Bailey
You have a perpetual fallback license for this version
Subscription is active until August 13, 2020
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 12
Registry: ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.title.product=false, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, ide.borderless.title.project.path=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.borderless.title.classpath=false, ide.require.transaction.for.model.changes=false
Non-Bundled Plugins: CMD Support, CyclomaticComplexity, Key Promoter X, String Manipulation, Jetbrains TeamCity Plugin, cn.yiiguxing.plugin.translate, com.intellij.ideolog, com.jetbrains.darkPurpleTheme, mobi.hsz.idea.gitignore, nb-mind-map-idea, com.jetbrains.rider.android, org.intellij.plugins.markdown, izhangzhihao.rainbow.brackets, com.intellij.plugin.adernov.powershell, some.awesome, zielu.gittoolbox
```

#### Windows Toolset
```
Microsoft Visual Studio Professional 2019
Version 16.2.3
VisualStudio.16.Release/16.2.3+29215.179
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA095
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00611.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.2.290.48383
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.290.48383
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.2.290.48383
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.2.290.48383
Azure Functions and Web Jobs Tools

C# Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20626.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate SQL Prompt   9.5.7.10212
Write, format, and refactor SQL effortlessly

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.95 (d16-2@37df81894)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.0 (d16-2/ebd65c9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969


Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

#### Mac Toolset
```
=== Visual Studio Community 2019 for Mac ===

Version 8.2.2 (build 21)
Installation UUID: 118f31c7-04a5-44b5-b0a3-4058658af66d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.9
	2.1.8
	2.1.7
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.505
	2.1.504
	2.1.503
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-30 21:29:36 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802020021
Git revision: d2ffd09000c5d24a206b715b63d409e8e965689a
Build date: 2019-08-02 00:25:49+00
Build branch: release-8.2
Xamarin extensions: 4cc9cbbe68baaeb6bc654f36e057b1bd124f3f65

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

### Build Logs

[JetBrainsLog.ReSharperBuild_2019_08_26_02_42_35_4604.log](https://github.com/xamarin/xamarin-macios/files/3539227/JetBrainsLog.ReSharperBuild_2019_08_26_02_42_35_4604.log)

_Copied from original issue xamarin/xamarin-macios#6845_

**Comment by rolfbjarne** [comment] 2019-08-26 08:28
_From @rolfbjarne on Mon, 26 Aug 2019 08:26:27 GMT_

I can reproduce this with desktop mono, full sample:

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Text;
using System.Xml.Serialization;
using System.Xml;

class C {
	static int Main () {
		var xml = @"<WhereList xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
    <Contents>
        <anyType xsi:type=""WhereClause"">
            <LeftExpression xsi:type=""xsd:string"">TaskInfo.StatusKey</LeftExpression>
            <WhereClauseType>Equals</WhereClauseType>
            <RightExpression xsi:type=""xsd:string"">[StatusDef].[CodeKey]</RightExpression>
        </anyType>
    </Contents>
</WhereList>";

                var deserialized = DeserializeMyObject(xml);
                if (deserialized.Contents[0] is XmlNode[]) {
                	Console.WriteLine ("Failed to deserialize.");
                	return 1;
                } else {
                	Console.WriteLine ("Success!");
                	return 0;
                }
	}

        private static WhereList DeserializeMyObject(string markup)
        {
            var serializer = new XmlSerializer(typeof(WhereList));
            return (WhereList)serializer.Deserialize(new StringReader(markup));
        }
}

public class WhereList
{
    public List<object> Contents { get; set; }
}

/// <summary>
/// Represents a query Where Clause
/// </summary>
[XmlInclude(typeof(WhereClauseType))]
[XmlInclude(typeof(List<string>))]
[XmlInclude(typeof(int))]
[XmlInclude(typeof(string))]
[XmlInclude(typeof(decimal))]
[XmlInclude(typeof(double))]
[XmlInclude(typeof(bool))]
public class WhereClause
{
    public object LeftExpression { get; set; }

    public WhereClauseType WhereClauseType { get; set; } = WhereClauseType.Equals;

    public object RightExpression { get; set; }
}

/// <summary>
/// The SQL Comparison operator to be used for the where clause expression
/// </summary>
[DataContract]
public enum WhereClauseType
{
    Is,
    Equals,
    Like
}
```

outputs:

> Failed to deserialize.

```
$ mono --version
Mono JIT compiler version 6.4.0.169 (2019-06/4a855304725 Wed Aug 14 14:40:14 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by MaximLipnin** [comment] 2019-08-27 10:31
I've tried the desktop sample on windows (.net/core), macos (net core, mono 5.18.1 and the latest) and everywhere I got "Failed to deserialize." Did it use to work earlier?

**Comment by rolfbjarne** [comment] 2019-08-27 11:51
@AceCoderLaura did this work before? If so, when and where?

**Comment by AceCoderLaura** [comment] 2019-08-29 00:00
It worked pretty recently, I think it started happening when I updated Visual Studio. We suddenly noticed the problem when our application tried to send the deserialized object to the server via our communication layer which couldn't serialize the XmlNodes. We checked if anything in our codebase or database had changed and it hadn't so we figured it must be one of the dependencies which we narrowed down to the XmlSerializer.

**Comment by MaximLipnin** [comment] 2019-08-29 06:58
Could you please attach the versions of the product/frameworks where it worked?

**Comment by MaximLipnin** [comment] 2019-08-29 07:26
if you add `[XmlInclude(typeof(WhereClause))]` attribute to  `WhereList` class then it should work:
```
[XmlInclude(typeof(WhereClause))]
public class WhereList
{
    public List<object> Contents { get; set; }
}
```

**Comment by marek-safar** [comment] 2019-09-09 09:28
@AceCoderLaura could you confirm that it resolves your issue?

**Comment by msgpacket** [comment] 2020-01-11 00:12
We have just verified that our problem (above from @pat-clevest) is fixed as of Visual Studio 2019 for Mac, version 8.4 (build 2657)

**Comment by MaximLipnin** [comment] 2020-09-14 06:37
It looks like the original issue has been addressed so I'm closing it. Feel free to re-open if the problem isn't gone.

**Closed by MaximLipnin** 2020-09-14 06:37 UTC
Labels: area-BCL: System.Xml
