### ISSUE TITLE
[AOT] fix ordering in AOT image

### ISSUE THREAD

**Issue by lewurm** [mono/mono#13695] opened 2019-03-27 17:36 UTC
Consider

```csharp
using System;
using System.Runtime.CompilerServices;

class Program
{
        [MethodImplAttribute(MethodImplOptions.InternalCall)]
        protected static extern void MarkerStart();

        [MethodImplAttribute(MethodImplOptions.InternalCall)]
        protected static extern void MarkerEnd();

        [MethodImplAttribute(MethodImplOptions.InternalCall)]
        protected static extern void NativeTestMethodOverheads();

        [MethodImplAttribute(MethodImplOptions.InternalCall)]
        protected static extern void NativeTestMethodVoid_Bool(IntPtr obj, UInt64 nativePropertyHandle, bool newValue);


        public static void Main()
        {
                MarkerStart();
                MarkerEnd();

                MarkerStart();
                MarkerEnd();

                NativeTestMethodVoid_Bool(IntPtr.Zero, 0, true);
                NativeTestMethodVoid_Bool(IntPtr.Zero, 0, true);
        }
}
```
We load AOT methods from the image like this:
https://github.com/mono/mono/blob/6062fa39c3f51547c07f80da1a4d7e3b5d53dfba/mono/mini/aot-runtime.c#L4824-L4830
For the example above `info.nmethods = 7`, `info.nextra_methods = 4`,  and thus `num_methods = 3`. However, the `method_index` for `Main ()` is 4, so the lookup fails.

This regression was introduced by https://github.com/mono/mono/commit/6062fa39c3f51547c07f80da1a4d7e3b5d53dfba

/cc @lateralusX

**Comment by buggeststar** [comment] 2020-01-19 05:29
Any pending fix or workaround for this issue? On latest stable Mono build (6.8.0), when running in AOT full mode, this issue causes similar errors: "Attempting to JIT compile method '...' while running in aot-only mode".

**Comment by lateralusX** [comment] 2020-01-24 13:11
I have been running with a fix in cross compilers that just eliminated that check since it is not correct anymore:

---
 mono/mini/aot-runtime.c | 5 -----
 1 file changed, 5 deletions(-)

diff --git a/mono/mini/aot-runtime.c b/mono/mini/aot-runtime.c
index 74ae3053f77..9a1c7013055 100644
--- a/mono/mini/aot-runtime.c
+++ b/mono/mini/aot-runtime.c
@@ -4902,11 +4902,6 @@ mono_aot_get_method (MonoDomain *domain, MonoMethod *method, MonoError *error)
 	} else {
 		/* Common case */
 		method_index = mono_metadata_token_index (method->token) - 1;
-
-		guint32 num_methods = amodule->info.nmethods - amodule->info.nextra_methods;
-		if (method_index >= num_methods)
-			/* method not available in AOT image */
-			return NULL;
 	}
 
 	code = (guint8 *)load_method (domain, amodule, m_class_get_image (klass), method, method->token, method_index, error);
-- 

@lewurm see any problems of just getting rid of the check since it is not correct anymore?

**Comment by lewurm** [comment] 2020-04-27 08:29
@lateralusX not sure if this is gonna break AOT<>interp mixed mode.  could you make a PR, so this change gets some test coverage?

I think the check needs to be refined to something like "is an AOT method available for this method token"? This could probably be handled by `load_method` and propagated properly through `error` somehow.

**Comment by lateralusX** [comment] 2023-08-29 09:20
Won't fix in mono/mono.

**Closed by lateralusX** 2023-08-29 09:20 UTC
Labels: area-Runtime: AOT

**Comment by lateralusX** [comment] 2023-09-07 09:16
The code is still around with similar logic in dotnet/runtime, but we have not seen any repro's on dotnet/runtime and we changed a bunch around aot compiler over the years. No harm taking it over, but maybe we should first see if it reproduces in dotnet/runtime.
