### ISSUE TITLE
System.Runtime.CompilerServices.UnsafeTests.ReadWriteDoublePointer test failure on devices in Xamarin.iOS

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#14872] opened 2019-06-07 10:59 UTC
## Steps to Reproduce

1. Clone https://github.com/xamarin/xamarin-macios
2. Checkout mono-2019-06 branch at 9209b4eb49bb59906500fd9baafd7d27cb74dd1b
3. `./configure --enable-xamarin && make world`
4. `make -C tests runner`
5. Run any **Debug** configuration in `[xUnit] Mono BCL tests group 3` under `iOS Unified 64-bits - device`
6. Observe test failure

Not that this only happens on devices and only in the Debug configuration!

### Current Behavior

```
  Test name: System.Runtime.CompilerServices.UnsafeTests.ReadWriteDoublePointer
   Exception messages: Assert.Equal() Failure
Expected: 20
Actual:   10
   Exception stack traces:   at System.Runtime.CompilerServices.UnsafeTests.ReadWriteDoublePointer () [0x00020] in /Users/alexander/dev/xamarin-macios/xamarin-macios/external/mono/external/corefx/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs:96 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Users/alexander/dev/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
```

### Expected Behavior

No failure

## On which platforms did you notice this

[ x ] macOS
[ ] Linux
[ ] Windows

**Version Used**: 2019-06

**Comment by marek-safar** [comment] 2019-06-11 17:11
@SamMonoRT could you assign this issue

**Comment by vargaz** [comment] 2019-06-12 21:11
Desktop testcase:
```
using System;
using System.Threading;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

public class Tests
{
	public unsafe static int Main (String[] args) {
		int value1 = 10;
		int value2 = 20;
		int* valueAddress = (int*)Unsafe.AsPointer(ref value1);
		int** valueAddressPtr = &valueAddress;
		Unsafe.Write(valueAddressPtr, new IntPtr(&value2));

		Console.WriteLine ("X1: " + *(*valueAddressPtr));
		return 0;
	}
}
```

mono bug.exe
X1: 20

mono -O=-inline bug.exe
X1: 10

mono -O=-alias-analysis,-inline bug.exe
X1: 20

It looks like the problem is in the alias-analysis pass.

**Comment by vargaz** [comment] 2019-06-12 21:12
It happens in debug mode on ios which disables inlining.

**Comment by BrzVlad** [comment] 2019-06-12 21:15
@vargaz thanks for the repro. Are you looking into this bug or I can take it ?

**Comment by mandel-macaque** [comment] 2019-06-14 08:37
This also happens on tvOS devices. But I'm not surprise since it happens on iOS too.

**Comment by mandel-macaque** [comment] 2019-06-14 08:46
Interestingly on the apple tvOS the test does pass on  SDK framework (release)

**Comment by lewurm** [comment] 2019-06-14 13:41
> Interestingly on the apple tvOS the test does pass on SDK framework (release)

Release uses LLVM

**Comment by marek-safar** [comment] 2019-06-17 12:54
@BrzVlad any update on this issue?

**Comment by vargaz** [comment] 2019-06-17 13:03
Its a problem in the JITs alias analysis pass.

**Closed** 2019-06-20 18:41 UTC
Labels: area-Runtime: AOT, regression, target-xamarin-ios
