### ISSUE TITLE
[sgen] Improve sgen-tarjan-bridge assertions 

### ISSUE THREAD

**Issue by kumpera** [mono/mono#9314] opened 2018-06-26 14:04 UTC
We recently got a report of the following assert:

```
F/        (13301): * Assertion at /Users/builder/jenkins/workspace/xamarin-android-d15-7/xamarin-android/external/mono/mono/metadata/sgen-tarjan-bridge.c:1140, condition `xref_count == xref_index' not met
```

There's nothing we can do about this without a repro. What we can do is improve assertion to include details on xref_count and xref_index. Plus do some code review of the code around it.

**Comment by lewurm** [comment] 2018-06-27 21:46
https://github.com/mono/mono/pull/9341

**Comment by davidjohnoliver** [comment] 2018-10-25 18:16
> There's nothing we can do about this without a repro.

In case you're not aware, there's [a repro](https://drive.google.com/file/d/0B7De5DfDEi--QlJEN29xNjhDZGc/view) linked in reactiveui/ReactiveUI#1379. I'm not the author of that issue but I tested the repro (Samsung Galaxy A5, Xamarin.Android 9.1.0.29) and can confirm that it crashes with the above assert message.

We've encountered this problem in several large Uno apps, unfortunately only in very narrow circumstances that I haven't been able to repro in a shareable sample, but seemingly associated with creating a lot of managed+native GC pressure.

**Comment by deakjahn** [comment] 2018-12-19 23:59
Same here. In a concrete app, after some UI manipulations, certainly not something that can be reproed easily. Considering that it's GC, couldn't it be changed to a warning rather than a crash? Some memory leak is still better than completely bringing down an applicaiton...

**Comment by claudioredi** [comment] 2019-06-17 13:43
We're getting hundred of crashes per week related to this assert in a relatively big app.

Is moving from `Tarjan` to `New` algorithm something that it's worth to try? It's very hard to understand what triggers this since this happens mostly on the wild in random circumstances.

**Comment by BrzVlad** [comment] 2019-06-19 11:21
@claudioredi Yes, you should be fine. We switched the default from new to tarjan about 2 years ago.

**Comment by jeromelaban** [comment] 2019-06-19 13:25
The "new" bridge is hurting the GC performance very significantly... this issue is still very active and is impacting somewhat recent devices.

**Comment by claudioredi** [comment] 2019-06-19 13:32
@jeromelaban It definitively seems to be affecting new devices (or newer Android versions) more. 

So you would not recommend moving to `New` algorithm even if we have hundred of this crashes per week?

**Comment by jeromelaban** [comment] 2019-06-19 13:34
@claudioredi it really depends on the performance impact you're getting... The repro provided here is pretty consistent, so it's a matter of choosing between to bad behaviors for enduser experience :(

**Comment by claudioredi** [comment] 2019-06-19 13:37
Thanks @jeromelaban. The only benchmark I found comparing the different GC strategies is this one https://devblogs.microsoft.com/xamarin/xamarin-android-garbage-collection-improvements/

It's old and I'm sure that's not the source of the final and universal truth but the difference in there between `New` and `Tarjan` seems to be minimal.

**Comment by pmahend1** [comment] 2019-11-07 13:03
Getting the same issue while using `ConcurrentStack` along with `ParallelTask`

**Comment by BrzVlad** [comment] 2020-01-08 13:39
Reliably reproduced this issue using the repro from ReactiveUI. Applying the fix for another tarjan bridge bug (https://github.com/mono/mono/commit/376c46bcf3bc101fba85a402914d60c6bda70e75) fixed the crash for me.

**Closed by BrzVlad** 2020-01-08 13:39 UTC
Labels: area-Runtime: GC

**Comment by davidjohnoliver** [comment] 2020-01-09 02:38
Thanks @BrzVlad , great news!

**Comment by ryanholden8** [comment] 2020-02-12 19:57
Wanted to say thank you for finding a fix for this issue! We are experiencing this issue. It is holding us back us back from moving forward with an app release since the crashes can happen several times a day.

Is there someway of knowing when this will be released to `Xamarin.Android`? It looks like this fix is on the `master` branch where as [Xamarin.Android 10.2](https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.2#mono-framework-version-update-to-68) is pulling it's mono runtime from the `2019-10` branch. Is there documentation somewhere on how to understand the release process with these PRs?

**Comment by BrzVlad** [comment] 2020-02-12 20:16
We branch every two months. The first branch containing the fix is 2020-02. Having xamarin android use this branch would take 1-2 months. After that, I'm not sure, but probably a similar amount of time to have the new xamarin android in the preview release.

I'm not sure why this issue is a blocker. Using the **_new_** bridge implementation should work fine. Do you have problems also with the **_new_** bridge ?

**Comment by ryanholden8** [comment] 2020-02-12 21:03
@BrzVlad - Thanks for the quick reply. That's a good point about switching the CG implementations. From reading the comments above, it sounded like the performance impact was large. Our target devices have low resources. But it's definitely worth testing out! Will report back. Thanks again!

**Comment by BrzVlad** [comment] 2020-02-12 21:09
Of course it would be better to use the tarjan bridge but I wouldn't worry too much about it. It was the default up until a few years ago. It is not some debug, workaround fallback, just the previous, less optimized, version.

**Comment by pmahend1** [comment] 2020-02-12 23:00
Setting GC to new bridge does work fine. I am not sure benchmarking between the two though.

**Comment by zoli13** [comment] 2020-03-04 11:18
Had exactly the same issue with a simple project (open an rg.popup with a single collectionview with 260 images, close, open, close...and crash with tarjan assert: `xref_count == xref_index`
Adding `MONO_GC_PARAMS=bridge-implementation=new` to Android environment fixed it (at least so far it seems)

**Comment by Deepfreezed** [comment] 2020-03-30 13:42
I am still getting this error on tarjan-bridge. Using the latest Xamarin version available (10.2.0.100). I can easily reproduce this by keep switching Xamarin Forms Shell Tabs, eventually it will error out. Current solution is to use 'new bridge' mentioned above. 

Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mono/metadata/sgen-tarjan-bridge.c:1140, condition `xref_count == xref_index' not met, function:processing_build_callback_data, xref_count is 119 but we added 117 xrefs

Fatal signal 6 (SIGABRT), code -6 in tid 27694 (.mobile.android)

**Comment by BrzVlad** [comment] 2020-03-30 19:05
The fix is not in 10.2 nor in the 10.3 preview, it will be in the following version.

**Comment by Deepfreezed** [comment] 2020-03-31 20:10
@BrzVlad Thanks for the info.

**Comment by brendanzagaeski** [comment] 2020-04-08 20:34
*Release status update*

The latest Preview version of Xamarin.Android 10.3.0.33 now uses the newer Mono Framework version that includes this fix. Specifically, mono/mono@376c46bcf3bc101fba85a402914d60c6bda70e75 is now present in Xamarin.Android 10.3.0.33, which uses the Mono runtime and class libraries from mono/mono@d90665a422e9f8d015585b3ca381d74faa033cc4.

The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.3.0.33

Fix included on Windows in Visual Studio 2019 version 16.6 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.6 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment] 2020-05-20 00:44
*Release status update*

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.3.1.0.

Fix included on Windows in Visual Studio 2019 version 16.6. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by BrzVlad** [comment] 2023-05-02 06:46
@oharkins Is this a reliable crasher ? Any change for a project reproducing this ?

**Comment by marcojak** [comment] 2023-05-20 10:05
Having the same issue again with Visual Studio 17.6 and Xamarin.Android 13.2.0.6

**Comment by pubudulk** [comment] 2024-10-08 09:38
This issue seems to be reproduced in latest Android.Xamarin versions also.
Created a new ticket https://github.com/dotnet/android/issues/9377

**Comment by pubudulk** [comment] 2024-10-08 09:39
> Having the same issue again with Visual Studio 17.6 and Xamarin.Android 13.2.0.6

Have you found any solution for this please?
