### ISSUE TITLE
Profiler cannot report the path to root which is keeping an object alive

### ISSUE THREAD

**Issue by alanmcgovern** [mono/mono#8461] opened 2018-04-26 09:21 UTC
## Steps to Reproduce

1. Profile VSM and open/close a xaml file multiple times

### Current Behavior

XamlPreviewWidget is not being GC'ed *and* the profiler does not show the path to the root which is keeping it alive.

### Expected Behavior

XamlPreviewWidget is not being GC'ed *and* the profiler *should* show the path to the root which is keeping it alive.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

5.12.0.222

**Comment by alanmcgovern** [comment] 2018-04-26 10:29
NOTE: I tried with the xamarin profiler and also dkarlas's krofiler and both were unable to explain why the object was alive. That's why i think this is a mono bug.

**Comment by abock** [comment] 2019-09-24 13:27
@marek-safar any chance we could get someone to look into this? We are pretty sure the editor is in a similar situation with objects not getting GC'd and the profiler is not revealing paths to roots.

**Comment by BrzVlad** [comment] 2019-09-26 17:42
duplicate of https://github.com/mono/mono/issues/16996

**Closed by BrzVlad** 2019-09-26 17:42 UTC
Labels: area-Profiler
