### ISSUE TITLE
Runtime crash when debugging async code

### ISSUE THREAD

**Issue by jbevain** [mono/mono#19125] opened 2020-03-04 17:48 UTC
## Steps to Reproduce

1. Compile:

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

namespace StepOverAwait
{
	public interface IMessage
	{
	}

	public class Request : IMessage
	{
	}

	public class Reply : IMessage
	{
	}

	public class CallResult<T>
		where T : IMessage
	{
		public readonly T result;
		public CallResult(T result) => this.result = result;
	}

	public interface ICallInvoker
	{
		Task<CallResult<TReply>> InvokeAsync<TRequest, TReply>(TRequest request)
			where TRequest : IMessage, new()
			where TReply : IMessage, new();
	}

	public class CallInvoker : ICallInvoker
	{
		public async Task<CallResult<TReply>> InvokeAsync<TRequest, TReply>(TRequest request)
			where TRequest : IMessage, new()
			where TReply : IMessage, new()
		{
			await Task.Delay(1000); //if you debug and step over this, unity will crash
			return new CallResult<TReply>(new TReply());
		}
	}

	class MainClass
	{
		CancellationTokenSource cts = new CancellationTokenSource();
		ICallInvoker invoker;
		Task taskB;

		bool done;

		void Awake()
		{
			invoker = new CallInvoker();
			taskB = MethodAsync();
		}

		void Update()
		{
			if (taskB.IsCompleted)
			{
				Console.WriteLine("success");
				done = true;
			}
		}

		public static void Main(string[] args)
		{
			Console.WriteLine("Hello World!");

			var c = new MainClass();
			c.Awake();

			while (!c.done)
			{
				Thread.Sleep(1000 / 60);
				c.Update();
			}
		}

		async Task<int> MethodAsync()
		{
			var reply = await invoker.InvokeAsync<Request, Reply>(new Request());
			await Task.Delay(5);
			return 0;
		}
	}
}
```

2. Put a breakpoint on the line that reads:

`			await Task.Delay(1000); //if you debug and step over this, unity will crash`

3. Run under the debugger, hit the breakpoint, step over.

### Current Behavior

Runtime crash in `get_this_async_id`

```
* Assertion at debugger-agent.c:4547, condition `is_ok (error)' not met, function:get_this_async_id, Could not execute the method because the containing type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[StepOverAwait.CallResult`1[TReply_REF]]', is not fully instantiated. assembly:<unknown assembly> type:<unknown type> member:(null)
```

### Expected Behavior

No crash.

## On which platforms did you notice this

[X] macOS
[] Linux
[X] Windows

**Version Used**:

6.6.0.166 (2019-08/d9001b5ae70 Wed Feb 12 19:20:16 EST 2020)

**Comment by lambdageek** [comment] 2020-03-04 18:17
Probably fixed by https://github.com/mono/mono/pull/17727, 
Looks like a duplicate of https://github.com/mono/mono/issues/17549

**Comment by thaystg** [comment] 2020-03-06 04:40
Yes, it was the same case. 
I've tested and I'll close the issue.

**Closed by thaystg** 2020-03-06 04:40 UTC
Labels: area-Debugger
