### ISSUE TITLE
Memory leak getting web pages when AutomaticDecompression is on

### ISSUE THREAD

**Issue by smr888** [mono/mono#15780] opened 2019-07-22 13:52 UTC
This test loops over a set of websites and gets their home pages.  When AutomaticDecompression on the HttpWebRequest object is set to allow gzip and deflate, a memory leak occurs.  I suspect this leak is happening when exceptions are thrown on the requests, but I don't know that for certain.  This test program encounters many more exceptions than our production code does, and its memory usage grows much faster.  I think there's a correlation between those two facts.

Commenting out the AutomaticDecompression line seems to stop the program from leaking, so I'm pretty sure the bug is in the decompression code somewhere.  Possibly it is not cleaning up properly when exceptions are thrown.

## Steps to Reproduce

1. Ubuntu 18.04, Mono 6.0.0.313, MonoDevelop 7.8.4 (build 2)

2. Compile and run the program below under the profiler, e.g.
mono --gc=sgen --profile=log:heapshot=50gc TestMemGrow.exe

3. Wait 10 minutes or so and view the profiler output with:

mprof-report --traces output.mlpd > out.txt

You should see a list of allocations of System.Byte[] that grows increasingly larger, across several classes.  In my testing I saw things like this:

Heap shot 3 at 202.083 secs: size: 10162088, object count: 55536, class count: 483, roots: 332326
	     Bytes      Count  Average Class name
	   5950320        861     6910 System.Byte[] (bytes: +1670352, count: +225)
		1404 root references (0 pinning)
		248 references from: Mono.Net.Security.BufferOffsetSize2
		192 references from: System.Net.WebRequestStream
		177 references from: System.Net.BufferOffsetSize
		129 references from: System.IO.Compression.DeflateStreamNative
…
Heap shot 7 at 527.855 secs: size: 20584392, object count: 101442, class count: 482, roots: 345181
	     Bytes      Count  Average Class name
	  13148384       1856     7084 System.Byte[] (bytes: +1660480, count: +241)
		1410 root references (0 pinning)
		552 references from: Mono.Net.Security.BufferOffsetSize2
		461 references from: System.Net.WebRequestStream
		422 references from: System.Net.BufferOffsetSize
		305 references from: System.IO.Compression.DeflateStreamNative
…
	Heap shot 11 at 839.110 secs: size: 31195824, object count: 146593, class count: 482, roots: 385828
	     Bytes      Count  Average Class name
	  20590992       2859     7202 System.Byte[] (bytes: +1858160, count: +242)
		1529 root references (0 pinning)
		870 references from: Mono.Net.Security.BufferOffsetSize2
		732 references from: System.Net.WebRequestStream
		666 references from: System.Net.BufferOffsetSize
		478 references from: System.IO.Compression.DeflateStreamNative
…
	Heap shot 15 at 1145.841 secs: size: 41837128, object count: 192620, class count: 482, roots: 387798
	     Bytes      Count  Average Class name
	  28016304       3881     7218 System.Byte[] (bytes: +1872896, count: +256)
		1500 root references (0 pinning)
		1186 references from: Mono.Net.Security.BufferOffsetSize2
		1008 references from: System.Net.WebRequestStream
		921 references from: System.Net.BufferOffsetSize
		654 references from: System.IO.Compression.DeflateStreamNative

**CODE:**

```C#
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Threading;


namespace TestMemGrow
{
    class Program
    {
        static void Main()
        {
            List<string> websites = new List<string>() { "http://www.amazon.com", "http://www.google.com", "http://www.yahoo.com", "http://www.ebay.com", "http://www.overstock.com",
                "http://www.marketwatch.com", "http://www.bn.com", "http://www.newegg.com", "http://www.wsj.com", "http://www.arstechnica.com", "http://www.slashdot.org",
                "http://www.mediaite.com", "http://www.disqus.com", "http://www.twitter.com", "http://www.snap.com", "http://www.facebook.com", "http://www.usps.com",
                "http://www.ups.com", "http://www.techcrunch.com", "http://www.oracle.com", "http://www.java.com", "http://www.apple.com", "http://www.microsoft.com",
                "http://www.ibm.com", "http://www.dell.com", "http://www.asus.com", "http://www.gigabyte.com", "http://www.intel.com", "http://www.crucial.com",
                "http://www.westerndigital.com", "http://www.samsung.com", "http://www.sandisk.com", "http://www.brother.com", "http://www.hp.com",
                "http://www.msn.com", "http://www.disney.com", "http://www.nintendo.com", "http://www.twitter.com", "http://www.youtube.com",
                "http://www.instagram.com", "http://www.linkedin.com", "http://www.wordpress.org", "http://www.pinterest.com", "http://www.wikipedia.org",
                "http://www.blogspot.com", "http://www.adobe.com", "http://www.tumblr.com", "http://www.vimeo.com", "http://www.flickr.com", "http://www.godaddy.com",
                "http://www.buydomains.com", "http://www.reddit.com", "http://www.w3.org","http://www.nytimes.com", "http://www.statcounter.com",
                "http://www.weebly.com","http://www.blogger.com","http://www.github.com", "http://www.jimdo.com", "http://www.myspace.com",
                "http://www.mozilla.org", "http://www.gravatar.com", "http://www.theguardian.com", "http://www.bluehost.com", "http://www.cnn.com", "http://www.foxnews.com",
                "http://www.msnbc.com", "http://www.wix.com", "http://www.paypal.com","http://www.stumbleupon.com", "http://www.digg.com","http://www.huffingtonpost.com",
                "http://www.feedburner.com", "http://www.imdb.com","http://www.yelp.com","http://www.dropbox.com", "http://www.baidu.com","http://www.washingtonpost.com",
                "http://www.slideshare.net","http://www.etsy.com","http://www.telegraph.co.uk", "http://www.about.com", "http://www.bing.com", "http://www.latimes.com",
                "http://www.tripadvisor.com","http://www.opera.com", "http://www.live.com", "http://www.wired.com", "http://www.bandcamp.com"};

            while (true)
            {
                foreach (string website in websites)
                {
                    try
                    {
                        GC.Collect();
                        Console.WriteLine("Getting " + website);
                        HttpWebRequest request = (HttpWebRequest)WebRequest.Create(website);
                        request.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
                        using (HttpWebResponse response = request.GetResponse() as HttpWebResponse)
                        {
                            using (StreamReader reader = new StreamReader(response.GetResponseStream()))
                            {
                                File.WriteAllText("florb.txt", reader.ReadToEnd());
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Caught exception " + ex.ToString());
                    }
                    Thread.Sleep(1000);
                }
            }
        }
    }
}
```

### Current Behavior

Memory use grows, System.Byte[] allocations grow.

### Expected Behavior

GC should clean these up and memory use should not grow.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 6.0.0.313 (tarball Sun Jul 14 09:57:59 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by baulig** [comment] 2019-07-22 21:05
Didn't we thoroughly investigate and fix that last time you reported it?

Duplicate of https://github.com/mono/mono/issues/8689.

**Comment by smr888** [comment] 2019-07-22 21:05
The last version didn't have the AutomaticDecompression enabled.  Same test program structure, but different bug.

**Closed by baulig** 2019-07-22 21:05 UTC
Labels: area-BCL: System

**Comment by baulig** [comment] 2019-07-22 21:48
There is already a lot of useful info in that other issue, so I reopened that one.

**Comment by wildbunny** [comment] 2020-04-24 11:48
Why is this closed? This is still happened exactly as described in the OP on the latest stable mono (6.8.0.105) on linux.

**Comment by smr888** [comment] 2020-04-24 12:05
Thanks for confirming this problem. Rather than continue on this bug, which I believe to be distinct from the one I had reported previously, [#8689](https://github.com/mono/mono/issues/8689), the decision was made to re-open that bug.

Since it was re-opened, I added to [#8689](https://github.com/mono/mono/issues/8689) a description of a workaround for this that has worked fine for us, which is to do the decompression manually as required rather than relying on the AutomaticDecompression. Since we had a fix I haven't worried about this.

**Comment by wildbunny** [comment] 2020-04-24 12:13
Thanks for the pointer - its a bit more difficult for me to implement your suggestion as I'm using 3rd party library to actually do the webrequest, could really do with this being fixed, or at least a pointer to where the fault is so I can fix it locally in the mono source and rebuild it

**Comment by smr888** [comment] 2020-04-24 12:24
Hmmm . . . well, since your third party library will be having this problem for all of its customers, maybe you can get them to implement the workaround. It seems like it would be in their interest to do so.
