### ISSUE TITLE
Native assertion failure when Npgsql is trying to execute command

### ISSUE THREAD

**Issue by Marshal313** [mono/mono#9897] opened 2018-08-06 08:08 UTC
## Note
I got this exception when trying to execute a command using Npgsql (Postgres database access library), But the exception is thrown from Mono Runtime and is not related to Npgsql. Though, I mention the steps I took to reproduce the error, using Npgsql .

## Steps to Reproduce
1. Given that PostgreSQL is installed and a database is present, add Npgsql through Nuget
2. As described in [Here](https://www.npgsql.org/doc/index.html), try to execute a command

### Expected Behavior
The command should be executed and returned with a result.

### Current Behavior
Somewhere along the way, Mono runtime throws [This exception](https://github.com/npgsql/npgsql/files/2261156/Exception.txt).

```
* Assertion at local-propagation.c:562, condition `ins->opcode > MONO_CEE_LAST' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper dynamic-method) object.lambda_method (System.Runtime.CompilerServices.Closure,Npgsql.TypeHandling.NpgsqlTypeHandler,object,Npgsql.NpgsqlLengthCache&,Npgsql.NpgsqlParameter) [0x00032] in <2c1e745790d7412db8f8fdd869d65478>:0
  at Npgsql.TypeHandling.NpgsqlTypeHandler`1<TDefault_REF>.ValidateObjectAndGetLength (object,Npgsql.NpgsqlLengthCache&,Npgsql.NpgsqlParameter) [0x00000] in C:\projects\npgsql\src\Npgsql\TypeHandling\NpgsqlTypeHandler`.cs:198
  at Npgsql.NpgsqlParameter.ValidateAndGetLength () [0x00034] in C:\projects\npgsql\src\Npgsql\NpgsqlParameter.cs:551
  at Npgsql.NpgsqlCommand.ValidateParameters () [0x00040] in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:800
  at Npgsql.NpgsqlCommand/<ExecuteDbDataReader>d__100.MoveNext () [0x0005c] in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1140
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<System.Data.Common.DbDataReader>.Start<Npgsql.NpgsqlCommand/<ExecuteDbDataReader>d__100> (Npgsql.NpgsqlCommand/<ExecuteDbDataReader>d__100&) [0x0002c] in /run/build/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Npgsql.NpgsqlCommand.ExecuteDbDataReader (System.Data.CommandBehavior,bool,System.Threading.CancellationToken) [0x0003d] in <65006cd395a3455e9c14c68dc5c8974f>:0
  at Npgsql.NpgsqlCommand/<ExecuteNonQuery>d__92.MoveNext () [0x00015] in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1042
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<int>.Start<Npgsql.NpgsqlCommand/<ExecuteNonQuery>d__92> (Npgsql.NpgsqlCommand/<ExecuteNonQuery>d__92&) [0x0002c] in /run/build/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Npgsql.NpgsqlCommand.ExecuteNonQuery (bool,System.Threading.CancellationToken) [0x00037] in <65006cd395a3455e9c14c68dc5c8974f>:0
  at Npgsql.NpgsqlCommand.ExecuteNonQuery () [0x00000] in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1025
  at TEMP.NpgSqlTest.Start (System.Threading.CancellationToken) [0x00055] in /mnt/ssd/Workstation/VFC/Projects/TEMP/NpgSqlTest.cs:32
  at TEMP.NpgSqlTest.Main () [0x00024] in /mnt/ssd/Workstation/VFC/Projects/TEMP/NpgSqlTest.cs:19
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) [0x0004d] in <2c1e745790d7412db8f8fdd869d65478>:0
```

### Stack Trace
It's the same file in the last link above : [Exception.txt](https://github.com/npgsql/npgsql/files/2261156/Exception.txt).

## On which platforms did you notice this
[ ] macOS
[ Xubuntu 18.04 ] Linux
[ ] Windows

**mono --version**
```
Mono JIT compiler version 5.12.0.301 (tarball Wed Jul 25 15:43:48 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

## Other Details
Prior to here, I opened [This issue](https://github.com/npgsql/npgsql/issues/2098) on Npgsql repository, The conclusion was that this is a Mono Runtime issue and needs to be moved here.

**Comment by lewurm** [comment] 2018-08-23 17:37
I tried to reproduce this on `macOS` with `5.12.0.305`, but your provided program outputs:
```
MONO_PATH=./System.Runtime.CompilerServices.Unsafe.4.5.0/lib/netstandard2.0/:./Npgsql.4.0.2/lib/netstandard2.0:./System.Threading.Tasks.Extensions.4.5.0/lib/portable-net45+win8+wp8+wpa81/ mono --debug NpgSqlTest.exe
NonQuery Result : 1
```
So I can't reproduce your issue. I'm assuming there is nothing special about the table your program is inserting to; I created it like this:
```sql
create table "auth.users" (username varchar(255), phoneNumber varchar(255));
```

So it could be related that it's running on Linux, but I doubt that. `Exception.txt` contains a native stack trace; unfortunately you haven't installed the debug symbols for mono. Could you install it via `apt-get install mono-runtime-dbg` and run your repro again?

**Comment by lewurm** [comment] 2018-08-23 19:20
likely a duplicate of https://github.com/mono/mono/issues/8811
I'm closing this for now.

**Closed by lewurm** 2018-08-23 19:20 UTC
Labels: area-Runtime: JIT
