### ISSUE TITLE
getting started/mono basics page appears to be quite out of date

### ISSUE THREAD

**Issue by vigilancetech-com** [mono/mono#8699] opened 2018-05-14 08:31 UTC
## Steps to Reproduce

1. On a linux machine install docker and mono image
2. csc tlstest.cs -r:System.dll
Microsoft (R) Visual C# Compiler version 2.6.0.62309 (d3f6b8e7)
Copyright (C) Microsoft Corporation. All rights reserved.

tlstest.cs(169,3): warning CS0618: 'ServicePointManager.CertificatePolicy' is obsolete: 'Use ServerCertificateValidationCallback instead'
tlstest.cs(199,22): warning CS0618: 'Dns.Resolve(string)' is obsolete: 'Use GetHostEntry instead'

3. mono hello.exe

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.XplatUI' threw an exception. ---> System.ArgumentNullException: Could not open display (X-Server required. Check your DISPLAY environment variable)
Parameter name: Display
  at System.Windows.Forms.XplatUIX11.SetDisplay (System.IntPtr display_handle) [0x00408] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.XplatUIX11..ctor () [0x00077] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.XplatUIX11.GetInstance () [0x00019] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.XplatUI..cctor () [0x00066] in <b0eb38f42f1041219336663febc755f3>:0 
   --- End of inner exception stack trace ---
  at System.Windows.Forms.Theme.get_MenuAccessKeysUnderlined () [0x00000] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.SystemInformation.get_MenuAccessKeysUnderlined () [0x00005] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.Control..ctor () [0x000e4] in <b0eb38f42f1041219336663febc755f3>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control..ctor()
  at System.Windows.Forms.WindowsFormsSynchronizationContext..cctor () [0x00000] in <b0eb38f42f1041219336663febc755f3>:0 
   --- End of inner exception stack trace ---
  at System.Windows.Forms.Control..ctor () [0x00014] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.ScrollableControl..ctor () [0x00000] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.ContainerControl..ctor () [0x0000e] in <b0eb38f42f1041219336663febc755f3>:0 
  at System.Windows.Forms.Form..ctor () [0x00012] in <b0eb38f42f1041219336663febc755f3>:0 
  at HelloWorld..ctor () [0x00000] in <ceec6debc160448bb9258c23369192ea>:0 
  at (wrapper remoting-invoke-with-check) HelloWorld..ctor()
  at HelloWorld.Main () [0x00001] in <ceec6debc160448bb9258c23369192ea>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializa

4.  I did export DISPLAY=:0.0 and still nothing

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment] 2018-05-14 13:02
Duplicate of #8214

**Closed by marek-safar** 2018-05-14 13:02 UTC
