### ISSUE TITLE
Improper symlink for System.Runtime.Serialization.Formatters.Soap.dll?

### ISSUE THREAD

**Issue by The-BigDaddy** [mono/mono#10025] opened 2018-08-10 16:17 UTC
### Description

So I've been trying to get more into .NET Core/Mono by looking into the Fsharp [Saturn Web Framework][https://github.com/SaturnFramework/Saturn]. I was following [their getting started guide](https://saturnframework.org/docs/guides/how-to-start/) and it requires FAKE. On running the `./build.sh` I get this error.

```
This runner is now obsolete with FAKE 5, please upgrade to the new .Net Core runner. See https://fake.build/fake-migrate-to-fake-5.html
To remove this warning you can append the '--removeLegacyFakeWarning' argument or set the 'FAKE_NO_LEGACY_WARNING' environment variable to 'true'
FsiEvaluationSession could not be created.


error FS0229: Error opening binary file '/usr/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll': Could not find file "/usr/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll"



error FS3160: Problem reading assembly '/usr/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll': Processing of a script fragment has stopped because an exception has been raised


Build failed.
Error:
Error while creating a fsi session.
InnerException:
Error creating evaluation session: StopProcessingExn None

```

However I can find the missing DLL with `sudo find / -type f -name "*System.Runtime.Serialization*" -iname "*.dll" 2>/dev/null` in several places

- `/usr/lib/mono/4.5-api/System.Runtime.Serialization.Formatters.Soap.dll`

- `/usr/lib/mono/4.5.1-api/System.Runtime.Serialization.Formatters.Soap.dll`

- `/usr/lib/mono/4.5.2-api/System.Runtime.Serialization.Formatters.Soap.dll`

- etc. etc. for each API version until 4.7.1

So what I'm assuming is that `System.Runtime.Serialization.Formatters.Soap.dll` is symlinked and running `la /usr/lib/mono/4.5` reveals this

```
lrwxrwxrwx 1 root root  126 Jul 29 10:02 System.Runtime.Serialization.Formatters.Soap.dll -> ../gac/System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Serialization.Formatters.Soap.dll
 ```

But running `la /usr/lib/mono/gac/System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a/` returns `total 0`. So nothing is in that folder.

So should I symlink the file found in the `/usr/lib/mono/4.5.2-api` to `/usr/lib/mono/4.5` as a work aroud? Or it is a possible build issue with my Linux distros package?

### Relavent info

- Distro: Void Linux

- `uname -a`: `Linux void 4.17.13_1 #1 SMP PREEMPT Tue Aug 7 00:31:18 UTC 2018 x86_64 GNU/Linux` 

- `mono --version`:

```
Mono JIT compiler version 5.10.1.47 (tarball Sun Jul 29 15:02:10 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

```

**Comment by hack2root** [comment] 2018-08-10 16:28
Did you try to migrate to new .Net Core runner. See https://fake.build/fake-migrate-to-fake-5.html?

**Comment by The-BigDaddy** [comment] 2018-08-10 16:39
Ah, no I haven't. However with just now going throught those steps; how do I run the `.paket/paket.exe` on a linux system? I've yet to really work with this stuff so I'm sorry for the dumb sounding question.

**Comment by The-BigDaddy** [comment] 2018-08-10 16:41
```
 ○ MSDotNET/FSharp/SaturnSample ./.paket/paket.exe
zsh: permission denied: ./.paket/paket.exe

 △ MSDotNET/FSharp/SaturnSample sudo chmod u+x ./.paket/paket.exe
Password:

 ○ MSDotNET/FSharp/SaturnSample ./.paket/paket.exe
zsh: exec format error: ./.paket/paket.exe

 △ MSDotNET/FSharp/SaturnSample .paket/paket.exe update
zsh: command not found: .paket/paket.exe
```

I'm clearly misunderstanding something. :stuck_out_tongue:

**Comment by hack2root** [comment] 2018-08-10 16:46
> Update to legacy FAKE 5. This should not be breaking. If it breaks you please open an issue.
> 
> With Paket: add prerelease after nuget FAKE in paket.dependencies file then .paket/paket.exe update, check that paket.lock references FAKE version 5

So at this point you shouldn't run your sample, SaturnSample, i suppose this commands is sample-aware, in my honest opinion ;)

**Comment by hack2root** [comment] 2018-08-10 16:54
@The-BigDaddy if it is mono i suppose you can run mono <your.exe>, if it is native fake, you will probably stay with fake  --target [command line option](https://fake.build/fake-commandline.html)

**Comment by The-BigDaddy** [comment] 2018-08-10 17:00
@hack2root hmmm well here's what happens after running `mono .paket/paket.exe` and then trying to use the build script via `./build.sh`

```
Executing Paket...
paket.lock file found, restoring packages...
Paket version 5.176.4
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 100 milliseconds
This runner is now obsolete with FAKE 5, please upgrade to the new .Net Core runner. See https://fake.build/fake-migrate-to-fake-5.html
To remove this warning you can append the '--removeLegacyFakeWarning' argument or set the 'FAKE_NO_LEGACY_WARNING' environment variable to 'true'
FsiEvaluationSession could not be created.


error FS0229: Error opening binary file '/usr/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll': Could not find file "/usr/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll"



error FS3160: Problem reading assembly '/usr/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll': Processing of a script fragment has stopped because an exception has been raised


Build failed.
Error:
Error while creating a fsi session.
InnerException:
Error creating evaluation session: StopProcessingExn None
-------------------
 FAKE usage
-------------------

    fake.exe [<scriptPath>] [<targetName>] [options]

    scriptPath: Optional.  Path to your FAKE build script.  If not specified, FAKE will use the first .fsx file in the working directory and fail if none exists.

    targetName: Optional.  Name of the target you wish to run.  This will override the target you specifed to run in the build script.
                           When targetName is equal --listTargets or -lt FAKE will list the targets with their dependencies.

    Options:

```

Or `fake -f build.fsx`

```
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/bigdaddy/.dotnet/tools/.store/fake-cli/5.3.1/fake-cli/5.3.1/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```

So this might end up as a FAKE issue....

**Comment by hack2root** [comment] 2018-08-10 17:05
@The-BigDaddy  if you were like me, you would probably copy from GAC to 

goto /gac and

`cp System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Serialization.Formatters.Soap.dll  /usr/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll
`

**Comment by The-BigDaddy** [comment] 2018-08-10 17:08
@hack2root well `System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Serialization.Formatters.Soap.dll` isn't there. There's nothing in `System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a` for me. 

```
 ○ ~ la /usr/lib/mono/gac/System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a/
total 0

```

**Comment by The-BigDaddy** [comment] 2018-08-10 17:09
> However I can find the missing DLL with sudo find / -type f -name "*System.Runtime.Serialization*" -iname "*.dll" 2>/dev/null in several places
> 
>     /usr/lib/mono/4.5-api/System.Runtime.Serialization.Formatters.Soap.dll
> 
>     /usr/lib/mono/4.5.1-api/System.Runtime.Serialization.Formatters.Soap.dll
> 
>     /usr/lib/mono/4.5.2-api/System.Runtime.Serialization.Formatters.Soap.dll
> 
>     etc. etc. for each API version until 4.7.1
> 
> So what I'm assuming is that System.Runtime.Serialization.Formatters.Soap.dll is symlinked and running la /usr/lib/mono/4.5 reveals this
> 
> lrwxrwxrwx 1 root root  126 Jul 29 10:02 System.Runtime.Serialization.Formatters.Soap.dll -> ../gac/System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Serialization.Formatters.Soap.dll
> 
> But running la /usr/lib/mono/gac/System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a/ returns total 0. So nothing is in that folder.
> 
> So should I symlink the file found in the /usr/lib/mono/4.5.2-api to /usr/lib/mono/4.5 as a work aroud? Or it is a possible build issue with my Linux distros package?

**Comment by hack2root** [comment] 2018-08-10 17:13
@The-BigDaddy There is an option that you are using different FW version, so you build against dotnet core app 2.1, the project considered build against .net fw, for example, where in .net 4.5 are major breaing changes, for example, serialzation dll are moved to separate dll, and this is fw misconfiguration for the project, IMHPO, not fake

**Comment by hack2root** [comment] 2018-08-10 17:14
@The-BigDaddy so sometimes mscore linked to non existent (whilst linking confuguration)

**Comment by hack2root** [comment] 2018-08-10 17:15
@The-BigDaddy My daughter toggler and wife are missing, sorry have to go to look for them , OMG

**Comment by The-BigDaddy** [comment] 2018-08-10 17:48
> here is an option that you are using different FW version, so you build against dotnet core app 2.1, the project considered build against .net fw, for example, where in .net 4.5 are major breaing changes, for example, serialzation dll are moved to separate dll, and this is fw misconfiguration for the project, IMHPO, not fake

Does anyone know how I would go about this?

**Comment by hack2root** [comment] 2018-08-10 18:19
@The-BigDaddy 

please give a log files for

dotnet --version

**Comment by The-BigDaddy** [comment] 2018-08-10 18:27
`dotnet --version`: 2.1.302

I installed Mono via my distros package manager, but I'll see if reinstalling does anything.

**Comment by The-BigDaddy** [comment] 2018-08-10 18:37
@hack2root it could be something wrong with my distros mono and mono-devel packages...reinstalling them did nothing.

**Comment by The-BigDaddy** [comment] 2018-08-10 18:39
@hack2root you think building Mono from source would make a difference or no?

**Comment by The-BigDaddy** [comment] 2018-08-15 05:50
@akoeplinger I'll have to link this whole issue to the [Void Linux package repo](https://github.com/void-linux/void-packages). Or investigate how the package was built for the repos myself. There _has_ to be something that was configured when building Mono as a package for Void.

**Comment by Hoshpak** [comment] 2018-08-15 09:02
I can confirm this is a packaging issue that will be resolved in Void shortly.

**Comment by akoeplinger** [comment] 2018-08-15 16:26
Looks like this was resolved: https://github.com/void-linux/void-packages/issues/1783#issuecomment-413184182.

Thanks!

**Closed by akoeplinger** 2018-08-15 16:26 UTC
Labels: needs more info
