### ISSUE TITLE
MSBuild on MacOS : Win32 IO returned 50 with mdk-5.16.0.151 (sym. links / secondary volumes)

### ISSUE THREAD

**Issue by sushihangover** [mono/mono#10623] opened 2018-09-14 16:55 UTC
From : https://developercommunity.visualstudio.com/content/problem/336413/msbuild-win32-io-returned-50-vs4m-macos-mdk-516011.html

Something in the change from 

monoframework-mdk-5.16.0.113.macos10.xamarin.universal.pkg

To:

monoframework-mdk-5.16.0.151.macos10.xamarin.universal.pkg

Breaks building via sym. links (secondary volumes), i.e. 

A solution opened on the path of ~/code/Projects/SomeDir/Some.sln in which “code” is a secondary volume symlink, ie.

lrwxr-xr-x 1 Sushi staff 18 Nov 20 2017 code -> /Volumes/Code/code

Results in:

`Win32 IO returned 50
`

When the build is copying assemblies from either /Library/Frameworks/… or from the nuget package directories.

Reverting back to Mono 5.16.0.113 fixes the problem (The rest of this MacOS setup is running the Alpha channel of VS4M)

>Matt Ward [MSFT] · 20 minutes ago 0

>I have seen something similar with Mono 5.16.0.151 when building a .NET Standard project with msbuild when the project is on an external drive. Mono fails to copy files from ~/.nuget/packages over to the external drive.

```
Copying file from "~/.nuget/packages/microsoft.build/15.8.166/lib/netstandard2.0/Microsoft.Build.dll" to "bin/Debug/netstandard2.0/Microsoft.Build.dll".
w32error-unix.c: unknown error (18) "Cross-device link"
/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(4364,5): warning MSB3026: Could not copy "~/.nuget/packages/microsoft.build/15.8.166/lib/netstandard2.0/Microsoft.Build.dll" to "bin/Debug/netstandard2.0/Microsoft.Build.dll". Beginning retry 1 in 1000ms. Win32 IO returned 50. Path: ~/.nuget/packages/microsoft.build/15.8.166/lib/netstandard2.0/Microsoft.Build.dll" or "bin/Debug/netstandard2.0/Microsoft.Build.dll  [/Volumes/External/downloads/Test/Test.csproj]

```

>This should be filed on https://github.com/mono/mono/issues. Can you file it over there? Or I can. I have not yet got around to reporting the problem.

### Current Behavior

`Win32 IO returned 50
`
### Expected Behavior

Error free build 

## On which platforms did you notice this

[* ] macOS

**Version Used**:

`5.16.0.151` via monoframework-mdk-5.16.0.151.macos10.xamarin.universal.pkg

**Comment by marek-safar** [comment] 2018-09-21 13:13
Duplicate of #10510

**Closed by marek-safar** 2018-09-21 13:13 UTC
