### ISSUE TITLE
[2019-02] Random socket failures with NuGet

### ISSUE THREAD

**Issue by garuma** [mono/mono#15211] opened 2019-06-17 17:22 UTC
## Steps to Reproduce

1. Use mono 2019-02
2. msbuild /restore

### Current Behavior

We are seeing intermittent/random failures on our CI since we have updated to use mono 2019-02 during `msbuild /restore` for NuGets. They all have the same stacktrace as appearing below.

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

MonoFramework-MDK-6.0.0.299
2019-02/d563138704cd6a89328b7d8099682492ab61826d

## Stacktrace

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetException (System.Exception exception) [0x0004b] in <912c4405bea646fbb1c40de71d0a641e>:0 
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException (System.Exception exception) [0x00000] in <912c4405bea646fbb1c40de71d0a641e>:0 
  at System.Net.Http.ConnectHelper+ConnectEventArgs.OnCompleted (System.Net.Sockets.SocketAsyncEventArgs _) [0x0006a] in <3069bc06d8d14bf38b07c61cf8c74eea>:0 
  at System.Net.Sockets.SocketAsyncEventArgs.Complete () [0x00009] in <bed73c683a6443baabed92b1febeb070>:0 
  at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure (System.Exception exception, System.Int32 bytesTransferred, System.Net.Sockets.SocketFlags flags) [0x0001d] in <bed73c683a6443baabed92b1febeb070>:0 
  at System.Net.Sockets.MultipleConnectAsync.AsyncFail (System.Exception e) [0x0001a] in <bed73c683a6443baabed92b1febeb070>:0 
  at System.Net.Sockets.MultipleConnectAsync.InternalConnectCallback (System.Object sender, System.Net.Sockets.SocketAsyncEventArgs args) [0x000b7] in <bed73c683a6443baabed92b1febeb070>:0 
  at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted (System.Net.Sockets.SocketAsyncEventArgs e) [0x0000e] in <bed73c683a6443baabed92b1febeb070>:0 
  at System.Net.Sockets.SocketAsyncEventArgs.Complete () [0x00009] in <bed73c683a6443baabed92b1febeb070>:0 
  at System.Net.Sockets.Socket+<>c.<.cctor>b__315_3 (System.IAsyncResult ares) [0x00057] in <bed73c683a6443baabed92b1febeb070>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) [0x0000b] in <bed73c683a6443baabed92b1febeb070>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <912c4405bea646fbb1c40de71d0a641e>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <912c4405bea646fbb1c40de71d0a641e>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <912c4405bea646fbb1c40de71d0a641e>:0 
```

**Comment by marek-safar** [comment] 2019-06-17 18:44
This looks serious. I suspect this might be because of corefx http changes but just guessing here

/cc @steveisok

**Comment by steveisok** [comment] 2019-06-17 18:53
I asked @baulig to triage.  He'll be taking a look this afternoon

**Comment by baulig** [comment] 2019-06-17 21:28
I cannot reproduce it locally, but don't need to to give an assessment of the situation.

Unfortunately, there is no easy solution to this and I'm not even sure whether it's fixable at all without complex changes.  We might get lucky and _hide_ the problem with some nasty hacks, though.

The fundamental issue is that our `SocketAsyncEventArgs` class is an ancient Mono implementation - and it's incompatible with CoreFX.  This causes problem with any CoreFX code that subclasses it, such as for instance here: https://github.com/mono/corefx/blob/d5f406ea037710aaf2c6b1bd4fe92fa723068a3a/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs#L115.

Problems with the `SocketAsyncEventArgs` have been happening all over last summer - see for instance https://github.com/mono/mono/issues/8871 and everything that's referenced by it.

To make matters worse, replacing it with the CoreFX version is non-trivial because we also have a Mono-specific `Socket` implementation (that's also slightly incompatible with CoreFX).

And just look at the actual code.  Here's Mono:

```cs
		protected virtual void OnCompleted (SocketAsyncEventArgs e)
		{
			if (e == null)
				return;
			
			EventHandler<SocketAsyncEventArgs> handler = e.Completed;
			if (handler != null)
				handler (e.current_socket, e);
		}
```

and here's CoreFX:

```cs
        protected virtual void OnCompleted(SocketAsyncEventArgs e)
        {
            _completed?.Invoke(e._currentSocket, e);
        }
```

The interesting question here is: is there any scenario where `e != this`?

**Comment by baulig** [comment] 2019-06-17 21:42
Trying to answer that `e != this` question here .... https://github.com/mono/mono/pull/15219/files

**Comment by baulig** [comment] 2019-06-18 01:04
Is this in any way related to it:

```
  Retrying 'FindPackagesByIdAsync' for source 'https://devdiv.pkgs.visualstudio.com/_packaging/6f96278a-705c-4bdc-8ea7-5e61d0ae3a85/nuget/v3/flat2/xamarin.android.support.constraint.layout.solver/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to write data to the transport connection: The socket is not connected.
    The socket is not connected
```

I see a bunch of these, but the restore still completes successfully.

**Comment by steveisok** [comment] 2019-07-18 12:05
@garuma Are you still experiencing this to any large degree? 

@baulig I know you couldn't find anything concrete, but could you please update the issue w/ your findings?

**Comment by baulig** [comment] 2019-07-18 17:19
See also https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935138 - there's more info in there; I'll close the other GitHub issue as a duplicate of this one.

**Comment by garuma** [comment] 2019-07-18 18:03
@steveisok yep we are still experiencing the issue. We also recently moved to target 2019-06 as well so it's one less version to backport to.

**Comment by slluis** [comment] 2019-07-25 16:00
This is currently causing VS for Mac to crash for many users (see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935138).

**Comment by steveisok** [comment] 2019-07-25 17:01
@slluis We are working on some options to address this.  I'll keep you in the loop.

**Comment by steveisok** [comment] 2019-07-25 22:49
@baulig and @directhex put together a draft pipeline here: 

https://devdiv.visualstudio.com/DevDiv/_build?definitionId=11762&_a=summary 

Since it's a random sort of failure, we can better control the environment and we are able to reproduce.  We know the specific complete function where the error occurs and are putting in additional debug info.  I'll update the issue when I know more.

**Comment by leculver** [comment] 2019-07-26 19:24
FYI @marek-safar this is currently 25% of the incoming crash rate of VS for Mac 8.1.

**Comment by steveisok** [comment] 2019-07-26 19:39
Thanks for the info.  We are still trying to gather more information on why this is happening.

**Comment by kdubau** [comment] 2019-07-29 13:37
> FYI @marek-safar this is currently 25% of the incoming crash rate of VS for Mac 8.1.

Same for VS for Mac **8.2** (now in Stable channel).

**Comment by steveisok** [comment] 2019-07-29 19:03
We made another test run and got more detail.  We have suspicions on a cause and are currently testing a fix.  In addition, we think we can reproduce in isolation.  

For more detail on what we found, see https://github.com/xamarin/designer/blob/build-mono-fixsocketerror/martin-report.md

**Comment by baulig** [comment] 2019-08-01 00:27
PR is up: https://github.com/mono/mono/pull/15947.

**Comment by steveisok** [comment] 2019-08-01 10:51
Since https://github.com/mono/mono/pull/15947 has been merged, closing.

**Closed by steveisok** 2019-08-01 10:51 UTC
Labels: area-BCL: System
