### ISSUE TITLE
SIGABRT with Npgsql 3.2.7 

### ISSUE THREAD

**Issue by pascalhaakmat** [mono/mono#8811] opened 2018-05-22 07:09 UTC
This simple program crashes Mono with SIGABRT when using Npgsql 3.2.7 and EntityFramework 6.2.0:

```csharp
        public static void Main(string[] args)
        {
            Console.WriteLine("Creating new user");
            using (var dc = new TestDbContext())
            {
                var user = new User();
                user.Username = "Test";
                dc.Users.Add(user);
                dc.SaveChanges();
            }
        }

```
Note that the problem does **not** occur when using Npgsql 3.2.6, and so I also reported this issue with the npgsql team under https://github.com/npgsql/npgsql/issues/1944

## Steps to Reproduce

1. Download console project: 
[Npgsql-SIGABRT.zip](https://github.com/mono/mono/files/2025417/Npgsql-SIGABRT.zip)

2. Configure appropriate PostgreSQL database connection string in App.config
3. Run the application

### Current Behavior

Hits an assertion and then terminates the program with SIGABRT:

```
Creating new user
* Assertion at method-to-ir.c:13203, condition `ins->opcode >= MONO_CEE_LAST' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at Npgsql.NpgsqlParameter.ValidateAndGetLength () [0x00043] in <eb33458f23da4b6db3190127f501e0de>:0
  at (wrapper remoting-invoke-with-check) Npgsql.NpgsqlParameter.ValidateAndGetLength () [0x00032] in <eb33458f23da4b6db3190127f501e0de>:0
  at Npgsql.NpgsqlCommand.ValidateParameters () [0x00041] in <eb33458f23da4b6db3190127f501e0de>:0
  at Npgsql.NpgsqlCommand/<Execute>d__71.MoveNext () [0x00015] in <eb33458f23da4b6db3190127f501e0de>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Npgsql.NpgsqlDataReader>.Start<Npgsql.NpgsqlCommand/<Execute>d__71> (Npgsql.NpgsqlCommand/<Execute>d__71&) [0x0002c] in /run/build/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<Npgsql.NpgsqlDataReader>.Start<Npgsql.NpgsqlCommand/<Execute>d__71> (Npgsql.NpgsqlCommand/<Execute>d__71&) [0x00007] in <a0fea0943f984048a442056f03888c06>:0
  at Npgsql.NpgsqlCommand.Execute (System.Data.CommandBehavior,bool,System.Threading.CancellationToken) [0x0003f] in <eb33458f23da4b6db3190127f501e0de>:0
  at Npgsql.NpgsqlCommand/<ExecuteDbDataReader>d__92.MoveNext () [0x00035] in <eb33458f23da4b6db3190127f501e0de>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<System.Data.Common.DbDataReader>.Start<Npgsql.NpgsqlCommand/<ExecuteDbDataReader>d__92> (Npgsql.NpgsqlCommand/<ExecuteDbDataReader>d__92&) [0x0002c] in /run/build/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<System.Data.Common.DbDataReader>.Start<Npgsql.NpgsqlCommand/<ExecuteDbDataReader>d__92> (Npgsql.NpgsqlCommand/<ExecuteDbDataReader>d__92&) [0x00007] in <a0fea0943f984048a442056f03888c06>:0
  at Npgsql.NpgsqlCommand.ExecuteDbDataReader (System.Data.CommandBehavior,bool,System.Threading.CancellationToken) [0x0003f] in <eb33458f23da4b6db3190127f501e0de>:0
  at Npgsql.NpgsqlCommand.ExecuteDbDataReader (System.Data.CommandBehavior) [0x00008] in <eb33458f23da4b6db3190127f501e0de>:0
  at System.Data.Common.DbCommand.ExecuteReader (System.Data.CommandBehavior) [0x00000] in /run/build/mono/external/corefx/src/System.Data.Common/src/System/Data/Common/DbCommand.cs:114
  at (wrapper remoting-invoke-with-check) System.Data.Common.DbCommand.ExecuteReader (System.Data.CommandBehavior) [0x00033] in <c4eba03d293a480fa62f05bf4d2ff80b>:0
```

### Expected Behavior

Expected behavior is for a new row to be created in the database.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

This is using MonoDevelop 7.3.3 (build 5) on Linux Mint 18.1 (Ubuntu 16.04) with Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:48:32 UTC 2018).

## Stacktrace

Full output with gdb debug info: 
[npgsql-3.2.7-mono-5.12.0.226-sigabrt-console.txt](https://github.com/mono/mono/files/2025330/npgsql-3.2.7-mono-5.12.0.226-sigabrt-console.txt)

**Comment by lewurm** [comment] 2018-08-23 19:16
That's probably a noob question, but I keep getting:
```
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 42P01: relation "dbo.Users" does not exist
```
am I supposed to create the table somehow by myself? if so, how?

/cc @roji

**Comment by Marshal313** [comment] 2018-08-24 02:49
@lewurm, So as you requested in issue #9897 I've run the code after installing `mono-runtime-dbg` package and it seems I get the exact same output. [Here it is in a text file](https://github.com/mono/mono/files/2316827/TheNewException.txt)
By the way I'm not sure if issue #9897 is really a duplicate of this Issue, Because both Exceptions and Stack traces are different, but whatever ...

I'm not really a pro when it comes to Native code and runtimes but I'd like to help. I have simply run the application in normal and debug mode, So should I compile it with some options or something so that `mono-runtime-dbg` would make a difference ?

**Just in case**, I'm not sure if building with Release configuration in MonoDevelop would AOT compile the code, But if it does, then I don't think it's related to JIT only because it throws the same exception.  
But as I said, I'm a native-noob :grin: so I don't really know what's going on with JIT and AOT here, or if runtime JIT is different than JIT Compiler and etc...

**Comment by lewurm** [comment] 2018-10-11 12:31
@Marshal313 Thanks! Unfortunately I can't reproduce the crash.

Likewise with the provided repro from the poster, I figured out the database scheme:
```sql
CREATE SCHEMA dbo;

CREATE SEQUENCE dbo."Users_Id_seq";

CREATE TABLE dbo."Users"                                                                                                                                           
(                                                                                                                                                                                  
"Id" integer NOT NULL DEFAULT nextval('dbo."Users_Id_seq"'::regclass),                                                                                                             
"Username" character varying(50) NOT NULL,                                                                                                                                         
CONSTRAINT pk_users_id PRIMARY KEY ("Id")                                                                                                                                          
); 
```

I get the following output:
```
$ strings Npgsql.dll | grep 3.2.7
3.2.7.0
3.2.7
$ MONO_PATH=. mono Npgsql-SIGABRT.exe && echo $?
Creating new user
0
```

I tried with:
```
$ mono --version
Mono JIT compiler version 5.12.0.301 (2018-02/4fe3280bba1 Fri Jul 20 08:25:42 EDT 2018)
```
and
```
$ mono --version
Mono JIT compiler version 5.12.0.227 (2018-02/7c317d0af31 Fri May  4 20:39:09 EDT 2018)
```

I assume I need better repro steps:
* what postgresql version is used?
* exact `.sql` file to create the database scheme

**Comment by marek-safar** [comment] 2019-03-11 12:29
Closing, please reopen if you can still reproduce the issue with requested details

**Closed by marek-safar** 2019-03-11 12:29 UTC
Labels: area-Runtime: JIT, needs more info
