### ISSUE TITLE
Could not AOT the assembly - assert `condition 'cfg->cbb == first_bb' not`

### ISSUE THREAD

**Issue by chamons** [mono/mono#14066] opened 2019-04-15 21:21 UTC
_From @elcometer on Mon, 15 Apr 2019 13:10:37 GMT_

### Steps to Reproduce

1.  Download https://www.elcometer.com/downloads/crossplatformsdk.zip
2.  Unzip and open solution in Visual Studio for Mac 2019
3.  Switch to Release > iPhone
2.  Build either Elcometer.Demo.iOS or Elcometer.Demo.Xamarin.Forms.iOS project.

### Expected Behavior

It should compile.

### Actual Behavior

It fails with AOT error - it used to work on Visual Studio for Mac 2017

### Environment

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.0.2 (build 23)
Installation UUID: e05bace0-2f38-430c-a35f-7623af353198
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Android ===

Version: 9.2.0.5 (Visual Studio Professional)
Android SDK: /Users/davidd/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ad371dab1b
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/davidd/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

=== Xamarin.Mac ===

Version: 5.8.0.0 (Visual Studio Professional)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin.iOS ===

Version: 12.6.0.25 (Visual Studio Professional)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== Build Information ===

Release ID: 800020023
Git revision: c576bb008dfe54cdcf596237e09564ebd2da4343
Build date: 2019-04-06 10:06:46+00
Build branch: master
Xamarin extensions: 2c996830618e7cb8e8be97984d643eb86f122e8d

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Fri Nov  2 20:43:16 PDT 2018
    root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64
```

### Build Logs

```
 Mono Ahead of Time compiler - compiling assembly /Users/davidd/Downloads/crossplatformsdk/Xamarin.Native/Elcometer.Demo.iOS/obj/iPhone/Release/mtouch-cache/64/3-Build/Elcometer.Core.dll
    AOTID F6EB5953-59F0-77AD-FF45-77444D6B631E
    * Assertion at /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mono/mini/decompose.c:1469, condition `cfg->cbb == first_bb' not met
    
    
    AOT Compilation exited with code 134, command:
    MONO_PATH=/Users/davidd/Downloads/crossplatformsdk/Xamarin.Native/Elcometer.Demo.iOS/obj/iPhone/Release/mtouch-cache/64/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/davidd/Downloads/crossplatformsdk/Xamarin.Native/Elcometer.Demo.iOS/obj/iPhone/Release/mtouch-cache/arm64/Elcometer.Core.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/davidd/Downloads/crossplatformsdk/Xamarin.Native/Elcometer.Demo.iOS/obj/iPhone/Release/mtouch-cache/64/3-Build/Msym,outfile=/Users/davidd/Downloads/crossplatformsdk/Xamarin.Native/Elcometer.Demo.iOS/obj/iPhone/Release/mtouch-cache/arm64/Elcometer.Core.dll.s "/Users/davidd/Downloads/crossplatformsdk/Xamarin.Native/Elcometer.Demo.iOS/obj/iPhone/Release/mtouch-cache/64/3-Build/Elcometer.Core.dll"
    Mono Ahead of Time compiler - compiling assembly /Users/davidd/Downloads/crossplatformsdk/Xamarin.Native/Elcometer.Demo.iOS/obj/iPhone/Release/mtouch-cache/64/3-Build/Elcometer.Core.dll
    AOTID F6EB5953-59F0-77AD-FF45-77444D6B631E
    * Assertion at /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mono/mini/decompose.c:1469, condition `cfg->cbb == first_bb' not met
```    

### Example Project (If Possible)

https://www.elcometer.com/downloads/crossplatformsdk.zip

_Copied from original issue xamarin/xamarin-macios#5898_

**Comment by chamons** [comment] 2019-04-15 21:21
_From @chamons on Mon, 15 Apr 2019 21:17:12 GMT_

Thanks for the steps to reproduce. I've been able to reproduce your issue.

Simplified steps to reproduce:

- Download[3-Build.zip](https://github.com/xamarin/xamarin-macios/files/3082103/3-Build.zip)
- Unzip
- cd 3-Build
- `MONO_PATH=. /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.0/bin/arm-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=armv7-ios,data-outfile=foo.out,static,asmonly,direct-icalls,full,soft-debug,dwarfdebug,no-direct-calls,outfile=Elcometer.Core.dll.s Elcometer.Core.dll`

```
Mono Ahead of Time compiler - compiling assembly /Users/donblas/Desktop/3-Build/Elcometer.Core.dll
AOTID FB718798-DE15-9984-FD0D-7A2DD5BBEE4D
* Assertion at /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mono/mini/decompose.c:1469, condition `cfg->cbb == first_bb' not met
```

**Comment by tobiasschulz** [comment] 2019-04-20 05:13
We aren't able to compile any of our apps because of this - are there any workarounds??

**Comment by vargaz** [comment] 2019-04-20 11:31
@chamons I think this was fixed in mono by:
https://github.com/mono/mono/commit/e4df5ef68036c4845a1eaef52101ee60c669404d

**Comment by tobiasschulz** [comment] 2019-04-20 12:31
That needs to be in VS2019 as soon as possible. Without it, the new VS is completely unusable with any codebase that triggers the bug. Which is storing enums in object? seriously?

**Comment by vargaz** [comment] 2019-04-20 12:40
As a workaround, either remove the 
throw new NotSupportedException(..) in Elcometer.Core.SortedList:Current ().
or make the EnumeratorMode enumerator in Elcometer.Core.SortedList a non-nested type.

**Comment by tobiasschulz** [comment] 2019-04-20 16:51
Ok what exactly is not supported? Having enums nested inside a class? Or boxing enums, or boxing nested enums?

**Comment by vargaz** [comment] 2019-04-20 16:56
Boxing generic enums, i.e. enums nested in a generic class.

**Comment by tobiasschulz** [comment] 2019-04-20 17:21
Ah thats a workaround that I might actually be able to implement in our codebase

**Comment by cshearercooper** [comment] 2019-04-24 15:12
We are having this same issue, and the workaround worked.  But please bump the priority of this issue, there's no guarantee we'll be able to use the same workaround in future code

**Comment by lambdageek** [comment] 2019-04-24 16:08
@chamons FYI a `2018-08` backport https://github.com/mono/mono/pull/14161 was merged recently.

**Comment by tdiehl** [comment] 2019-05-28 23:38
I'm seeing this error as well. Based on the comment above, it looked like this should be fixed in an updated version of Mono? I've tried the "Preview" channel of VS 2019 Mac which has Mono 5.18.1.24 (2018-08/082e1a23463 Tue Apr 30 13:26:14 EDT 2019) which seems to have the fix, but I'm still seeing the same error. I can attach a test case if needed, and if this should have been fixed in 5.18.1.24.

**Comment by tdiehl** [comment] 2019-05-30 05:54
@chamons, not sure if this is a different variant of the same bug, but I'm getting the same error even when running VS 2019 Preview with Mono 5.18.1.24, which seems like it should have the fix mentioned by @lambdageek if I understand correctly.

Repro steps and project below.

### Steps to Reproduce

1. Download https://1drv.ms/u/s!AjFxKKS320ycgdcz0SmZdbduhd7C6w
2. Unzip and open solution in Visual Studio for Mac 2019 (stable or preview) 
3. Switch to Release > iPhone
4. Build the TestApp project

### Expected Behavior

It should compile.

### Actual Behavior

It fails with AOT error - it used to work on Visual Studio for Mac 2017

### Environment

```
=== Visual Studio Professional 2019 (Preview) for Mac ===

Version 8.1 Preview (8.1 build 2460)
Installation UUID: 5d49c26f-3240-4aef-97a8-760832332566
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010024

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.24 (2018-08/082e1a23463) (64-bit)
	Package version: 518010024

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.4
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.1.5.1 (Visual Studio Professional)
Commit: HEAD/234003d1a
Android SDK: /Users/todd.diehl/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.3
SDK Build Tools Version: 28.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/todd.diehl/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-06 18:50:08 UTC

=== Xamarin Designer ===

Version: 16.1.0.459
Hash: aa1cc9a67
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-05-09 18:28:48 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.150 (Visual Studio Professional)
Hash: 99c0cfab
Branch: d16-1
Build date: 2019-04-22 17:21:29-0400

=== Xamarin.iOS ===

Version: 12.10.0.150 (Visual Studio Professional)
Hash: 99c0cfab
Branch: d16-1
Build date: 2019-04-22 17:21:28-0400

=== Build Information ===

Release ID: 801002460
Git revision: f8e004f45bb52a2f5b7b0b80b96496a76205e48d
Build date: 2019-05-10 18:53:20+00
Build branch: release-8.1
Xamarin extensions: 735d3d5d1daaee9cf9b045febed581680960e8b2

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Faithlife Embedded Soft Debug 1.2
AddinMaker 1.5.0
Paket 0.5.1
```

### Build Logs

```
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/todd.diehl/Projects/TestApp/TestApp/obj/iPhone/Release/response-file.rsp 
    AOT Compilation exited with code 134, command:
    MONO_PATH=/Users/todd.diehl/Projects/TestApp/TestApp/obj/iPhone/Release/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/12.10.0.150/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/todd.diehl/Projects/TestApp/TestApp/obj/iPhone/Release/mtouch-cache/arm64/Faithlife.Data.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/todd.diehl/Projects/TestApp/TestApp/obj/iPhone/Release/mtouch-cache/3-Build/Msym,outfile=/Users/todd.diehl/Projects/TestApp/TestApp/obj/iPhone/Release/mtouch-cache/arm64/Faithlife.Data.dll.s "/Users/todd.diehl/Projects/TestApp/TestApp/obj/iPhone/Release/mtouch-cache/3-Build/Faithlife.Data.dll"
    Mono Ahead of Time compiler - compiling assembly /Users/todd.diehl/Projects/TestApp/TestApp/obj/iPhone/Release/mtouch-cache/3-Build/Faithlife.Data.dll
    AOTID 8B760C54-2BE6-372F-CEAD-DE966B049D8D
    * Assertion at /Users/builder/jenkins/workspace/archive-mono/2018-08/ios/release/mono/mini/decompose.c:1469, condition `cfg->cbb == first_bb' not met
    
    
    MTOUCH : error MT3001: Could not AOT the assembly '/Users/todd.diehl/Projects/TestApp/TestApp/obj/iPhone/Release/mtouch-cache/3-Build/Faithlife.Data.dll'
```

### Example Project (If Possible)

https://1drv.ms/u/s!AjFxKKS320ycgdcz0SmZdbduhd7C6w

**Comment by tdiehl** [comment] 2019-06-14 15:46
Tested my repro in VS 2019 for Mac 8.1 and appears to be resolved. Thanks!

**Closed** 2019-12-16 08:24 UTC
Labels: area-Runtime: AOT, regression
