### ISSUE TITLE
ArrayTypeMismatchException when using array of generic ICollection<T> or IList<T>

### ISSUE THREAD

**Issue by jonpryor** [mono/mono#6266] opened 2017-12-17 02:09 UTC
### Steps to Reproduce

1. Run the following program:

```csharp
using System.Collections.Generic;

public interface IFoo
{
  int MyInt { get; }
}

public class Bar : IFoo
{
  public int MyInt => 0;
}

class App {
  public static void Main ()
  {
    ICollection<IFoo> arr1 = new Bar[1] { new Bar() };
    ICollection<IFoo> arr2 = new Bar[1] { new Bar() };

    ICollection<IFoo>[] a2d = new ICollection<IFoo>[2] {
      arr1,
      arr2,
    };
  }
}
```

### Expected Behavior

No exception thrown.

### Actual Behavior

Throws an `ArrayTypeMismatchException` at last line of test code at runtime when using `ICollection<T>` or `IList<T>`. 

```
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
  at (wrapper stelemref) System.Object:virt_stelemref_interface (intptr,object)
  at App.Main () [0x0001f] in /Users/jon/tmp/csharp/gxa-1120.cs:19 
```

The following types are working properly as expected:

* `IEnumerable`
* `IEnumerable<T>`
* `ICollection`
* `IList`

Code is compiling successfully with all types.

### Version Information

Visual Studio: 15.5.2
Mono: MonoAndroid70 / 4.0.30319 / 8.1.0.25
Android: 7.0
Kernel: 4.1.18-gdd36b34

### On which platforms did you notice this

-[X] macOS
-[ ] Linux
-[ ] Windows
-[X] Xamarin.Android

**Version Used**:

Desktop macOS: 5.4.1.7 (2017-06/e66d9abbb27)  
Xamarin.Android 8.1: d15-5-2017-06/950ea65

**Comment by jonpryor** [comment] 2017-12-17 02:10
Originally filed at: https://github.com/xamarin/xamarin-android/issues/1120

**Comment by lambdageek** [comment] 2017-12-18 22:00
@alexischr Does this look like a duplicate of or related to [Bugzilla #59400](https://bugzilla.xamarin.com/show_bug.cgi?id=59400)

**Comment by alexischr** [comment] 2017-12-18 22:24
It looks related but it is not a duplicate as that one is specifically for `GetEnumerator` behavior and its fix won't fix this.

**Comment by marek-safar** [comment] 2018-02-21 22:16
@monojenkins backport 2018-02

**Closed** 2018-02-21 22:27 UTC
Labels: area-Runtime: JIT
