### ISSUE TITLE
[netcore] Make System.Data.Tests.SqlTypes.SqlStringTest.ReadWriteXmlTest Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15179] opened 2019-06-15 22:31 UTC
Fails similarly to #15174, but w/ a different type.

```
System.Data.Tests.SqlTypes.SqlStringTest.ReadWriteXmlTest [FAIL]
      System.InvalidOperationException : There is an error in XML document (0, 0).
      ---- System.InvalidProgramException : Invalid IL code in Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSqlString:Read1_string (): IL_00bc: castclass 0x0100000d
      
      
      Stack Trace:
           at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
           at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
           at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
           at System.Data.Tests.SqlTypes.SqlStringTest.ReadWriteXmlTestInternal(String xml, String testval, String unit_test_id)
           at System.Data.Tests.SqlTypes.SqlStringTest.ReadWriteXmlTest()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make it pass.

**Comment by filipnavara** [comment] 2019-07-24 18:59
Here's the full IL of the generated method:
```
      IL_0000: ldnull    
      IL_0001: stloc.0   
      IL_0002: ldarg.0   
      IL_0003: call      0x0a000005
      IL_0008: callvirt  0x0a000006
      IL_000d: pop       
      IL_000e: ldarg.0   
      IL_000f: call      0x0a000005
      IL_0014: callvirt  0x0a000007
      IL_0019: ldc.i4.1  
      IL_001a: bne.un    IL_00e7
      IL_001f: ldarg.0   
      IL_0020: call      0x0a000005
      IL_0025: callvirt  0x0a000008
      IL_002a: ldarg.0   
      IL_002b: ldfld     0x0afffff3
      IL_0030: bne.un    IL_004a
      IL_0035: ldarg.0   
      IL_0036: call      0x0a000005
      IL_003b: callvirt  0x0a000009
      IL_0040: ldarg.0   
      IL_0041: ldfld     0x0afffff2
      IL_0046: ceq       
      IL_0048: br.s      IL_004b
      IL_004a: ldc.i4.0  
      IL_004b: brfalse   IL_00db
      IL_0050: ldarg.0   
      IL_0051: ldtoken   0x01000002
      IL_0056: call      0x0a00000a
      IL_005b: call      0x0a00000b
      IL_0060: callvirt  0x0a00000c
      IL_0065: callvirt  0x0a00000d
      IL_006a: stloc.1   
      IL_006b: br        IL_00a2
      IL_0070: ldloc.1   
      IL_0071: callvirt  0x0a00000e
      IL_0076: stloc.2   
      IL_0077: ldloc.2   
      IL_0078: call      0x0a00000f
      IL_007d: brtrue    IL_00a1
      IL_0082: ldloc.2   
      IL_0083: callvirt  0x0a000010
      IL_0088: ldlen     
      IL_0089: conv.i4   
      IL_008a: ldc.i4.0  
      IL_008b: ceq       
      IL_008d: ldc.i4.0  
      IL_008e: ceq       
      IL_0090: brtrue    IL_00a1
      IL_0095: ldloc.2   
      IL_0096: ldnull    
      IL_0097: call      0x0a000011
      IL_009c: br        IL_00bc
      IL_00a1: nop       
      IL_00a2: ldloc.1   
      IL_00a3: callvirt  0x0a000012
      IL_00a8: brtrue    IL_0070
      IL_00ad: ldtoken   0x01000002
      IL_00b2: call      0x0a00000a
      IL_00b7: call      0x0a000013
      IL_00bc: castclass 0x0100000d
      IL_00c1: call      0x0a000014
      IL_00c6: unbox     0x01000002
      IL_00cb: ldobj     0x01000002
      IL_00d0: box       0x01000002
      IL_00d5: stloc.0   
      IL_00d6: br        IL_00e2
      IL_00db: ldarg.0   
      IL_00dc: call      0x0a000015
      IL_00e1: throw     
      IL_00e2: br        IL_00f3
      IL_00e7: ldarg.0   
      IL_00e8: ldnull    
      IL_00e9: ldstr     
      IL_00ee: call      0x0a000016
      IL_00f3: ldloc.0   
      IL_00f4: stloc.3   
      IL_00f5: ldloc.3   
      IL_00f6: ret       
```

The sequence generated at IL_00c6 is [this code]( https://github.com/dotnet/corefx/blob/8c2be7893fa585cba9c094c27b69d7c8e0822ef3/src/System.Private.Xml/src/System/Xml/Serialization/CodeGenerator.cs#L1235-L1285). I still didn't trace it as far back as to what code generates IL_00bc.

**Comment by filipnavara** [comment] 2019-07-24 19:35
Also, the tests pass just fine under the interpreter.

**Comment by vargaz** [comment] 2019-07-25 02:17
It means there is an IL offset where there are 2 incoming IL stacks with different number of values.

converting (in B15: stack: 1) IL_009c: br        IL_00bc
1 item(s) on exit from B15
storing 0 to temp 7
converting (in B13: stack: 0) IL_00a1: nop       
loading 0 from temp 7
converting (in B11: stack: 1) IL_00a2: ldloc.1   
converting (in B11: stack: 2) IL_00a3: callvirt  0x0a000012
converting (in B11: stack: 2) IL_00a8: brtrue    IL_0070
1 item(s) on exit from B11
storing 0 to temp 7
loading 0 from temp 7
converting (in B17: stack: 1) IL_00ad: ldtoken   0x01000002
converting (in B17: stack: 2) IL_00b7: call      0x0a000013
2 item(s) on exit from B17

Here are offset bc, you have an il stack of height 1 coming in from offset 9c, and another with height 2 coming in from b7.

**Comment by filipnavara** [comment] 2019-07-25 07:25
Thanks, I missed the jump to IL_00bc. I guess I've been staring at it for too long.

**Comment by filipnavara** [comment] 2019-07-25 07:42
Stack trace leading to generation of the `castclass` instruction:

```
        /Users/filipnavara/Documents/mono/netcore/System.Private.CoreLib/src/System.Reflection.Emit/ILGenerator.cs(791,0): at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, Type cls)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/CodeGenerator.cs(677,0): at System.Xml.Serialization.CodeGenerator.Castclass(Type target)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/CodeGenerator.cs(1275,0): at System.Xml.Serialization.CodeGenerator.InternalConvert(Type source, Type target, Boolean isAddress)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/CodeGenerator.cs(672,0): at System.Xml.Serialization.CodeGenerator.ConvertValue(Type source, Type target)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationReaderILGen.cs(3254,0): at System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(String source, String arrayName, String choiceSource, ElementAccessor element, ChoiceIdentifierAccessor choice, String checkSpecified, Boolean checkForNull, Boolean readOnly, Int32 fixupIndex, Int32 elementIndex)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationReaderILGen.cs(2554,0): at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(Member[] members, Member anyElement, String elementElseString)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationReaderILGen.cs(2272,0): at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(Member[] members, String elementElseString, String elseString, Member anyElement, Member anyText)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationReaderILGen.cs(670,0): at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(XmlTypeMapping xmlTypeMapping)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationReaderILGen.cs(279,0): at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateElement(XmlMapping xmlMapping)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/Compilation.cs(497,0): at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/Compilation.cs(77,0): at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs(292,0): at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs(276,0): at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs(226,0): at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
        /_/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs(185,0): at System.Xml.Serialization.XmlSerializer..ctor(Type type)
```

**Comment by marek-safar** [comment] 2019-07-25 08:12
This is CoreFX bug. The ILGenForCreateInstance method generates IL code which has an imbalanced stack.

**Comment by filipnavara** [comment] 2019-07-25 08:22
I am still not seeing how the unbalanced stack happens though. According to the comment above it's the `while (e.MoveNext()) ;` (https://github.com/dotnet/corefx/blob/8c2be7893fa585cba9c094c27b69d7c8e0822ef3/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriterILGen.cs#L2472-L2479) loop:

```
      IL_00a1: nop       
      IL_00a2: ldloc.1   
      IL_00a3: callvirt  0x0a000012
      IL_00a8: brtrue    IL_0070
```

which translates to the verbose output:
```
converting (in B13: stack: 0) IL_00a1: nop
loading 0 from temp 7
converting (in B11: stack: 1) IL_00a2: ldloc.1
converting (in B11: stack: 2) IL_00a3: callvirt 0x0a000012
converting (in B11: stack: 2) IL_00a8: brtrue IL_0070
```

How does the stack ever become depth 2 with this IL?

**Comment by filipnavara** [comment] 2019-07-25 08:40
Oh, I guess I was misreading the verbose output. Not that I see the problem source but at least it explains few things :-)

**Comment by filipnavara** [comment] 2019-07-25 10:12
I'll have to dig into the spec to see whether it is really a CoreFX bug or not...

```
converting (in B2: stack: 0) IL_0002: ldarg.0   
converting (in B2: stack: 1) IL_0003: call      0x0a000005
converting (in B2: stack: 1) IL_0008: callvirt  0x0a000006
converting (in B2: stack: 1) IL_000d: pop       
converting (in B2: stack: 0) IL_000e: ldarg.0   
converting (in B2: stack: 1) IL_000f: call      0x0a000005
converting (in B2: stack: 1) IL_0014: callvirt  0x0a000007
converting (in B2: stack: 1) IL_0019: ldc.i4.1  
converting (in B2: stack: 2) IL_001a: bne.un    IL_00e7
converting (in B5: stack: 0) IL_001f: ldarg.0   
converting (in B5: stack: 1) IL_0020: call      0x0a000005
converting (in B5: stack: 1) IL_0025: callvirt  0x0a000008
converting (in B5: stack: 1) IL_002a: ldarg.0   
converting (in B5: stack: 2) IL_002b: ldfld     0x0affffdf
converting (in B5: stack: 2) IL_0030: bne.un    IL_004a
converting (in B7: stack: 0) IL_0035: ldarg.0   
converting (in B7: stack: 1) IL_0036: call      0x0a000005
converting (in B7: stack: 1) IL_003b: callvirt  0x0a000009
converting (in B7: stack: 1) IL_0040: ldarg.0   
converting (in B7: stack: 2) IL_0041: ldfld     0x0affffde
converting (in B7: stack: 2) IL_0046: ceq       
converting (in B7: stack: 1) IL_0048: br.s      IL_004b
1 item(s) on exit from B7
created temp 6 (R53) of type System.Int32
storing 0 to temp 6
converting (in B6: stack: 0) IL_004a: ldc.i4.0  
1 item(s) on exit from B6
storing 0 to temp 6
loading 0 from temp 6
converting (in B8: stack: 1) IL_004b: brfalse   IL_00db
converting (in B10: stack: 0) IL_0050: ldarg.0   
converting (in B10: stack: 1) IL_0051: ldtoken   0x01000002
converting (in B10: stack: 2) IL_005b: call      0x0a00000b
converting (in B10: stack: 2) IL_0060: callvirt  0x0a00000c
converting (in B10: stack: 2) IL_0065: callvirt  0x0a00000d
converting (in B10: stack: 2) IL_006a: stloc.1   
converting (in B10: stack: 1) IL_006b: br        IL_00a2
1 item(s) on exit from B10
created temp 7 (R67) of type System.Object
storing 0 to temp 7
converting (in B12: stack: 0) IL_0070: ldloc.1   
converting (in B12: stack: 1) IL_0071: callvirt  0x0a00000e
converting (in B12: stack: 1) IL_0076: stloc.2   
converting (in B12: stack: 0) IL_0077: ldloc.2   
converting (in B12: stack: 1) IL_0078: call      0x0a00000f
converting (in B12: stack: 1) IL_007d: brtrue    IL_00a1
converting (in B14: stack: 0) IL_0082: ldloc.2   
converting (in B14: stack: 1) IL_0083: callvirt  0x0a000010
converting (in B14: stack: 1) IL_0088: ldlen     
converting (in B14: stack: 1) IL_0089: conv.i4   
converting (in B14: stack: 1) IL_008a: ldc.i4.0  
converting (in B14: stack: 2) IL_008b: ceq       
converting (in B14: stack: 1) IL_008d: ldc.i4.0  
converting (in B14: stack: 2) IL_008e: ceq       
converting (in B14: stack: 1) IL_0090: brtrue    IL_00a1
converting (in B15: stack: 0) IL_0095: ldloc.2   
converting (in B15: stack: 1) IL_0096: ldnull    
converting (in B15: stack: 2) IL_0097: call      0x0a000011
converting (in B15: stack: 1) IL_009c: br        IL_00bc
1 item(s) on exit from B15
storing 0 to temp 7
converting (in B13: stack: 0) IL_00a1: nop       
loading 0 from temp 7
converting (in B11: stack: 1) IL_00a2: ldloc.1   
converting (in B11: stack: 2) IL_00a3: callvirt  0x0a000012
converting (in B11: stack: 2) IL_00a8: brtrue    IL_0070
1 item(s) on exit from B11
storing 0 to temp 7
loading 0 from temp 7
converting (in B17: stack: 1) IL_00ad: ldtoken   0x01000002
converting (in B17: stack: 2) IL_00b7: call      0x0a000013
2 item(s) on exit from B17
```

The stack calculated at IL_0070 is incorrect for all code paths. It will always be reached with "stack: 1".

**Comment by marek-safar** [comment] 2019-07-25 10:18
I looked into that more and I am no longer sure I see the issue either JIT is reporting an issue at `IL_00bc: castclass 0x0100000d` but to me, the stack looks fine. What is suspicious thought that 

`converting (in B11: stack: 2) IL_00a8: brtrue    IL_0070`

has stack 2. It should be just after this call https://github.com/dotnet/corefx/blob/8c2be7893fa585cba9c094c27b69d7c8e0822ef3/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriterILGen.cs#L2478 and have stack depth 1

**Comment by filipnavara** [comment] 2019-07-25 10:27
The whole problem starts at IL_0070 and spreads further from there. IL_00bc is a red herring since at that point you are far away from the original miscalculation. Anything past IL_0050 should have stack >= 1. IL_0070 is reached only through a back-branch at IL_00a8 where stack depth is always 1 after the condition is evaluated hence IL_0070 should start at depth 1 but it does not. This later leads to converging branches at IL_00bc disagreeing.

I am now 99% sure this is Mono issue.

**Comment by marek-safar** [comment] 2019-07-25 10:30
For me `converting (in B11: stack: 2) IL_00a8: brtrue    IL_0070` is the suspicious place. It should have stack: 1 but it has 2 after this call https://github.com/dotnet/corefx/blob/8c2be7893fa585cba9c094c27b69d7c8e0822ef3/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriterILGen.cs#L2478 which is instance method call returning bool

**Comment by marek-safar** [comment] 2019-07-25 10:47
@vargaz helped me to understand this better. `br` instruction does not clear the stack so when we enter `IL_00a2` the stack still contains result of https://github.com/dotnet/corefx/blob/8c2be7893fa585cba9c094c27b69d7c8e0822ef3/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriterILGen.cs#L2465 call which is not wanted here. Simple pop should resolve the issue for this code path to start with clear stack https://gist.github.com/vargaz/57f1193d5f36ef856c94d28cd2d31532

Note: We have a bug in stack depth reporting logging for `nop` instructions as seen at IL_00a1 which should print stack: 1 not stack: 0

**Comment by filipnavara** [comment] 2019-07-25 10:52
The `stack: X` numbers are BEFORE the instruction is executed. The stack at that point should have the return value from `MoveNext` (IL_00a3) and argument 0 from IL_0002.

**Comment by jaykrell** [comment] 2019-07-25 10:54
1.7.5 Backward branch constraints
It shall be possible, with a single forward-pass through the CIL instruction stream for any method, to infer the
exact state of the evaluation stack at every instruction (where by “state” we mean the number and type of each
item on the evaluation stack).
In particular, if that single-pass analysis arrives at an instruction, call it location X, that immediately follows an
unconditional branch, and where X is not the target of an earlier branch instruction, then the state of the
evaluation stack at X, clearly, cannot be derived from existing information. In this case, the CLI demands that
the evaluation stack at X be empty.
Following on from this rule, it would clearly be invalid CIL if a later branch instruction to X were to have a
non-empty evaluation stack

**Comment by filipnavara** [comment] 2019-07-25 10:55
Thanks @jaykrell. I think that's the piece of information that makes it CoreFX bug.

**Comment by jaykrell** [comment] 2019-07-25 10:57
I don't think pop makes it valid. More clearly invalid.
I think you have to store into a local variable to communicate simply across branches, w/o worrying about stack height balancing act.
Perhaps some bogus dead forward branch to the target could do also.

**Comment by filipnavara** [comment] 2019-07-25 11:10
What `ILGenForCreateInstance` generates is itself valid, under the assumption that the stack is empty in the beginning. After all it is replicating what C# compiler does (or did at that time). The problem is that the assumption is violated which results in the violation of the specification (as pasted above).

Fix is to remove the `ldarg.0` at https://github.com/dotnet/corefx/blob/8c2be7893fa585cba9c094c27b69d7c8e0822ef3/src/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationReaderILGen.cs#L3251-L3252. Then stack will be aligned. After `ILGenForCreateInstance` is called we have to store the result in local variable (`stloc.X`), load the argument 0 (`ldarg.0`) and finally load the saved value (`ldloc.X`).

**Comment by MaximLipnin** [comment] 2020-01-27 12:49
This issue was addressed in https://github.com/dotnet/runtime/pull/2087 and I had no repro for this test within the work https://github.com/dotnet/runtime/pull/2087. I'm closing it.

**Closed by MaximLipnin** 2020-01-27 12:49 UTC
Labels: area-netcore: CoreLib, epic: CoreFX tests
