### ISSUE TITLE
Crash while debugging a Blazor page in a large project after hanging for a very long time

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19924] opened 2020-06-05 17:38 UTC
---
**Issue moved from dotnet/aspnetcore#22584**
- Please respond to @vsfeedback.

---

_From @vsfeedback on Friday, June 5, 2020 5:37:59 PM_

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1064741/crash-while-debugging-a-blazor-page-in-a-large-pro.html)._

---
Crash while debugging a Blazor page in a large project after hanging for a very long time

Crash dump has been attached

---
#### Visual Studio Feedback System on 6/5/2020, 02:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2020-06-05 17:39
@lewing have got this through VS Feedback. The dump is available in AZDO for investigation.

**Comment by lewing** [comment] 2020-07-08 12:44
@thaystg can you take a look at the log an verify it isn't the proxy?

**Comment by thaystg** [comment] 2020-07-08 13:22
Yes, doing it right now! :)

**Comment by thaystg** [comment] 2020-07-08 15:58
Hi, I think that we should close this issue because it's nothing in the proxy. The error is similar to another issue: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1140974
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1137400
The problem is: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by lewing** [comment] 2020-07-10 01:57
Closing.  Please reopen if you think this was closed in err.

**Closed by lewing** 2020-07-10 01:57 UTC
Labels: area-Debugger, target-wasm
