### ISSUE TITLE
Issues with HttpClient on mono 6.0.0.311

### ISSUE THREAD

**Issue by owenniblock** [mono/mono#15830] opened 2019-07-25 16:56 UTC
## Steps to Reproduce

1. Use latest VSfM 8.2
2. [Grab this project on a mac](https://github.com/King-of-Spades/AppCenter-Samples/tree/master/Xamarin.UITest/UITestDemo)
3. Follow the instructions for running the UITests using Xamarin.UITest on iOS
4. See the error
5. Downgrade `mono` to older version (e.g. 5.18.1.28)
6. Rerun the tests
7. Error goes away

### Current Behavior

Test run receives the following error:

```
System.Net.Http.HttpRequestException : Connection refused
  ----> System.Net.Sockets.SocketException : Connection refused
```

### Expected Behavior

Test runs successfully.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 6.0.0.311 (2019-02/494641b300c Mon Jul  1 20:30:26 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Stacktrace

```
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00180] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:84 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ea] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:371 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:529 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x0003f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:284 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00070] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:32 
  at Xamarin.UITest.Shared.Http.HttpClient.Request (System.String method, System.String endpoint, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy, System.Nullable`1[T] timeOut) [0x00103] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest.Shared/Http/HttpClient.cs:79 
  at Xamarin.UITest.Shared.Http.HttpClient.Get (System.String endpoint, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy, System.Nullable`1[T] timeOut) [0x00001] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest.Shared/Http/HttpClient.cs:38 
  at Xamarin.UITest.iOS.HttpCalabashConnection.Version () [0x00001] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest/iOS/HttpCalabashConnection.cs:51 
  at Xamarin.UITest.iOS.iOSAppLauncher.GetCalabashDevice (Xamarin.UITest.iOS.ICalabashConnection connection) [0x00092] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest/iOS/iOSAppLauncher.cs:863 
  at Xamarin.UITest.iOS.iOSAppLauncher.EnsureCalabashRunning (Xamarin.UITest.iOS.ICalabashConnection connection) [0x00001] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest/iOS/iOSAppLauncher.cs:883 
  at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Http.HttpClient httpClient, Xamarin.UITest.TestCloud.TestCloudiOSAppConfiguration testCloudAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient testCloudWsClient, Xamarin.UITest.Shared.Http.HttpClient xtcServicesClient, System.Boolean testCloudUseDeviceAgent) [0x00084] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest/iOS/iOSAppLauncher.cs:91 
  at Xamarin.UITest.iOS.iOSApp..ctor (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Execution.IExecutor executor) [0x002cb] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest/iOS/iOSApp.cs:166 
  at Xamarin.UITest.iOS.iOSApp..ctor (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration) [0x00000] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest/iOS/iOSApp.cs:55 
  at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp (Xamarin.UITest.Configuration.AppDataMode appDataMode) [0x00011] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest/Configuration/iOSAppConfigurator.cs:209 
  at iOSDeviceAgentNullEnvVarTests.BeforeEach () [0x00001] in /Users/owenniblock/Xamarin.UITest/src/IntegrationTests/iOSDeviceAgent/iOSDeviceAgentNullEnvVarTests.cs:20 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:391 
--SocketException
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x000c8] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:65 
```

### Working theory

Something to do with the [introduction of the Sockets Http Handler](https://github.com/mono/mono/commit/6c59f0e12410272c9f203aeacef12833a9e6f96f) is interfering with the operation of the legacy HttpClient.

**Comment by brminnick** [comment] 2019-07-25 17:04
I confirmed the same exception is thrown on Mono v6.4.0.81

**Comment by cheles** [comment] 2019-07-30 10:10
@marek-safar is there any due date for next milestone? I can confirm this regression on my machine, but it's intermitent. I have a developer that reports this happening constantly.
 
@owenniblock 's workaround (downgrade Mono) would imply downgrading Visual Studio for Mac to 8.1 as 8.2 would require mono 6.x to start.

**Comment by owenniblock** [comment] 2019-07-30 10:53
@cheles - you should be able to select the version of Mono you're using in VS 4 Mac (that's what. we're currently doing to work around this issue):

<img width="961" alt="Screenshot 2019-07-30 at 11 51 21" src="https://user-images.githubusercontent.com/4696224/62123786-9680d000-b2c0-11e9-926f-4507308c4f0d.png">

It's happening constantly for us too.

**Comment by marek-safar** [comment] 2019-07-30 12:43
@cheles we are looking into it and would ideally fix it in 6.0 update (cc @steveisok)

**Comment by steveisok** [comment] 2019-08-01 15:32
So, after taking a closer look, Xamarin.UITest is probably going to need to be tweaked because this is a timing issue.  There's a retry routine here: 

`at Xamarin.UITest.iOS.iOSAppLauncher.GetCalabashDevice (Xamarin.UITest.iOS.ICalabashConnection connection)` 

It only retries in the case of a WebException.  They may want to do that blindly because I was able to get it working if I did another pass in the retry loop.

As for why the exception has changed, I can speculate that we're more accurate.  Since iOS is the server in this case, we would have to profile that side to determine for sure. 

At this point, I don't see us needing to fix anything.  @baulig, please double check my assessment.

**Comment by steveisok** [comment] 2019-08-01 15:40
Here's the UITest code I'm referring to in particular:

https://github.com/xamarin/Xamarin.UITest/blob/432c0886064bdd5037d71147b7f2e3560c223609/src/Xamarin.UITest/iOS/iOSAppLauncher.cs#L840-L865

**Comment by owenniblock** [comment] 2019-08-01 16:56
@steveisok - that's awesome. Let me take a look on our side. Apologies, we should have spotted this when we did our initial investigation!

**Comment by baulig** [comment] 2019-08-01 17:23
I believe the new behavior is more correct - `HttpClient` has it's own exception types such as for instance `System.Net.Http.HttpRequestException` and throwing a `System.Net.WebException` doesn't make much sense because not all handlers are even using the `System.Net.WebRequest` framework.

The UITest code needs to be updated to check for `HttpRequestException`.

**Comment by steveisok** [comment] 2019-08-01 17:36
OK, so I think there's enough detail here to close the issue.  Thanks everyone.

**Closed by steveisok** 2019-08-01 17:36 UTC
Labels: area-BCL: System.Net.Http, won't fix
