### ISSUE TITLE
mono/2020-02 Performance Regression

### ISSUE THREAD

**Issue by jonpryor** [mono/mono#19138] opened 2020-03-05 23:24 UTC
The Xamarin.Android team is experiencing a performance regression from mono/2020-02, which is particularly noticeable in our build times.

Xamarin.Android PR which bumps from mono/2019-12 to mono/2020-02: https://github.com/xamarin/xamarin-android/pull/4219

xamarin/xamarin-android@12df2beb AzDO build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3528469&view=results

  * Of note, the **Mac** stage completed in 48 min 24 seconds.

xamarin/xamarin-android#4219 PR build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3521173&view=results

  * Of note, the **Mac** stage completed in 1 hour 18 min 3 seconds.

That's roughly a *30 minute* increase in the build time, with the only significant change being the system mono used to build things.

One particularly apparent increase is around the execution of [`Microsoft.DotNet.ApiCompat.exe`](https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.ApiCompat):

## Steps to Reproduce

1. Download and extract
[`xamarin-android-assemblies.zip`](https://github.com/mono/mono/files/4295575/xamarin-android-assemblies.zip)

2. Download or otherwise obtain `Microsoft.DotNet.ApiCompat.exe`.  The xamarin-android build has a `@(PackageReference)` to a obtain it:

        <PackageReference Include="Microsoft.DotNet.ApiCompat" Version="5.0.0-beta.20078.1" IncludeAssets="none" />

    Though this presumably comes from a custom NuGet source? https://github.com/xamarin/xamarin-android/blob/12df2beba094a7cb767537c2ed062a977a6c8c80/NuGet.config

3. Run `Microsoft.DotNet.ApiCompat.exe`.

```shell
$ time mono packages/microsoft.dotnet.apicompat/5.0.0-beta.20078.1/tools/net472/Microsoft.DotNet.ApiCompat.exe \
    xamarin-android-assemblies/contract/Mono.Android.dll \
    -i xamarin-android-assemblies/reference/Mono.Android.dll
```

### Current Behavior

(3) is where things get *weird*.  My "baseline" on macOS Catalina:

```shell
$ mono --version | head -1
Mono JIT compiler version 6.6.0.155 (2019-08/296a9afdb24 Thu Nov 14 06:12:25 EST 2019)

$ time mono packages/microsoft.dotnet.apicompat/5.0.0-beta.20078.1/tools/net472/Microsoft.DotNet.ApiCompat.exe \
    xamarin-android-assemblies/contract/Mono.Android.dll \
    -i xamarin-android-assemblies/reference/Mono.Android.dll
...
mono  xamarin-android-assemblies/contract/Mono.Android.dll -i   2.46s user 0.11s system 111% cpu 2.298 total
```

When @grendello ran on his Linux machine, with `Mono JIT compiler version 6.10.0.92 (tarball Wed Mar  4 08:49:16 UTC 2020`:

```
real	0m8,933s
user	0m9,390s
sys	0m0,172s
```

(Note: Polish locale, adjust commas as appropriate.))

Compare to when @grendello ran using mono/master, with `Mono JIT compiler version 6.13.0 (master/b91580bafa7 Tue  3 Mar 09:54:44 CET 2020)`:

```
real	4m16,261s
user	5m5,473s
sys	0m34,325s
```

Execution time jumped from ~9s to over *4 minutes*.

### Expected Behavior

We expect mono/2020-02 to have performance similar to mono/2019-12, not ~28x *slower*.

## On which platforms did you notice this

- [X] macOS
- [X] Linux
- [ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by fanyang-mono** [comment] 2020-03-06 18:52
The same root cause as https://github.com/mono/mono/issues/18572

**Comment by marek-safar** [comment] 2020-03-12 17:20
It's very likely this is duplicate of #18572

**Closed by marek-safar** 2020-03-12 17:20 UTC
Labels: area-Runtime: Performance, regression
