### ISSUE TITLE
System.Net.NetworkInformation.Ping: Xamarin Mono Returning Wrong PingReply.Address

### ISSUE THREAD

**Issue by OneVideo** [mono/mono#12684] opened 2019-01-30 15:12 UTC
[N.B.: manual copy of https://developercommunity.visualstudio.com/content/problem/417428/systemnetnetworkinformationping-xamarin-mono-retur.html after 30 days of no propagation/update]

Upon TtlExpired reported in Ping Class's Reply, the Reply Address is not reported as belonging to the intermediate router where the ICMP message was dropped.

- - - Calling C# Code Demonstrating Unexpected Result - - -
```c#
IPAddress[] addresses = Dns.GetHostAddresses(HostNameOrIPAddress);
_destination = addresses[0];

_options = new PingOptions(1, true);

_ping = new Ping();
_ping.PingCompleted += new PingCompletedEventHandler(OnPingCompleted);
_ping.SendAsync(_destination, _timeout, this.Buffer, _options, null);

void OnPingCompleted(object sender, PingCompletedEventArgs e)
{

var address = e.Reply.Address;

// Returning destination address requested in originally issued .SendAsync

// though e.Reply.Status == System.Net.NetworkInformation.IPStatus.TtlExpired

// Expect address of the responding IP router situated between requesting Android runtime and

// host at the requested destination address.

// Network packet sniffer confirms ICMP message is sent from requesting host with Ttl == 1 and reply is made to the requesting host. Expected results can be seen in a Windows 10 host on the same Wi-Fi subnet using tracert in a command shell.

}
```
Compiled for Android runtime: 8.1
Using Visual Studio 2017 version 15.9.4, Xamarin.Android SDK 9.1.4.2, Xamarin 4.12.3.77

Multiple runtimes tested on Wi-Fi network segment with same unexpected behaviors/results: Samsung SM-G920V API 24, Google Pixel 3 API 28

N.B.: Project References

to System.Core at

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Core.dll

to Mono.Android at

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v8.1\Mono.Android.dll

**Comment by marek-safar** [comment] 2019-08-17 11:02
@steveisok could we retest if this is still happening with master?

**Comment by steveisok** [comment] 2019-08-19 19:25
Yep, will do.

**Comment by OneVideo** [comment] 2019-10-16 01:47
Verifying - No Change In Production Release: 
*  Retested using 
    - Target runtime = Google Pixel 3a, Android 9
    - Compile Using Android 10.0 (Q), Deployed Mono = 9.5.0-3
    - Visual Studio 2019 = 16.3.1, Microsoft NETCore Platforms = v3.0.0
*  _ping.PingCompleted += new PingCompletedEventHandler(OnPingCompleted); fires with TtlExpired and reporting address value equaling the requested far-destination IP address and not a/any of the intermediate hosts.

What does it do there?

**Comment by marek-safar** [comment] 2019-10-21 08:01
@steveisok any update on this?

**Comment by steveisok** [comment] 2019-10-21 13:01
I had tried to validate myself, but couldn't reproduce.  I'll ask someone on the team to give it a try.

**Comment by OneVideo** [comment] 2019-10-21 14:49
Thanks for that.

Here is a WinRAR archive of a Xamarin Hello World project with the code inside.  

               https://bit.ly/2BuaKA3

Inside and attached is a screenshot of the PingReply response we see.

We appreciate your responsiveness.

 

With thanks,

OneVideo

**Comment by MaximLipnin** [comment] 2019-11-20 10:07
I've re-tested the attached sample with `VS 2019 16.3.9` and it still has a repro - `e.Reply.Address` has value of destination address not a/any of the intermediate hosts.
We use legacy implementation for `Ping` class and seems that it just re-uses the requested destination address in the reply result.  
(JFR Net Framework works good and returns other address than shown in the attached screenshot.)

**Comment by steveisok** [comment] 2020-03-13 14:42
For android (and other unprivileged scenarios), we are shelling out to ping as we do not have access to raw sockets.  As a result, we just return the destination address as part of the reply.  Core appears to do the same thing.  

I'm going to close this issue as there does not appear to a solution other than what we currently have.

**Closed by steveisok** 2020-03-13 14:42 UTC
Labels: area-BCL: System

**Comment by OneVideo** [comment] 2020-03-26 14:05
We think you are mistaken: MonoTouch was previously revised to perform non-priviledged ICMP, so there is a known-good solution. See:

"So I changed that line (RawSocketPing.cs at line 177) :
pingSocket = new Socket(destEndPoint.AddressFamily, SocketType.Raw, ProtocolType.Icmp);
to that :
pingSocket = new Socket(destEndPoint.AddressFamily, SocketType.Dgram, ProtocolType.Icmp);

And that worked"

references: https://forums.xamarin.com/discussion/410/ping-in-monotouch-icmp-requests
and https://xamarin.github.io/bugzilla-archives/96/964/bug.html
