### ISSUE TITLE
Add support for JsonMediaTypeFormatter for mobile

### ISSUE THREAD

**Issue by ankitgo** [mono/mono#9835] opened 2018-08-01 04:53 UTC
I am trying to use the JsonMediaTypeFormatter and it doesn't work on Xamarin Android. 
Looks like this method is not supported. Is there any plan to add support for this? 
It looks like it is similar to this issue: https://github.com/mono/mono/issues/6376
I am not sure if it is the JsonMediaTypeFormatter that is causing this issue. Is it the one?

Exception: System.TypeInitializationException: The type initializer for 'System.Net.Http.FormattingUtilities' threw an exception.

 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
 	0x26 in object.e508080f-3a8d-4685-a711-e33a56baa3c6	C#
 	0xC in System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor	C#
 	0x1 in Microsoft.VisualStudio.Services.WebApi.VssJsonMediaTypeFormatter..ctor	C#
 	0x4 in Microsoft.VisualStudio.Services.WebApi.VssJsonMediaTypeFormatter..ctor	C#
 	0x84 in Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase..ctor	C#
 	0x4 in Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient..ctor	C#
 	0x34 in Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider..ctor	C#
 	0xF0 in Microsoft.VisualStudio.Services.WebApi.VssConnection..ctor	C#
 	0x5 in Microsoft.VisualStudio.Services.WebApi.VssConnection..ctor	C#
 	0xA in Microsoft.VisualStudio.Services.WebApi.VssConnection..ctor	C#
 	0xD in Microsoft.VisualStudio.Services.WebApi.VssConnection..ctor	C#

**Comment by ankitgo** [comment] 2018-08-01 05:03
I believe it is the JsonMediaTypeFormatter
Tried this line and it fails on Xamarin.Android. 
JsonMediaTypeFormatter jsonMediaTypeFormatter = new JsonMediaTypeFormatter();

**Comment by marek-safar** [comment] 2018-08-01 14:14
Duplicate of #6376

**Closed by marek-safar** 2018-08-01 14:14 UTC
