### ISSUE TITLE
Returning tuple broken when enabling fullAOT+LLVM 

### ISSUE THREAD

**Issue by spouliot** [mono/mono#13610] opened 2019-03-22 17:58 UTC
## Steps to Reproduce

1. Call the following code from an iOS app
```
public static async Task<(bool isAnswerCorrect, bool isInternetConnectionAvailable)> Test ()
{
	return (true, true);
}
```

note: full test case in https://github.com/xamarin/xamarin-macios/issues/5798

2. Run on device **without** LLVM -> success
3. Run on device **with** LLVM -> failure (false is returned)

### Current Behavior

Broken (regression, it works in XI stable) when enabling LLVM

### Expected Behavior

Should work on both mono and LLVM fullAOT backend

## On which platforms did you notice this

[x] iOS
[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

2018-08 (d16-0), 2018-10 (xamarin-macios/master) and 2019-02 are all broken

Current XI stable is fine (2018-04)

## Stacktrace

none

**Comment by spouliot** [comment] 2019-03-22 17:59
c.c. @chamons @vargaz

**Comment by marek-safar** [comment] 2019-03-22 19:08
@alexanderkyte @vargaz please investigate the regression

**Comment by alexanderkyte** [comment] 2019-03-25 17:18
Here, let me add a sane-sized executable reproduction: https://gist.github.com/alexanderkyte/1974de18f51cb2a984908524809ec87c

**Comment by alexanderkyte** [comment] 2019-03-25 17:19
Looks like we don't have any unit tests for this on the mono side, only acceptance/integration tests. This PR caused this breakage: https://github.com/mono/mono/pull/13312 . 

I'll have a fix for this shortly. 

We need to add this bug reproduction to the test harness at some point.

**Comment by lewurm** [comment] 2019-03-25 17:22
> This PR caused this breakage: #13312 .

Mentioned PR was merged 6 days ago, but the bug started to happen with `2018-08`. Regression was likely introduced by something else.

**Comment by alexanderkyte** [comment] 2019-03-25 17:36
```

	0x10220f7f4 - /Users/akyte/perf_mono/mono/mono/mini/mono : dump_native_stacktrace
	0x10220f736 - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_dump_native_crash_info
	0x1020c8b45 - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_handle_native_crash
	0x10220eb10 - /Users/akyte/perf_mono/mono/mono/mini/mono : sigabrt_signal_handler
	0x7fff6c299f5a - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x1038629f8 - /Users/akyte/perf_mono/mono/mono/mini/mono : eg_my_charset
	0x7fff6c0371ae - /usr/lib/system/libsystem_c.dylib : abort
	0x7fff6bfff1ac - /usr/lib/system/libsystem_c.dylib : basename_r
	0x10216f4ea - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_llvm_set_call_nonnull_ret
	0x10216acc5 - /Users/akyte/perf_mono/mono/mono/mini/mono : process_call
	0x102158aff - /Users/akyte/perf_mono/mono/mono/mini/mono : process_bb
	0x102149438 - /Users/akyte/perf_mono/mono/mono/mini/mono : emit_method_inner
	0x1021477cf - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_llvm_emit_method
	0x101fb0231 - /Users/akyte/perf_mono/mono/mono/mini/mono : mini_method_compile
	0x101fb410b - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_jit_compile_method_inner
	0x101fba348 - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_jit_compile_method_with_opt
	0x101fb99bd - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_jit_compile_method
	0x1020cf2a8 - /Users/akyte/perf_mono/mono/mono/mini/mono : common_call_trampoline
	0x1020ce4c8 - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_magic_trampoline
	0x103e17393 - Unknown
	0x103ee60e4 - Unknown
```

**Comment by alexanderkyte** [comment] 2019-03-25 17:37
```	0x10216f4ea - /Users/akyte/perf_mono/mono/mono/mini/mono : mono_llvm_set_call_nonnull_ret
```

was not merged until https://github.com/mono/mono/pull/13312

**Comment by vargaz** [comment] 2019-03-25 20:25
I can reproduce. When was the last time this worked ?

**Comment by spouliot** [comment] 2019-03-25 20:27
mentioned above
_2018-08 (d16-0), 2018-10 (xamarin-macios/master) and 2019-02 are all broken

Current XI stable is fine (2018-04)
_

**Comment by vargaz** [comment] 2019-03-25 20:29
So 2018-04 was still using the old llvm 3.6.

**Comment by spouliot** [comment] 2019-03-25 20:35
ouch :(

**Comment by lambdageek** [comment] 2019-03-26 00:08
Doesn't have to be a tuple.  This also fails (prints 0. expected to print 1)

```
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

public struct OneThing<T1> {
	public T1 Item1;
}

public class P {

	[MethodImpl (MethodImplOptions.NoInlining)]
	public static int TestCaller () {
		var t = Task.FromResult<OneThing<int>>(new OneThing<int> {Item1 = 42});
		t.Wait ();
		double a = t.Result.Item1;
		return (a == 42) ? 1 : 0;
	}

	public static int Main () {
		var t = TestCaller ();
		var i = t;
		Console.WriteLine ($"{i}");
		return 0;
	}
}
```

compile with `mono --runtime=mobile --aot=llvmonly example.exe` run with `mono --runtime=mobile --llvmonly example.exe`

[example.opt.ll](https://gist.github.com/lambdageek/a57798e212c1306f66f53615292cd2be)

**Comment by lambdageek** [comment] 2019-03-26 00:18
Don't need  tasks either.  Just a generic method will do.

```csharp
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

public struct OneThing<T1> {
	public T1 Item1;
}

public class S<T> {
	public T Result;

	public S(T val) {
		Result = val;
	}

}

public class Maker {
	[MethodImpl (MethodImplOptions.NoInlining)]
	public static S<T> FromResult<T> (T result) {
		return new S<T>(result);
	}
}

public class P {

	[MethodImpl (MethodImplOptions.NoInlining)]
	public static int TestCaller () {
		var t = Maker.FromResult<OneThing<int>>(new OneThing<int> {Item1 = 42});
		int a = t.Result.Item1;
		return (a == 42) ? 1 : 0;
	}

	public static int Main () {
		var t = TestCaller ();
		var i = t;
		Console.WriteLine ($"{i}");
		return 0;
	}
}
```

**Comment by rolfbjarne** [comment] 2019-03-27 15:15
I bumped mono in our d16-0 branch to the tip of 2018-08, and I can still repro the problem, both with the test cases from https://github.com/mono/mono/issues/13610#issuecomment-476296234 and https://github.com/mono/mono/issues/13610#issuecomment-476425907.

This is the bump: https://github.com/xamarin/xamarin-macios/commit/ae85cc5dc8e5812a84c9c68682db9e56585c03a6 (the `d16-0-mono-13610` branch).

CC @chamons

**Closed** 2019-03-28 12:07 UTC
Labels: area-Runtime: AOT, regression, target-xamarin-ios
