### ISSUE TITLE
msbuild msvc\mono.sln fails with VS2015 (ok with VS2017)

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#8877] opened 2018-05-25 11:02 UTC
## Steps to Reproduce

1. git clone mono
2. install vs, ~~either vs2015 or~~ 2017 with also the 2015 tools
3. open a vs2015 command windows (2017 works)

### Current Behavior

Many errors like:
C:\s2\mono\msvc\build-init.vcxproj(30,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not

### Expected Behavior

Build without error, or tell me to use VS2017.
(really I'd like to use cmake than msbuild, one meta  build system for all targets but oh well)

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Comment by akoeplinger** [comment] 2018-05-25 11:07
This sounds like your C++ installation in VS2015 isn't working. Which workloads did you install?

**Comment by marek-safar** [comment] 2018-05-25 11:27
@lateralusX is that intentional?

**Comment by lateralusX** [comment] 2018-05-25 11:52
This should work (I'm running full VS 2015/2017 on the same machine) and that import is initially coming straight from the vcxproj template, so either the vcxproj have been updated to a new tools version where $(VCTargetsPath) is not properly set or that there is a problem with the installed VS2015 build tools. I expect it to work if you use full VS2015 or VS2017 and that is what's been running on Jenkins for a long time (VS2015), running VS2017 with VS2015 build tools and then build from MSBuild could be a scenario not tested before (at least I have not done that in the past), but since this is pretty much coming from vanilla vcxproj's VS2015 template, all C/C++ VS2015 vcxproj's will probably fail on this machine.

**Comment by jaykrell** [comment] 2018-05-25 13:48
This is VS2017 with also the VS2015 tools. Not a full VS2015.

**Comment by jaykrell** [comment] 2018-05-25 17:26
The initial issue describes two scenarios but sorry I meant just one -- VS2017 w/ VS2015 tools, not full 2015 that I didn't try.

**Comment by lateralusX** [comment] 2018-05-28 06:33
OK, so then this is probably a problem with either this specific install or the build tools workload together with msbuild. I have successfully build using pure VS2017 build tool installation as well as VS2015 and VS2017 with C/C++ workloads (both community and professional versions). I think we could leave this as is for now and if several people need this scenario revisit later.

**Comment by lateralusX** [comment] 2018-10-25 08:08
Validated on clean image including VS 2015 C++ build tools and it works. Also validated when adding VS 2017 build tools with "Visual C++ build tools" workload into the same image, having both VS 2017 and VS2015 build tools installed at the same time. Build using the VS 2015 msbuild environment using C:\Program Files (x86)\Microsoft Visual C++ Build Tools\vcbuildtools_msbuild.bat. Build using the VS 2017 msbuild environment using C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsMSBuildCmd.bat. Closing this issue as "No repro".

**Closed by lateralusX** 2018-10-25 08:08 UTC
Labels: area-Build, os-windows

**Comment by jaykrell** [comment] 2018-10-25 08:17
I reproed this recently.
It is using the VS2015 command line that is optionally installed with VS2017.

**Comment by lateralusX** [comment] 2018-10-25 13:56
OK, looked a little more into this and installed VS 2017 "Desktop development with C++" workload together with VC++ 2015.3 v14.00 (v140) toolset for desktop. I could then get similar errors if I try to use one of the VS 2015 preconfigured command prompts. The problem is that the $(VCTargetsPath) variable used in vcxprojs are not defined in that environment. This is a known problem with VC++ 2015.3 v14.00 (v140) toolset for desktop as described by this post https://developercommunity.visualstudio.com/content/problem/270758/vc-20153-v1400-v140-toolset-for-desktop-does-not-s.html and resolved as designed and not a Mono build related issue. You can either start a command prompt as specified in the post or use a VS 2017 development command prompt.
