### ISSUE TITLE
MemoryLeak in Directory.GetFiles

### ISSUE THREAD

**Issue by HeikoWeiss** [mono/mono#7734] opened 2018-03-21 12:06 UTC
## Steps to Reproduce

1. just do in a loop for example: Directory.GetFiles( "/var/log" )

## Current Behavior

MemoryLeak

### On which platforms did you notice this

[ ] macOS
[ X] Linux
[ ] Windows

**Version Used**:

5.11.0.345

### Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by akoeplinger** [comment] 2018-03-21 19:16
This is most likely a duplicate of https://github.com/mono/mono/issues/7655.

**Comment by HeikoWeiss** [comment] 2018-03-22 06:15
I tried this, and it seems to fix the memory leak:

File: w32file-unix.c
Method: findhandle_close
Change:
...
	removed = g_hash_table_remove (finds, (gpointer) findhandle);
	g_assert (removed);

        /* Insert --> */ mono_refcount_dec (findhandle);

	mono_coop_mutex_unlock (&finds_mutex);
....

**Comment by marek-safar** [comment] 2018-03-22 10:06
Closing as a duplicate

**Closed by marek-safar** 2018-03-22 10:06 UTC
Labels: area-BCL: mscorlib
