### ISSUE TITLE
flaky System.IO.Tests.FileSystemWatcherTests.System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_StopCalledOnBackgroundThreadDoesNotDeadlock

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#9565] opened 2018-07-14 22:37 UTC
## Steps to Reproduce

1. Submit a PR.

### Current Behavior

Flaky failures, for example:

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64/16045/

```
	Test Result (1 failure / +1)
Test collection for System.IO.Tests.FileSystemWatcherTests.System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_StopCalledOnBackgroundThreadDoesNotDeadlock
	
https://jenkins.mono-project.com/job/test-mono-pull-request-amd64/16045/testReport/junit/Test%20collection%20for%20System.IO.Tests/FileSystemWatcherTests/System_IO_Tests_FileSystemWatcherTests_FileSystemWatcher_StopCalledOnBackgroundThreadDoesNotDeadlock/

                                                MESSAGE:
                                                Assert.True() Failure\nExpected: True\nActual:   False
                                                +++++++++++++++++++
                                                STACK TRACE:
                                                  at System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_StopCalledOnBackgroundThreadDoesNotDeadlock () [0x000b7] in /mnt/jenkins/workspace/test-mono-pull-request-amd64/external/corefx/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs:616 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in /mnt/jenkins/workspace/test-mono-pull-request-amd64/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
```

### Expected Behavior

Success.

**Comment by lewurm** [comment] 2018-07-16 10:03
duplicate of https://github.com/mono/mono/issues/9561

**Closed by lewurm** 2018-07-16 10:03 UTC
Labels: area-BCL: System, flaky issue
