### ISSUE TITLE
Subscribing to NetworkChange.NetworkAddressChanged crashes on Mono.Android

### ISSUE THREAD

**Issue by nor0x** [mono/mono#15399] opened 2019-06-25 13:55 UTC
## Steps to Reproduce

1. Create new Mono.Android project (test case is Xamarin.Forms with Android platform backend)
2. Try subscribing to `NetworkChange.NetworkAddressChanged` event
3. Run code on arm64-v8a

Here is a link to a basic repro project that keeps crashing for me
[https://github.com/nor0x/mono_NetworkChangeRepro](https://github.com/nor0x/mono_NetworkChangeRepro)

This repro is working fine on Xamarin.iOS (Simulator and Device) and Xamarin.Android (Simulator). It only fails on my Android device.

I also noticed that there is already the closed issue #8263 - but the solution there didn't work for me. 

### Current Behavior

The app crashes when a subscription to the `NetworkChange.NetworkAddressChanged` is added.

### Expected Behavior

Not crashing and successfully receiving events of `NetworkChange.NetworkAddressChanged`

## On which platforms did you notice this

[x] Android

**Version Used**:

Mono 5.18.1.28

## Stacktrace
this is the only output I get when the crash happens
```
[hwaps] JNI_OnLoad
[Mono] DllImport unable to load library 'dlopen failed: library "/System/Library/Frameworks/SystemConfiguration.framework/libSystemConfiguration" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "/System/Library/Frameworks/SystemConfiguration.framework/libSystemConfiguration" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "/System/Library/Frameworks/CoreFoundation.framework/libCoreFoundation" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "/System/Library/Frameworks/SystemConfiguration.framework/libSystemConfiguration" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "/System/Library/Frameworks/SystemConfiguration.framework/libSystemConfiguration" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "/System/Library/Frameworks/SystemConfiguration.framework/libSystemConfiguration" not found'.
Thread started: <Thread Pool> #2
[] * Assertion at /Users/builder/jenkins/workspace/xamarin-android-d16-1/xamarin-android/external/mono/mono/metadata/threadpool-io.c:368, condition `fd >= 0' not met
[libc] Fatal signal 6 (SIGABRT), code -6 in tid 7788 (Thread Pool I/O)
```

Maybe somebody can help me out here. Thanks

**Comment by jaykrell** [comment] 2019-06-26 10:02
Should be fixed by https://github.com/mono/mono/pull/15408.
Regressed by https://github.com/mono/mono/pull/11599.

**Comment by lambdageek** [comment] 2019-06-26 15:45
Jay is correct - @CoffeeFlux is working on this in #15408.

@nor0x does the assertion happen for you with Xamarin Android 9.4 (Visual studio for mac 8.2 Preview)?  @CoffeeFlux and I had a substantially similar repro, but it didn't crash for us with XA 9.4, only with XA 9.3 (Visual Studio for mac 8.1)

**Comment by lambdageek** [comment] 2019-06-26 15:48
This is a duplicate of https://github.com/mono/mono/issues/14848

**Comment by CoffeeFlux** [comment] 2019-06-26 19:43
Closed by https://github.com/mono/mono/commit/19bb89805ac2eb56b09fed40cab1dd342f97a5e3

**Closed by CoffeeFlux** 2019-06-26 19:43 UTC
Labels: area-Runtime: Threading, target-amd64, target-arm64, target-xamarin-android

**Comment by nor0x** [comment] 2019-06-27 05:59
sorry for the duplicate post and thanks for the fix 🙌
