### ISSUE TITLE
Sigsegv in libmacho.dylib getsectbynamefromheader_64

### ISSUE THREAD

**Issue by Therzok** [mono/mono#20107] opened 2020-07-13 14:28 UTC
## Steps to Reproduce

1. N/A, see https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1147473

### Current Behavior

```
[System.dll] System.Diagnostics.Process.GetModules_internal +11
[System.dll] System.Diagnostics.Process.get_Modules +16
```

This seems to be causing a crash in `getsectbynamefromheader_64`. Maybe null is being passed to it?

### Expected Behavior

No crash.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:

6.10.0.104

## Stacktrace

```
[libmacho.dylib] getsectbynamefromheader_64 +19
[libmonosgen-2.0.1.dylib] mono_w32process_get_modules +67
[libmonosgen-2.0.1.dylib] mono_w32process_module_get_name +112
[libmonosgen-2.0.1.dylib] ves_icall_System_Diagnostics_Process_GetModules_internal +25e
[libmonosgen-2.0.1.dylib] ves_icall_System_Diagnostics_Process_GetModules_internal_raw +53
[System.dll] Unknown +0
[System.dll] System.Diagnostics.Process.GetModules_internal +0
[System.dll] System.Diagnostics.Process.get_Modules +0
```

**Comment by SamMonoRT** [comment] 2020-07-15 17:47
@imhameed - this is the issue we spoke about in the meeting this morning

**Comment by Therzok** [comment] 2020-07-26 01:59
Is there something else you need from our side to be able to figure this out?

**Comment by kdubau** [comment] 2020-08-13 20:31
This only happens on Big Sur.

**Comment by Therzok** [comment] 2020-08-13 23:19
I see hits in 10.15 and 10.14 aswell though.

**Comment by imhameed** [comment] 2020-08-19 00:33
I don't really know what to make of any of the information in the AzDO bug, and I haven't been able to reproduce this with a managed program locally. I did create a small C test program that crashes with a `EXC_BAD_ACCESS`/`SIGSEGV` at the same relative instruction address in `getsectbynamefromheader_64` that is reported in this issue (0x19). This happens when `getsectbynamefromheader_64` is passed a pointer to memory that hasn't been mapped for reading.

We pass the result of `_dyld_get_image_header` to `getsectbynamefromheader_64` in [`mono_w32process_get_modules`](https://github.com/mono/mono/blob/66e2b84002f037d7fd07d399f31196f05bd19597/mono/metadata/w32process-unix-osx.c#L144). From what I can tell by reading the dyld source code, there are two cases here that can make `_dyld_get_image_header` return an invalid pointer:
1. A `dlopen`ed library was concurrently unloaded between the call to `_dyld_image_count` and `_dyld_get_image_header`, and `i` has advanced beyond the new loaded image size limit. `_dyld_get_image_header` will then return `NULL` for the out of bounds index we pass to it.
2. A `dlopen`ed library was concurrently unloaded between the call to `_dyld_get_image_header` and `getsectbynamefromheader_64`. The image header pointer returned by `_dyld_get_image_header` was valid at the time of the call but was made invalid after the pages comprising the loaded MachO image were unloaded.

Adding "null checks" would help us avoid 1 but not 2. We could alternatively use `_dyld_register_func_for_add_image` and `_dyld_register_func_for_remove_image`; the callback we'd pass to them would run under a dyld-internal lock that also protects dyld's internal array of all loaded images [1], so we could maintain a list of loaded modules in the runtime that we can safely sample from.

[1] This isn't entirely true for dyld3. From an initial reading it looks like there's a possible race, when dyld3 is enabled, where one thread calls `_dyld_register_func_for_add_image`, another thread calls `dlopen`, and the callback in the first thread isn't notified of the image `dlopen`ed in the second thread. See `addLoadNotifier` in [AllImages.cpp](https://opensource.apple.com/source/dyld/dyld-733.6/dyld3/AllImages.cpp.auto.html). But I'm not completely sure about this yet. This shouldn't be a problem for us anyway, because we'd call `_dyld_register_func_for_add_image` early during the initialization of the runtime.

**Comment by SamMonoRT** [comment] 2020-08-24 23:09
@imhameed @Therzok - we'll need to backport the fix to 2020-02. Keeping this issue open till we complete the backport.

**Comment by imhameed** [comment] 2020-08-25 17:06
https://github.com/mono/mono/commit/620cf538206fe0f8cd63d76c502149b331f56f51 was committed to 2020-02. I'm closing this issue.

**Closed by imhameed** 2020-08-25 17:06 UTC
Labels: area-Runtime: PAL
