### ISSUE TITLE
Cryptography:  ArgumentNullException exception loading SignedCms

### ISSUE THREAD

**Issue by dtivel** [mono/mono#7456] opened 2018-03-07 14:38 UTC
## Steps to Reproduce
In PowerShell:
1. Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/v4.6.0/nuget.exe -OutFile nuget.exe
2. Invoke-WebRequest -Uri https://www.nuget.org/api/v2/package/TestPackage.AuthorSigned/1.0.0 -OutFile TestPackage.AuthorSigned.1.0.0.nupkg
3. & 'C:\Program Files\Mono\bin\mono.exe' .\nuget.exe verify -Signatures .\TestPackage.AuthorSigned.1.0.0.nupkg -Verbosity Detailed

## Current Behavior
`SignedCms.Decode(...)` fails with an `ArgumentNullException`.  Consequently, NuGet is unable to validate a package signature.

## Expected Behavior
Functional parity with .NET Framework 4.6 cryptography.

### On which platforms did you notice this

[ ] macOS ([mhutch first discovered this on macOS](https://github.com/NuGet/Home/issues/6634))
[ ] Linux
[X] Windows

**Version Used**:

Mono:  5.10.0
NuGet:  4.6.0.4971

### Stacktrace

```
Value cannot be null.
Parameter name: keyValue
System.ArgumentNullException: Value cannot be null.
Parameter name: keyValue
  at System.Security.Cryptography.X509Certificates.X509Utils.FindOidInfo (System.UInt32 keyType, System.String keyValue, System.Security.Cryptography.OidGroup oidGroup) [0x00003] in <d41da37a36b24e48860314e6379f5847>:0
  at System.Security.Cryptography.X509Certificates.X509Utils.FindOidInfoWithFallback (System.UInt32 key, System.String value, System.Security.Cryptography.OidGroup group) [0x00000] in <d41da37a36b24e48860314e6379f5847>:0
  at System.Security.Cryptography.Oid..ctor (System.String oid, System.Security.Cryptography.OidGroup group, System.Boolean lookupFriendlyName) [0x00009] in <d41da37a36b24e48860314e6379f5847>:0
  at System.Security.Cryptography.Oid..ctor (System.String oid) [0x00000] in <d41da37a36b24e48860314e6379f5847>:0
  at System.Security.Cryptography.Pkcs.SignerInfo..ctor (System.String hashName, System.Security.Cryptography.X509Certificates.X509Certificate2 certificate, System.Security.Cryptography.Pkcs.SubjectIdentifierType type, System.Object o, System.Int32 version) [0x0000d] in <db525cea83484147adbc43bccfb2e015>:0
  at System.Security.Cryptography.Pkcs.SignedCms.Decode (System.Byte[] encodedMessage) [0x001e4] in <db525cea83484147adbc43bccfb2e015>:0
  at NuGet.Packaging.Signing.Signature.Load (System.Byte[] data) [0x00016] in <65ffefa648c943c5bf72ce3f67c65a94>:0
  at NuGet.Packaging.Signing.Signature.Load (System.IO.Stream stream) [0x00026] in <65ffefa648c943c5bf72ce3f67c65a94>:0 
  at NuGet.Packaging.PackageArchiveReader+<GetSignatureAsync>d__24.MoveNext () [0x000cb] in <65ffefa648c943c5bf72ce3f67c65a94>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at NuGet.Packaging.Signing.PackageSignatureVerifier+<VerifySignaturesAsync>d__3.MoveNext () [0x001ad] in <65ffefa648c943c5bf72ce3f67c65a94>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at NuGet.Commands.VerifyCommandRunner+<VerifySignatureForPackageAsync>d__3.MoveNext () [0x000a6] in <65ffefa648c943c5bf72ce3f67c65a94>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <015934fc22b447f8a64cfcd71d6a204c>:0
  at NuGet.Commands.VerifyCommandRunner+<ExecuteCommandAsync>d__2.MoveNext () [0x00191] in <65ffefa648c943c5bf72ce3f67c65a94>:0
```

**Comment by marek-safar** [comment] 2018-03-07 15:20
Duplicate of #7413

**Closed by marek-safar** 2018-03-07 15:20 UTC
