### ISSUE TITLE
[2019-12] System.Core tests crash on iOS 64b devices.

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#18455] opened 2020-01-14 22:37 UTC
In the integration PR (https://github.com/xamarin/xamarin-macios/pull/7537) we are running into issues when running the System.Core tests from the second part of the split test dll.

An example of the segfault can be found here:

07:44:26.2262310 	0x105a7e334 - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : mono_dump_native_crash_info
07:44:26.2262380 	0x105a746bc - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : mono_handle_native_crash
07:44:26.2262670 	0x105a82a14 - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : mono_sigsegv_signal_handler
07:44:26.2262730 	0x194880894 - /usr/lib/system/libsystem_platform.dylib : <redacted>
07:44:26.2262760 	0x105bb88c4 - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : sgen_check_whole_heap_stw
07:44:26.2263920 	0x105bb7a04 - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : sgen_check_whole_heap_stw
07:44:26.2264090 	0x105bb432c - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : sgen_perform_collection
07:44:26.2264420 	0x105bb40f4 - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : sgen_ensure_free_space
07:44:26.2265700 	0x105baa2d4 - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : sgen_alloc_obj_nolock
07:44:26.2265940 	0x105b63604 - /private/var/containers/Bundle/Application/A4488A3B-0BB2-4955-A96F-F648A0C80E5E/com.xamarin.bcltests.SystemCoreXunit Part 2.app/Frameworks/Mono.framework/Mono : mono_gc_alloc_vector

the tests only fail/crash on release mode on a device. The following links contain useful information:

* Full test run [report](http://xamarin-storage/jenkins/xamarin-macios/pull-request/6f9193f5775639a80101bd2bbcf2605aed544719/3382850/device-tests/jenkins-results/tests/index.html).
* Full [crash](http://xamarin-storage/jenkins/xamarin-macios/pull-request/6f9193f5775639a80101bd2bbcf2605aed544719/3382850/device-tests/jenkins-results/tests/%5bxUnit%5d%20Mono%20SystemCoreXunit%20Part%202/1853/run-dfa7a72864912a924fe96ee65ce8551f3210a068-20200114_074413.log).

**Comment by SamMonoRT** [comment] 2020-01-14 22:48
@BrzVlad can you take a look.

**Comment by BrzVlad** [comment] 2020-01-14 23:11
the stacktrace makes no sense

**Comment by akoeplinger** [comment] 2020-01-15 10:57
It looks like the test run was aborted after timeout, the full crash dump in http://xamarin-storage/jenkins/xamarin-macios/pull-request/6f9193f5775639a80101bd2bbcf2605aed544719/3382850/device-tests/jenkins-results/tests/%5bxUnit%5d%20Mono%20SystemCoreXunit%20Part%202/1853/run-dfa7a72864912a924fe96ee65ce8551f3210a068-20200114_074413.log shows `08:29:24.0727520 Test run timed out after 45 minute(s).`

**Comment by BrzVlad** [comment] 2020-01-15 18:58
I reproduced a crash in the GC running those tests. The culprit is wrong generated code by llvm, which overflows an array, caused by https://github.com/mono/mono/pull/18041. The commit looks revertable.

The problem with the generated code is that it uses a stp instruction (which writes 16bytes) to write a 12byte value type in an array (the value type element is generic instance).

@vargaz Might have this been fixed on master ? Should we revert the commit ?

**Comment by BrzVlad** [comment] 2020-01-15 23:05
```
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

public class MyList<T> {

        T[] array = new T[4];
        int size = 0;

        [MethodImpl(MethodImplOptions.NoInlining)]
        public void MyAdd(T item)
        {   
            if (size < (uint)array.Length)
            {   
                array [size] = item;
                size++;
            }
        }

}

public class Program {
        public static int Main (string[] args)
        {
                var p = new MyList<KeyValuePair<int, KeyValuePair<int,int>>> ();
                KeyValuePair<int, KeyValuePair<int,int>> kvp = new KeyValuePair<int, KeyValuePair<int,int>> (3, new KeyValuePair<int,int> (1, 2));

                p.MyAdd (kvp);
                p.MyAdd (kvp);
                p.MyAdd (kvp);
                p.MyAdd (kvp);
                GC.Collect (0);
                return 0;
        }
}
```

Repro case above for any platform. Compile the repro above with `--aot=full,llvm` and run the application in --full-aot mode. The array will be overflowed, the buggy method is `MyList_1_T_INST_MyAdd_T_INST`. In order to confirm the corruption, run with `MONO_GC_DEBUG=nursery-canaries,no-managed-allocator`.

@vargaz Do you want to give a quick attempt at the bug, or revert and leave for later ?

**Comment by vargaz** [comment] 2020-01-15 23:29
Will look into it

**Comment by lambdageek** [comment] 2020-01-23 21:06
Also needs #18552 and backports

**Comment by BrzVlad** [comment] 2020-01-29 11:27
@lewurm @vargaz Is there anything left to fix here ?

**Comment by lewurm** [comment] 2020-01-29 11:53
> @lewurm @vargaz Is there anything left to fix here ?

maybe a missing backport https://github.com/mono/mono/pull/18552#issuecomment-579395342, but that doesn't affect iOS as far as I know.

**Comment by akoeplinger** [comment] 2020-11-17 11:39
Closing this since the XI integration PR landed with the fix and we don't care about 2019-10 anymore so a backport isn't needed.

**Closed by akoeplinger** 2020-11-17 11:39 UTC
