### ISSUE TITLE
Strings with UTF8 multi-byte characters are corrupted in writing on mono

### ISSUE THREAD

**Issue by AigioL** [mono/mono#18509] opened 2020-01-20 01:18 UTC
## Steps to Reproduce

https://github.com/neuecc/MessagePack-CSharp/issues/782

```cs
var user2 = MessagePackSerializer.Deserialize<UserDTO>(MessagePackSerializer.Serialize(user));
```

https://github.com/AigioL/MessagePack.Tests.NUnit.Droid/blob/75509708a97bf365f6eda4b669af65db423de369/MsgPackV1.Tests.NUnit.Droid/TestClass.cs#L21-L33

https://github.com/AigioL/MessagePack.Tests.NUnit.Droid/blob/master/MsgPackV1.Tests.NUnit.Droid/Models/UserDTO.cs

<img src="https://raw.githubusercontent.com/AigioL/MessagePack.Tests.NUnit.Droid/master/screenshot/2.0.335+1efbae4115.jpg" width=240>

### Current Behavior

```cs
user.NickName == user2.NickName // false
```

<img src="https://raw.githubusercontent.com/AigioL/MessagePack.Tests.NUnit.Droid/master/screenshot/debug.png">

### Expected Behavior

```cs
user.NickName == user2.NickName // true
```

## On which platforms did you notice this

- Linux
- Windows

**Version Used**:
MessagePack [v2.0.335+1efbae4115](https://www.nuget.org/packages/MessagePack/2.0.335)
VisualStudio.16.Release/16.4.2+29613.14
Xamarin.Android SDK   10.1.1.0 (d16-4/f2c9364)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: bef1e63
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

**Comment by CoffeeFlux** [comment] 2020-01-21 16:14
Isn't this just a duplicate of #18516?

**Comment by AigioL** [comment] 2020-01-21 16:15
duplicate #18516

**Closed** 2020-01-21 16:16 UTC
