### ISSUE TITLE
5.12 Core dump while writing to a stream

### ISSUE THREAD

**Issue by NickCraver** [mono/mono#8965] opened 2018-05-31 01:46 UTC
I'm not that familiar with Mono, but we were trying to get the StackExchange.Redis builds to work without issue on it and hit some bugs in 5.12 but not in 5.10.1.47. Contextual information is at the end of this PR: https://github.com/StackExchange/StackExchange.Redis/pull/314#issuecomment-393358956.

I was unable to get a minimal repro, but was able to readily reproduce it with out build via WSL + Mono.

#### Repro steps, though there are probably better ways
On Windows:
1. Grab [StackExchange.Redis @ee12f613](https://github.com/StackExchange/StackExchange.Redis/commit/ee12f61368784e31ab8ccb6bbe7b0ae530e6558f)
2. Run `build.cmd`, or open the `StackExchange.Redis.sln` and build via Visual Studio.
3. Run `<repo>\RedisConfigs\start-all.cmd` (runs the redis servers to test against)

In WSL:
1. Manually run the xunit tests from within the `net462` folder, example run:
```
<snip>/StackExchange.Redis/StackExchange.Redis.Tests/bin/Release/net462$
mono /mnt/c/Users/<user>/.nuget/packages/xunit.runner.console/2.4.0-beta.2.build3981/tools/net452/xunit.console.exe StackExchange.Redis.Tests.dll -class "StackExchange.Redis.Tests.Config"
```

Here's what happens:
```
xUnit.net Console Runner v2.4.0-beta.2.build3981 (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: StackExchange.Redis.Tests
  Discovered:  StackExchange.Redis.Tests
  Starting:    StackExchange.Redis.Tests
* Assertion at local-propagation.c:330, condition `ins->opcode > MONO_CEE_LAST' not met

* Assertion at local-propagation.c:330, condition `ins->opcode > MONO_CEE_LAST' not met
Stacktrace:
  at <unknown> <0xffffffff>
  at StackExchange.Redis.PhysicalConnection.WriteUnified (System.IO.Stream,byte[],string) <0x000a3>
  at StackExchange.Redis.PhysicalConnection.Write (StackExchange.Redis.RedisKey) <0x0009b>
  at StackExchange.Redis.Message/CommandKeyMessage.WriteImpl (StackExchange.Redis.PhysicalConnection) <0x00053>
  at StackExchange.Redis.LoggingMessage.WriteImpl (StackExchange.Redis.PhysicalConnection) <0x000b6>
  at StackExchange.Redis.PhysicalBridge.WriteMessageToServer (StackExchange.Redis.PhysicalConnection,StackExchange.Redis.Message) <0x0031a>
  at StackExchange.Redis.PhysicalBridge.WriteMessageDirect (StackExchange.Redis.PhysicalConnection,StackExchange.Redis.Message) <0x0031f>
  at StackExchange.Redis.PhysicalBridge.WriteQueue (int) <0x0016b>
  at StackExchange.Redis.SocketManager.WriteAllQueues () <0x0018f>
Aborted (core dumped)
```
([here's the method at the top of that stack for reference](https://github.com/StackExchange/StackExchange.Redis/blob/ee12f61368784e31ab8ccb6bbe7b0ae530e6558f/StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs#L581))

#### On which platforms did you notice this
 - [ ] macOS
 - [x] Linux (Ubuntu 18.04 under WSL)
 - [ ] Windows

I'm unfamiliar with Mono, but wanted to note this regression between 5.10.1.47 and 5.12. Hopefully this is a dupe and it's already been resolved :)

**Comment by marek-safar** [comment] 2018-06-03 06:53
@vargaz does this look like regression?

/cc @luhenry

**Comment by vargaz** [comment] 2018-06-03 11:19
This is similar to what was fixed by:
https://github.com/mono/mono/commit/3aeeae6230445e3544fde47221edf45f5230a316
but it could be a different problem.

**Comment by knocte** [comment] 2018-09-10 07:30
> This is similar to what was fixed by:
> 3aeeae6

@vargaz but that change is both in 5.12 and 5.10, while @NickCraver claims to be a regression (a bug that didn't exist in 5.10 while it exists in 5.12).

**Comment by vargaz** [comment] 2018-09-18 12:44
What is the exact mono version this fails with ?

**Comment by marek-safar** [comment] 2018-11-20 16:31
Please reopen the issue if you can provide requested information

**Comment by NickCraver** [comment] 2018-11-20 17:31
@marek-safar This was provided in the first line of the issue: 5.12

**Comment by lewurm** [comment] 2018-11-20 18:02
It could be a duplicate of https://github.com/mono/mono/issues/8811

@NickCraver it would be helpful if you could provide all the required assemblies in a ZIP archive (that is, the build result), so we can just do what you described here:
```console
$ cd $DIR/StackExchange.Redis/StackExchange.Redis.Tests/bin/Release/net462
$ mono /mnt/c/Users/<user>/.nuget/packages/xunit.runner.console/2.4.0-beta.2.build3981/tools/net452/xunit.console.exe StackExchange.Redis.Tests.dll -class "StackExchange.Redis.Tests.Config"
```

**Comment by akoeplinger** [comment] 2018-11-21 13:30
I tried and couldn't repro the crash on Mono 5.12.0.301 or 5.16.0.179 on WSL-Ubuntu1604 as well as Mono 5.12.0.220, 5.12.0.226, 5.20.0.89 on OSX 10.12 so it was probably already fixed. Thank you!

**Closed by akoeplinger** 2018-11-21 13:30 UTC
Labels: area-Runtime: JIT, needs more info, regression
