### ISSUE TITLE
Memory leak using Google Calendar API

### ISSUE THREAD

**Issue by alexbk66** [mono/mono#14196] opened 2019-04-24 06:14 UTC
[GCMemLeak.zip](https://github.com/mono/mono/files/3110635/GCMemLeak.zip)

Using Google Calendar C# API on Linux causes significant memory leak.  
Must be Mono issue because on Windows it's running ok.
Could be related to https://github.com/mono/mono/issues/8689, but it's closed?

## Steps to Reproduce

1. Obtain google calendar api credentials https://console.developers.google.com/apis/credentials
2. Execute attached solution (it expects ClentID and ClientSecret command line arguments)
3. Memory usage steadily grows after each API request

### Current Behavior

Memory usage grows after each API request (appr. by 1Mb)
After running for a day (at 15 sec intervals) memory usage goes to 1 Gb

### Expected Behavior

Stable memory usage. On Windows it's using 20~30 Mb

## On which platforms did you notice this

[ ] macOS
[x] Linux Ubuntu 18.10 (VM)
[ ] Windows

**Version Used**:

5.20.1.19

**Comment by lambdageek** [comment] 2019-04-24 17:21
Hi, I think what you might be seeing is a property of how Mono's garbage collector (sgen) behaves.

By default sgen will ask the OS for more memory whenever it needs to grow the major heap.

you can run the program with some debugging output from sgen by setting `MONO_GC_DEBUG=5`.

You can also limit the maximum size of the major heap by setting `MONO_GC_PARAMS=max-heap-size=50mb` (for a small 50mb heap - not realistic for real programs but good enough for this example).

One other thing that I did, was to add a call to `GC.Collect (GC.MaxGeneration)` inside the loop body after `MemReport ("after");` to trigger a major collection after each loop iteration.

With this change and with the above environment variables set, I get into a steady state:

```
Memory after: 23 Mb, 41 Mb
2019-04-24 13:20:05 Start major collection 12
2019-04-24 13:20:05 Scanning pinned roots (190751 bytes, 431/12 entries)
2019-04-24 13:20:05 Finding pinned pointers: 68 in 417 usecs
2019-04-24 13:20:05 old generation done
2019-04-24 13:20:05 Finalize queue handling scan for old generation: 248 usecs 2 ephemeron rounds
2019-04-24 13:20:05 Heap size: 24150016, LOS size: 114968
2019-04-24 13:20:05 restarted (pause time: 13673 usec, max: 21366)
```

So mono is using about 24mb for its major heap and about 114k for its large object space.

**Comment by alexbk66** [comment] 2019-04-25 02:06
I do GC.Collect - doesn't make any difference.

**Comment by alexbk66** [comment] 2019-04-25 02:07
Do you think "I think what you might be seeing" is good enough reason to close the ticket?
I attached the source code which proves it doesn't work.  Memory keeps growing until the app crashes.

**Comment by lambdageek** [comment] 2019-04-25 14:05
@alexbk66 What worked for me was to both set a max heap size and to trigger a collection.  just doing one or the other  was not enough.

**Comment by alexbk66** [comment] 2019-04-25 14:49
Thank you @lambdageek I tried both of course, like this:
`MONO_GC_DEBUG=5 MONO_GC_PARAMS=max-heap-size=50m  mono authenticator.exe xxx xxx`
For how long did you run the test?  If you leavi it running for a day, what happens?

**Comment by SamMonoRT** [comment] 2019-05-31 15:13
@naricc - please take a look at this one.

**Comment by alexbk66** [comment] 2019-05-31 16:26
Interesting enough one of my customers tested on Mono 6 and according to him Mono 6 didn't have this memory leak...
https://forums.homeseer.com/forum/internet-or-network-related-plug-ins/internet-or-network-discussion/ak-google-calendar-alexbk66/1299258-can%E2%80%99t-install-the-plugin-on-linux/page8

**Comment by SamMonoRT** [comment] 2019-05-31 17:29
@naricc - seems like we should validate that its fixed in latest, if it's indeed fixed,

**Comment by naricc** [comment] 2019-06-03 20:20
Just inserting a GC.Collect, memory usage seems stable at 22 MB running on my machine.

**Comment by alexbk66** [comment] 2019-06-04 01:30
As I said 25 Apr - I do GC.Collect - doesn't make any difference. (Guys I'm not retarded)
After one day memory goes to 1Gb.

**Comment by naricc** [comment] 2019-06-04 15:38
Is that still true on the latest? I can try running it for longer; it usually gets an http error within a few hours and dies, but I can modify it a little to catch that and keep going.

**Comment by alexbk66** [comment] 2019-06-05 03:21
What do you mean by "on the latest"?  Nothing is changed from last month.  For production I had to extract Google Calendar API code into separate service and use .NET Remoting to communicate with it.  So now when I detect that the service memory usage goes above configurable threshold (i.e. 500Mb) - the service will just kill itself.  And when client needs it - the service will restart.
A lot of unnecessary code here, so hoping it could be removed one day (i.e. with Mono 6 release).

**Comment by alexbk66** [comment] 2019-06-05 03:23
You can see the discussion here:
https://forums.homeseer.com/forum/internet-or-network-related-plug-ins/internet-or-network-discussion/ak-google-calendar-alexbk66/1299258-can%E2%80%99t-install-the-plugin-on-linux/page5

**Comment by naricc** [comment] 2019-06-06 20:23
By latest I meant a recent version nightly, or even the version 6 preview. It seems like it is fixed in the version 6 preview, based on my attempts to reproduce it.

**Comment by alexbk66** [comment] 2019-06-07 03:46
Man, did you see my post above 6 days ago? I'm using whatever is latest in apt.  But as I mentioned it seems to be fixed in Mono 6, but I didn't try myself

**Comment by naricc** [comment] 2019-06-10 22:21
Right, I marked it closed because I verified it was fixed in 6. I will keep it closed unless we decide to backport the fix.

**Comment by alexbk66** [comment] 2019-06-11 04:25
So, is it actually fixed in 6?  Can I tell my customers to upgrade to 6?

**Comment by naricc** [comment] 2019-06-13 21:22
I have been unable to reproduce it in the 6 preview. 6 is not released yet; I don't know if your customers want to/are interested in using the preview.

**Closed** 2019-06-24 14:40 UTC
Labels: area-Runtime: GC, question
